#!/usr/bin/env python3
"""Checks for section 8 of openness-covering.typ.

Covering an abelian profinite group by finitely many open subgroups reduces to
covering a finite abelian group by subgroups.  This verifies, by brute force on
random instances, the three facts the section rests on:

  (1) every subgroup of a finite abelian group is the direct sum of its primary
      parts -- what lets membership be tested one prime at a time;
  (2) the inclusion-exclusion / Haar-measure criterion of 8.3(a);
  (3) the per-prime type criterion of 8.3(b);

and separately that sigma(g) = q+1, with q the least prime for which
dim_{F_q} g/qg >= 2, against exhaustive search; and the Bose-Burton statement
of 8.2, that minimal covers by index-ell subgroups are exactly the pencils; and
Neumann's index bound together with the candidate-pool sizes of 8.4.

    python3 cover-check.py
"""
import itertools, random
from functools import reduce

def elems(mods):  return list(itertools.product(*[range(d) for d in mods]))
def add(x, y, mods): return tuple((a + b) % d for a, b, d in zip(x, y, mods))

def gen(gens, mods):
    """Subgroup generated by `gens`."""
    zero = tuple([0] * len(mods))
    S, frontier = {zero}, [zero]
    while frontier:
        new = []
        for s in frontier:
            for g in gens:
                t = add(s, g, mods)
                if t not in S:
                    S.add(t); new.append(t)
        frontier = new
    return frozenset(S)

def primes_of(n):
    ps, d = set(), 2
    while d * d <= n:
        while n % d == 0: ps.add(d); n //= d
        d += 1
    if n > 1: ps.add(n)
    return sorted(ps)

def order(x, mods):
    zero = tuple([0] * len(mods)); o, y = 1, x
    while y != zero: y = add(y, x, mods); o += 1
    return o

def primary(S, ell, mods):
    """The ell-primary part of a subgroup S."""
    out = set()
    for x in S:
        o = order(x, mods)
        while o % ell == 0: o //= ell
        if o == 1: out.add(x)
    return frozenset(out)

def sumset(parts, mods):
    acc = {tuple([0] * len(mods))}
    for P in parts:
        acc = {add(a, b, mods) for a in acc for b in P}
    return frozenset(acc)


def check_criteria(trials=300, seed=11):
    random.seed(seed)
    shapes = [[4,2],[6,6],[2,2,3],[9,3],[12,2],[4,4],[2,2,2],[10,10],[8,2]]
    bad = {"decomp": 0, "incl_excl": 0, "types": 0}
    for _ in range(trials):
        mods = random.choice(shapes)
        G = elems(mods); Gset = frozenset(G); N = len(G)
        m = random.randint(2, 4)
        subs = [gen(random.sample(G, random.randint(1, 2)), mods) for _ in range(m)]
        ps = primes_of(N)
        truth = (frozenset().union(*subs) == Gset)

        for A in subs:                                              # (1)
            if sumset([primary(A, l, mods) for l in ps], mods) != A:
                bad["decomp"] += 1

        tot = 0                                                     # (2)
        for r in range(1, m + 1):
            for S in itertools.combinations(range(m), r):
                inter = reduce(lambda a, b: a & b, [subs[i] for i in S])
                tot += (-1) ** (r + 1) * len(inter)
        if (tot == N) != truth: bad["incl_excl"] += 1

        Tsets = []                                                  # (3)
        for l in ps:
            Gl = primary(Gset, l, mods); Al = [primary(A, l, mods) for A in subs]
            Tsets.append({frozenset(i for i in range(m) if y in Al[i]) for y in Gl})
        covered = all(reduce(lambda a, b: a & b, choice)
                      for choice in itertools.product(*Tsets))
        if covered != truth: bad["types"] += 1

    print(f"{trials} random instances")
    for k, label in [("decomp",    "subgroup = direct sum of primary parts"),
                     ("incl_excl", "inclusion-exclusion criterion  (8.3a)"),
                     ("types",     "per-prime type criterion       (8.3b)")]:
        print(f"  {label:<42}{'OK' if bad[k] == 0 else str(bad[k]) + ' FAIL'}")


def sigma_bruteforce(mods, cap=8):
    G = frozenset(elems(mods))
    subs = {gen(g, mods) for r in (0, 1, 2) for g in itertools.combinations(elems(mods), r)}
    subs = [S for S in subs if S != G]
    if not subs: return None
    for k in range(2, cap + 1):
        for C in itertools.combinations(subs, k):
            if frozenset().union(*C) == G: return k
    return None

def sigma_formula(mods):
    best = None
    for q in primes_of(reduce(lambda a, b: a * b, mods)):
        if sum(1 for d in mods if d % q == 0) >= 2:
            best = q if best is None else min(best, q)
    return None if best is None else best + 1

def check_sigma():
    print("\ncovering number")
    print(f"  {'group':<14}{'brute force':>12}{'q+1':>8}")
    for mods in [[2,2],[3,3],[4,2],[6,6],[2,2,2],[9,3],[5,5],[12,2],[4,4],[10,10],[6],[8],[15]]:
        b, f = sigma_bruteforce(mods), sigma_formula(mods)
        flag = "ok" if b == f else "MISMATCH"
        print(f"  {'x'.join(map(str, mods)):<14}{str(b):>12}{str(f):>8}   {flag}")


# --- Bose-Burton: minimal covers by index-ell subgroups are pencils (section 8.2) ---

def _vecs(d, l): return list(itertools.product(range(l), repeat=d))

def _hyperplanes(d, l):
    """Kernels of nonzero linear forms; one per form up to scalar."""
    seen = {}
    for chi in _vecs(d, l):
        if any(chi):
            seen[frozenset(x for x in _vecs(d, l)
                           if sum(a * b for a, b in zip(chi, x)) % l == 0)] = chi
    return list(seen)

def _subspaces(d, l, dim):
    V, out = _vecs(d, l), set()
    for gens in itertools.combinations(V, dim):
        S = {tuple([0] * d)}
        for co in itertools.product(range(l), repeat=dim):
            S.add(tuple(sum(c * g[j] for c, g in zip(co, gens)) % l for j in range(d)))
        if len(S) == l ** dim: out.add(frozenset(S))
    return list(out)

def _index_l_subgroups(mods, l):
    V, out = elems(mods), set()
    for r in (1, 2, 3):
        for g in itertools.combinations(V, r):
            S = gen(g, mods)
            if len(V) // len(S) == l: out.add(S)
    return sorted(out, key=sorted)

def check_modl():
    """The reduction of 8.2 for g not elementary abelian: every index-l subgroup
    contains l*g, so the question descends to V = g/lg, and minimal covers are
    still exactly the pencils."""
    print("\nreduction mod l*g, for g not elementary abelian")
    print(f"  {'g':<14}{'l':>2}{'|V|':>6}{'d':>3}{'#idx-l':>8}{'min':>5}{'l+1':>5}"
          f"{'#minimal':>10}  pencils  A>=lg")
    cases = [([4,2],2), ([12,2],2), ([27,3],3), ([8,4,2],2), ([9,3,3],3)]
    for mods, l in cases:
        G = frozenset(elems(mods)); N = len(G)
        lg = frozenset(tuple((l*x[j]) % mods[j] for j in range(len(mods))) for x in elems(mods))
        A = _index_l_subgroups(mods, l)
        d = 0
        while l ** d < N // len(lg): d += 1
        mn, minimal = None, []
        for k in range(1, len(A) + 1):
            hit = [C for C in itertools.combinations(A, k) if frozenset().union(*C) == G]
            if hit: mn, minimal = k, hit; break
        idx2 = {C[0] & C[1] for C in itertools.combinations(A, 2)
                if N // len(C[0] & C[1]) == l*l and lg <= (C[0] & C[1])}
        pencils = [frozenset(S for S in A if U <= S) for U in idx2]
        print(f"  {'x'.join(map(str,mods)):<14}{l:>2}{N//len(lg):>6}{d:>3}{len(A):>8}"
              f"{mn:>5}{l+1:>5}{len(minimal):>10}"
              f"{'  yes' if all(frozenset(C) in pencils for C in minimal) else '   NO':>9}"
              f"{'    yes' if all(lg <= S for S in A) else '     NO'}")

def check_blocking():
    """Minimum number of index-ell subgroups covering F_ell^d is ell+1, and every
    minimal cover is the pencil of hyperplanes through a codimension-2 subspace."""
    print("\nminimal covers by index-ell subgroups")
    print(f"  {'l':>2} {'d':>2} {'#hyp':>6} {'min':>5} {'l+1':>5} {'#minimal':>9}  all pencils")
    for l in (2, 3):
        for d in (2, 3):
            V = frozenset(_vecs(d, l)); H = _hyperplanes(d, l)
            minimal, mn = [], None
            for k in range(1, len(H) + 1):
                hit = [C for C in itertools.combinations(range(len(H)), k)
                       if frozenset().union(*[H[i] for i in C]) == V]
                if hit: mn, minimal = k, hit; break
            pencils = [frozenset(i for i, K in enumerate(H) if U <= K)
                       for U in _subspaces(d, l, d - 2)]
            ok = all(frozenset(C) in pencils for C in minimal)
            print(f"  {l:>2} {d:>2} {len(H):>6} {mn:>5} {l+1:>5} {len(minimal):>9}  "
                  f"{'yes' if ok else 'NO'}")


# --- Neumann's index bound, and the size of the candidate pool (section 8.4) ---

def _all_subgroups(mods):
    V = elems(mods); out = set()
    for r in (0, 1, 2, 3):
        for g in itertools.combinations(V, r): out.add(gen(g, mods))
    return sorted(out, key=len)

def check_neumann():
    """In an irredundant cover of size k, every member has index <= k."""
    shapes = [[2,2],[4,2],[2,2,2],[3,3],[6,6],[4,4],[9,3],[2,4],[12,2]]
    tested = viol = 0
    for mods in shapes:
        G = frozenset(elems(mods)); N = len(G)
        subs = [S for S in _all_subgroups(mods) if S != G]
        for k in range(2, 5):
            for C in itertools.combinations(subs, k):
                if frozenset().union(*C) != G: continue
                if not all(frozenset().union(*[A for j, A in enumerate(C) if j != i]) != G
                           for i in range(k)): continue          # keep only irredundant
                tested += 1
                if max(N // len(A) for A in C) > k: viol += 1
    print(f"\nNeumann bound on {tested} irredundant covers")
    print(f"  max index <= size of cover              {'OK' if viol == 0 else str(viol) + ' FAIL'}")

def check_pool():
    """Open subgroups of Z_p^2 of index <= k: the candidate pool of section 8.4."""
    print("\ncandidate pool: open subgroups of Z_p^2 of index <= k")
    ks = (3, 5, 50)
    print("  " + "p".rjust(4) + "".join(f"k={k}".rjust(8) for k in ks))
    for p in (2, 5, 47):
        row = []
        for k in ks:
            j, tot = 0, 0
            while p ** j <= k:
                tot += sum(p ** i for i in range(j + 1)); j += 1
            row.append(tot)
        print("  " + str(p).rjust(4) + "".join(str(v).rjust(8) for v in row))


if __name__ == "__main__":
    check_criteria()
    check_sigma()
    check_blocking()
    check_modl()
    check_neumann()
    check_pool()
