#!/usr/bin/env python3
"""Checks for section 8 of openness-covering.typ.

Covering an abelian profinite group by finitely many open subgroups reduces to
covering a finite abelian group by subgroups.  This verifies, by brute force on
random instances, the three facts the section rests on:

  (1) every subgroup of a finite abelian group is the direct sum of its primary
      parts -- what lets membership be tested one prime at a time;
  (2) the inclusion-exclusion / Haar-measure criterion of 8.3(a);
  (3) the per-prime type criterion of 8.3(b);

and separately that sigma(g) = q+1, with q the least prime for which
dim_{F_q} g/qg >= 2, against exhaustive search.

    python3 cover-check.py
"""
import itertools, random
from functools import reduce

def elems(mods):  return list(itertools.product(*[range(d) for d in mods]))
def add(x, y, mods): return tuple((a + b) % d for a, b, d in zip(x, y, mods))

def gen(gens, mods):
    """Subgroup generated by `gens`."""
    zero = tuple([0] * len(mods))
    S, frontier = {zero}, [zero]
    while frontier:
        new = []
        for s in frontier:
            for g in gens:
                t = add(s, g, mods)
                if t not in S:
                    S.add(t); new.append(t)
        frontier = new
    return frozenset(S)

def primes_of(n):
    ps, d = set(), 2
    while d * d <= n:
        while n % d == 0: ps.add(d); n //= d
        d += 1
    if n > 1: ps.add(n)
    return sorted(ps)

def order(x, mods):
    zero = tuple([0] * len(mods)); o, y = 1, x
    while y != zero: y = add(y, x, mods); o += 1
    return o

def primary(S, ell, mods):
    """The ell-primary part of a subgroup S."""
    out = set()
    for x in S:
        o = order(x, mods)
        while o % ell == 0: o //= ell
        if o == 1: out.add(x)
    return frozenset(out)

def sumset(parts, mods):
    acc = {tuple([0] * len(mods))}
    for P in parts:
        acc = {add(a, b, mods) for a in acc for b in P}
    return frozenset(acc)


def check_criteria(trials=300, seed=11):
    random.seed(seed)
    shapes = [[4,2],[6,6],[2,2,3],[9,3],[12,2],[4,4],[2,2,2],[10,10],[8,2]]
    bad = {"decomp": 0, "incl_excl": 0, "types": 0}
    for _ in range(trials):
        mods = random.choice(shapes)
        G = elems(mods); Gset = frozenset(G); N = len(G)
        m = random.randint(2, 4)
        subs = [gen(random.sample(G, random.randint(1, 2)), mods) for _ in range(m)]
        ps = primes_of(N)
        truth = (frozenset().union(*subs) == Gset)

        for A in subs:                                              # (1)
            if sumset([primary(A, l, mods) for l in ps], mods) != A:
                bad["decomp"] += 1

        tot = 0                                                     # (2)
        for r in range(1, m + 1):
            for S in itertools.combinations(range(m), r):
                inter = reduce(lambda a, b: a & b, [subs[i] for i in S])
                tot += (-1) ** (r + 1) * len(inter)
        if (tot == N) != truth: bad["incl_excl"] += 1

        Tsets = []                                                  # (3)
        for l in ps:
            Gl = primary(Gset, l, mods); Al = [primary(A, l, mods) for A in subs]
            Tsets.append({frozenset(i for i in range(m) if y in Al[i]) for y in Gl})
        covered = all(reduce(lambda a, b: a & b, choice)
                      for choice in itertools.product(*Tsets))
        if covered != truth: bad["types"] += 1

    print(f"{trials} random instances")
    for k, label in [("decomp",    "subgroup = direct sum of primary parts"),
                     ("incl_excl", "inclusion-exclusion criterion  (8.3a)"),
                     ("types",     "per-prime type criterion       (8.3b)")]:
        print(f"  {label:<42}{'OK' if bad[k] == 0 else str(bad[k]) + ' FAIL'}")


def sigma_bruteforce(mods, cap=8):
    G = frozenset(elems(mods))
    subs = {gen(g, mods) for r in (0, 1, 2) for g in itertools.combinations(elems(mods), r)}
    subs = [S for S in subs if S != G]
    if not subs: return None
    for k in range(2, cap + 1):
        for C in itertools.combinations(subs, k):
            if frozenset().union(*C) == G: return k
    return None

def sigma_formula(mods):
    best = None
    for q in primes_of(reduce(lambda a, b: a * b, mods)):
        if sum(1 for d in mods if d % q == 0) >= 2:
            best = q if best is None else min(best, q)
    return None if best is None else best + 1

def check_sigma():
    print("\ncovering number")
    print(f"  {'group':<14}{'brute force':>12}{'q+1':>8}")
    for mods in [[2,2],[3,3],[4,2],[6,6],[2,2,2],[9,3],[5,5],[12,2],[4,4],[10,10],[6],[8],[15]]:
        b, f = sigma_bruteforce(mods), sigma_formula(mods)
        flag = "ok" if b == f else "MISMATCH"
        print(f"  {'x'.join(map(str, mods)):<14}{str(b):>12}{str(f):>8}   {flag}")


if __name__ == "__main__":
    check_criteria()
    check_sigma()
