#set page(paper: "a4", margin: (x: 2.4cm, y: 2.6cm), numbering: "1")
#set text(size: 11pt)
#set par(justify: true, leading: 0.65em)
#set heading(numbering: "1.")
#show heading: set block(above: 1.4em, below: 0.75em)

#let Nrd = math.op("Nrd")
#let Gal = math.op("Gal")
#let Br = math.op("Br")
#let Pic = math.op("Pic")
#let Tr = math.op("Tr")
#let ann = math.op("ann")

#let box-stmt(name, body) = block(
  width: 100%,
  inset: 10pt,
  radius: 3pt,
  fill: luma(245),
  stroke: (left: 2pt + luma(150)),
)[*#name.* #body]

#align(center)[
  #text(15pt, weight: "bold")[
    A smooth cubic surface over $QQ$ which is the blow-up of \
    a nontrivial Severi--Brauer surface in six conjugate points
  ]
  #v(0.3em)
  #text(10pt)[Note prepared in response to the question: give one explicit equation.]
]

#v(0.8em)

= The example

Let $S subset bb(P)^3_QQ$ be the cubic surface

$ S : quad x^3 + 2 y^3 + 4 z^3 + 4 x y z + 7 w^3 - 7 w^2 x = 0 , $

or, in the affine chart $w = 1$, the single equation in three variables

$ x^3 + 2 y^3 + 4 z^3 + 4 x y z - 7 x + 7 = 0 . $

#box-stmt("Theorem")[
$S$ is a smooth cubic surface over $QQ$ with $S(QQ) = nothing$. There is a morphism
$phi : S -> X$ defined over $QQ$, where $X$ is the Severi--Brauer surface of a
central division algebra $A$ of degree $3$ over $QQ$ (ramified exactly at $2$ and $7$),
such that $phi_(overline(QQ))$ is the blow-up of $X_(overline(QQ)) ≅ bb(P)^2_(overline(QQ))$
in six distinct points in general position. In particular $X(QQ) = nothing$, and the six
blown-up points form a single $Gal(overline(QQ)\/QQ)$-orbit; equivalently, the six
exceptional curves form a Galois-stable sixer of lines on $S$.
]

The rest of the note explains where the equation comes from and proves each assertion.
Everything is a finite check by hand except the last statement of the Theorem (the six
points are one orbit rather than two orbits of three), which is a Gröbner basis
computation recorded in @sec:orbit.

= The strategy

Let $A$ be a central simple algebra of degree $3$ over a field $k$ (char. $0$), with
reduced norm $Nrd : A -> k$, a cubic form on the $9$-dimensional $k$-vector space $A$.
Let $V subset A$ be a $4$-dimensional $k$-subspace and put

$ S_V := { Nrd|_V = 0 } subset bb(P)(V) ≅ bb(P)^3_k . $

If $S_V$ is smooth then it is a del Pezzo surface of degree $3$, and it carries a
canonical morphism to the Severi--Brauer surface of $A$ given by "taking the kernel";
see @sec:blowdown. Two features make this the right construction:

- if $A$ is a *division* algebra, then $Nrd(a) = 0 arrow.r.double a = 0$, so $S_V (k) = nothing$
  for free, and the target Severi--Brauer surface has no rational point either;
- over $overline(k)$ one has $A ≅ M_3$ and $Nrd = det$, so $S_V$ is a *determinantal*
  cubic surface, and the classical theory of determinantal representations of cubic
  surfaces (Grassmann, Schur; see [1], [2]) says exactly that the kernel map
  is the contraction of a sixer.

So the only real work is to choose $A$ and $V$ so that the resulting cubic form is
smooth, and then to write it down.

= The division algebra

Let $zeta = e^(2 pi i \/ 7)$ and let
$ L = QQ(zeta)^+ = QQ(theta), quad theta = zeta + zeta^(-1), quad
  f(T) = T^3 + T^2 - 2 T - 1 = 0 , $
the cyclic cubic field of conductor $7$. Its Galois group is generated by
$ sigma : theta arrow.bar theta^2 - 2 quad (= zeta^2 + zeta^(-2)) , $
and $sigma^3 = id$. For the record, the elementary symmetric functions of the conjugates
of $theta$ are $e_1 = -1$, $e_2 = -2$, $e_3 = 1$; in particular $N_("L/Q") (theta) = 1$ and
$Tr_("L/Q") (theta sigma(theta)) = -2$.

Let $A$ be the cyclic algebra
$ A = (L\/QQ, sigma, 2) = L ⊕ L e ⊕ L e^2, quad
  e^3 = 2, quad e lambda = sigma(lambda) e quad (lambda in L) . $

#box-stmt("Lemma 1")[$A$ is a division algebra; it is ramified exactly at $2$ and $7$.]

_Proof._ $Gal(L\/QQ) ≅ (ZZ\/7)^times \/{plus.minus 1}$, and the class of $2$ is nontrivial
($2 in.not {1,6}$), so $2$ is inert in $L$ and $L ⊗ QQ_2$ is the unramified cubic extension
of $QQ_2$. For $lambda$ in that field, $v_2 (N(lambda)) = 3 v(lambda) in 3 ZZ$, whereas
$v_2 (2) = 1$; hence $2$ is not a local norm at $2$, so a fortiori
$2 in.not N_("L/Q") (L^times)$. A cyclic algebra $(L\/QQ, sigma, b)$ is split if and only if
$b$ is a norm, so $A$ is nonsplit, and a nonsplit central simple algebra of prime degree is
a division algebra. The local invariant at $2$ is $plus.minus 1\/3$; away from $2$ and $7$
the extension $L\/QQ$ is unramified and $b = 2$ is a unit, so $A_v$ splits, and $L$ is real
so $A_infinity$ splits. As the invariants sum to $0$, the only other ramified place is $7$.
#h(1fr) $square$

*Reduced norm.* $A$ is a left $L$-vector space with basis $1, e, e^2$, and right
multiplication $R_a (u) = u a$ is left $L$-linear with $R_(a b) = R_b R_a$. Writing
$a = lambda_0 + lambda_1 e + lambda_2 e^2$ in this basis one gets the matrix

$ M(a) = mat(
  lambda_0, 2 sigma(lambda_2), 2 sigma^2 (lambda_1);
  lambda_1, sigma(lambda_0), 2 sigma^2 (lambda_2);
  lambda_2, sigma(lambda_1), sigma^2 (lambda_0)
) in M_3 (L), $

and $Nrd(a) = det M(a)$, i.e. the classical formula

$ Nrd(lambda_0 + lambda_1 e + lambda_2 e^2)
 = N(lambda_0) + 2 N(lambda_1) + 4 N(lambda_2)
   - 2 Tr(lambda_0 thin sigma(lambda_1) thin sigma^2 (lambda_2)), $

with $N = N_("L/Q")$, $Tr = Tr_("L/Q")$. (Note $M$ is an isomorphism
$A^(op) ⊗_QQ L ≅ M_3 (L)$, so it also exhibits $L$ as a splitting field.)

= The subspace and the equation

Put
$ eta := theta^2 + theta + 1, quad "so" quad
  eta = theta xi quad "with" quad xi := theta^2 + 2 theta - 1, quad xi^3 = 7 xi + 7 . $
Take the $4$-dimensional $QQ$-subspace
$ V = ⟨ thin theta, thin eta, thin theta e, thin e^2 thin ⟩_QQ subset A , $
i.e. $lambda_0 = x theta + w eta$, $lambda_1 = y theta$, $lambda_2 = z$ with
$(x,y,z,w) in QQ^4$.

The three ingredients are elementary computations in $L$:

$ N(x theta + w eta) &= N(theta) dot N(x + w xi) = x^3 - 7 x w^2 + 7 w^3
   quad ("since" xi^3 - 7 xi - 7 = 0), \
  N(theta) &= 1, quad N(1) = 1, \
  Tr(theta thin sigma(theta)) &= -2, quad Tr(eta thin sigma(theta)) = 0 . $

Substituting into the formula for $Nrd$:

$ Nrd|_V (x,y,z,w)
 &= N(x theta + w eta) + 2 y^3 N(theta) + 4 z^3
    - 2 y z dot Tr((x theta + w eta) sigma(theta)) \
 &= (x^3 - 7 x w^2 + 7 w^3) + 2 y^3 + 4 z^3 - 2 y z (-2 x + 0) \
 &= bold(x^3 + 2 y^3 + 4 z^3 + 4 x y z + 7 w^3 - 7 w^2 x) . $

This is the cubic form $F$ of the Theorem: $S = { F = 0 }$.

= Smoothness

#box-stmt("Lemma 2")[$S$ is smooth over $QQ$ (hence geometrically smooth).]

_Proof._ The partial derivatives are
$ F_x = 3 x^2 + 4 y z - 7 w^2, quad F_y = 6 y^2 + 4 x z, quad
  F_z = 12 z^2 + 4 x y, quad F_w = 7 w (3 w - 2 x) . $
Suppose all four vanish at some point of $overline(QQ)^4$.

*Case $w = 0$.* Then $3 x^2 = -4 y z$, $3 y^2 = -2 x z$, $3 z^2 = -x y$. Multiplying the
three relations gives $27 x^2 y^2 z^2 = -8 x^2 y^2 z^2$, so $x y z = 0$. If $x = 0$ then
$y = 0$ from the second relation and then $z = 0$ from the third; the cases $y = 0$ and
$z = 0$ are identical. So $x = y = z = w = 0$.

*Case $w eq.not 0$.* Then $x = 3 w \/ 2$; rescale so that $w = 2$, $x = 3$. The remaining
equations read $4 y z = 1$, $y^2 = -2 z$, $z^2 = -y$. Substituting $y = -z^2$ into
$y^2 = -2z$ gives $z(z^3 + 2) = 0$. If $z = 0$ then $y = 0$, contradicting $4 y z = 1$;
if $z^3 = -2$ then $4 y z = -4 z^3 = 8 eq.not 1$, again a contradiction.

Hence the singular locus is empty. #h(1fr) $square$

(Equivalently, a Gröbner basis of the Jacobian ideal contains $x^5, y^4, z^4, w^5$.)

Consequently $S$ is a del Pezzo surface of degree $3$, anticanonically embedded in
$bb(P)^3$, with $K_S^2 = 3$.

#box-stmt("Remark")[
The choice of $V$ matters. The tempting choice $V = L ⊕ QQ e$ gives the norm
cubic $N(lambda) = -2 t^3$, which has three $A_2$-singularities; more generally, if $V$
contains a cubic étale subalgebra of $A$ then $bb(P)(V)$ meets the rank-one locus (the
singular locus of ${det = 0}$) and $S_V$ is singular. The subspace above contains no
such subalgebra, and Lemma 2 confirms smoothness.
]

= No rational points

#box-stmt("Lemma 3")[$S(QQ) = nothing$; in fact $S(QQ_2) = S(QQ_7) = nothing$.]

_Proof._ A rational point of $S$ is a nonzero $a in V subset A$ with $Nrd(a) = 0$. In a
division algebra the reduced norm vanishes only at $0$ (an element is invertible iff its
reduced norm is nonzero), so no such $a$ exists. The same argument over $QQ_2$ and $QQ_7$
applies because $A ⊗ QQ_2$ and $A ⊗ QQ_7$ are division algebras by Lemma 1. #h(1fr) $square$

So $S$ is *not* a counterexample to the Hasse principle --- it already fails to have points
at $2$ and at $7$. (One checks directly that $F$ has no primitive zero mod $8$, nor mod $49$.)
This is unavoidable in this construction: $S(k_v) eq.not nothing$ forces $A ⊗ k_v$ to split.

= The blow-down to the Severi--Brauer surface <sec:blowdown>

Recall that $X := "SB"(A)$ may be defined as the $k$-variety of right ideals of $A$ of
$k$-dimension $3$ (reduced dimension $1$). Over $overline(k)$, with $A ≅ M_3$, such ideals
are $I_U = {a : "col"(a) subset U}$ for lines $U subset overline(k)^3$, so
$X_(overline(k)) ≅ bb(P)^2$; and $X(k) eq.not nothing$ iff $A ≅ M_3 (k)$.

Since $S$ is smooth, no point of $bb(P)(V)$ has rank $1$: a rank-one point would be a
singular point of the determinantal hypersurface ${det = 0}$ lying on $bb(P)(V)$, where all
partials of $det$ --- and hence all partials of $det|_V$ --- vanish. Therefore every
$v in S(overline(QQ))$ has rank exactly $2$, and

$ phi : S -> X, quad v arrow.bar ann_r (v) = {a in A : v a = 0} $

is a well-defined morphism over $QQ$ (the right annihilator of a rank-$2$ element is a right
ideal of dimension $3$; over $overline(QQ)$ it is $I_(ker v)$, so $phi$ is the kernel map,
given by the $2 times 2$ minors). Its fibres are
$ phi^(-1) (I_U) = bb(P)(V inter W_U), quad W_U := {v in A : v u = 0} quad (0 eq.not u in U), $
where $dim W_U = 6$. Since $dim V + dim W_U = 10 > 9$, every fibre is nonempty, so $phi$ is
surjective; for generic $U$ the intersection is a line in $V$, i.e. a single point, so
$phi_(overline(QQ))$ is a birational morphism of smooth projective surfaces
$S_(overline(QQ)) -> bb(P)^2$. Hence it is a composite of blow-downs, and
$K^2_(bb(P)^2) - K_S^2 = 9 - 3 = 6$ of them. Every nontrivial fibre is a linear subspace
$bb(P)(V inter W_U)$ of $bb(P)^3$ contained in $S$, hence a *line* (it cannot be a plane, as
$S$ is smooth), in particular irreducible; so no blown-up point is infinitely near another.

#box-stmt("Conclusion")[
$phi_(overline(QQ))$ is the blow-up of $bb(P)^2$ in six distinct points, necessarily in
general position (no $3$ collinear, not all $6$ on a conic, since $-K_S$ is very ample).
The six exceptional curves are six pairwise disjoint lines on $S$ --- a sixer --- and they
are permuted by $Gal(overline(QQ)\/QQ)$ because $phi$ is defined over $QQ$. Their images
form a $QQ$-rational closed subscheme $Z subset X$ of degree $6$: a Galois-stable set of six
points. Finally $X(QQ) = nothing$ since $A$ is division, i.e. $X$ is a nontrivial
Severi--Brauer surface, of class $[A] in Br(QQ)[3]$ ramified at $2$ and $7$.
]

Applying the same construction with left annihilators gives the second blow-down
$phi' : S -> "SB"(A^(op))$; the two sixers form a double six, and $[A^(op)] = -[A]$ is again
nontrivial.

= Structure of the six points <sec:orbit>

The residue field of any closed point of $X = "SB"(A)$ splits $A$, so its degree is
divisible by $"ind"(A) = 3$. Hence $Z$ is either one closed point of degree $6$ or two of
degree $3$. For our surface it is the former:

#box-stmt("Proposition")[
$Z$ is a single closed point of degree $6$: the six blown-up points form one
$Gal(overline(QQ)\/QQ)$-orbit, and likewise for the second blow-down $phi'$.
]

_Verification._ Split $A$ by $L$ using $M$ above, so $X_L ≅ bb(P)^2_L$ with coordinates
$p = (p_1 : p_2 : p_3)$, and let $v_1 = theta$, $v_2 = eta$, $v_3 = theta e$, $v_4 = e^2$ be
the chosen basis of $V$. A point $p$ is one of the six exactly when the $3 times 4$ matrix
$ [M(v_1) p thin | thin M(v_2) p thin | thin M(v_3) p thin | thin M(v_4) p] $
has rank $lt.eq 2$, i.e. when its four $3 times 3$ minors vanish. A Gröbner basis of the
ideal they generate (over $L$) shows there are no solutions with $p_3 = 0$, that $p_1$ is a
polynomial in $p_2$, and that
$ p_2^6 + (348 theta^2 + 232 theta - 712) thin p_2^3
  + (748 theta^2 + 1208 theta - 252) = 0 . $
This sextic is irreducible over $L$ (its resolvent quadratic in $p_2^3$ has non-square
discriminant in $L$, and $p_2^3$ generates a further cubic extension), so the six points are
a single orbit already under $Gal(overline(QQ)\/L)$, a fortiori under
$Gal(overline(QQ)\/QQ)$. The same computation with row vectors $q^t M(v_i)$ gives the
analogous irreducible sextic for $phi'$. #h(1fr) $square$

So: $S$ is the blow-up of the nontrivial Severi--Brauer surface $X$ in one closed point of
degree $6$, whose residue field is a sextic field splitting $A$.

= Remarks

+ *Reversibility.* The construction is not ad hoc: by the theory of determinantal
  representations ([1], §6; [2], §9.3), every blow-down structure
  $S -> X$ over $k$ on a smooth cubic surface arises from a pair $(A, V)$ as above, with
  $[A] in Br(k)[3]$ the class of $X$. Galois-stable sixers on $S$ correspond to
  determinantal representations by an Azumaya algebra.

+ *Other examples.* Any cyclic cubic field $L$, any $b in QQ^times$ that is not a norm, and
  any $V$ avoiding the rank-one locus will do. The search that produced the equation above
  ran over $V = ⟨ a_0, a_1, a_2 e, a_3 e^2 ⟩$ with $a_i in L$ small; several
  hundred smooth examples appear, e.g.
  $ 7 w^3 - 7 w^2 x + x^3 + 4 x y z - 2 y^3 - 4 z^3 = 0 quad "and" quad
    7 w^3 + 7 w^2 x - x^3 + 4 x y z + 2 y^3 - 4 z^3 = 0 . $

+ *Sanity checks on the equation.* Setting $y = z = w = 0$ etc. recovers
  $N(theta) = 1$, $N(eta) = 7$, $2 N(theta) = 2$, $4 N(1) = 4$; the mixed term $4 x y z$ is
  $-2 Tr(theta sigma(theta)) x y z$. The absence of a $w y z$ term reflects
  $Tr(eta thin sigma(theta)) = 0$.

#v(1em)
#line(length: 100%, stroke: 0.5pt + luma(180))

#heading(numbering: none, level: 1)[References]

#set enum(numbering: "[1]")
+ A. Beauville, _Determinantal hypersurfaces_, Michigan Math. J. *48*
  (2000), 39--64.
+ I. Dolgachev, _Classical Algebraic Geometry: a Modern View_,
  Cambridge Univ. Press, 2012, §9.3 (determinantal representations of cubic surfaces).
+ Yu. I. Manin, _Cubic Forms_, 2nd ed., North-Holland, 1986 (blow-down structures, sixers
  and the Galois action on $Pic$).
+ P. Gille, T. Szamuely, _Central Simple Algebras and Galois Cohomology_, Cambridge Univ.
  Press, 2006 (cyclic algebras, reduced norms, Severi--Brauer varieties).
