#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show link: set text(fill: blue.darken(20%))
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#align(center)[
  #text(size: 16pt, weight: "bold")[Descent is a substitute for discreteness]
  #v(2mm)
  #text(size: 10pt)[Dirichlet's unit theorem in the shape of Mordell--Weil: the arithmetic
  half and the height half are both there, and the reason nobody uses them]
  #v(1mm)
  #text(size: 9pt, style: "italic")[a question of René Pannekoek's; checks in
  `dirichlet-mordell-weil.gp`]
]

#v(4mm)

#block(fill: luma(240), inset: 9pt, radius: 3pt, width: 100%)[
  *The one-line answer.* Yes, the split exists, and it is exactly the Mordell--Weil one: the weak
  statement is the finiteness of $cal(O)_K^times slash (cal(O)_K^times)^m$ --- a Selmer group,
  proved by Kummer theory and Hermite--Minkowski --- and the analytic half is Northcott plus a
  descent (@sec-parallel). It is never used, and the reason is a one-line computation: for a *unit*
  the Weil height is *purely archimedean*,
  $ h(u) = norm(lambda(u))_1 slash 2n , $
  so the logarithmic embedding already *is* the height, and it is a homomorphism into a
  *non-compact* Euclidean space with discrete image. Finite generation falls out with no descent at
  all (@sec-why). $E(K)$ admits no such map, because its archimedean avatar is *compact*
  (@sec-compact) --- and descent is precisely what one uses instead. What is left over is that
  Dirichlet's theorem asserts strictly *more* than Mordell--Weil: the rank formula (@sec-realsplit)
  has no Mordell--Weil analogue at all, and is where all of its difficulty sits.
]

= The two theorems, and the dictionary they sit in <sec-dict>

Both theorems are statements about the same diagram. For an elliptic curve, descent by $m$ gives

$ 0 --> E(K) slash m E(K) --> "Sel"^m (E slash K) --> Ш(E slash K)[m] --> 0 . $

For the multiplicative group, take $"Sel"^m (GG_m slash K) = {x in K^times slash (K^times)^m :
"ord"_v (x) equiv 0 space (mod m) "for all finite" v}$ --- the *virtual units*, i.e. $H^1$ with
unramified local conditions --- and send $x$ to the class of the ideal $frak(a)$ with
$(x) = frak(a)^m$. That gives

$ 1 --> cal(O)_K^times slash (cal(O)_K^times)^m --> "Sel"^m (GG_m slash K) --> "Cl"(K)[m] --> 1 . $

Same sequence, same proof. The dictionary is then forced:

#align(center, table(
  columns: 2, align: (left, left),
  stroke: 0.4pt + luma(170), inset: (x: 10pt, y: 4pt),
  table.header([$GG_m$ over $K$], [$E$ over $K$]),
  [units $cal(O)_K^times$], [Mordell--Weil group $E(K)$],
  [Dirichlet's unit theorem], [Mordell--Weil theorem],
  [roots of unity $mu_K$], [torsion $E(K)_"tors"$],
  [unit rank $r_1 + r_2 - 1$], [rank $r$],
  [unit regulator $R$], [height regulator $"Reg"$],
  [*class group* $"Cl"(K)$], [*$Ш(E slash K)$*],
  [class number formula], [BSD],
))

#v(2mm)
The two hard invariants sit in the same slot: $"Cl"(K)$ measures ideals that are locally principal
everywhere but not globally, $Ш$ measures torsors with points everywhere locally but not globally.
The question of this note is about the two *proofs* in the first two rows, which look nothing
alike.

= The unit theorem in the Mordell--Weil shape <sec-parallel>

The Mordell--Weil proof has two halves that are logically independent: *weak Mordell--Weil*, that
$E(K) slash m E(K)$ is finite, which is arithmetic and cohomological; and the *descent*, which
converts that finiteness into finite generation using a height. Both halves exist for units.

== The weak unit theorem <sec-weak>

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Proposition.* For every $m >= 1$, the group $cal(O)_K^times slash (cal(O)_K^times)^m$ is finite.

  #v(2mm)
  _Proof._ Suppose first $mu_m subset K$. Let $u$ be a unit. At a finite place $v$ with
  $v tack.r.not m$ one has $"ord"_v (u) = 0$, so $K_v (u^(1 slash m)) slash K_v$ is generated by an
  $m$-th root of a unit with $m$ invertible in the residue field: unramified. Hence
  $K(u^(1 slash m)) slash K$ has degree dividing $m$ and is *unramified outside the primes above
  $m$ and the archimedean places*. Ramification confined to a fixed finite set, together with a
  bounded degree, bounds the different and so the discriminant; by *Hermite--Minkowski* there are
  only finitely many extensions of $K$ of bounded degree and bounded discriminant. Let $M$ be their
  compositum: a finite abelian extension of $K$ of exponent $m$. The Kummer pairing
  $ cal(O)_K^times slash (cal(O)_K^times)^m times "Gal"(M slash K) --> mu_m , wide
    (u, sigma) |--> sigma(u^(1 slash m)) slash u^(1 slash m) $
  is nondegenerate on the left by construction, so
  $cal(O)_K^times slash (cal(O)_K^times)^m arrow.hook "Hom"("Gal"(M slash K), mu_m)$, which is
  finite. In general apply this over $K' = K(mu_m)$; the kernel of
  $H^1(K, mu_m) --> H^1(K', mu_m)$ is $H^1("Gal"(K' slash K), mu_m)$, finite, and
  $cal(O)_K^times slash (cal(O)_K^times)^m$ injects into $H^1(K, mu_m)$. $qed$
]

#v(2mm)
This is the same argument as weak Mordell--Weil, with $mu_m$ in place of $E[m]$, and it is *not
circular*: Hermite--Minkowski is proved from Minkowski's convex body theorem alone --- one produces
a generator of the field with bounded conjugates, hence with bounded characteristic polynomial ---
and uses no unit theorem.

#block(fill: rgb("#fff4e6"), inset: 8pt, radius: 3pt, width: 100%)[
  *It is worth being honest about the cost.* Once Dirichlet's theorem is known, @sec-weak is
  immediate: a finitely generated abelian group modulo $m$ is finite. Proving it *independently* is
  strictly more expensive than the theorem it is being used to prove. That is already a hint that
  this is not the road one wants.
]

== The descent <sec-descent>

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Descent lemma.* Let $A$ be an abelian group with a function $h : A --> RR_(>= 0)$ satisfying
  #v(1mm)
  (i) *Northcott*: ${a in A : h(a) <= B}$ is finite for every $B$;
  #h(6mm) (ii) $h(a^m) = m dot h(a)$;
  #h(6mm) (iii) $h(a b) <= h(a) + h(b)$ and $h(a^(-1)) = h(a)$.
  #v(1mm)
  If $A slash A^m$ is finite for some $m >= 2$, then $A$ is finitely generated.

  #v(2mm)
  _Proof._ Let $a_1, ..., a_r$ represent $A slash A^m$ and put $C = max_i h(a_i)$. Given
  $u in A$ write $u = a_i v^m$; then
  $ m dot h(v) = h(v^m) = h(u a_i^(-1)) <= h(u) + C , wide "so" wide
    h(v) <= (h(u) + C) slash m . $
  If $h(u) > C slash (m-1)$ this gives $h(v) < h(u)$. Iterating produces a strictly decreasing
  sequence of heights, all of whose terms lie in the *finite* set ${h <= h(u)}$; so after finitely
  many steps the height drops to $<= C slash (m-1)$. Hence $A$ is generated by
  $a_1, ..., a_r$ together with ${a : h(a) <= C slash (m-1)}$, a finite set. $qed$
]

#v(2mm)
Apply this with $A = cal(O)_K^times$ and $h$ the absolute Weil height. Conditions (ii) and (iii)
are standard properties of $h$ on $K^times$, condition (i) is Northcott's theorem, and
$A slash A^m$ is finite by @sec-weak. So $cal(O)_K^times$ is finitely generated --- Dirichlet's
theorem, proved exactly as Mordell--Weil is.

One difference in the machinery is worth recording, because it makes this half *easier* than its
elliptic counterpart. On $K^times$ the height is *linear*, $h(x^m) = m h(x)$ on the nose, so one
descent step contracts by $1 slash m$. On $E$ the canonical height is *quadratic*,
$hat(h)(m P) = m^2 hat(h)(P)$, contracting by $1 slash m^2$; that is a better rate, but it has to
be *earned*, via the parallelogram law and the comparison of $hat(h)$ with a naive height. Nothing
of the sort is needed on $GG_m$. Both rates are verified in check 5.

= Why nobody proves it that way <sec-why>

Because the analytic half alone already finishes the job, and the reason is one line.

#block(fill: luma(240), inset: 9pt, radius: 3pt, width: 100%)[
  *A unit has no finite-place content.* By definition $"ord"_v (u) = 0$ at every finite $v$, so
  $abs(u)_v = 1$ there and every non-archimedean term of the Weil height vanishes:
  $ h(u) = 1/n sum_(v divides infinity) n_v log^+ abs(u)_v , wide n = [K : QQ] . $
  The product formula then reads $sum_(v divides infinity) n_v log abs(u)_v = 0$ --- which *is* the
  trace-zero hyperplane --- and for real numbers summing to zero the positive parts carry half the
  $ell^1$ mass. Hence
  $ h(u) = 1/(2n) sum_(v divides infinity) n_v abs(log abs(u)_v)
         = norm(lambda(u))_1 slash 2n , $
  where $lambda$ is the logarithmic embedding. *On units the Weil height is the $ell^1$ norm of the
  logarithmic embedding.*
]

So the map $lambda : cal(O)_K^times --> RR^(r_1 + r_2)$ does four jobs at once: it is a group
homomorphism; it is a height; its kernel is $mu_K$, so it is injective modulo torsion; and
Northcott says its image is *discrete*. A discrete subgroup of a Euclidean space is a lattice,
hence finitely generated. There is no need for $cal(O)_K^times slash (cal(O)_K^times)^m$, and no
need for a descent.

Check 1 verifies the identity on twelve fundamental units across six signatures: the log vector
sums to zero to full precision, the two expressions for $h$ agree, and $abs(N(u)) = 1$ throughout.
Check 2 makes Northcott exact in the real quadratic case, where $h(epsilon) = R slash 2$ and so
$\#{u : h(u) <= B} = 2(2 floor(2B slash R) + 1)$ --- verified on $QQ(sqrt(2))$, $QQ(sqrt(5))$,
$QQ(sqrt(79))$ at three values of $B$ each, with no mismatch.

#block(fill: rgb("#fff4e6"), inset: 8pt, radius: 3pt, width: 100%)[
  *And it is the units specifically.* The same map on all of $K^times$ is *not* discrete: already
  for $K = QQ$ the image of $QQ^times$ under $x |-> log abs(x)$ is dense in $RR$. Discreteness is
  bought exactly by the condition that defines a unit. "Unit" $=$ "no finite-place content" $=$
  "the archimedean places already see everything".
]

= Compactness is the dividing line <sec-compact>

Why does $E(K)$ admit no such map? Not for want of trying: the obstruction is a fact about the
archimedean points, and it is absolute.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  $product_(v divides infinity) E(K_v)$ is a *compact* real Lie group --- a product of circles and
  real tori. An infinite subgroup of a compact group is never discrete. So *no* homomorphism from
  an infinite $E(K)$ into archimedean data can have discrete image.

  #v(1.5mm)
  For $GG_m$ the same product is $(RR^times)^(r_1) times (CC^times)^(r_2)$, which modulo its
  maximal compact subgroup is $RR^(r_1 + r_2)$: *non-compact*, of dimension $r_1 + r_2$. That
  quotient is the logarithmic embedding, and there is room in it for a lattice.
]

Concretely: if $E(K)$ is infinite, its closure in the identity component $E(RR)^0 tilde.equiv
RR slash ZZ$ is a closed infinite subgroup of the circle, hence *all* of it. Rational points are
dense there. Check 4 exhibits the two behaviours side by side on `43a1` $: y^2 + y = x^3 + x^2$
(discriminant $-43 < 0$, so $E(RR)$ is connected and every rational point has a real elliptic
logarithm) against the units of $QQ(sqrt(2))$:

#block(breakable: false, align(center, table(
  columns: 4, align: (right, right, right, right),
  stroke: 0.4pt + luma(170), inset: (x: 9pt, y: 3.5pt),
  table.header([$N$], [units: $min_(n <= N) abs(log abs(epsilon^n))$],
               [`43a1`: $min_(n <= N) norm(n z slash omega)$], [$1 slash N$]),
  [$10$],     [$0.881373587020$], [$0.039592976609$], [$0.1$],
  [$10^2$],   [$0.881373587020$], [$0.001453654969$], [$0.01$],
  [$10^3$],   [$0.881373587020$], [$0.000344292455$], [$0.001$],
  [$10^4$],   [$0.881373587020$], [$0.000076485148$], [$0.0001$],
  [$10^5$],   [$0.881373587020$], [$0.000000218581$], [$0.00001$],
)))

#v(2mm)
The unit column is *constant*: no power of $epsilon$ ever comes closer to $1$ than $epsilon$ does,
which is discreteness. The $E(QQ)$ column decays like $1 slash N$: the multiples of the generator
accumulate at the origin.

#block(fill: luma(240), inset: 9pt, radius: 3pt, width: 100%)[
  *This is the whole answer to the question.* The canonical height decomposes as
  $hat(h) = sum_v lambda_v$ over *all* places, with genuinely nonzero contributions at the finite
  ones. Its job is to restore, out of the finite places, the discreteness that the archimedean
  places cannot supply on their own. For units every non-archimedean local height is zero and there
  is nothing to restore --- so the machinery has nothing to do.

  #v(1.5mm)
  *Descent is a substitute for discreteness.* One reaches for it exactly when the group has no
  discrete Euclidean model to be read off in advance.
]

= The split that is actually there <sec-realsplit>

Dirichlet's proof *does* divide in two, but along a different seam:

#block(inset: (left: 12pt, y: 2pt), stroke: (left: 2pt + luma(190)))[
  *(a)* $lambda(cal(O)_K^times)$ is *discrete* in the trace-zero hyperplane $H$ --- Northcott,
  elementary. Gives: $cal(O)_K^times$ is finitely generated of rank $<= r_1 + r_2 - 1$.

  #v(1.5mm)
  *(b)* $lambda(cal(O)_K^times)$ *spans* $H$ --- Minkowski, the hard half. Gives: the rank is
  *exactly* $r_1 + r_2 - 1$.
]

Step (a) is the analogue of the entire Mordell--Weil theorem. Step (b) has *no* Mordell--Weil
analogue: its counterpart is the computation of $"rank" E(K)$, which is BSD. So Dirichlet's theorem
is Mordell--Weil *plus a rank formula*, and the extra clause carries all of the difficulty. This is
why the two proofs look unlike each other even though @sec-parallel shows they can be made to
coincide: they are not proving the same amount.

Check 3 verifies (b) on nine fields covering the signatures $[2,0]$, $[0,1]$, $[1,1]$, $[0,2]$,
$[4,0]$, $[2,1]$, $[1,2]$ --- rank $= r_1 + r_2 - 1$ in every case --- and recomputes the covolume
of the log lattice from the embeddings, matching the regulator:

#align(center, table(
  columns: 5, align: (left, center, center, right, right),
  stroke: 0.4pt + luma(170), inset: (x: 9pt, y: 3.5pt),
  table.header([field], [$[r_1, r_2]$], [rank], [$R$], [covolume]),
  [$x^2 - 2$], [$[2,0]$], [$1$], [$0.8813735870$], [$0.8813735870$],
  [$x^2 + 5$], [$[0,1]$], [$0$], [$1.0000000000$], [$1.0000000000$],
  [$x^2 - 79$], [$[2,0]$], [$1$], [$5.0751347504$], [$5.0751347504$],
  [$x^3 - 2$], [$[1,1]$], [$1$], [$1.3473773483$], [$1.3473773483$],
  [$x^3 - x - 1$], [$[1,1]$], [$1$], [$0.2811995743$], [$0.2811995743$],
  [$x^4 + x^3 + x^2 + x + 1$], [$[0,2]$], [$1$], [$0.9624236501$], [$0.9624236501$],
  [$x^4 - 10 x^2 + 1$], [$[4,0]$], [$3$], [$2.6608985802$], [$2.6608985802$],
  [$x^4 - x - 1$], [$[2,1]$], [$2$], [$0.3781993325$], [$0.3781993325$],
  [$x^5 - x - 1$], [$[1,2]$], [$2$], [$0.4323438788$], [$0.4323438788$],
))

= What the asymmetry explains <sec-explains>

The dictionary of @sec-dict leaves one puzzle open: on the $GG_m$ side the *rank* is free and the
*class number* is hard, while on the $E$ side the *rank* is the hard thing. @sec-compact answers
it, and the answer is the same fact from the other direction.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  A group whose archimedean avatar is *non-compact* has its rank pinned down by that avatar: the
  lattice lives in a Euclidean space whose dimension is visible in advance, and the only question
  is whether it fills it. A group whose archimedean avatar is *compact* has no such ambient space,
  and no archimedean invariant to read the rank off.
]

#v(2mm)
That line is where it should be. For an algebraic *torus* $T$ the rank of the $S$-unit group
$T(cal(O)_S)$ is still given by a formula in the Galois module of characters and the decomposition
groups at the places of $S$ (Ono, @sec-refs [6]) --- Dirichlet's theorem is the case
$T = GG_m$. For an abelian variety no such formula is known or expected. For a *semiabelian*
variety $1 --> T --> G --> A --> 0$ over a number field, finite generation of $G(K)$ is one
theorem covering both cases, and the rank splits into a computable toric part and an unknown
abelian part. The dividing line inside that one theorem is exactly the dividing line of
@sec-compact.

#block(fill: rgb("#fff4e6"), inset: 8pt, radius: 3pt, width: 100%)[
  *A remark on the other side of the ledger.* The class number formula puts $h$ and $R$ on the same
  side of one equation, so what one field spends on the regulator another spends on the class
  number --- `mersenne-fermat-class.typ` §4.1 watches exactly that happen at Mersenne
  discriminants, where $QQ(sqrt(-M_p))$ spends its arithmetic on $h$ and $QQ(sqrt(+M_p))$ spends
  nearly all of it on $R$. Nothing above says the $h$ side has a formula for *its* size. What it
  says is that the $R$ side is the side whose *rank* has one, and that this is an archimedean
  accident rather than a structural advantage.
]

= What the companion script checks <sec-gp>

`dirichlet-mordell-weil.gp`, results in `results/dirichlet-mordell-weil.txt`.

#v(1mm)
- *(1)* The identity of @sec-why: on twelve fundamental units across six signatures, the
  archimedean log vector sums to zero, $abs(N(u)) = 1$, and
  $(1 slash n) sum n_v log^+ abs(u)_v = norm(lambda(u))_1 slash 2n$. Zero discrepancies.
- *(2)* Northcott made exact: $h(epsilon) = R slash 2$ and
  $\#{u : h(u) <= B} = 2(2 floor(2B slash R) + 1)$ in three real quadratic fields at three bounds
  each. Zero mismatches.
- *(3)* Step (b) of @sec-realsplit: rank $= r_1 + r_2 - 1$ on nine fields, and the covolume of the
  log lattice recomputed from the embeddings equals `bnfinit`'s regulator.
- *(4)* The contrast of @sec-compact: $min_(n <= N) abs(log abs(epsilon^n))$ is constant in $N$,
  while $min_(n <= N) norm(n z slash omega)$ on `43a1` stays below $1 slash N$ at every $N$ up to
  $10^5$.
- *(5)* The contraction rates of @sec-descent: $h(epsilon^m) slash h(epsilon) = m$ against
  $hat(h)(m P) slash hat(h)(P) = m^2$, for $m = 2, ..., 6$.

= References <sec-refs>

#block(inset: (left: 4pt))[
#set enum(numbering: "[1]")
+ J. H. Silverman, *The Arithmetic of Elliptic Curves*, 2nd ed., Springer 2009. Chapter VIII: weak
  Mordell--Weil, the descent theorem VIII.3.1, and the height machinery @sec-descent is modelled
  on.
+ J.-P. Serre, *Lectures on the Mordell--Weil Theorem*, Vieweg 1989. The proof of weak
  Mordell--Weil that runs through Hermite--Minkowski rather than through the $S$-unit theorem ---
  the one @sec-weak imitates.
+ J. Neukirch, *Algebraic Number Theory*, Springer 1999. I §7 for Dirichlet's unit theorem in the
  form of @sec-realsplit; III §2 for Minkowski's discriminant bound and Hermite's theorem.
+ E. Bombieri, W. Gubler, *Heights in Diophantine Geometry*, CUP 2006. §1.5--1.6 for the absolute
  Weil height, the product formula, and Northcott's theorem; the place to read @sec-why as a
  statement about heights rather than about units.
+ S. Lang, *Fundamentals of Diophantine Geometry*, Springer 1983. The descent lemma in the general
  form stated in @sec-descent.
+ T. Ono, *Arithmetic of algebraic tori*, Ann. of Math. *74* (1961), 101--139. The unit theorem for
  tori: the rank of the $S$-unit group is archimedean local data, which is the claim
  @sec-explains rests on.
]
