\\ ec-density-bm.gp -- computations for ec-density-bm.typ.
\\ Run from this directory:
\\     gp -q -s 4000000000 ec-density-bm.gp < /dev/null > results/ec-density-bm.txt
\\
\\ Is the failure of density of E(Q) in E(Q_p) -- the phenomenon of
\\ ec-padic-closure.typ -- a Brauer-Manin obstruction / a Tate-pairing
\\ reciprocity argument?  Yes, and the two are the same argument.
\\
\\ On an elliptic curve the Brauer-Manin pairing IS the sum over places of the
\\ local Tate duality pairing
\\        E(Q_v) x H^1(Q_v, E) -> Q/Z,
\\ and reciprocity is global (Poitou-Tate/Cassels) duality.  At the level of a
\\ 2-isogeny phi : E -> E' with kernel <T>, T = (0,0), on
\\        E : y^2 = x(x^2 + a x + b),
\\ the local pairing is a HILBERT SYMBOL: the descent map sends Q to x(Q) in
\\ Q_v^* / (Q_v^*)^2, the dual class is d in Q_v^*/(Q_v^*)^2, and
\\        <Q, d>_v = (1/2) * (d, x(Q))_v .
\\ The Brauer class carrying it is the quaternion algebra A_d = (d, x) on E,
\\ which is UNRAMIFIED because div(x) = 2(T) - 2(O) has even multiplicities.
\\ Reciprocity is then Hilbert reciprocity, prod_v (d, x(Q))_v = 1.
\\
\\ Two cases are worked out:
\\   (2) conductor 128, p = 7 GOOD reduction, d = 7.
\\   (3) conductor 960, p = 3 BAD reduction (I_4), d = 3.
\\ In each, inv_v A = 0 at every place v != p and every local point, so
\\ reciprocity forces inv_p A = 0 at every RATIONAL point, while inv_p A = 1/2
\\ somewhere on E(Q_p).  That open set contains no rational point: non-density,
\\ proved by Brauer-Manin.
\\ (4) records what quaternion classes can and cannot reach.

\\ ------------------------------------------------------------------ utilities

\\ is z a square in Q_p ?
issqQp(z, p) =
{ if (z == 0, return(1));
  my(m = valuation(z, p));
  if (m % 2, return(0));
  my(u = z / p^m);
  if (p == 2, return(Mod(numerator(u),8) / Mod(denominator(u),8) == Mod(1,8)));
  kronecker(numerator(u) * denominator(u), p) == 1;
}

\\ rational representatives of S_v = x(E(Q_v)) inside Q_v^*/(Q_v^*)^2.
\\ The 2-torsion point (0,0) contributes the class of b by definition.
Svreps(a, b, v, EMAX, NMAX) =
{ my(L = List([b]));
  for (e = -EMAX, EMAX,
    for (n = 1, NMAX,
      if (n % v == 0, next);
      foreach ([1,-1], sg,
        my(x = sg*n*v^e, fx = sg*n*v^e * ((sg*n*v^e)^2 + a*(sg*n*v^e) + b));
        if (fx != 0 && issqQp(fx, v), listput(L, x)))));
  Vec(L);
}

cden(Q) = if (Q == [0], 0, sqrtint(denominator(Q[1])));

\\ |E(Q_p)/E_1(Q_p)|
Nquot(E, p) =
{ my(a = ellap(E,p));
  if (Mod(E.disc,p) != 0, p+1-a, elllocalred(E,p)[4] * (p - a));
}

\\ index of the image of <gens> in E(Q_p)/E_1(Q_p)
idxE1(E, gens, p, N) =
{ my(r = #gens, tot = 0, cnt = 0);
  forvec (n = vector(r, i, [0, N-1]),
    my(R = [0]);
    for (i = 1, r, if (n[i], R = elladd(E, R, ellmul(E, gens[i], n[i]))));
    tot++;
    if (R == [0] || Mod(cden(R), p) == 0, cnt++));
  N * cnt / tot;
}

singpt(E, p) =
{ my(a1=E.a1, a2=E.a2, a3=E.a3, a4=E.a4, a6=E.a6);
  for (x = 0, p-1, for (y = 0, p-1,
    if (Mod(y^2 + a1*x*y + a3*y - x^3 - a2*x^2 - a4*x - a6, p) == 0 &&
        Mod(a1*y - 3*x^2 - 2*a2*x - a4, p) == 0 &&
        Mod(2*y + a1*x + a3, p) == 0, return([x,y]))));
  [];
}

\\ the full worked case
worked(a, b, p, d) =
{ my(E = ellinit([0,a,0,b,0]), g, gens, N, S2, lr, good);
  good = (Mod(E.disc, p) != 0);
  g = ellrank(E);
  gens = concat(ellsaturation(E, g[4], 200), elltors(E)[3]);
  N = Nquot(E, p);
  print("  E : y^2 = x^3 + ", a, "x^2 + ", b, "x");
  print("      conductor ", ellglobalred(E)[1], ",  min disc ", E.disc, " = ",
        factor(E.disc));
  print("      rank ", g[1], " (certified ", g[1] == g[2],
        "),  analytic rank ", ellanalyticrank(E)[1],
        ",  torsion ", elltors(E)[1]);
  print("      E(Q) generated by ", gens);
  if (good,
    print("      p = ", p, " : GOOD reduction, E(F_p) = ", ellgroup(E,p),
          " of order ", N),
    lr = elllocalred(E,p);
    print("      p = ", p, " : BAD reduction, Kodaira ", lr[2],
          " (4+n = I_n), c_p = ", lr[4], ", a_p = ", ellap(E,p));
    print("      singular point mod p = ", singpt(E,p),
          ",   |E(Q_p)/E_1(Q_p)| = ", N));
  print("      index of the closure, by the filtration method of");
  print("      ec-padic-closure.typ : ", idxE1(E, gens, p, N));
  print("");
  print("      the Brauer class is  A = (", d, ", x).");
  print("      div(x) = 2(T) - 2(O) with T = (0,0), so every residue is trivial");
  print("      and A lies in Br(E); inv_v A(Q) = 1/2 iff (", d, ", x(Q))_v = -1.");
  print("");
  print("      inv_oo A = 0 : x^2 + ", a, "x + ", b, " has discriminant ",
        a^2 - 4*b, " < 0, so it is positive,");
  print("        hence y^2 = x * (positive) forces x >= 0 at every real point.");
  print("      inv_v A = 0 for every odd v != ", p, " : if v_v(x) > 0 then");
  print("        x^2+", a, "x+", b, " = ", b, " mod v is a unit (v is good, so v does not divide b),");
  print("        so v_v(y^2) = v_v(x) is even; and v_v(x) < 0 gives x = A/C^2.");
  print("        So every class in S_v is a UNIT class, and the Hilbert symbol of");
  print("        two units at an odd place is trivial.");
  S2 = Svreps(a, b, 2, 3, 60);
  print("      inv_2 A = 0 : checked on ", #S2, " representatives of S_2, values ",
        Set(apply(x -> hilbert(d, x, 2), S2)));
  print("");
  print("      so at a RATIONAL point every term but v = ", p,
        " vanishes, and Hilbert");
  print("      reciprocity  prod_v (", d, ", x(Q))_v = 1  forces inv_", p, " A = 0.");
  print("");
  print("        Q                          inv_oo  inv_2  inv_", p,
        "   product over all v");
  my(G = gens[1], T = if (#gens > 1, gens[2], [0]));
  for (n = 1, 8,
    foreach ([0,1], e,
      my(Q = ellmul(E,G,n));
      if (e && T != [0], Q = elladd(E,Q,T));
      if (e && T == [0], next);
      if (Q == [0] || Q[1] == 0, next);
      my(x = Q[1], ps = factor(2*p*abs(numerator(x)*denominator(x)))[,1]);
      my(pr = hilbert(d,x,0));
      for (j = 1, #ps, pr *= hilbert(d,x,ps[j]));
      print("     ", if (#Str(Q) > 26, Str("(", n, "G", if(e,"+T",""), ")"), Q),
            "        ", (1-hilbert(d,x,0))/2, "      ", (1-hilbert(d,x,2))/2,
            "      ", (1-hilbert(d,x,p))/2, "         ", pr)));
  print("");
  print("      but inv_", p, " A = 1/2 somewhere on E(Q_", p, ") :");
  for (x0 = 1, 500,
    my(fx = x0*(x0^2 + a*x0 + b));
    if (fx != 0 && issqQp(fx, p) && hilbert(d, x0, p) == -1,
      print("        x = ", x0, " : x(x^2+", a, "x+", b, ") = ", fx,
            " is a square in Q_", p, ",");
      print("        so E(Q_", p, ") has a point with x = ", x0, ", and (", d,
            ",", x0, ")_", p, " = -1.");
      break));
  print("      That open set contains NO rational point.  E(Q) is not dense in E(Q_",
        p, ").");
  print("");
}

\\ ---- helpers for section (5): 2-descent over the cubic etale algebra
POL5 = x^3 - 16*x + 16;
pair5(L, X, d, v, rts) =
{ my(a = Mod(X - x, POL5), r = 1);
  if (v == 0,
    for (j = 1, #rts, if (X - rts[j] < 0 && subst(lift(d), x, rts[j]) < 0, r = -r)),
    foreach (idealprimedec(L, v), pr, r *= nfhilbert(L, a, d, pr)));
  r;
}

print("=========================================================================");
print(" Non-density of E(Q) in E(Q_p) as a Brauer-Manin obstruction");
print("=========================================================================");
print("");

print("(1) The general statement.");
print("    Br_1(E)/Br_0(E) = H^1(Q, Pic E-bar) = H^1(Q, E), and for beta in");
print("    H^1(Q,E) the invariant of the corresponding Brauer class at a local");
print("    point is the LOCAL TATE PAIRING <Q_v, beta_v>_v.  Reciprocity,");
print("    sum_v <Q, beta_v>_v = 0 for Q in E(Q), is global duality.  So");
print("    'Tate pairing + reciprocity' and 'Brauer-Manin' are one argument.");
print("    Manin's theorem: if Sha(E) is finite then the Brauer-Manin set is");
print("    EXACTLY the closure of E(Q) in the adelic points.  Both curves below");
print("    have analytic rank 1, so Gross-Zagier + Kolyvagin make Sha finite and");
print("    the theorem applies unconditionally to them.");
print("");

print("-------------------------------------------------------------------------");
print("(2) GOOD reduction: conductor 128 at p = 7, with A = (7, x).");
print("");
worked(-2, 2, 7, 7);

print("-------------------------------------------------------------------------");
print("(3) BAD reduction: conductor 960 at p = 3 (type I_4), with A = (3, x).");
print("");
worked(-4, 9, 3, 3);

print("-------------------------------------------------------------------------");
print("(4) What a quaternion class can and cannot reach.");
print("");
{
print("    A class of order 2 in Br(E) cuts out a subgroup of index at most 2, so");
print("    it can only ever explain an index-2 failure.  The examples of");
print("    ec-padic-closure.typ with larger index need classes of larger order:");
print("");
print("      curve (conductor)          p    total index   order needed   comment");
foreach ([[[0,0,1,-1,0], 23, "37"], [[0,0,1,-1,0], 59, "37"],
          [[1,1,1,-1,0], 11, "89"], [[0,1,1,0,0], 43, "43"]], t,
  my(E = ellinit(t[1]), p = t[2]);
  my(g = ellrank(E), gens = concat(ellsaturation(E,g[4],100), elltors(E)[3]));
  my(N = Nquot(E,p), P = gens[1], Q = gens[1], m = 0, v, tot);
  for (k = 1, 500, if (Q != [0] && Mod(cden(Q), p) == 0, m = k; break);
                   Q = elladd(E,Q,P));
  v = valuation(cden(Q), p);
  tot = (N/m) * p^(v-1);
  print("      ", t[1], " (", t[3], ")      ", p, "      ", tot,
        "        ", if (tot == 1, "-", tot),
        "      ", if (tot == 2, "quaternion algebra suffices",
                      Str("needs order ", tot, ": NOT a quaternion algebra"))));
print("");
print("    The index-11 failure at conductor 89, p = 11 -- the formal-group layer");
print("    E_1/E_2 -- therefore cannot be seen by ANY quaternion algebra.  Manin's");
print("    theorem still applies (Sha is finite there), so a Brauer class of order");
print("    11 does the job, but it is not an algebra one writes down by hand.");
print("    The moral: BM explains all of it, but the EXPLICIT quaternion story");
print("    reaches exactly the index-2 part -- which is the reduction layer, and");
print("    is where 2-descent lives.");
}
print("");
\\ ------------------------- (5) is a rational 2-isogeny needed?  NO.

print("-------------------------------------------------------------------------");
print("(5) Does an index-2 failure require a 2-isogeny over Q?  NO.");
print("    A 2-isogeny over Q means a Galois-stable kernel of order 2, i.e. a");
print("    RATIONAL 2-torsion point.  What the argument actually needs is a class");
print("    of order 2 in Br(E), i.e. a class in H^1(Q, E[2]) -- and full 2-descent");
print("    on E[2] exists for every curve.  The isogeny was only a CONVENIENCE: it");
print("    puts the descent map into Q*/(Q*)^2, so the pairing is a Hilbert symbol");
print("    over Q and the class is one quaternion algebra with CONSTANT entries.");
print("    Without it one works over the cubic etale algebra L = Q[t]/(f), the");
print("    descent map is Q -> X(Q) - theta in L*/(L*)^2, the pairing is");
print("    prod_{w|v} (X(Q)-theta, d)_w over the places of L, and the Brauer class");
print("    is the CORESTRICTION cor_{L(E)/Q(E)} (d, X - theta) -- still unramified,");
print("    since div(X-theta) = 2(T_theta) - 2(O) is even and corestriction");
print("    preserves that, and still of order 2.  It is simply not a quaternion");
print("    algebra over Q(E) with constant slots.");
print("");
{
my(E = ellinit([0,0,0,-16,16]), L, rts, d, P, Q);
print("    The decisive example is the FIRST curve of these notes:");
print("      E : Y^2 = X^3 - 16X + 16    (conductor ", ellglobalred(E)[1],
      ", the model X = 4x, Y = 8y+4 of y^2+y = x^3-x)");
print("      isogeny class size = ", #ellisomat(E,,1)[1],
      "  -> NO rational isogeny of ANY degree,");
print("      t^3-16t+16 irreducible over Q : ", polisirreducible(x^3-16*x+16),
      "  -> E[2] irreducible, Galois group S_3.");
print("      Yet the closure of E(Q) in E(Q_23) has index 2 (section 2 of");
print("      ec-padic-closure.typ).  Here is the order-2 class that proves it.");
L = bnfinit(POL5, 1);
rts = [real(z) | z <- polroots(POL5)];
d = Mod(1/4*x^2 - 2*x - 11, POL5);
print("");
print("      L = Q(theta), theta^3 = 16 theta - 16 :  disc ", L.disc,
      ", class number ", L.no, ", signature ", L.sign);
print("      d = ", lift(d), "   N(d) = ", nfeltnorm(L,d), " = ",
      sqrtint(nfeltnorm(L,d)), "^2");
print("        (square norm is exactly the condition for d to lie in");
print("         H^1(Q,E[2]) = ker(N : L*/L*^2 -> Q*/Q*^2))");
my(fa = idealfactor(L,d));
print("      the ideal (d) = one prime above 23 of residue degree ",
      fa[1,1].f, ", exponent ", fa[1,2], " -- so d is a unit away from 23.");
print("");
print("      pairing prod_{w|v} (X(Q)-theta, d)_w on the rational points nP,");
print("      P = (0,4) the saturated generator:");
print("         n     X(nP)          v=oo   v=2   v=23   v=37   product");
P = [0,4]; Q = P;
for (n = 1, 8,
  my(X = Q[1], ps = Set(concat([0,2,23,37],
      factor(2*23*37*abs(numerator(X)*denominator(X)))[,1]~)), pr = 1);
  foreach (Vec(ps), v, pr *= pair5(L,X,d,v,rts));
  print("         ", n, "   ", if (#Str(X) > 14, "(large)", X), "            ",
        pair5(L,X,d,0,rts), "     ", pair5(L,X,d,2,rts), "     ",
        pair5(L,X,d,23,rts), "      ", pair5(L,X,d,37,rts), "      ", pr);
  Q = elladd(E,Q,P));
print("");
print("      the pairing is +1 at v = oo, 2, 37 for EVERY local point (checked by");
print("      scanning X in Q_v with X^3-16X+16 a v-adic square), and at every other");
print("      v it is +1 because v_w(X(Q)-theta) is even outside 2 and the bad");
print("      primes while d is a unit there.  Reciprocity over L then forces the");
print("      v = 23 factor to be +1 at every RATIONAL point -- as the table shows.");
print("");
print("      but at X = -1 : X^3-16X+16 = ", (-1)^3-16*(-1)+16,
      ", a square in Q_23 (", (-1)^3-16*(-1)+16, " = ",
      lift(Mod((-1)^3-16*(-1)+16,23)), " mod 23, a residue),");
print("      so E(Q_23) has a point with X = -1, and there");
print("         prod_{w|23} (X-theta, d)_w = ", pair5(L,-1,d,23,rts));
print("      That 23-adic neighbourhood contains no rational point.");
}
print("");
print("    So: no 2-isogeny, no rational 2-torsion, no isogeny at all -- and still");
print("    an index-2 Brauer-Manin obstruction.  The implication in the other");
print("    direction is what is true: a rational 2-isogeny makes the class a");
print("    single quaternion algebra, which is why sections 2 and 3 look simple.");
print("");

\\ ------------------- (6) why index 4 and index 11 are harder

print("-------------------------------------------------------------------------");
print("(6) Index 4 and index 11: n-descent exists for every n, so why are these");
print("    harder?  Three reasons, of increasing severity.");
print("");
{
my(E, P, p, G, Ep, m);
print("    (i) THE ORDER OF THE CLASS IS FORCED.  The local quotient is cyclic:");
E = ellinit([0,0,1,-1,0]); P = [0,0]; p = 59;
G = ellgroup(E,p); Ep = ellinit(E,p);
m = ellorder(Ep, [Mod(P[1],p), Mod(P[2],p)]);
print("      conductor 37, p = 59 : E(F_59) = Z/", G[1], " cyclic, ord(Pbar) = ", m,
      ",");
print("        and 13P is in E_1 but not E_2, so Gamma contains E_1 and");
print("        E(Q_59)/Gamma = Z/", G[1], " mod Z/", m, " = Z/", G[1]/m,
      "  -- CYCLIC of order 4.");
my(E2 = ellinit([1,1,1,-1,0]), q = 11);
print("      conductor 89, p = 11 : reduction is ONTO E(F_11) = Z/",
      ellgroup(E2,q)[1], ", and 14P lies in E_2,");
print("        so E(Q_11)/Gamma = E_1/E_2 = Z/11  -- CYCLIC of order 11.");
print("      A family of classes of order 2 cuts out a quotient of EXPONENT 2, so");
print("      it can never produce Z/4.  Index 4 needs a class of order 4, index 11");
print("      one of order 11.");
print("");
print("      How much does each n-descent see at p = 59?  (E(F_59) is cyclic of");
print("      order 52, Pbar has order 13, so Pbar lies in nE(F_59) iff 52/gcd(n,52)");
print("      is a multiple of 13.)");
foreach ([2,4,13,26,52], n,
  my(g = 52, idx = gcd(n,g), sees = ((g/idx) % m == 0));
  print("        n = ", n, " : E(F_p)/nE(F_p) = Z/", idx,
        ",  image of E(Q) ", if (sees, "trivial", "nontrivial"),
        "  -> n-descent sees index ", if (sees, idx, 1)));
print("      so 2-descent already gets a factor 2 of the 4; the last factor 2");
print("      needs 4-descent.  Nothing smaller will do.");
}
print("");
print("    (ii) THE DESCENT ALGEBRA GROWS.  For n = 2 it is the CUBIC etale algebra");
print("      L = Q[t]/(f) -- which is why section 5 fits on a page.  For n = 11:");
{
my(E2 = ellinit([1,1,1,-1,0]), f11 = elldivpol(ellinit([1,1,1,-1,0]),11));
print("      conductor 89, deg elldivpol(E,11) = ", poldegree(f11),
      " = (11^2-1)/2, and it factors over Q with degrees ",
      [poldegree(factor(f11)[j,1]) | j <- [1..#factor(f11)~]], " -- irreducible,");
print("      so nothing collapses.  |GL_2(F_11)| = ", (11^2-1)*(11^2-11),
      " bounds [Q(E[11]):Q].");
print("      Also, a degree-n cyclic algebra needs mu_n, and mu_n is in Q only for");
print("      n = 2; for n > 2 one builds over Q(mu_n) and corestricts.");
}
print("");
print("    (iii) WILDNESS AT THE PLACE WHERE DETECTION HAPPENS -- the real wall.");
print("      The n-th norm residue symbol at v is TAME exactly when v does not");
print("      divide n:");
{
foreach ([[2,59],[2,2],[4,59],[4,2],[11,11]], t,
  print("        n = ", t[1], ", v = ", t[2], " : ",
        if (t[1] % t[2] == 0, "WILD", "tame")));
}
print("      Index 4 at p = 59 : 59 does not divide 4, so the symbol is TAME at");
print("        the place where the class must be non-trivial.  (It is wild at");
print("        v = 2, but there one only needs VANISHING, and that wildness is the");
print("        classical mod-8 kind.)");
print("      Index 11 at p = 11 : n = p.  Wild exactly where detection happens.");
print("");
print("      And this is STRUCTURAL, not bad luck.  E_1(Q_p) = Z_p is pro-p, so");
print("      every finite quotient of the formal group is a p-group; cutting");
print("      E_1/E_2 = Z/p always demands a class of order p evaluated at the place");
print("      p.  By contrast E_0/E_1 has order p+1-a_p (good) or p -+ 1 (multiplic-");
print("      ative), prime to p away from anomalous primes -- the tame world.");
print("      So the filtration of ec-padic-closure.typ is also a TAME/WILD");
print("      filtration: the top layers are tame and explicitly reachable, the");
print("      formal-group layer is wild.");
print("");
print("    Tooling: PARI's nfhilbert is literally 'X^2 - aY^2 - bZ^2 has a");
print("    solution' -- quadratic only, no exponent argument; Sage's");
print("    hilbert_symbol likewise.  Neither has an n-th norm residue symbol for");
print("    n > 2.  These notes already hit that exact wall in descent-s3.typ,");
print("    which needed a CUBIC norm-residue symbol at the wild place v = 3.");
print("    The index-11 case is the same gap, one prime up: not blocked by");
print("    mathematics, blocked by an unimplemented wild symbol.");
print("");

\\ -------------- (7) is Brauer-Manin just descent, repackaged?

print("-------------------------------------------------------------------------");
print("(7) Is Brauer-Manin just the n-descents, repackaged?");
print("");
print("    For an elliptic curve, essentially YES and the identification is EXACT:");
print("    E-bar is a curve over an algebraically closed field, so Br(E-bar) = 0 by");
print("    Tsen -- an elliptic curve has NO transcendental Brauer group.  Hence");
print("      Br(E) = Br_1(E),   Br(E)/Br_0(E) = H^1(Q,E) = union_n H^1(Q,E)[n],");
print("    and H^1(Q,E)[n] = coker(E(Q)/n -> H^1(Q,E[n])) is exactly the output of");
print("    n-descent.  Nothing is left over.  For a fixed (E,p) one n suffices (the");
print("    exponent of the finite group E(Q_p)/Gamma); across all p you need");
print("    n -> infinity along p-powers, since the formal group is Z_p.");
print("");
print("    Three qualifications:");
print("");
print("    (1) It is a DUALITY, not a restatement.  Descent cuts down H^1(Q,E[n])");
print("        using the local conditions W_v and bounds the GROUP; Brauer-Manin");
print("        cuts down prod_v E(Q_v) using classes and bounds the CLOSURE.");
print("        The sharpening: A_beta vanishes at every v != p iff beta_v is in");
print("        W_v^perp = W_v there, and detects at p iff beta_p is not in W_p.  So");
print("        the classes that obstruct at p are exactly Sel_n^(p) / Sel_n, the");
print("        Selmer group RELAXED at p modulo the honest one.");
{
my(E = ellinit([0,0,1,-1,0]), r = ellrank(E));
print("        For conductor 37 at p = 23, n = 2 :  ellrank = ", r);
print("          rank ", r[1], ", torsion ", elltors(E)[1], ", Sha[2] = ", r[3],
      "  ->  dim Sel_2 = ", r[1] + r[3]);
print("          and d = theta^2/4 - 2theta - 11 of section 5 lies in Sel_2^(23)");
print("          but not in Sel_2, so dim Sel_2^(23) >= 2.  Whether such a class");
print("          exists is a Greenberg-Wiles computation, not a formality --");
print("          see selmer-local-conditions.typ.");
}
print("");
print("    (2) That the descents see EVERYTHING is a theorem.  closure(E(Q)) is");
print("        contained in the Brauer-Manin set formally (reciprocity); the");
print("        REVERSE inclusion is Manin's theorem and needs Sha finite, proved");
print("        via Poitou-Tate and the Cassels-Tate pairing.  Unconditional here");
print("        only because these curves have analytic rank 1.");
print("");
print("    (3) The equivalence is special to E.  Off an abelian variety there is no");
print("        group law, no isogeny and no n-descent, but there is still a Brauer");
print("        group and still sum_v inv_v = 0 -- e.g. the class (2, x+4) on the");
print("        negative Pell conic of integral-bm.typ is not an n-descent class of");
print("        anything.  The packaging buys PORTABILITY; on E it buys nothing new.");
print("");

print("done.");
