#set page(
  paper: "a4",
  margin: (x: 2.2cm, y: 2.4cm),
  numbering: "1",
)
#set text(size: 10.5pt, lang: "en")
#set par(justify: true, leading: 0.62em)
#set heading(numbering: none)

#show heading.where(level: 1): it => block(above: 1.6em, below: 0.9em)[
  #set text(size: 15pt, weight: "bold")
  #it.body
]
#show heading.where(level: 2): it => block(above: 1.25em, below: 0.7em)[
  #set text(size: 12pt, weight: "bold")
  #it.body
]
#show heading.where(level: 3): it => block(above: 1.1em, below: 0.55em)[
  #set text(size: 11pt, weight: "bold", style: "italic")
  #it.body
]

#let thm(name, body) = block(
  width: 100%,
  inset: 10pt,
  radius: 3pt,
  stroke: 0.6pt + luma(140),
  fill: luma(250),
)[
  *#name.* #body
]

#align(center)[
  #text(size: 18pt, weight: "bold")[
    Is it monodromy?
  ]

  #v(0.4em)
  #text(size: 11pt, style: "italic")[
    Part IV: closed paths, web holonomy, and the cross-ratio $lambda$
  ]

  #v(0.3em)
  #text(size: 9.5pt)[
    Companion to #emph[Orders from a pair of elliptic fibrations]
  ]
]

#v(1.2em)

#block(
  width: 100%,
  inset: 10pt,
  radius: 3pt,
  fill: luma(245),
)[
  *The question.* The construction feels monodromy-like: one builds a closed
  path, going from $P$ to $Q$ and back to $P$, entirely by multiplication along
  fibres. Is there a relation to monodromy around $P_0$?

  *Short answer.* The instinct points at something real, but the precise word is
  *holonomy of a pseudogroup*, not monodromy of a local system. The distinction
  matters, and pinning it down explains two things that otherwise look like
  coincidences: why a _cross-ratio_ appeared, and why the round trip — rather
  than a single hop — is what carries the invariant.

  Notation is as in Parts I–III: $f_1, f_2$ are the two elliptic fibrations,
  $Omega_i (x)$ the $f_i$-orbit closure of $x$, $z_i$ the local height functions
  cutting out the torsion multisections through $P_0$, and
  $lambda = alpha gamma$ the cross-ratio introduced in Theorem B.
]

= 1. The closed path is real, and it breaks antisymmetry

The observation is sharper than it may first appear. In Theorem A we produce $Q$
with $p^k Q = P$. But then $P$ is literally a multiple of $Q$, so
$
  P <_1 Q #h(2em) "and" #h(2em) Q < P .
$
So $<$ is *not antisymmetric* near $P_0$: it is only a preorder, and the loop in
question is exactly its symmetric part. This gives the local structure a clean
description.

- The symmetric part $tilde$ of $<$ is the *orbit equivalence relation of the
  pseudogroup* $Gamma_U$ generated by the two fibrewise translation actions
  restricted to $U$.
- $<$ descends to a genuine partial order on $U slash tilde$.
- Theorem A says exactly: near a $P_0$ torsion on $f_1$, the local preorder has
  nontrivial symmetric part, i.e. $Gamma_U$ has fat orbits. Theorem B computes
  those orbits: they are the level sets of
  $A(x) = max(abs(z_1 (x)), abs(gamma z_2 (x)))$.

So "closed path" $=$ "orbit of a holonomy pseudogroup", and the order-theoretic
shadow of the loop is failure of antisymmetry. That is the honest translation of
the intuition.

= 2. The right frame: web geometry

Here is the thing that genuinely deserves the name being reached for.

A germ of *two* transverse foliations on a surface has _no_ local invariants: one
can always straighten both simultaneously into a product. That is precisely the
collapse of Part II. If the two elliptic fibrations were all we had, nothing could
ever escape.

What we actually have is four foliations at $P_0$.

#table(
  columns: (0.75fr, 1.4fr),
  inset: 9pt,
  align: left + top,
  stroke: 0.5pt + luma(180),
  table.header([*Foliation*], [*Meaning*]),

  [${t_1 = c}$], [the $f_1$-fibres],
  [${t_2 = c}$], [the $f_2$-fibres],
  [${z_1 = c}$],
  [constant $f_1$-height: the $f_1$-torsion multisections and their translates],
  [${z_2 = c}$], [the same for $f_2$],
)

That is a *$4$-web germ*. And the classical fact is: $d$-webs in the plane have no
local invariants for $d <= 2$; a $3$-web has the Blaschke curvature, a function;
and a $d$-web with $d >= 4$ already has a _pointwise_ invariant, namely the
*cross-ratio of the $d$ tangent directions*.

So
$
  lambda = (T O_2, T O_1 ; T F_1, T F_2)
$
is not an accident of the chosen normalisation — it is the first web invariant of
the configuration, and it is forced to appear. This is the strongest evidence that
the phenomenon is web holonomy rather than anything else.

= 3. Why it is not literally monodromy

Two obstructions to the naive reading.

/ No loop around $P_0$: Over $CC$, the set $U without {P_0}$ is simply connected in
  complex dimension $2$, since it retracts to $S^3$. There is nothing to go
  around.

/ Wrong kind of degeneration: Monodromy of an elliptic fibration lives around
  _singular_ fibres and acts on $H_1$ of the nearby fibre. But in Theorems A and
  B, $P_0$ sits on two perfectly smooth fibres meeting transversally. Nothing
  about the fibrations degenerates at $P_0$. What degenerates is the
  *section-level* structure: $P_0$ is torsion, so $abs(ell_1)$ collapses, so
  $Omega_1$ collapses. That is a Mordell–Weil phenomenon, not a Kodaira one.

= 4. Where the analogy nonetheless becomes tight

There _is_ a divisor to go around: $D = { z_1 z_2 = 0 }$, the two torsion
multisections through $P_0$, meeting normally at $P_0$. Then
$U without D tilde.eq (CC^*)^2$ and $pi_1 = ZZ^2$, generated by the two meridians.
The "loop around $P_0$" is their product, the boundary of the normal crossing.
This is exactly the configuration in which a local monodromy invariant is supposed
to live, and $lambda$ is its avatar.

Better still, the dichotomy of Theorems B and B$'$ is _literally_ the
classification of a holonomy germ by its multiplier:

- $abs(lambda)_p <= 1$: the round-trip map is non-expanding, $A$ is a Lyapunov
  function, orbits are trapped in balls, and one hop already saturates — nothing
  is gained by iterating;
- $abs(lambda)_p > 1$: expanding germ; each round trip multiplies the scale by
  $abs(lambda)$, and orbits escape to the boundary of $U$.

That is the $p$-adic version of the attracting/repelling — Siegel versus Poincaré
— dichotomy for germs of analytic diffeomorphisms fixing a point. So $lambda$
behaves in every respect like a *holonomy multiplier of the web at $P_0$*, with
$abs(lambda)$ as its eigenvalue.

*And this is exactly why the round trip matters.* A single hop is governed by
$gamma$, which is _not_ an invariant: it depends on the normalisation of
$z_1, z_2$. Only the closed loop produces $alpha gamma$, which is. The intuition
that the closed path is the essential object is correct precisely at this level:
the invariant is a property of loops, not of paths.

= 5. Where honest monodromy really does enter

Three places, all arithmetic rather than local-analytic.

+ *Which $Q$ exist rationally.* The set ${ Q : p^k Q = P }$ is a torsor under
  $F_1 (P)[p^k]$, and how many of its points are $QQ_p$-rational is governed by
  the image of Galois in $"GL"_2 (ZZ_p)$ acting on the Tate module. Theorem A
  gives divisibility in the formal group; the count and field of definition of the
  $Q$'s is a monodromy question.

+ *Why ${z_1 = 0}$ is a multisection.* Its degree over $PP^1$ is exactly the size
  of the monodromy orbit of the torsion point $P_0$ in $F_1 [n]$. So the geometric
  object whose vanishing creates the whole phenomenon is _defined by_ the
  monodromy of $f_1$.

+ *Globally*, the interaction of the two fibrations — the intersection number
  $F_1 dot.op F_2$ of Part I — is controlled by monodromy on $op("NS")(S)$ and by
  the Mordell–Weil lattices of the two fibrations, via Shioda–Tate.

= 6. A caveat about the mechanism

One place where the web picture is not the whole story. The escape in Theorem B is
not driven by non-commutativity of two flows. Writing $X_i$ for the fibrewise
translation fields, one checks
$
  X_1 = partial_(z_1) - alpha partial_(z_2), #h(2em)
  X_2 = partial_(z_2) - gamma partial_(z_1)
$
to leading order, and these commute at that order. If they generated an honest
two-dimensional abelian action, then
$op("orbit")(P) ∩ F_1 (P) = Omega_1 (P)$ exactly, and nothing would escape.

What actually drives it is that the flows are *step-size constrained*, the allowed
step at $x$ being $abs(z_i (x))$, which degenerates along $z_i = 0$. One hops
along $F_2$ to a point where $abs(z_1)$ is _larger_, takes a correspondingly
larger $F_1$-step there, and returns. So the primitive condition for a single hop
is just $gamma != 0$, i.e. *the $f_1$-torsion multisections are not
$f_2$-invariant*.

This makes the phenomenon closer to a sub-Riemannian, or bounded-generation,
reachability problem than to curvature. The web-holonomy language becomes the
right one only at the level of the _iterated_ loop, where $lambda$ takes over —
which is again the point about closed paths.

= A question to push on

Can the "collapse to a preorder with fat symmetric part" be axiomatised? Given a
germ of a $d$-web with a compatible filtration by allowed step sizes, is the
reachability preorder always determined by finitely many cross-ratio-type
invariants?

Theorem B says yes for $d = 4$ with $abs(lambda) <= 1$, where one hop saturates.
What happens over a degree-$d$ extension $K slash QQ_p$ — where the fibres carry
$ZZ_p^d$ and the step constraint becomes genuinely directional — is unclear, and
that looks like where a real holonomy _representation_, rather than a single
multiplier, would have to appear.
