#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show link: set text(fill: blue.darken(20%))
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#align(center)[
  #text(size: 16pt, weight: "bold")[The Jacobian is a different]
  #v(2mm)
  #text(size: 10pt)[An intrinsic form of Hensel's lemma: the coordinate-free invariant is
  $"Fitt"_0 (Omega_(X slash cal(O)))$, and $v(det J)$ is the length of the differentials along
  the point]
  #v(1mm)
  #text(size: 9pt, style: "italic")[on a question of Rene Pannekoek]
]

#v(4mm)

= The question, and the answer in one line <sec-answer>

Let $cal(O) = cal(O)_v$ be the ring of integers of $K_v$, complete, with uniformiser $pi$, maximal
ideal $frak(m)$ and residue field $k_v$. Given $F_1, dots, F_n in cal(O)[x_1, dots, x_n]$ and an
approximate solution $a in cal(O)^n$, the multivariate Hensel lemma reads:

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Hensel (Newton), coordinate version.* Let $J = (partial F_i slash partial x_j)$ and
  $e = v(det J(a))$. If
  $ F(a) equiv 0 mod frak(m)^(2e+1) , $
  then there is a unique $x in cal(O)^n$ with $F(x) = 0$ and $x equiv a mod frak(m)^(e+1)$.
]

The question is what $e$ *is*, since $det J$ depends on the chosen equations and the chosen
coordinates. The answer is that $det J$ is not really a function but a *generator of an ideal
sheaf*, and that ideal sheaf is intrinsic:

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *The invariant is the Kähler different*
  $ frak(d)_(X slash cal(O)) = "Fitt"_0 (Omega_(X slash cal(O))) subset.eq cal(O)_X , $
  the zeroth Fitting ideal of the sheaf of relative differentials. It is defined with no reference
  to coordinates; for a *square* system it is generated by $det(partial F_i slash partial x_j)$; and
  its value along a section $a$ is
  $ v(det J(a)) = "length"_(cal(O)) (a^* Omega_(X slash cal(O))) . $
  Hensel's lemma then says: *an approximate point lifts as soon as it is a solution to precision
  better than the square of the different.* The failure of étaleness is the whole content of $e$,
  and $frak(d)$ is what measures it.
]

So the guess in the question is right --- it is the sheaf of differentials --- and the precise
functional attached to it is the zeroth Fitting ideal. @sec-fitting through @sec-hensel make this exact.
@sec-why explains why $Omega$ *has* to be the answer, from deformation theory. @sec-meaning says
what $e$ measures in three familiar situations, one of which explains a constant in these notes that
has never been given a reason: why square classes at $v = 2$ need $a$ modulo $8$, and at odd $v$ only
$a$ modulo $v$.

= Fitting ideals, and why they are coordinate-free <sec-fitting>

Let $R$ be a ring and $M$ a finitely presented $R$-module, with presentation
$ R^r -->^Phi R^s --> M --> 0 . $

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Definition.* $"Fitt"_i (M)$ is the ideal of $R$ generated by the $(s-i) times (s-i)$ minors of
  $Phi$ (with the conventions $"Fitt"_i = R$ for $i >= s$, and the empty minor equal to 1).

  #v(2mm)
  *Theorem (Fitting).* $"Fitt"_i (M)$ depends only on $M$, not on the chosen presentation. It
  commutes with base change: $"Fitt"_i (M ⊗_R R') = "Fitt"_i (M) R'$.
]

That single sentence is the whole mechanism by which a coordinate computation becomes an invariant.
Two further facts are used below.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Lemma 2.1.* $"Ann"(M)^s subset.eq "Fitt"_0 (M) subset.eq "Ann"(M)$. In particular
  $"Fitt"_0 (M) = R$ if and only if $M = 0$.

  #v(2mm)
  *Lemma 2.2.* Let $R$ be a discrete valuation ring and $Phi$ an $s times s$ matrix over $R$ with
  $det Phi != 0$. Then
  $ "length"_R ("coker" Phi) = v(det Phi) . $

  #v(1.5mm)
  _Proof._ Smith normal form: $Phi = U D V$ with $U, V in "GL"_s (R)$ and
  $D = "diag"(pi^(a_1), dots, pi^(a_s))$. Then $"coker" Phi tilde.equiv ⊕_i
  R slash pi^(a_i)$, of length $sum_i a_i = v(det D) = v(det Phi)$. $qed$
]

= The Kähler different <sec-kahler>

Let $X -> "Spec" cal(O)$ be locally of finite type.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Definition* (#link("https://stacks.math.columbia.edu/tag/0BVV")[Stacks 0BVV, 0BVW])*.* The
  *Kähler different* of $X slash cal(O)$ is
  $ frak(d)_(X slash cal(O)) = "Fitt"_0 (Omega_(X slash cal(O))) , $
  a quasi-coherent sheaf of ideals on $X$.
]

Three properties, all in the Stacks project's chapter on discriminants and differents, and all
exactly what is needed.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *(K1) It computes the Jacobian* (#link("https://stacks.math.columbia.edu/tag/0BVZ")[0BVZ],
  Lemma 7.4)*.* For $B = A[x_1, dots, x_n] slash (F_1, dots, F_n)$ --- $n$ equations in $n$
  variables --- the Kähler different of $B$ over $A$ is the ideal generated by
  $det(partial F_i slash partial x_j)$.

  #v(1.5mm)
  *(K2) It cuts out the non-unramified locus*
  (#link("https://stacks.math.columbia.edu/tag/0BVY")[0BVY], Lemma 7.3)*.* The closed subscheme
  $V(frak(d))$ is exactly the set of points at which $X -> "Spec" cal(O)$ fails to be unramified.

  #v(1.5mm)
  *(K3) It commutes with base change*
  (#link("https://stacks.math.columbia.edu/tag/0BVX")[0BVX], Lemma 7.2)*.*
]

(K1) is immediate and worth seeing, because it is the entire bridge between the two formulations.
For $B = A[x] slash (F)$ the conormal sequence is
$ ⊕_(i=1)^n B thin F_i -->^d ⊕_(j=1)^n B thin d x_j
  --> Omega_(B slash A) --> 0 , quad d F_i = sum_j (partial F_i) / (partial x_j) d x_j , $
so $Omega_(B slash A) = "coker"(J)$ with $J$ the Jacobian matrix, *which is square*. By the
definition of $"Fitt"_0$ with $s = r = n$, the only minor is $det J$. Hence
$frak(d) = (det J)$ --- and by Fitting's theorem this ideal does not depend on the presentation,
though the matrix certainly does.

= The invariant along a point <sec-point>

Let $a in X(cal(O))$, i.e. a section $a : "Spec" cal(O) -> X$.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Proposition 4.1.* Suppose $X$ is presented near $a$ by $n$ equations in $n$ variables, and
  $det J(a) != 0$. Then
  $ a^* frak(d)_(X slash cal(O)) = (det J(a)) subset.eq cal(O) , quad "and" quad
    e(a) := v(det J(a)) = "length"_(cal(O)) (a^* Omega_(X slash cal(O))) . $
  Both sides are independent of the presentation.

  #v(2mm)
  _Proof._ $a^* Omega_(X slash cal(O)) = Omega ⊗_B cal(O) = "coker"(J(a) : cal(O)^n -> cal(O)^n)$,
  since forming $Omega$ and forming cokernels both commute with base change. Fitting ideals commute
  with base change (K3), so $a^* frak(d) = "Fitt"_0("coker" J(a)) = (det J(a))$; and Lemma 2.2
  converts that into a length. $qed$
]

For an *approximate* solution the same works, with one caveat about precision. If
$F(a) equiv 0 mod pi^N$ then $a$ defines a point
$ a_N in X(cal(O) slash pi^N) , $
and $a_N^* frak(d) = (det J(a)) subset.eq cal(O) slash pi^N$. This determines
$e = v(det J(a))$ *provided $e < N$* --- which is exactly the regime the theorem lives in, since
$N >= 2e+1 > e$.

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *So the hypothesis of Hensel's lemma is a statement about the point $a_N in X(cal(O) slash pi^N)$
  and the scheme $X$, and about nothing else.* One may compute $e$ in whichever coordinates are
  convenient, or by pure thought (@sec-meaning), and the answer is the same.
]

= Hensel's lemma, intrinsically <sec-hensel>

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Theorem 5.1 (intrinsic Hensel).* Let $X$ be an $cal(O)$-scheme which near the point in question
  admits a presentation by $n$ equations in $n$ variables. Let $a_N in X(cal(O) slash pi^N)$ and
  suppose
  $ a_N^* frak(d)_(X slash cal(O)) = (pi^e) subset.eq cal(O) slash pi^N , quad N >= 2 e + 1 . $
  Then the image of $a_N$ in $X(cal(O) slash pi^(e+1))$ lifts to a point of $X(cal(O))$, and the
  lift is unique.

  #v(2mm)
  _Proof._ Choose any square presentation. By (K1) and Proposition 4.1, $det J(a)$ generates
  $a_N^* frak(d)$, so $v(det J(a)) = e$; and $a_N in X(cal(O) slash pi^N)$ says exactly
  $F(a) equiv 0 mod pi^N$, so $F(a) equiv 0 mod pi^(2e+1)$. The coordinate version of
  @sec-answer applies and returns $x$ with $F(x) = 0$ and $x equiv a mod pi^(e+1)$; the last
  congruence is the assertion that $x$ lifts the image of $a_N$ in $X(cal(O) slash pi^(e+1))$.
  Uniqueness is the uniqueness in the coordinate version. $qed$
]

Two remarks on the shape of the statement, both of which the coordinate version obscures.

*The conclusion cannot be "$a_N$ itself lifts".* The lift only agrees with $a$ to precision
$e + 1$, not to precision $N$. This is not a defect of the proof: with
$X = "Spec" cal(O)[x] slash (pi x)$ and $a = pi^(N-1)$ one has $e = 1$ and $N$ as large as one
likes, but the only $cal(O)$-point is $x = 0$, which agrees with $a$ to precision $N - 1$ and no
better. The intrinsic statement has to be about the *truncation* of $a_N$, and $e + 1$ is the right
truncation.

*The case $e = 0$ is the classical statement.* By (K2), $frak(d) = cal(O)_X$ at $a$ means $X$ is
unramified over $cal(O)$ there; with flatness that is étale. So:

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *Hensel's lemma, stripped: an étale $cal(O)$-scheme has $X(cal(O)) -> X(k_v)$ bijective.* The
  general case is a quantitative degeneration of this, and $e$ is exactly the number of digits by
  which the scheme fails to be étale along the point.
]

= Why it has to be $Omega$ <sec-why>

The appearance of $Omega_(X slash cal(O))$ is not a coincidence of the formula for
$Omega_(B slash A)$. Lifting points is a deformation problem, and deformation problems along
square-zero extensions are governed by the cotangent complex, whose $H^0$ is $Omega$.

Precisely: let $A' ->> A$ be a square-zero extension of $cal(O)$-algebras with kernel $I$, and let
$x : "Spec" A -> X$ be an $cal(O)$-morphism. Then

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  - the obstruction to lifting $x$ to $"Spec" A' -> X$ lies in
    $"Ext"^1_A (L x^* L_(X slash cal(O)), I)$;
  - if a lift exists, the set of lifts is a torsor under
    $"Hom"_A (x^* Omega_(X slash cal(O)), I)$.
]

Take $A' = cal(O) slash pi^(N+1) ->> cal(O) slash pi^N = A$, with $I tilde.equiv k_v$. Then:

- *$X$ smooth over $cal(O)$*: $Omega$ is locally free, the obstruction vanishes, lifts always exist
  and form a torsor of size $\#"Hom"(x^*Omega, k_v) = \#k_v^d$. This is formal smoothness.
- *$X$ étale*: $Omega = 0$, so there is no obstruction and *no ambiguity*: the lift is unique at
  every stage, and the inverse limit is a unique $cal(O)$-point. This is Hensel's lemma, and the
  proof is one line once the machine is set up.
- *$X$ neither*: $x^* Omega != 0$ is a torsion module of length $e$. It measures the ambiguity at
  each stage directly, and it controls the obstruction. Newton's method is what converts "$e$
  digits of ambiguity per step" into the global threshold $2e + 1$: each Newton step doubles the
  precision and loses $e$ to the inversion of $J$, so $N |-> 2N - e$, which is a contraction
  exactly when $N > 2 e$.

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *That last line is the whole quantitative content.* The iteration $N |-> 2N - e$ has $N = 2e$ as
  its fixed point: starting below it, precision decays; starting strictly above it, precision runs
  away to infinity. The threshold $2e+1$ is not an artefact of the estimates --- it is the fixed
  point of the Newton recursion, and @sec-meaning shows it is attained.
]

= What $e$ measures <sec-meaning>

== Collision of branches <sec-collision>

Take $n = 1$, $F$ monic, and $a$ an exact root, so $F = (x - a) G$. Then $F'(a) = G(a)$ and,
factoring $G = product_(beta != a) (x - beta)$ over $overline(K)_v$,
$ e = v(F'(a)) = sum_(beta != a) v(a - beta) . $

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *So $e$ is the total order of contact between the branch through $a$ and all the other branches of
  $X$.* If $e = 0$ the section $a$ is an isolated, clopen branch --- $"Spec" cal(O)$ is a connected
  component of $X$ near $a$ --- and one digit suffices to find it. If $e > 0$, other branches sit
  within distance $pi^e$ of $a$, and no approximation coarser than that can tell them apart. The
  threshold $2e+1$ says: *approximate past the collision radius, with one digit to spare, and the
  root is pinned down.*
]

== The different, in the arithmetic sense <sec-arith>

The name is not an analogy. The main theorem of the Stacks chapter is that for a quasi-finite
*syntomic* (flat and lci) morphism, the different --- defined by the trace element on the relative
dualising module --- *agrees with the Kähler different*. For $cal(O)_L$ over $cal(O)_K$ with
$L slash K$ finite separable and the residue extension separable, $cal(O)_L$ is monogenic,
$cal(O)_L = cal(O)_K [theta]$ with minimal polynomial $f$, and

$ frak(d)_(cal(O)_L slash cal(O)_K) = (f'(theta)) , quad
  e = v_L (f'(theta)) = d(L slash K) , $

the classical different exponent: $d = e_(L slash K) - 1$ when $L slash K$ is tamely ramified, and
$e_(L slash K) <= d <= e_(L slash K) - 1 + v_L (e_(L slash K))$ in the wild case. Checked in
`hensel-different.gp`:

#align(center, table(
  columns: 4, align: (left, center, center, center),
  stroke: 0.4pt + luma(170), inset: (x: 8pt, y: 3.5pt),
  table.header([$f$], [$N(frak(d)_(cal(O)_K))$], [$N(f'(theta))$], [equal?]),
  [$x^2 - 2$], [$8$], [$8$], [yes],
  [$x^2 + 1$], [$4$], [$4$], [yes],
  [$x^3 - 2$], [$108$], [$108$], [yes],
  [$x^2 - 5$], [$5$], [$20$], [*no*],
))

#v(2mm)

The last row is worth the space. $ZZ[sqrt(5)]$ is *not* the maximal order --- $cal(O)_K =
ZZ[(1 + sqrt(5)) slash 2]$, of index 2 --- and $20 = 5 dot 2^2$ accordingly. The moral is exactly
the one the intrinsic formulation demands:

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  $"Fitt"_0 (Omega)$ is an invariant of the $cal(O)$-*algebra one presents*, not of its
  normalisation. That is a feature: Hensel's lemma is a statement about the scheme $X$ cut out by
  the given equations, singularities and all, and $e$ must see the singularities. If one silently
  normalises, the invariant drops and the theorem becomes false.
]

== Why square classes need $8$ at $v = 2$ and $p$ at odd $v$ <sec-squares>

This is the case used on nearly every page of these notes, and it has an exact explanation.

Take $X = "Spec" cal(O)[x] slash (x^2 - u)$ for a unit $u$. One equation, one variable, and
$ frak(d)_(X slash cal(O)) = (2 x) = (2) quad "since" x "is a unit" . $
So $e = v(2)$ --- *zero at every odd place and one at $v = 2$* --- and Theorem 5.1 gives the
threshold $2e + 1$:

#align(center, table(
  columns: 5, align: (left, center, center, center, left),
  stroke: 0.4pt + luma(170), inset: (x: 8pt, y: 3.5pt),
  table.header([place], [$e = v(2)$], [$2e+1$], [criterion for $u in (cal(O)^times)^2$], [$\# QQ_p^times slash "squares"$]),
  [$v$ odd], [$0$], [$1$], [$u$ a square mod $p$], [$4$],
  [$v = 2$], [$1$], [$3$], [$u equiv 1$ mod $8$], [$8$],
))

#v(2mm)

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *The "mod 8" is the different.* Every time these notes say "four square classes at odd $v$, eight
  at $v = 2$", or "for $a$ odd the curve over $QQ_2$ depends only on $a$ modulo 8", they are
  quoting $2 e + 1$ for $e = v(2) = 1$. The place $v = 2$ is not awkward for a computational reason;
  it is awkward because *the squaring map is ramified there and nowhere else*, and $e$ is exactly
  the ramification.
]

And the threshold is *attained*, so nothing coarser will do. `hensel-different.gp` sweeps the units:
at $p = 2$, "square mod $8$" agrees with "square in $ZZ_2$" on every unit tested, while "square mod
$4$" disagrees on four of them, the first being
$ u = 5 : quad 5 equiv 1 mod 4 quad "is a square mod" 4, quad "but" quad 5 equiv 5 mod 8
  quad "is not a square in" ZZ_2 . $
Precision $2e = 2$ fails, precision $2e + 1 = 3$ succeeds: the bound of Theorem 5.1 is sharp.

= Beyond the square case <sec-general>

== More variables than equations <sec-nonsquare>

If $X = V(F_1, dots, F_r) subset AA^n$ has relative dimension $d = n - r > 0$, "the Jacobian" is not
even a square matrix, and the coordinate statement has to be phrased as "*some* $r times r$ minor
has valuation $e$". Intrinsically there is no choice to make:

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *The Jacobian ideal is* $frak(J)_(X slash cal(O)) = "Fitt"_d (Omega_(X slash cal(O)))$.

  #v(1.5mm)
  With $n$ generators $d x_j$ and $r$ relations $d F_i$, $"Fitt"_d$ is the ideal of
  $(n - d) times (n - d) = r times r$ minors of the Jacobian --- so the intrinsic ideal is generated
  by *all* the maximal minors at once, and $e = v(a^* frak(J))$ is the minimum of their valuations,
  which is what "some minor" was groping at. Smoothness of relative dimension $d$ is
  $frak(J) = cal(O)_X$, and $frak(J) = frak(d)$ when $d = 0$.
]

Theorem 5.1 holds verbatim with $frak(d)$ replaced by $frak(J)$.

== Non-complete-intersections: Elkik's ideal <sec-elkik>

If $X$ is presented by more equations than its codimension, $"Fitt"_d (Omega)$ is still intrinsic but
is no longer the right invariant: it does not know which subsystems cut out $X$ and which are
redundant. The repair is due to Elkik
(#link("https://www.numdam.org/item/?id=ASENS_1973_4_6_4_553_0")[Ann. Sci. ÉNS *6* (1973) 553--603]).
For $B = A[x_1, dots, x_n] slash I$ she defines an ideal $H_(B slash A)$ generated by the products
$ Delta_alpha dot k , quad k in ((F_(alpha_1), dots, F_(alpha_p)) : I) , $
over all subsystems $alpha$ of $I$ and all $p times p$ minors $Delta_alpha$ of the Jacobian of that
subsystem --- the minor is weighted by an ideal quotient measuring how far the subsystem is from
generating all of $I$. Its vanishing locus is again the non-smooth locus, and her theorem carries the
same exponents: *if $pi^h in H(a)$ and $F(a) equiv 0$ modulo $pi^N$ with $N > 2h$, the approximate
solution can be corrected to an exact one, congruent to $a$ modulo $pi^(N - h)$.*

Setting $N = 2h+1$ recovers a lift agreeing to precision $h+1$, which is Theorem 5.1. And in the
square lci case the full subsystem has $(I : I) = B$, so $H_(B slash A)$ contains the Kähler
different and the classical criterion is already available.

== When $e = infinity$ <sec-greenberg>

If $a$ lies on the singular locus, $a^* frak(J) = 0$ and no threshold exists: Theorem 5.1 says
nothing, and it should not, since points can genuinely fail to lift. What survives is Greenberg's
theorem: for $X$ of finite type over $cal(O)$ there are constants $c, N_0$ such that for
$N >= N_0$, every point of $X(cal(O) slash pi^(c N))$ has the same image in
$X(cal(O) slash pi^N)$ as some genuine point of $X(cal(O))$. That is the qualitative shadow of
$2e+1$ once $e$ is allowed to be unbounded, and Elkik's theorem is what makes it effective.

= The dictionary <sec-dictionary>

#align(center, table(
  columns: 2, align: (left, left),
  stroke: 0.4pt + luma(170), inset: (x: 8pt, y: 4pt),
  table.header([coordinate version], [intrinsic version]),
  [the Jacobian matrix $J = (partial F_i slash partial x_j)$],
    [the presentation matrix of $Omega_(X slash cal(O))$],
  [$det J$], [a generator of $frak(d)_(X slash cal(O)) = "Fitt"_0 (Omega_(X slash cal(O)))$],
  [$det J(a)$ is a unit], [$X -> "Spec" cal(O)$ is unramified at $a$],
  [$e = v(det J(a))$], [$e = "length"_(cal(O)) (a^* Omega_(X slash cal(O)))$],
  [$F(a) equiv 0$ mod $frak(m)^N$], [$a$ is a point of $X(cal(O) slash pi^N)$],
  [$N >= 2e+1$], [the point is a solution to better than $frak(d)^2$],
  [$x equiv a$ mod $frak(m)^(e+1)$], [the lift refines the image of $a$ in $X(cal(O) slash pi^(e+1))$],
  [some $r times r$ minor is non-zero], [$"Fitt"_d (Omega_(X slash cal(O)))$, $d$ the relative dimension],
  [redundant equations spoil the minors], [Elkik's $H_(B slash A)$, minors weighted by $(F_alpha : I)$],
))

= Where this bites in these notes <sec-uses>

The threshold $2e + 1$ with $e = v(2)$ is the reason for a pattern that runs through the whole
corpus and has so far been treated as a brute fact.

- `localimg.gp` computes local images over "4 classes for odd $v$, 8 classes for $v = 2$"; `p2.gp`
  is a separate script *only* because $p = 2$ needs 8 square classes. Both are @sec-squares.
- `selmer-involution.typ` proves its theorem at $v = 2$ by an exhaustive check over $a$ modulo 8,
  and observes that "over $QQ_2$ every unit is a cube, so the cubic part of any sextic twist by a
  unit is trivial". That asymmetry is the same computation for $x^3 - u$ in place of $x^2 - u$:
  there $frak(d) = (3 x^2) = (3)$, so $e = v(3) = 0$ at $v = 2$ and the cube map is *étale* over
  $ZZ_2$ --- one digit suffices, and every unit is a cube. *Squares are hard at 2 and cubes are
  easy, for the same reason and with the same invariant.*
- `cover2.gp` asks whether every point of $X(ZZ_p)$ modulo $p^k$ is hit by a rational point, and has
  to choose $k$. The right $k$ is $2e+1$ for $e$ the valuation of the Jacobian ideal along the
  relevant section, and the intrinsic formulation says that number can be computed from $X$ rather
  than discovered by experiment.

#v(2mm)

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Summary.* The invariant is $frak(d)_(X slash cal(O)) = "Fitt"_0 (Omega_(X slash cal(O)))$, the
  Kähler different: an ideal sheaf on $X$, generated by $det J$ in any square presentation, cutting
  out the locus where $X$ is not unramified over $cal(O)$, and equal to the classical different when
  $X$ is a quasi-finite syntomic $cal(O)$-scheme. Along a section it evaluates to $(pi^e)$ with
  $e = "length"(a^* Omega)$. Hensel's lemma says an approximate point lifts as soon as it solves the
  equations to precision better than $frak(d)^2$, and the lift is pinned down to precision
  $frak(d)$. In relative dimension $d$ replace $"Fitt"_0$ by $"Fitt"_d$; without lci, replace it by
  Elkik's $H_(B slash A)$; on the singular locus, replace the theorem by Greenberg's.
]
