\\ hensel-different.gp -- companion to hensel-different.typ.
\\ Run from this directory:
\\     gp -q -s 2000000000 hensel-different.gp < /dev/null > results/hensel-different.txt
\\
\\ The document's claim is that the coordinate-free invariant behind the
\\ multivariate Hensel lemma is the KAEHLER DIFFERENT
\\
\\     d_{X/O} = Fitt_0(Omega_{X/O}),      generated by det(dF_i/dx_j),
\\
\\ and that the classical threshold "F(a) = 0 mod m^(2e+1), e = v(det J(a))"
\\ reads: solve to precision better than the SQUARE of the different.
\\ This script checks the four assertions the document makes concretely.
\\
\\   (1) SQUARE CLASSES.  For f = x^2 - u the Kaehler different is (2x), so
\\       e = v(2) : zero at odd v, one at v = 2.  The threshold 2e+1 is then
\\       1 at odd p and 3 at p = 2 -- i.e. a unit is a square iff it is a
\\       square mod p, resp. iff it is 1 mod 8.  This is exactly the "4 square
\\       classes at odd v, 8 at v = 2" used throughout these notes.
\\   (2) SHARPNESS.  At p = 2 precision 2e = 2 is NOT enough: 5 is a square
\\       mod 4 but not in Z_2.
\\   (3) THE DIFFERENT.  For a monogenic ring of integers, v(f'(theta)) is the
\\       different exponent.  Including the instructive failure when the order
\\       presented is not maximal.
\\   (4) PRESENTATION INDEPENDENCE.  Adding a redundant variable and equation
\\       changes the Jacobian matrix but not its determinant.

\\ ------------------------------------------------- (1) and (2): square classes

\\ is the unit u a square in Z_p ?
issqZp(u, p) =
{ if (p == 2, (u % 8) == 1, issquare(Mod(u, p))); };

\\ is u a square modulo p^k ?
issqmod(u, p, k) =
{ my(M = p^k);
  for (t = 0, M - 1, if ((t^2 - u) % M == 0, return(1)));
  0;
};

squareclasses() =
{ my(e, thr);
  print("(1) square classes: f = x^2 - u,  Kaehler different = (2x),  e = v(2)");
  print("");
  foreach ([2, 3, 5, 7], p,
    e = valuation(2, p);
    thr = 2*e + 1;
    print("    p = ", p, "   e = v(2) = ", e, "   Hensel threshold 2e+1 = ", thr);
    \\ Sweep units u well past the modulus: the question is whether the
    \\ PREDICATE "u is a square mod p^k" decides "u is a square in Z_p".
    my(bad = 0, M = p^(thr+2));
    for (u = 1, M - 1,
      if (gcd(u, p) != 1, next);
      if (issqmod(u, p, thr) != issqZp(u, p), bad++));
    print("      units u < p^", thr+2, " where 'square mod p^", thr,
          "' disagrees with 'square in Z_p' : ", bad);
    if (thr > 1,
      my(bad2 = 0, wit = 0);
      for (u = 1, M - 1,
        if (gcd(u, p) != 1, next);
        if (issqmod(u, p, thr-1) != issqZp(u, p),
          bad2++; if (wit == 0, wit = u)));
      print("      same test one step short, at p^", thr-1, " : ", bad2,
            " disagreements, first at u = ", wit);
      print("      (nonzero = the threshold 2e+1 is sharp)")));
  print("");
  print("    #Q_p^*/(Q_p^*)^2 = 2 * #(units mod squares) = 4 for odd p, 8 for p = 2,");
  print("    which is 2e+1 read off as a number of digits.");
  print("");
};

sharp() =
{ print("(2) sharpness at p = 2, on u = 5:");
  print("      5 mod 4 = ", 5 % 4, "   a square mod 4?  ", issqmod(5, 2, 2),
        "     (precision 2e = 2)");
  print("      5 mod 8 = ", 5 % 8, "   a square mod 8?  ", issqmod(5, 2, 3),
        "     (precision 2e+1 = 3)");
  print("      is 5 a square in Z_2?  ", issqZp(5, 2));
  print("      so precision 2e is not enough and 2e+1 is: the bound is attained.");
  print("");
};

\\ ------------------------------------------------------------ (3) the different

different() =
{ my(nf, th, nfd, nkd);
  print("(3) v(f'(theta)) against the different exponent, for B = Z[x]/(f):");
  print("");
  print("       f                N(different of O_K)   N(f'(theta))   equal?");
  foreach ([x^2 - 2, x^2 + 1, x^3 - 2, x^2 - 5], f,
    nf = nfinit(f);
    th = Mod(x, f);
    nfd = idealnorm(nf, nf.diff);
    nkd = abs(nfeltnorm(nf, nfalgtobasis(nf, subst(deriv(f), x, th))));
    print("       ", f, "        ", nfd, "                  ", nkd,
          "          ", if (nfd == nkd, "yes", "NO")));
  print("");
  print("    The last row is the instructive failure: Z[sqrt 5] is not the");
  print("    maximal order (O_K = Z[(1+sqrt5)/2]), and Fitt_0(Omega) is an");
  print("    invariant of the algebra PRESENTED, not of its normalisation.");
  print("    Index [O_K : Z[sqrt5]] = 2, and 20 = 5 * 2^2 accordingly.");
  print("");
};

\\ ------------------------------------------------ (4) presentation independence

presentation() =
{ my(f, g, J1, J2);
  print("(4) presentation independence, on B = Z[x]/(f) presented two ways:");
  f = x^3 - 2;
  g = x^2 + 3*x;                      \\ any polynomial
  print("      one variable   : F = ", f, "        det J = ", deriv(f));
  print("      two variables  : F1 = ", f, ", F2 = y - (", g, ")");
  print("        J = [[dF1/dx, dF1/dy], [dF2/dx, dF2/dy]] = [[", deriv(f),
        ", 0], [", -deriv(g), ", 1]]");
  J2 = deriv(f) * 1 - 0 * (-deriv(g));
  print("        det J = ", J2, "     equal to the one-variable answer?  ",
        if (J2 == deriv(f), "yes", "NO"));
  print("      Adding a redundant variable and the equation that eliminates it");
  print("      changes the matrix and not the determinant -- as Fitt_0 must.");
  print("");
};

squareclasses();
sharp();
different();
presentation();
quit;
