/* ============================================================
   p-adic density of Q-points on X : y^2 = f(x)f(t),  f = x^3+Ax+B
   X = Kum(E x E),  E : v^2 = f(u),  E_d : Y^2 = X^3 + A d^2 X + B d^3
   ============================================================ */

PREC = 100;

sqclass(d, p) = { my(v = valuation(d,p), u = d/p^v); 2*(v%2) + if(kronecker(u,p)==1,0,1); }
sqclassname(k, p) = if(k==0, "1", k==1, "u", k==2, Str(p), Str("u*",p));

/* M = # E(Qp)/E_1(Qp) for a MINIMAL model Em, p odd */
Mval(Em, p) = {
  my(ap = ellap(Em,p), lr = elllocalred(Em,p));
  if(lr[2] == 1, lr[4]*(p+1-ap), lr[4]*(p-ap));
}

padiccurve(Em, p) = {
  ellinit([Em.a1+O(p^PREC), Em.a2+O(p^PREC), Em.a3+O(p^PREC),
           Em.a4+O(p^PREC), Em.a6+O(p^PREC)]);
}

inE1(Q, p) = (Q == [0]) || (valuation(Q[1],p) < 0);

/* Is the subgroup generated by pts dense in Em(Qp)?  (Em minimal, p odd) */
densegroup(Em, pts, p) = {
  my(M, r, Ep, P, S, coefs, basis, idx, rem, dv, mi, bvec, k, kP, Q, S2, C2, jP, cc, b, T);
  M = Mval(Em, p);
  r = #pts;
  if(M == 0 || r == 0, return(0));
  Ep = padiccurve(Em, p);
  P = vector(r, i, [pts[i][1]+O(p^PREC), pts[i][2]+O(p^PREC)]);
  S = [[0]];
  coefs = [vector(r, j, 0)];
  basis = List();
  idx = 1;
  for(i = 1, r,
    rem = M \ idx;      /* m_i divides this; rem==1 still contributes a kernel vector */
    dv = divisors(rem);
    mi = 0; bvec = 0;
    for(t = 1, #dv,
      k = dv[t];
      kP = ellmul(Ep, P[i], k);
      for(s = 1, #S,
        Q = if(S[s] == [0], kP, elladd(Ep, kP, S[s]));
        if(inE1(Q, p),
          mi = k;
          bvec = coefs[s]; bvec[i] += k;
          break(2)
        )
      )
    );
    if(mi == 0, next);
    listput(basis, bvec);
    S2 = List(); C2 = List();
    for(j = 0, mi-1,
      jP = if(j == 0, [0], ellmul(Ep, P[i], j));
      for(s = 1, #S,
        Q = if(j == 0, S[s], if(S[s] == [0], jP, elladd(Ep, jP, S[s])));
        cc = coefs[s]; cc[i] += j;
        listput(S2, Q); listput(C2, cc)
      )
    );
    S = Vec(S2); coefs = Vec(C2); idx *= mi
  );
  if(idx != M, return(0));
  for(i = 1, #basis,
    b = basis[i]; Q = [0];
    for(j = 1, r,
      if(b[j] != 0,
        T = ellmul(Ep, P[j], b[j]);
        Q = if(Q == [0], T, elladd(Ep, Q, T))
      )
    );
    if(Q != [0] && valuation(Q[1],p) == -2, return(1))
  );
  0;
}

/* generators of a finite-index subgroup of E_d(Q) */
twistdata(A, B, d) = {
  my(Ec, v, Em, R, pts, tors);
  Ec = ellinit([A*d^2, B*d^3]);
  v = 0;
  Em = ellminimalmodel(Ec, &v);
  R = ellrank(Em);
  pts = R[4];
  if(#pts > 0, pts = ellsaturation(Em, pts, 50));
  tors = elltors(Em);
  pts = concat(pts, tors[3]);
  [Em, pts, R[1], R[2]];
}
