\\ kummer-j0-brauer.gp -- the Azumaya algebra of kummer-example-j0.typ section 7
\\
\\ Run from this directory:
\\     gp -q -s 4000000000 kummer-j0-brauer.gp < /dev/null > results/kummer-j0-brauer.txt
\\
\\ X : y^2 = (x^3 + 9)(t^3 - 81)   is Kum(E x E') for  E : y^2 = x^3 + 9  and
\\ E' : v^2 = u^3 - 81, and the twists E_d, E'_d map to it by U = dx, S = dt.
\\
\\ Over K = Q(u), u^3 = 3 -- the field generated by the x-coordinate of a
\\ 2-torsion point, which is the 2-descent etale algebra of every twist at once --
\\ both cubics factor:
\\     x^3 + 9  = (x + u^2)(x^2 - u^2 x + 3u)   =: (x + u^2) g(x)
\\     t^3 - 81 = (t - 3u )(t^2 + 3u t + 9u^2)  =: (t - 3u ) h(t)
\\ and the claim is
\\     A := cor_{K(X)/Q(X)} ( g(x), h(t) )  in Br(X),
\\     inv_q A(T) = beta_q(P, P')  for T the image of (P,P') in X(Q_q).
\\
\\ Everything below tests that claim and then re-derives the section 6 verdict
\\ from A alone, with no twist appearing anywhere.

K  = nfinit(u^3 - 3);
U1 = Mod(u,   u^3 - 3);
U2 = Mod(u^2, u^3 - 3);

g(x) = x^2 - U2*x + 3*U1;
h(t) = t^2 + 3*U1*t + 9*U2;

\\ inv_q of A at the point (x,t) of X: sum over the places of K above q
{invA(x, t, q) = my(D = idealprimedec(K, q), s = 1);
  for (i = 1, #D, s *= nfhilbert(K, g(x), h(t), D[i])); s;}

\\ and at the archimedean place: K has one real embedding
{invAoo(x, t) = my(a = nfeltembed(K, g(x)), b = nfeltembed(K, h(t)), s = 1);
  for (i = 1, K.r1, if (real(a[i]) < 0 && real(b[i]) < 0, s = -s)); s;}

\\ the twisted form of the same pairing, straight from section 6.5
{betaq(Up, Sp, d, q) = my(D = idealprimedec(K, q), s = 1);
  for (i = 1, #D,
    s *= nfhilbert(K, Mod(Up + d*u^2, u^3-3), Mod(Sp - 3*d*u, u^3-3), D[i]));
  s;}

\\ is a a square in Q_q?
{issqq(a, q) = my(v, w);
  if (a == 0, return(1));
  v = valuation(a, q); if (v % 2, return(0));
  w = a/q^v; w = numerator(w)*denominator(w);
  if (q == 2, lift(Mod(w,8)) == 1, kronecker(w, q) == 1);}

\\ square classes.  At 2 the eight classes are labelled as in section 6.12.
{sq2(a) = my(v = valuation(a,2), w = lift(Mod(a/2^v, 8)));
  if (v % 2 == 0, w, 2*w);}
{sqq(a, q) = my(v = valuation(a,q), w = a/q^v);
  [v % 2, kronecker(numerator(w), q) * kronecker(denominator(w), q)];}

\\ ---------------------------------------------------------------- check 1
\\ The two factorisations over K, and that they are what makes the twist go away:
\\ on E_d, (U + d u^2) * g(U/d) = (V/d)^2 exactly.  That identity is the whole
\\ reason A mentions no twist while beta does.

check1() =
{ my(bad = 0, n = 0);
  if ((x + U2)*g(x) != x^3 + 9,   bad++);
  if ((t - 3*U1)*h(t) != t^3 - 81, bad++);
  printf("  (1) x^3+9 = (x+u^2)g(x) and t^3-81 = (t-3u)h(t) over K : %d wrong of 2\n", bad);
  bad = 0;
  for (d = -30, 30, if (d == 0, next);
    for (a = -60, 60,
      my(s = a^3 + 9*d^3);
      if (s == 0 || !issquare(s), next);
      n++;
      if ((a + d*U2) * g(a/d) != (sqrtint(s)/d)^2, bad++));
    for (b = -60, 60,
      my(s = b^3 - 81*d^3);
      if (s == 0 || !issquare(s), next);
      n++;
      if ((b - 3*d*U1) * h(b/d) != (sqrtint(s)/d)^2, bad++)));
  printf("      the descent class equals the twist-free factor, up to a square : %d wrong of %d\n",
         bad, n);
};

\\ ---------------------------------------------------------------- check 2
\\ A evaluates to beta.  For sampled local points P on E_d and P' on E'_d,
\\     prod_{w|q} (U(P) + d u^2, S(P') - 3d u)_w  =  prod_{w|q} (g(x), h(t))_w
\\ with x = U/d, t = S/d -- the left side is section 6.5, the right side is A.

check2(DS, QS) =
{ my(bad = 0, n = 0);
  for (i = 1, #DS, my(d = DS[i]);
    for (j = 1, #QS, my(q = QS[j], PS = List(), SS = List());
      for (a = -40, 40,
        my(s = a^3 + 9*d^3);
        if (s != 0 && issqq(s, q), listput(PS, a)));
      for (b = -40, 40,
        my(s = b^3 - 81*d^3);
        if (s != 0 && issqq(s, q), listput(SS, b)));
      PS = Vec(PS); SS = Vec(SS);
      for (k = 1, #PS, for (l = 1, #SS,
        my(Up = PS[k], Sp = SS[l], x = Up/d, t = Sp/d);
        if (g(x) == 0 || h(t) == 0, next);
        n++;
        if (betaq(Up, Sp, d, q) != invA(x, t, q), bad++)))));
  printf("  (2) inv_q A = beta_q, twist-free against twisted : %d wrong of %d\n", bad, n);
};

\\ ---------------------------------------------------------------- check 3
\\ inv_q A vanishes identically for q != 2 -- condition (E) of section 6.6,
\\ now a statement about one function on X(Q_q) instead of about every twist.

check3(QS, B) =
{ for (j = 1, #QS, my(q = QS[j], XS = List(), TS = List(), n = 0, nz = 0);
    for (a = -B, B, my(c = a^3 + 9);  if (c != 0, listput(XS, [a, sqq(c,q)])));
    for (b = -B, B, my(c = b^3 - 81); if (c != 0, listput(TS, [b, sqq(c,q)])));
    XS = Vec(XS); TS = Vec(TS);
    for (i = 1, #XS, for (k = 1, #TS,
      if (XS[i][2] != TS[k][2], next);          \\ same square class => y exists
      my(x = XS[i][1], t = TS[k][1]);
      if (g(x) == 0 || h(t) == 0, next);
      n++;
      if (invA(x, t, q) == -1, nz++)));
    printf("      q = %-4d : %7d points of X(Q_q) sampled, inv_q = 1/2 at %d\n", q, n, nz));
  \\ and the real place: both entries are positive definite at the real
  \\ embedding of K (their discriminants are negative), so the symbol is +1
  \\ for a reason, not merely on a sample.
  my(n = 0, nz = 0);
  for (a = -B, B, for (b = -B, B,
    my(c = a^3 + 9, e = b^3 - 81);
    if (c == 0 || e == 0 || c*e < 0, next);
    if (g(a) == 0 || h(b) == 0, next);
    n++;
    if (invAoo(a, b) == -1, nz++)));
  printf("      q = oo   : %7d points of X(R)   sampled, inv_oo = 1/2 at %d\n", n, nz);
  printf("               disc of g at the real place = %.4f, of h = %.4f : both < 0,\n",
         real(nfeltembed(K, U2^2 - 12*U1)[1]), real(nfeltembed(K, 9*U2 - 36*U2)[1]));
  printf("               so g > 0 and h > 0 on all of R and inv_oo = 0 identically\n");
};

\\ ---------------------------------------------------------------- check 4
\\ inv_2 A on X(Q_2), by square class of the point.  The class of T is the class
\\ of x(T)^3 + 9, because a point of X lifts to E_d x E'_d exactly for
\\ d = x^3 + 9 = t^3 - 81 modulo squares.  This reproduces the verdict table of
\\ section 6.13 with no twist in sight.

check4(B) =
{ my(XS = List(), TS = List(), CL = [1,3,5,7,2,6,10,14], odd0 = 1, even0 = 1);
  for (a = -B, B, my(c = a^3 + 9);  if (c != 0, listput(XS, [a, sq2(c)])));
  for (b = -B, B, my(c = b^3 - 81); if (c != 0, listput(TS, [b, sq2(c)])));
  XS = Vec(XS); TS = Vec(TS);
  for (m = 1, #CL, my(c = CL[m], n = 0, nz = 0);
    for (i = 1, #XS, if (XS[i][2] != c, next);
      for (k = 1, #TS, if (TS[k][2] != c, next);
        my(x = XS[i][1], t = TS[k][1]);
        if (g(x) == 0 || h(t) == 0, next);
        n++;
        if (invA(x, t, 2) == -1, nz++)));
    printf("      class [%2d] %s : %6d points, inv_2 = 1/2 at %6d  %s\n",
           c, if (c % 2, "odd ", "even"), n, nz, if (nz, "*** NON-ZERO ***", "zero"));
    if (c % 2 && nz, odd0 = 0);
    if (c % 2 == 0 && nz == 0, even0 = 0));
  printf("      inv_2 A vanishes on all four odd classes : %s\n", if (odd0, "yes", "NO"));
  printf("      inv_2 A is non-zero on all four even classes : %s\n", if (even0, "yes", "NO"));
};

\\ ---------------------------------------------------------------- check 5
\\ Reciprocity on X(Q): sum_v inv_v A(T) = 0.  This is Hilbert reciprocity in K
\\ regrouped by the places of Q, and it is what pins inv_2 to 0 on rational
\\ points -- the step that turns "inv_2 is non-constant" into non-density.

\\ multiples of the generators and torsion of E, as affine x-coordinates
mults(E, N) =
{ my(r = ellrank(E), G = concat(r[4], elltors(E)[3]), L = List());
  for (i = 1, #G,
    my(P = G[i]);
    for (n = 1, N,
      my(Q = ellmul(E, P, n));
      if (Q != [0] && !setsearch(Set(Vec(L)), Q[1]), listput(L, Q[1]))));
  Vec(L);
};

check5(DS, N) =
{ my(PTS = List(), bad = 0);
  for (i = 1, #DS, my(d = DS[i],
      PS = mults(ellinit([0,0,0,0,  9*d^3]), N),
      SS = mults(ellinit([0,0,0,0,-81*d^3]), N));
    for (k = 1, #PS, for (l = 1, #SS,
      my(x = PS[k]/d, t = SS[l]/d);
      if (g(x) == 0 || h(t) == 0, next);
      listput(PTS, [x, t]))));
  PTS = Vec(PTS);
  for (i = 1, #PTS,
    my(x = PTS[i][1], t = PTS[i][2], s = invAoo(x, t), N2, F);
    N2 = 6 * numerator(norm(g(x))) * denominator(norm(g(x)))
           * numerator(norm(h(t))) * denominator(norm(h(t)));
    F = factor(abs(N2));
    for (j = 1, #F[,1], s *= invA(x, t, F[j,1]));
    if (s != 1, bad++));
  printf("  (5) sum_v inv_v A(T) = 0 on X(Q) : %d wrong of %d rational points\n",
         bad, #PTS);
};

\\ ---------------------------------------------------------------- check 6
\\ inv_2 A is locally constant, so { inv_2 A = 1/2 } really is an OPEN set of
\\ X(Q_2) and "X(Q) misses it" really is non-density.  Take points where
\\ inv_2 A = 1/2 and perturb both coordinates 2-adically.

check6(B, K2) =
{ my(seeds = List(), bad = 0, n = 0);
  for (a = -30, 30, my(c = a^3 + 9); if (c == 0, next);
    for (b = -30, 30, my(e = b^3 - 81); if (e == 0, next);
      if (sq2(c) != sq2(e), next);
      if (g(a) == 0 || h(b) == 0, next);
      if (invA(a, b, 2) == -1, listput(seeds, [a,b]))));
  seeds = Vec(seeds);
  for (i = 1, min(#seeds, B),
    my(x0 = seeds[i][1], t0 = seeds[i][2]);
    for (m = -3, 3, for (r = -3, 3,
      my(x = x0 + m*2^K2, t = t0 + r*2^K2);
      if (g(x) == 0 || h(t) == 0, next);
      n++;
      if (invA(x, t, 2) != -1, bad++))));
  printf("  (6) inv_2 A is constant on the discs x0 + 2^%d Z_2, t0 + 2^%d Z_2\n", K2, K2);
  printf("      around %d points where it is 1/2 : %d wrong of %d\n", min(#seeds,B), bad, n);
};

\\ ------------------------------------------------------------------------ run

{
print("======================================================================");
print("kummer-j0-brauer.gp -- the Azumaya algebra of kummer-example-j0.typ s7");
print("");
print("K = Q(u), u^3 = 3;  disc = ", K.disc, ";  signature = ", [K.r1, K.r2]);
print("A = cor_{K(X)/Q(X)} ( x^2 - u^2 x + 3u,  t^2 + 3u t + 9u^2 )");
print("");
check1();
print("");
check2([1,-1,2,-2,3,5,-5,6,7,-7,10,-30], [2,3,5,7]);
print("");
print("  (3) inv_q A vanishes identically for q != 2 (condition (E)):");
check3([3,5,7,11,13,47,61], 40);
print("");
print("  (4) inv_2 A on X(Q_2), by square class of the point:");
check4(60);
print("");
check5([1,-1,2,-3,5,-5,6,-7,10,-30], 4);
print("");
check6(40, 8);
print("");
print("The last two lines of (4) are the whole of section 6 in one function:");
print("inv_2 A is a locally constant function on X(Q_2) that is not constant,");
print("(3) says every other place contributes nothing, and (5) pins the total");
print("to 0 on X(Q).  So X(Q) misses the open set where inv_2 A = 1/2, and is");
print("not dense in X(Q_2).  The eight square classes of section 6.12 are the");
print("eight values inv_2 A takes -- no twist is mentioned anywhere above.");
}
quit;
