\\ kummer-example-p13.gp --- computations for kummer-example-p13.typ
\\
\\   E  : y^2 = x(x-5)(x-7)          twists  E_d  : y^2 = x(x-5d)(x-7d)
\\   E' : v^2 = u(u-1)(u-2)          twists  E'_d : y^2 = x(x-d)(x-2d)
\\
\\ E' is the congruent number curve (j = 1728), so E'_d has positive rank iff |d|
\\ is congruent.  Both curves have full rational 2-torsion, for every d.
\\
\\ Run as:   gp -q kummer-example-p13.gp

p = 13;
Ed(d)  = ellinit([0,-12*d,0,35*d^2,0]);
Epd(d) = ellinit([0,-3*d,0,2*d^2,0]);

\\ transport a rational point on E_d to E_{d0} (d = d0*lam^2) and reduce mod p
{tr(P,lam) = if(P==[0], [0],
   if(valuation(P[1],p) < 0, [0], [Mod(P[1],p)/lam^2, Mod(P[2],p)/lam^3]));}
{sqm(a) = lift(sqrt(Mod(a,p)));}

\\ subgroup of EF generated by a list of points
{sub(EF,pts) = my(S=Set([[0]]), fr=[[0]], nw);
  while(#fr, nw = List();
    for(i=1,#fr, for(j=1,#pts, my(Q = elladd(EF,fr[i],pts[j]));
      if(!setsearch(S,Q), S = setunion(S,Set([Q])); listput(nw,Q))));
    fr = Vec(nw));
  S;}

\\ level of the pro-p part generated by P; full <=> 1 (good) or 0 (additive I0*)
{lev(E,P,M) = my(Q = ellmul(E,P,M)); if(Q==[0], 99, -valuation(Q[1],p)/2);}
{gens(E) = my(r = ellrank(E), P = r[4]);
  if(#P==0 && r[1]==1, P = [ellheegner(E)]);
  if(#P==0, [], ellsaturation(E,P,40));}

\\ ---------------------------------------------------------------- search
{search(B) = my(L = List());
  for(a=1,B, foreach([a,-a], d,
    if(core(abs(d)) != abs(d), next);
    if(ellrank(Ed(d))[1] < 1, next);
    if(ellrank(Epd(d))[1] < 1, next);
    listput(L,d)));
  Vec(L);}

\\ ------------------------------------------------- certificate, good reduction
\\ d0 in {1,2}: reference twist for a unit square class.
{report(d0, ds) =
  my(EF = ellinit([0,-12*d0,0,35*d0^2,0],p), FF = ellinit([0,-3*d0,0,2*d0^2,0],p));
  my(M = ellcard(EF), Mp = ellcard(FF), tot = Set());
  printf("\n--- class [%d] :  T = %s (%d)   T' = %s (%d)\n",
         d0, ellgroup(EF), M, ellgroup(FF), Mp);
  foreach(ds, d,
    my(E = Ed(d), F = Epd(d), lam = sqm(d/d0));
    my(g1 = gens(E), g2 = gens(F));
    my(t1 = [[Mod(0,p),Mod(0,p)],[Mod(5*d0,p),Mod(0,p)],[Mod(7*d0,p),Mod(0,p)]]);
    my(t2 = [[Mod(0,p),Mod(0,p)],[Mod(d0,p),Mod(0,p)],[Mod(2*d0,p),Mod(0,p)]]);
    my(S1 = sub(EF, concat(apply(P->tr(P,lam),g1), t1)));
    my(S2 = sub(FF, concat(apply(P->tr(P,lam),g2), t2)));
    printf("  d=%4d  rk %d gens %s  ->  images %s   [T:S_d]=%d\n",
           d, #g1, g1, apply(P->tr(P,lam),g1), M/#S1);
    printf("          rk %d gens %s  ->  images %s   [T':S'_d]=%d   levels %d,%d\n",
           #g2, g2, apply(P->tr(P,lam),g2), Mp/#S2,
           vecmin(apply(P->lev(E,P,M),g1)), vecmin(apply(P->lev(F,P,Mp),g2)));
    for(i=1,#S1, for(j=1,#S2, tot = setunion(tot, Set([[S1[i],S2[j]]])))));
  printf("  ==> union covers %d of %d : %s\n", #tot, M*Mp,
         if(#tot == M*Mp, "COVERS", "does NOT cover"));}

\\ --------------------------------------------------- certificate, additive I0*
\\ T is the component group = image of the rational 2-torsion, so only the level
\\ can fail.  Full pro-p part <=> v_p(x(4P)) = 0.
{reportram(nm, d) =
  my(E = Ed(d), F = Epd(d), L1 = elllocalred(E,p), L2 = elllocalred(F,p));
  my(g1 = gens(E), g2 = gens(F));
  printf("\n--- class %s :  d = %d\n", nm, d);
  printf("  E_d : kod %s  c_%d = %d  p-torsion over Q_p: %d  gens %s  v(x(4P)) = %d\n",
     L1[2], p, L1[4], #polrootspadic(elldivpol(E,p),p,8), g1,
     vecmin(apply(P->valuation(ellmul(E,P,4)[1],p),g1)));
  printf("  E'_d: kod %s  c_%d = %d  p-torsion over Q_p: %d  gens %s  v(x(4P)) = %d\n",
     L2[2], p, L2[4], #polrootspadic(elldivpol(F,p),p,8), g2,
     vecmin(apply(P->valuation(ellmul(F,P,4)[1],p),g2)));}

\\ ------------------------------------------------------------------- run
{
print("twists with both ranks positive, |d| <= 60:");
print(search(60));
report(1,  [30]);            \\ class [1]  : single twist
report(2,  [6]);             \\ class [2]  : single twist, via rank 2
report(2,  [-31,-6,41]);     \\ class [2]  : the three-twist pencil
reportram("[13]", 13);
reportram("[26]", -78);
}
quit
