#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show link: set text(fill: blue.darken(20%))
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#align(center)[
  #text(size: 16pt, weight: "bold")[How local Tate duality is proved]
  #v(2mm)
  #text(size: 10pt)[The purely local fact --- what it rests on, why it already
  contains local class field theory, and the two instances the rest of these notes use]
  #v(1mm)
  #text(size: 9pt, style: "italic")[on a question of Rene Pannekoek;
  checked in `local-duality.gp`, output in `results/local-duality.txt`]
]

#v(4mm)

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *The short answer.* Everything reduces to one computation, $"inv" : "Br"(K) tilde.equiv QQ slash ZZ$,
  and then to formal cohomological machinery. But the theorem is not *cheaper* than local class
  field theory: the case $M = ZZ slash n$, $i = 1$ of the duality statement *is* the norm residue
  isomorphism. There is no route to the local fact that bypasses LCFT --- they sit at the same
  depth. What is genuinely soft is the *tame* part: away from the residue characteristic the
  unramified subgroups are exact annihilators for elementary reasons, and that is the version the
  survey actually uses at good places.
]

= The statement <sec-statement>

Let $K slash QQ_p$ be finite, $M$ a finite $G_K$-module, and $M^D = "Hom"(M, overline(K)^times)$
its Cartier dual. Cup product followed by the invariant gives
$ H^i (K, M) times H^(2-i) (K, M^D) --> H^2 (K, overline(K)^times) = "Br"(K)
  -->^("inv") QQ slash ZZ , $
and the theorem is that this is a *perfect pairing of finite groups* for $i = 0, 1, 2$.

For abelian varieties there is the companion statement
$ A(K)^and times H^1 (K, hat(A)) --> QQ slash ZZ , $
perfect, with $A(K)$ profinitely completed and $H^1$ discrete torsion. This is the pairing that
`ec-density-bm.typ` writes as $⟨Q_v, beta_v⟩_v$. It follows from the finite-module case by a limit
argument (@sec-av).

= The engine: $"inv" : "Br"(K) tilde.equiv QQ slash ZZ$ <sec-inv>

This is the one hard local input. It comes in two halves: *every class is split by an unramified
extension*, and *for unramified cyclic extensions the group can be computed by hand*. Together
they give $"Br"(K) = union.big_n "Br"(K_n slash K) = union.big_n 1/n ZZ slash ZZ$.

== A valuation on a division algebra, and why uniqueness is the point <sec-valD>

Let $D$ be a central division algebra over $K$ of degree $n$, so $dim_K D = n^2$. One wants to do
to $D$ what one does to a field: put a valuation on it, take its valuation ring, and look at the
residue algebra. The obstacle is that $D$ is not commutative, so there is no direct construction.

The way in is that *every single element of $D$ lives in a field*: for $x in D$, the subring
$K(x)$ generated by $K$ and $x$ is commutative, hence a finite field extension of $K$. So one can
try to define
$ w(x) := "the extension of " v " to " K(x), " evaluated at " x . $

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *This is exactly where uniqueness is used, and it is used twice.*

  #v(1.5mm)
  *(1) Well-definedness.* $K$ is complete, so $v$ extends to a finite extension $F slash K$ in
  *exactly one* way, by $v_F (y) = 1/[F:K] dot v(N_(F slash K) (y))$. Were there several
  extensions, $w(x)$ would depend on a choice of extension --- and worse, on which subfield of
  $D$ one chose to view $x$ in, since a given $x$ lies in many. Uniqueness makes $w$ a
  well-defined function on all of $D$ at once, and makes the values computed in different
  subfields automatically consistent.

  #v(1.5mm)
  *(2) Checking the axioms.* $w(x y) = w(x) + w(y)$ is multiplicativity of the reduced norm. The
  ultrametric inequality is the one that has no non-commutative proof --- but it does not need
  one: dividing through, it reduces to $w(1 + z) >= min(0, w(z))$, and $1 + z$ lies in the
  *field* $K(z)$, where the inequality is the ordinary one. Uniqueness is what lets the value
  computed inside $K(z)$ be the value in $D$.
]

So $w$ is a valuation, $cal(O)_D = {w >= 0}$ is a ring --- the unique maximal order --- with a
unique maximal ideal $frak(m)_D = {w > 0}$, and one may form the *residue algebra*
$ overline(D) = cal(O)_D slash frak(m)_D , $
a finite-dimensional division algebra over the finite residue field $k$ of $K$. Without the
uniqueness there is no $w$, hence no $cal(O)_D$, no $overline(D)$, and the whole route below
collapses at the first step.

== The residue algebra is a field, and $e = f = n$ <sec-efn>

Two facts now do the work.

- *Wedderburn's little theorem*: a finite division ring is commutative. So $overline(D)$ is a
  *field*, a finite extension of $k$; write $f = [overline(D) : k]$.
- *The degree formula* $dim_K D = e f$, where $e = [w(D^times) : v(K^times)]$ --- the same
  $[L:K] = e f$ that holds for field extensions, and proved the same way, by lifting a
  $k$-basis of $overline(D)$ and multiplying by powers of a uniformiser of $D$.

Since $w$ takes values in $1/n ZZ$ (it is $1/n$ times a valuation of $K$, via the reduced norm)
one has $e <= n$; and $f <= n$ because $overline(D)$ embeds in a maximal subfield's residue
field. But $e f = dim_K D = n^2$. Two numbers at most $n$ with product $n^2$ must both equal $n$:
$ e = f = n . $
In particular $overline(D) slash k$ has degree exactly $n$ --- the residue algebra is as large as
it could possibly be.

== Lifting, and why a maximal subfield splits <sec-lift>

$overline(D) slash k$ is an extension of finite fields, hence generated by one element
$overline(alpha)$. Hensel lifts $overline(alpha)$ to $alpha in cal(O)_D$ with $K(alpha) slash K$
*unramified of degree $n$*. Since the maximal subfields of $D$ have degree exactly $n$,
$K(alpha)$ is a maximal subfield, and it is unramified.

It remains that a maximal subfield splits:

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *If $L subset D$ is a maximal subfield then $D ⊗_K L tilde.equiv M_n (L)$.* Let $D$ act on
  itself by left multiplication and let $L$ act by right multiplication; the two commute, so
  $D ⊗_K L -> "End"_L (D)$. $D$ is an $L$-vector space of dimension $n$, so the target is
  $M_n (L)$. The source is a simple algebra, so the map is injective; and both sides have
  $L$-dimension $n^2$. Injective plus equal dimensions gives an isomorphism. $qed$
]

So $[D]$ dies in $"Br"(L)$ for an unramified $L slash K$, which is the first half:
$"Br"(K) = union.big_n "Br"(K_n slash K)$, $K_n$ the unramified extension of degree $n$.

== Computing $"Br"(L slash K)$ for $L$ unramified <sec-brlk>

Let $L slash K$ be unramified cyclic of degree $n$, $G = "Gal"(L slash K) = ⟨sigma⟩$. Two steps.

*Step 1: $"Br"(L slash K) tilde.equiv H^2 (G, L^times)$.* This is the crossed-product theorem ---
a central simple algebra split by $L$ *is* a crossed product $⊕_(tau in G) L u_tau$, and
associativity of its multiplication table is the $2$-cocycle condition. It is written out in
§6 of `csa-brauer.typ`, so nothing new is needed here.

*Step 2: for $G$ cyclic, $H^2 (G, M) tilde.equiv M^G slash N_G (M)$*, so
$H^2 (G, L^times) = K^times slash N_(L slash K) (L^times)$. Now compute that norm group, and
this is where "unramified" enters:

- $L^times = pi^ZZ times cal(O)_L^times$, with $pi$ a uniformiser of $K$ --- and $pi$ stays a
  uniformiser of $L$ precisely because $L slash K$ is unramified. So $N(pi) = pi^n$.
- *Units are norms:* $N(cal(O)_L^times) = cal(O)_K^times$. On residue fields the norm
  $ell^times -> k^times$ is $x |-> x^((q^f - 1) slash (q-1))$, whose image is the subgroup of
  index $(q^f-1) slash (q-1)$ in a cyclic group of order $q^f - 1$ --- that is, all of $k^times$.
  Then one climbs the unit filtration: on $U^((i)) slash U^((i+1))$ the norm becomes the *trace*
  $ell -> k$, surjective because the extension is separable. Completeness assembles the
  successive approximations.

Hence $N(L^times) = {x in K^times : n divides v(x)}$, and
$ K^times slash N(L^times) tilde.equiv ZZ slash n , quad x |-> v(x) mod n , quad
  "inv"(x) := v(x) slash n in 1/n ZZ slash ZZ . $

One check remains: that these invariants are *compatible* as $n$ grows, so that
$1/n ZZ slash ZZ arrow.r.hook 1/(n m) ZZ slash ZZ$ under inflation $K_n subset K_(n m)$. That is
a direct computation with norms and Frobenius, and in the limit gives
$"inv" : "Br"(K) tilde.equiv QQ slash ZZ$.

== The $n = 2$ case, checked <sec-n2check>

Everything above is visible in the quaternion case, where the Hilbert symbol computes it. Take
$u$ a non-residue unit, so $K = QQ_p (sqrt(u))$ is the unramified quadratic extension.

#align(center)[
#table(columns: 2, align: (left, left), stroke: 0.4pt, inset: 6pt,
  [statement], [check],
  [units are norms], [$(u, w)_p = +1$ for every unit $w$, at every odd $p < 40$ --- no exceptions],
  [a uniformiser is not], [$(u, p)_p = -1$ at every such $p$],
  [so $N(L^times) = {v " even"}$ and $"inv"(x) = v(x) slash 2$], [the index is $2$, detected by
    $v_p mod 2$],
  [the unramified subfield sits in the division algebra and splits it],
    [$(u,p)$ is a division algebra since $(u,p)_p = -1$, and $u$ becomes a square in
     $QQ_p (sqrt u)$, which therefore splits it],
)]

and the residue-field input of Step 2 is checked directly: the norm
$FF_(q^f)^times -> FF_q^times$ is surjective for every prime $q <= 19$ and $f <= 4$.

= Why the theorem contains local class field theory <sec-lcft>

Take $M = ZZ slash n$ with trivial action, so $M^D = mu_n$, and look at $i = 1$:
$ H^1 (K, ZZ slash n) times H^1 (K, mu_n) = "Hom"(G_K, ZZ slash n) times K^times slash (K^times)^n
  --> 1/n ZZ slash ZZ , quad (chi, a) |-> chi("rec"(a)) . $
Perfectness of *this* pairing is precisely the statement that the reciprocity map
$"rec" : K^times -> G_K^"ab"$ induces an isomorphism $K^times slash (K^times)^n tilde.equiv
G_K^"ab" slash n$ --- the norm residue isomorphism. So local duality is not a lemma on the way to
LCFT; it has LCFT inside it. The cases $i = 0, 2$ for the same $M$ are just $"inv"$ again.

== The instance you can check by hand: $n = 2$ <sec-n2>

$mu_2 = {plus.minus 1}$ already lies in $QQ_p$, so both sides are $QQ_p^times slash (QQ_p^times)^2$
and the pairing is the Hilbert symbol. Perfectness is then literally non-degeneracy of the Gram
matrix over $FF_2$:

#align(center)[
#table(columns: 4, align: (center, center, center, center), stroke: 0.4pt, inset: 5pt,
  [$p$], [$\#(QQ_p^times slash "sq")$], [Gram rank over $FF_2$], [radical],
  [$2$], [$8$], [$3$ of $3$], [trivial],
  [$3, 5, 7, 11, 13$], [$4$], [$2$ of $2$], [trivial],
)]

At every $p$, including $2$, the only class pairing trivially with everything is the trivial one.
That is local Tate duality for $ZZ slash 2$, verified exhaustively.

= The proof proper: dévissage <sec-devissage>

With the $M = ZZ slash n$ case in hand, the rest is formal. Write
$alpha^i (M) : H^i (K, M) -> H^(2-i)(K, M^D)^or$ for the map induced by the pairing. One shows
$alpha^i$ is an isomorphism by:

+ *Finiteness.* $H^i (K, M)$ is finite for finite $M$ --- so Pontryagin duality behaves and one may
  argue by counting.
+ *The five lemma.* $alpha^i$ is a map of long exact sequences in $M$, so the class of $M$ for
  which it is an isomorphism is closed under extensions. Induct on $\#M$: reduce to $M$ killed by
  a prime.
+ *Shapiro plus induced modules.* Choose $L slash K$ finite Galois with $G_L$ acting trivially on
  $M$. Then $M$ embeds in $"Ind"_(G_L)^(G_K) (M|_(G_L))$, and for induced modules Shapiro's lemma
  turns the statement over $K$ into the statement over $L$ --- where the module is *trivial*, i.e.
  @sec-lcft.

That is the whole architecture. Serre, _Galois Cohomology_ II.5; Milne, _Arithmetic Duality
Theorems_ I.2; Neukirch--Schmidt--Wingberg VII.2. There is also a conceptual repackaging: $G_K$ is a
duality group of cohomological dimension $2$ with dualizing module the roots of unity, so the
theorem is Poincaré duality for $"Spec" K$ viewed as a $2$-dimensional object.

= The numerical half: Tate's Euler characteristic formula <sec-euler>

The companion result, proved by the same dévissage, is
$ (\#H^0 (K,M) dot \#H^2 (K,M)) slash \#H^1 (K,M) = ||\#M||_K . $
This is what upgrades "isotropic" to "*maximal* isotropic", and it is the fact the other documents
lean on.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  Take $M = E[n]$, self-dual under the Weil pairing, so $\#H^2 = \#H^0 = \#E[n](K)$. Then
  $ \#H^1 (K, E[n]) = \#E[n](K)^2 dot |n|_K^(-2) , quad "while" quad
    \#(E(K) slash n) = \#E[n](K) dot |n|_K^(-1) . $
  Hence $\#W^2 = \#H^1$: the local Kummer image $W = E(K) slash n E(K)$ is *exactly*
  half-dimensional. Isotropy itself comes from the diagram
  $0 -> E(K) slash n -> H^1(K,E[n]) -> H^1(K,E)[n] -> 0$: two Kummer classes pair through the
  image in $H^1(K,E)$, which is zero on $E(K) slash n$. So $W$ is *Lagrangian*.
]

The factor $|n|_K^(-1)$ is invisible away from $n$ and is the entire subtlety at $v divides n$.
Checked for $n = 2$ at $v = 2$, where it is live:

#align(center)[
#table(columns: 4, align: (left, center, center, center), stroke: 0.4pt, inset: 5pt,
  [curve], [$dim E[2](QQ_2)$], [$dim W_2$], [$dim H^1$],
  [$y^2+y=x^3-x$ (37)], [$0$], [$1$], [$2$],
  [$y^2+x y+y=x^3+x^2-x$ (89)], [$1$], [$2$], [$4$],
  [$y^2+y=x^3+x^2$ (43)], [$0$], [$1$], [$2$],
  [$y^2=x^3-2x$], [$1$], [$2$], [$4$],
  [$y^2=x^3-x$], [$2$], [$3$], [$6$],
)]

$dim W_2 = dim E[2](QQ_2) + 1$ against $dim H^1 = 2 dim E[2](QQ_2) + 2$: half throughout, with the
$+1$ and $+2$ being exactly the $|2|_2^(-1)$ correction that is absent at odd places.

= Symmetric versus alternating self-duality <sec-symalt>

Worth separating, because the two are easy to conflate and the difference is what makes the
Kummer surface behave differently from the Pell conic.

- $ZZ slash 2$ is self-dual *symmetrically*. Over $QQ_2$ the Hilbert form on
  $QQ_2^times slash (QQ_2^times)^2 tilde.equiv FF_2^3$ is non-degenerate on an *odd*-dimensional
  space, so a Lagrangian would need dimension $3 slash 2$ --- there is none. The diagonal
  $(a,a)_2$ is non-trivial for $a in {-1,-2,-5,-10}$, and the largest totally isotropic subspace
  has dimension $1$ (e.g. spanned by $2$).
- $E[n]$ is self-dual *alternatingly*, via the Weil pairing, on an *even*-dimensional space --- and
  there Lagrangians exist. $W_v$ is one.

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  That is the whole reason for the collapse in `density-bridge.typ` §2. On the Kummer surface the
  reciprocity sum pairs *two points*, both in the Lagrangian $W_v$, so it vanishes identically and
  gives $0 = 0$; the twisted pairing exists to break exactly this. The quaternion argument of
  `integral-bm.typ` pairs a point against a *class*, and $ZZ slash 2$ has no Lagrangian to collapse
  into --- so no such degeneration occurs there.
]

= The tame case is soft, the wild case is not <sec-tamewild>

For $ell != p$ the module is unramified at good reduction, and $H^1_"ur"(K, M)$ and
$H^1_"ur"(K, M^D)$ are exact annihilators of each other, each of order $\#H^0$. That alone gives
the duality in the tame range, with no fundamental class --- and it is precisely the "unramified
isotropy" that kills $beta_v$ at good places throughout the survey.

#align(center)[
#table(columns: 4, align: (center, center, center, center), stroke: 0.4pt, inset: 5pt,
  [$p$], [unramified classes], [order], [half of $\#H^1$?],
  [$3, 5, 7, 11, 13$], [${1, u}$], [$2$], [*yes*],
  [$2$], [${1, 5}$], [$2$], [*no* --- $\#H^1 = 8$],
)]

At $ell = p$ the module is no longer unramified --- the formal group is in the way --- the count
fails, and one is thrown back on $"inv"$ and LCFT in full. Which is the same tame/wild line as
`wild-symbols.typ`: soft and residue-field-sized away from the residue characteristic, genuinely
analytic at it.

= From finite modules to abelian varieties <sec-av>

From $0 -> E(K) slash n -> H^1(K, E[n]) -> H^1(K,E)[n] -> 0$ and self-duality of $E[n]$, the two
outer terms are exact annihilators of each other under the duality pairing, hence perfectly paired.
Now take the inverse limit over $n$ on the left, giving $E(K)^and$, and the direct limit over $n$ on the
right, giving all of $H^1(K,E)$ (which is torsion). That is
$ E(K)^and times H^1 (K, E) --> QQ slash ZZ , $
the pairing used in `ec-density-bm.typ`. For a general abelian variety it is $A(K) times H^1(K, hat(A))$;
for elliptic curves $hat(E) = E$ by the principal polarisation, which is exactly why $E[n]$ is
self-dual and why the Weil pairing appears where it does.

#v(3mm)

_Companion file:_ `local-duality.gp`, run as

```sh
gp -q -s 4000000000 local-duality.gp < /dev/null > results/local-duality.txt
```

It verifies the $ZZ slash 2$ case as non-degeneracy of the Hilbert symbol (exhaustive Gram
matrices at $p = 2,3,5,7,11,13$), the unramified annihilation and its failure at $2$, the
Lagrangian count for $E[2]$ over $QQ_2$ including the $|2|_2^(-1)$ correction, and the largest
totally isotropic subspace of $QQ_2^times slash "sq"$.
