#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show link: set text(fill: blue.darken(20%))
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#align(center)[
  #text(size: 16pt, weight: "bold")[Class groups at Mersenne and Fermat discriminants]
  #v(2mm)
  #text(size: 10pt)[Reconstructing a one-line comment of Lemmermeyer's: two phenomena,
  and neither is the one the wording suggests]
  #v(1mm)
  #text(size: 9pt, style: "italic")[checks in `mersenne-fermat-class.gp`]
]

#v(4mm)

#block(fill: luma(245), inset: 9pt, radius: 3pt, width: 100%)[
  On MathOverflow 151396, "The exponent of Ш of $y^2 = x^3 + p x$, where $p$ is a Fermat prime",
  Franz Lemmermeyer commented:

  #v(2mm)
  #align(center)[_"There are similar phenomena in connection with class groups of quadratic fields
  whose discriminants are Mersenne or Fermat primes. These things are not trivial."_]

  #v(2mm)
  He was asked for a reference and, in the saved copy of the page, gave none.
]

#block(fill: rgb("#fff4e6"), inset: 8pt, radius: 3pt, width: 100%)[
  *This note is a reconstruction, not a report.* Nothing below is evidence of what Lemmermeyer
  meant. It is an attempt to find phenomena that fit the description, and it finds *two* --- which
  are different from each other, so the comment does not pin down one of them.
]

= What the comment is a comment on <sec-context>

The question observes $Ш(y^2 = x^3 + p x) tilde.equiv (ZZ slash 2^(k-1))^2$ for $p = F_k = 2^(2^k)+1$,
i.e. $Ш = 0, (ZZ slash 2)^2, (ZZ slash 4)^2, (ZZ slash 8)^2$ at $p = 5, 17, 257, 65537$. As
`sha-fermat.typ` §1 puts it, that splits into two questions of very different character: *why the
shape $(ZZ slash 2^e)^2$* --- forced, elementary --- and *why $e = k-1$* --- the whole content, and
unexplained. Any "similar phenomenon" should have that same two-part character, and both candidates
below do.

= Reading A: Mersenne, where the shape forces a large cyclic subgroup <sec-mersenne>

$M_p = 2^p - 1 equiv 3$ (mod $4$), so $-M_p equiv 1$ (mod $4$) is a *prime* discriminant and
$h(-M_p)$ is odd by genus theory. Now use the shape of the number.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Proposition.* In $QQ(sqrt(-M_p))$ the prime $frak(p)_2$ above $2$ has order *exactly* $p-2$ in
  the class group. Hence
  $ (p - 2) space divides space h(-M_p) . $

  #v(2mm)
  _Proof._ $alpha = (1 + sqrt(-M_p)) slash 2$ has norm $(1 + M_p) slash 4 = 2^(p-2)$, and $2$
  splits since $-M_p equiv 1$ (mod $8$); so $frak(p)_2^(p-2)$ is principal and the order divides
  $p-2$. Conversely suppose $frak(p)_2^k$ is principal, $0 < k < p-2$, generated by
  $(x + y sqrt(-M_p)) slash 2$: then $x^2 + M_p y^2 = 2^(k+2)$. If $y eq.not 0$ this forces
  $2^p - 1 <= 2^(k+2)$, i.e. $k >= p-2$. If $y = 0$ the generator is rational and
  $frak(p)_2^k = (2^(k slash 2))= frak(p)_2^(k slash 2) overline(frak(p))_2^(k slash 2)$, which by
  unique factorisation needs $frak(p)_2 = overline(frak(p))_2$ --- false. $qed$
]

#align(center, table(
  columns: 6, align: (center, right, right, center, center, left),
  stroke: 0.4pt + luma(170), inset: (x: 8pt, y: 3.5pt),
  table.header([$p$], [$M_p$], [$h(-M_p)$], [$p-2$], [$"ord"[frak(p)_2]$], [$"Cl"$]),
  [$5$], [$31$], [$3$], [$3$], [$3$], [$ZZ slash 3$],
  [$7$], [$127$], [$5$], [$5$], [$5$], [$ZZ slash 5$],
  [$13$], [$8191$], [$55$], [$11$], [$11$], [$ZZ slash 55$],
  [$17$], [$131071$], [$285$], [$15$], [$15$], [$ZZ slash 285$],
  [$19$], [$524287$], [$255$], [$17$], [$17$], [$ZZ slash 255$],
  [$31$], [$2147483647$], [$19865$], [$29$], [$29$], [$ZZ slash 19865$],
))

#v(2mm)
This *is* the two-part character of @sec-context. The structure --- a cyclic subgroup of order
$p-2$ --- is forced and elementary. The size is not: $p - 2 approx log_2 M_p$ while
$h approx sqrt(M_p)$, so the theorem explains a vanishing fraction of the class number, and the
ratio $h slash (p-2)$ (1, 1, 1, 5, 19, 15, 685) is exactly as unexplained as the exponent $k-1$ is
in the Ш question. "These things are not trivial" fits.

This family is studied: divisibility of $h$ for $QQ(sqrt(1 - 2 m^k))$ is the subject of
#link("https://arxiv.org/abs/2111.04387")[arXiv:2111.04387], and $-M_p = 1 - 2^p$ is the case at
hand.

= Reading B: Fermat, where the shape makes the symbols explicit <sec-fermat>

The Mersenne argument gives *nothing* for Fermat primes. In $QQ(sqrt(F_k))$ one has
$(sqrt(F_k)-1)(sqrt(F_k)+1) = F_k - 1 = 2^(2^k)$, so $"ord"[frak(p)_2]$ divides $2^k$; but $F_k$ is
a prime discriminant, so $h$ is odd, so that order is $1$ and no bound drops out. A different
mechanism is needed, and there is one.

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *A Fermat prime comes with its own $a^2 + b^2$.* $F_k = 1^2 + (2^(2^(k-1)))^2$, so in the
  representation $p = a^2 + b^2$ with $a$ odd and $b$ even --- the one that governs *biquadratic*
  residues --- the answer is explicit: $a = 1$, $b = 2^(2^(k-1))$. Every quartic symbol therefore
  collapses to a condition on $k$.
]

By `cubic-residues.typ` §6.3, $2$ is a fourth power mod $p$ exactly when $8 divides b$ --- here
exactly when $2^(k-1) >= 3$, i.e. when $k >= 3$. And the $2$-class group of $QQ(sqrt(-F_k))$ ---
discriminant $-4 F_k$, two prime discriminant factors, so cyclic of even order --- jumps there:

#align(center, table(
  columns: 5, align: (center, right, center, center, center),
  stroke: 0.4pt + luma(170), inset: (x: 9pt, y: 3.5pt),
  table.header([$k$], [$F_k$], [$b = 2^(2^(k-1))$], [$2$ a fourth power?], [$2$-part of
    $"Cl"(-4F_k)$]),
  [$1$], [$5$], [$2$], [no], [$2$],
  [$2$], [$17$], [$4$], [no], [$4$],
  [$3$], [$257$], [$16$], [*yes*], [$16$],
  [$4$], [$65537$], [$256$], [*yes*], [$64$],
))

#v(2mm)
The $2$-part runs $2, 4, 16, 64$: it *skips $8$*, and the skip is exactly at $k = 3$, exactly where
$2$ becomes a fourth power. That is the signature of Rédei's theory --- the $4$-rank and $8$-rank of
a $2$-class group are governed by quadratic and quartic residue symbols among the prime
discriminant factors --- and for Fermat primes those symbols are not conditions to be checked but
functions of $k$.

This reading is much closer to Lemmermeyer's own work: *Reciprocity Laws* is the standard reference
for exactly these quartic and octic symbols, and his theorem that $p equiv 9$ (mod $16$) forces
$h(QQ(root(4,p))) equiv 2$ (mod $4$) (@sec-refs [3]) is the same genre. Fermat primes are
$1$ (mod $16$) for $k >= 2$ so that theorem does not apply to them, but the class numbers of those
quartic fields grow anyway: $1, 2, 60$ for $k = 1, 2, 3$.

= What the comment does and does not settle <sec-status>

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  Both readings are real, both are checked below, and *they are not the same phenomenon*:

  #v(1.5mm)
  - *Mersenne (@sec-mersenne)*: the binary shape of the discriminant forces a large cyclic
    subgroup, by a norm computation. Nothing to do with residue symbols.
  - *Fermat (@sec-fermat)*: the binary shape makes the residue symbols that govern the $2$-class
    group explicit. Nothing to do with a forced subgroup --- the analogous forcing is empty there.

  #v(1.5mm)
  So a comment naming both families in one breath is naming two mechanisms. What they share is the
  *shape* of the answer, and it is the shape of the Ш question they were a comment on: the special
  form of the prime hands you the structure and never the size.
]

= What the companion script checks <sec-gp>

`mersenne-fermat-class.gp`, results in `results/mersenne-fermat-class.txt`.

#v(1mm)
- *(1)* $-M_p$ and $F_k$ are prime discriminants with $h$ odd; $-4F_k$ has two prime discriminant
  factors and $h$ even. The genus-theory frame for everything else.
- *(2)* $"ord"[frak(p)_2] = p-2$ exactly, and $(p-2) divides h(-M_p)$, on seven Mersenne primes up
  to $2^(31)-1$.
- *(3)* $8 divides b$ agrees with the direct quartic test at every Fermat prime, and the table of
  @sec-fermat.
- *(4)* $h(QQ(F_k^(1 slash 4)))$ for $k = 1,2,3$.
- *(5)* The size comparison of @sec-mersenne: $p-2$ against $h$ against $sqrt(M_p)$.

= References <sec-refs>

#block(inset: (left: 4pt))[
#set enum(numbering: "[1]")
+ #link("https://mathoverflow.net/questions/151396/")[MathOverflow 151396], "The exponent of Ш of
  $y^2 = x^3 + p x$, where $p$ is a Fermat prime". The source of the comment. Treated in this
  repository by `sha-fermat.typ`.
+ F. Lemmermeyer, *Reciprocity Laws: from Euler to Eisenstein*, Springer 2000. The quartic and
  octic residue symbols of @sec-fermat, and the Rédei theory that connects them to $2$-class
  groups.
+ #link("https://arxiv.org/abs/1009.3990")[arXiv:1009.3990], "A result of Lemmermeyer on class
  numbers": if $p equiv 9$ (mod $16$) then $h(QQ(root(4,p))) equiv 2$ (mod $4$). Same genre, and
  the reason @sec-fermat is the reading closer to his own work.
+ #link("https://arxiv.org/abs/2111.04387")[arXiv:2111.04387], "The divisibility of the class number
  of the imaginary quadratic fields $QQ(sqrt(1-2m^k))$" --- the family containing @sec-mersenne.
+ L. Rédei, H. Reichardt, *Die Anzahl der durch vier teilbaren Invarianten der Klassengruppe eines
  beliebigen quadratischen Zahlkörpers*, J. reine angew. Math. *170* (1934), 69--74. The $4$-rank,
  which is what @sec-fermat is watching.
]
