#!/usr/bin/env python3
"""Turn the raw output of the survey runs into survey-tables.typ.

Reads   results/survey-Nmin20.txt   (the main run: 30 surfaces, p <= 200)
        results/surfaces-cremona.txt (the curve list, from surfaces.sage)
and the follow-up runs results/survey-{deephunt,audit,rankaudit,p2deep,
p2hunt}.txt, whose few numbers are transcribed in the tables below.

Run from this directory:  python3 survey-tables.py
"""
import json, re, os

path = "results/survey-Nmin20.txt"
txt = open(path).read().splitlines()

surfaces = []
cur = None
for ln in txt:
    if ln.startswith("=== "):
        m = re.match(r"=== (\S+)(?: \[(\w+)\])?\s+f = x\^3 \+ \((-?\d+)\)x\^2 \+ \((-?\d+)\)x \+ \((-?\d+)\)", ln)
        lbl = ln[4:].split("  f =")[0].strip()
        a, b, c = re.findall(r"\((-?\d+)\)", ln)[:3]
        cur = dict(label=lbl, f=(int(a), int(b), int(c)), primes=[], w2=None)
        surfaces.append(cur)
    elif ln.startswith("INFO "):
        cur["discf"] = int(re.search(r"discf=(-?\d+)", ln).group(1))
        cur["rootsQ2"] = int(re.search(r"rootsQ2=(\d+)", ln).group(1))
    elif ln.startswith("SWEEP "):
        cur["twists"] = int(re.search(r"twists=(\d+)", ln).group(1))
        cur["tsweep"] = int(re.search(r"time=(\d+)", ln).group(1))
    elif ln.startswith("P "):
        t = ln.split()
        cur["primes"].append(dict(p=int(t[1]), w=[int(x) for x in t[2:6]],
                                  path=t[6], nf=int(t[7])))
    elif ln.startswith("ODD "):
        cur["full"] = int(re.search(r"full=(\d+)/", ln).group(1))
        cur["nprimes"] = int(re.search(r"full=\d+/(\d+)", ln).group(1))
        cur["cheap"] = int(re.search(r"cheap=(\d+)", ln).group(1))
        cur["desc"] = int(re.search(r"desc=(\d+)", ln).group(1))
        cur["todd"] = int(re.search(r"time=(\d+)", ln).group(1))
    elif ln.startswith("TWO "):
        cur["w2"] = [int(x) for x in re.search(r"\[([^\]]*)\]", ln).group(1).split(",")]
        cur["cover2"] = int(re.search(r"cover=(\d+)/", ln).group(1))
        cur["tp2"] = int(re.search(r"time=(\d+)", ln).group(1))
    elif ln.startswith("TOTAL "):
        cur["ttot"] = int(re.search(r"time=(\d+)", ln).group(1))


by = {s["label"].split()[0]: s for s in surfaces}

# ---- identification from the Sage/Cremona listing ----------------------
ident = {}
for ln in open("results/surfaces-cremona.txt"):
    t = ln.split()
    if len(t) < 12 or ln.startswith("#"):
        continue
    ident[t[1]] = dict(Nmin=int(t[0]), N=int(t[2]), f=(int(t[3]), int(t[4]), int(t[5])),
                       j=t[6], cm=int(t[7]), rank=int(t[8]), tors=int(t[9]), nfac=int(t[10]))
ident["496a"] = dict(Nmin=496, N=496, f=(0,1,1), j="6912/31", cm=0, rank=1, tors=1, nfac=1)

ORDER = [s["label"].split()[0] for s in surfaces]

# ---- final p = 2 status, after the deeper searches ----------------------
p2final = {k: list(by[k]["w2"]) for k in ORDER}
for lbl, w in [("14a1", [-231,-29,-1595,1199,-814,22,-182,-1218]),
               ("14a3", [-231,-29,-1595,1199,-814,22,-182,-1218]),
               ("14a4", [-231,-29,469,1199,-814,22,-182,-1218]),
               ("15a3", [-95,3,13,4807,34,22,10,30]),
               ("15a8", [1785,-285,-6315,10695,-3390,-9690,2490,-690]),
               ("17a3", [-39,19,157,-10481,-14,86,26,-114]),
               ("17a4", [-2279,19,157,0,1378,86,26,1742])]:
    p2final[lbl] = w

# ---- the odd-prime failures, and what the deeper search did ------------
resolved = {("19a3", 3, 2): 12306}          # found at cofactor m <= 20000
FAILS = [("11a1", 11, 1, 2, 50, "I_5", 5, 115),
         ("14a1",  7, 0, 2, 18, "I_3", 3, 144),
         ("14a2",  7, 0, 2, 36, "I_6", 6, 143),
         ("15a1",  5, 0, 2, 16, "I_4", 4, 145),
         ("15a4",  5, 0, 2, 32, "I_8", 8, 144),
         ("17a1", 17, 0, 2, 64, "I_4", 4, 167),
         ("19a1", 19, 1, 2, 54, "I_3", 3,  96),
         ("27a1",  3, 3, 2,  9, '"IV"^*', 3, 96)]
FAILSET = {(l, p, k) for (l, p, k, *_) in FAILS}

def cname(k, p):
    return ["1", "u", str(p), "u %s" % p][k]

def esc(s):
    return s.replace("_", "-")

out = []
W = out.append

W("// GENERATED by gen.py from results/survey-*.txt -- do not edit by hand.\n")

# ============ 1. identification table ==================================
W("#let idtable = table(")
W("  columns: 9, align: (left, right, right, left, right, right, right, right, right),")
W("  stroke: 0.4pt + luma(170), inset: (x: 4pt, y: 2.5pt),")
W("  table.header([*surface*], [$N_min$], [$N$], [$f = x^3 + a x^2 + b x + c$],")
W("               [$r$], [$T$], [$n_QQ$], [$n_(QQ_2)$], [$|op(\"disc\") f|$]),")
for lbl in ORDER:
    i = ident[lbl]; s = by[lbl]
    a, b, c = i["f"]
    def term(co, v):
        if co == 0: return ""
        sg = "+" if co > 0 else "-"
        return " %s %s%s" % (sg, abs(co) if (abs(co) != 1 or v == "") else "", v)
    poly = "x^3" + term(a, "x^2") + term(b, "x") + term(c, "")
    ctl = "" if i["cm"] == 0 else "#super[CM]"
    W("  [%s%s], [%d], [%d], [$%s$], [%d], [%d], [%d], [%d], [%d]," %
      (lbl, ctl, i["Nmin"], i["N"], poly, i["rank"], i["tors"],
       {1: 0, 2: 1, 3: 3}[i["nfac"]], s["rootsQ2"], abs(s["discf"])))
W(")\n")

# ============ 2. summary table =========================================
W("#let summarytable = table(")
W("  columns: 8, align: (left, center, center, center, center, right, right, right),")
W("  stroke: 0.4pt + luma(170), inset: (x: 5pt, y: 2.5pt),")
W("  table.header([*surface*], [odd $p$], [$p = 2$], [cheap], [descent],")
W("               [sweep], [odd $p$], [$p = 2$]),")
for lbl in ORDER:
    s = by[lbl]
    n2 = sum(1 for x in p2final[lbl] if x != 0)
    nodd = s["full"] + sum(1 for (l, p, k), d in resolved.items() if l == lbl)
    # + : completed only by the deeper cofactor pass;  * : still short
    deep_odd = any(l == lbl for (l, _p, _k) in resolved)
    base2 = sum(1 for x in s["w2"] if x != 0)
    mark = "#super[\*]" if nodd < 45 else ("#super[+]" if deep_odd else "")
    m2 = "#super[\*]" if n2 < 8 else ("#super[+]" if base2 < 8 else "")
    W("  [%s], [%d/45%s], [%d/8%s], [%d], [%d], [%.1f], [%.1f], [%.1f]," %
      (lbl, nodd, mark, n2, m2, s["cheap"], s["desc"],
       s["tsweep"]/1000, s["todd"]/1000, s["tp2"]/1000))
W(")\n")

# ============ 3. p = 2 witness table ===================================
W("#let p2table = table(")
W("  columns: 9, align: (left, right, right, right, right, right, right, right, right),")
W("  stroke: 0.4pt + luma(170), inset: (x: 4pt, y: 2.5pt),")
W("  table.header([*surface*], [$[1]$], [$[3]$], [$[5]$], [$[7]$],")
W("               [$[2]$], [$[6]$], [$[10]$], [$[14]$]),")
for lbl in ORDER:
    cells = "".join(" [%s]," % (d if d != 0 else "#text(fill: rgb(\"#b00\"))[---]")
                    for d in p2final[lbl])
    W("  [%s],%s" % (lbl, cells))
W(")\n")

# ============ 4. the failing classes ===================================
W("#let failtable = table(")
W("  columns: 8, align: (left, right, center, center, right, center, right, right),")
W("  stroke: 0.4pt + luma(170), inset: (x: 5pt, y: 3pt),")
W("  table.header([*surface*], [$p$], [class], [$g$], [$M_p$], [Kodaira], [$c_p$],")
W("               [rank $>= 2$ twists tried]),")
for (lbl, p, k, g, M, kod, cp, n2) in FAILS:
    W("  [%s], [%d], [$[%s]$], [%d], [%d], [$%s$], [%d], [%d]," %
      (lbl, p, cname(k, p).replace(" ", " dot "), g, M, kod, cp, n2))
W(")\n")

# ============ 5. per-surface witness tables ============================
def ptab(rows):
    o = ["table(", "  columns: 5, align: right, stroke: 0.4pt + luma(170),",
         "  inset: (x: 4pt, y: 2pt),",
         "  table.header([$p$], [$[1]$], [$[u]$], [$[p]$], [$[u p]$]),"]
    for r in rows:
        o.append("  " + r)
    o.append(")")
    return "\n".join(o)

W("#let primetables = [")
for lbl in ORDER:
    s = by[lbl]; i = ident[lbl]
    a, b, c = i["f"]
    def term(co, v):
        if co == 0: return ""
        return " %s %s%s" % ("+" if co > 0 else "-", abs(co) if (abs(co) != 1 or v == "") else "", v)
    poly = "x^3" + term(a, "x^2") + term(b, "x") + term(c, "")
    W("  === %s#h(1fr)#text(size: 9pt)[$f = %s$, $N_min = %d$]" % (lbl, poly, i["Nmin"]))
    rows = []
    for q in s["primes"]:
        cs = []
        for kk in range(4):
            d = q["w"][kk]
            if d == 0:
                key = (lbl, q["p"], kk)
                if key in resolved:
                    cs.append("[%d#super[+]]" % resolved[key])
                else:
                    cs.append("[#text(fill: rgb(\"#b00\"))[---]]")
            else:
                cs.append("[%d]" % d)
        rows.append("[%d], %s," % (q["p"], ", ".join(cs)))
    half = (len(rows) + 1) // 2
    W("  #set text(size: 8pt)")
    W("  #grid(columns: (auto, auto), column-gutter: 0.9cm, align: top,")
    W("    " + ptab(rows[:half]).replace("\n", "\n    ") + ",")
    W("    " + ptab(rows[half:]).replace("\n", "\n    ") + ",")
    W("  )")
    W("  #set text(size: 10.5pt)")
    W("  #v(2mm)")
W("]\n")

open("survey-tables.typ", "w").write("\n".join(out) + "\n")
print("wrote survey-tables.typ,", len(out), "lines")
tot = sum(s["ttot"] for s in surfaces)
print("main run total %.1f s" % (tot/1000))

