/* template3.gp --- the 14a1 template applied to the two remaining odd-level
 * classes of section 3.3: 14a2 at p = 7 and 19a1 at p = 19, both at ell = 3.
 *
 * The technique is chapter 6. For each curve:
 *   (A) the base curve E_0 with rational 3-torsion, and the twist relating it
 *       to the surface's model y^2 = f(x);
 *   (B) the critical place p: both lines rational over Q_p (so dim W_p = 2),
 *       the image of (c_1, c_2) on W_p, and the tame cubic symbol table;
 *   (C) the wild place v = 3, over all FOUR square classes of Q_3^x.
 *
 * Every image is computed as the SUBGROUP GENERATED by the values on a set of
 * points shown to generate the relevant quotient -- taking the set of values
 * alone is not enough and gives sizes that are not subgroup orders.
 *
 * Run:  gp -q -s 4000000000 < template3.gp
 */

read("kummer2.gp");
read("survey.gp");

disc(m)   = if(m % 4 == 1, m, 4*m);
tw(E0, m) = if(m == 1, E0, ellinit(elltwist(ellinit(E0), disc(m))));
lines3(E) = { my(fa = factor(elldivpol(E, 3)), L = List());
  for(i = 1, #fa~, if(poldegree(fa[i,1]) == 1,
    listput(L, -polcoef(fa[i,1], 0)/polcoef(fa[i,1], 1))));
  Vec(L); }
/* the point with this x, if it is Q_v-rational: [1, y] or [0, 0] */
ycoord(E, x0, v, prec) = {
  my(D = (E.a1*x0 + E.a3)^2 + 4*(x0^3 + E.a2*x0^2 + E.a4*x0 + E.a6) + O(v^prec), y);
  if(D == 0, return([1, (-(E.a1*x0 + E.a3))/2]));
  if(!issquare(D, &y), return([0, 0]));
  [1, (-(E.a1*x0 + E.a3) + y)/2]; }
slope(E, x0, y0) = (3*x0^2 + 2*E.a2*x0 + E.a4 - E.a1*y0)/(2*y0 + E.a1*x0 + E.a3);

/* classes in Q_v^x modulo cubes, as vectors in (Z/3)^2 */
cubp(z, p) = { my(k = valuation(z, p), u = z/p^k, c, g = lift(znprimroot(p)^((p-1)/3)));
  c = Mod(truncate(u), p)^((p-1)/3);
  for(j = 0, 2, if(c == Mod(g, p)^j, return([k % 3, j]))); error("not a cube root of 1"); }
cub3(z) = { my(k = valuation(z, 3), u = z/3^k, t);
  t = truncate(u) % 9; if(t > 4, t = 9 - t); [k % 3, t]; }
/* subgroup of (Z/3)^n generated by a list of vectors */
span(V, n) = { my(S = [vector(n)], nw = 1, T);
  while(nw, nw = 0;
    for(i = 1, #S, for(j = 1, #V,
      T = vector(n, k, (S[i][k] + V[j][k]) % 3);
      if(!setsearch(Set(S), T), S = concat(S, [T]); nw = 1))));
  Set(S); }

inEn(P, v, n) = (P == [0]) || (valuation(P[1], v) <= -2*n);
genq(Em, v, n, pts) = {
  my(Ep = padiccurve(Em, v), G = List([[0]]), nw, grew = 1, T);
  for(k = 1, #pts, nw = 1;
    for(j = 1, #G, if(inEn(elladd(Ep, pts[k], ellneg(Ep, G[j])), v, n), nw = 0; break));
    if(nw, listput(G, pts[k])));
  while(grew, grew = 0;
    for(i = 1, #G, for(j = 1, #G, T = elladd(Ep, G[i], G[j]); nw = 1;
      for(k = 1, #G, if(inEn(elladd(Ep, T, ellneg(Ep, G[k])), v, n), nw = 0; break));
      if(nw, listput(G, T); grew = 1))));
  [#G, Mval(Em, v) * if(n == 1, 1, 3)]; }

/* --- the tame cubic symbol on Q_p^x/cubes, p = 1 mod 3 ---
 * With a = p^al u_a and b = p^be u_b, the tame formula is
 *      (a,b)_p = ((-1)^(al be) u_a^be / u_b^al)^((p-1)/3).
 * The sign drops: p = 1 mod 3 and p odd give p = 1 mod 6, so (p-1)/3 is even.
 * Writing a class as [al, j] with u^((p-1)/3) = zeta^j, the symbol is additive:
 *      (a,b)_p = j_a be - j_b al   in Z/3. */
tamec(A, B, p) = (A[2]*B[1] - B[2]*A[1]) % 3;
symtable(p) = { my(cl = List(), nz = 0, dg = 0);
  for(k = 0, 2, for(j = 0, 2, listput(cl, [k, j])));
  cl = Vec(cl);
  for(i = 1, 9, for(j = 1, 9,
    my(s = tamec(cl[i], cl[j], p));
    if(s != 0, nz++); if(i == j && s != 0, dg++)));
  print("   the tame cubic symbol on Q_", p, "^x modulo cubes: ", nz,
        " of 81 non-zero, diagonal non-zero ", dg, "   => ",
        if(dg == 0 && nz > 0, "alternating and non-degenerate, hence symplectic on W_p",
           "PROBLEM")); }

/* --- (B) the critical place --- */
atp(name, E0, m, p, prec, XMAX) = {
  my(ev = tw(E0, m), E = ellinit(ev), vE, Em, xs, ys, ms, pts, img = List(), g,
     nrat = 0, S, diag = 0, anti = 0);
  Em = ellminimalmodel(E, &vE);
  xs = lines3(E);
  ys = vector(#xs, i, ycoord(E, xs[i], p, prec));
  for(i = 1, #xs, if(ys[i][1], nrat++));
  print("   ", name, "  d = ", m, "   lines x = ", xs, "   both rational over Q_", p, ": ",
        nrat == 2, "   dim W_", p, " = ", nrat, "   M = ", Mval(Em, p));
  if(nrat != 2, print("      not both rational -- skipped"); return);
  ms = vector(2, i, slope(E, xs[i], ys[i][2]));
  pts = ppointsE(E, p, prec, XMAX);
  g = genq(Em, p, 1, apply(P -> ellchangepoint(P, vE), pts));
  for(k = 1, #pts,
    my(L1 = pts[k][2] - ys[1][2] - ms[1]*(pts[k][1] - xs[1]),
       L2 = pts[k][2] - ys[2][2] - ms[2]*(pts[k][1] - xs[2]), A, B);
    if(valuation(L1, p) > prec - 10 || valuation(L2, p) > prec - 10, next);
    A = cubp(L1, p); B = cubp(L2, p);
    listput(img, [A[1], A[2], B[1], B[2]]));
  S = span(Vec(img), 4);
  for(k = 1, #S, my(w = S[k]);
    if(w[1] == w[3] && w[2] == w[4], diag++);
    if(w[1] == (-w[3]) % 3 && w[2] == (-w[4]) % 3, anti++));
  print("      generates E(Q_", p, ")/E_1: ", g[1], " of ", g[2],
        if(g[1] == g[2], " yes", " NO"),
        "   image of (c_1,c_2): ", #S, " elements, ",
        if(diag == #S, "diagonal", if(anti == #S, "antidiagonal", "NEITHER")),
        if(#S == 9, "   => c_1 alone identifies W_p", "")); }

/* --- (C) the wild place v = 3 --- */
at3(name, E0, m, prec, XMAX) = {
  my(ev = tw(E0, m), E = ellinit(ev), vE, Em, xs, nrat = 0, x0 = 0, y0 = 0, sl,
     pts, img = List(), g, S);
  Em = ellminimalmodel(E, &vE);
  xs = lines3(E);
  for(i = 1, #xs, my(y = ycoord(E, xs[i], 3, prec));
    if(y[1], nrat++; if(x0 == 0 && y0 == 0, x0 = xs[i]; y0 = y[2])));
  print("   ", name, "  d = ", m, "   Q_3-rational 3-torsion points: ", nrat,
        "   dim W_3 = ", 1 + nrat, "   Kodaira ", elllocalred(Em, 3)[2],
        if(elllocalred(Em,3)[2] == 1, Str("  a_3 = ", ellap(Em,3)), ""));
  if(nrat == 0, print("      dim W_3 = 1, so beta_3 is trivial (beta is alternating)"); return);
  sl = slope(E, x0, y0);
  pts = ppointsE(E, 3, prec, XMAX);
  g = genq(Em, 3, 2, apply(P -> ellchangepoint(P, vE), pts));
  for(k = 1, #pts, my(L = pts[k][2] - y0 - sl*(pts[k][1] - x0));
    if(valuation(L, 3) > prec - 10, next);
    listput(img, cub3(L)));
  S = span(apply(w -> [w[1], if(w[2] == 1, 0, if(w[2] == 2, 1, 2))], Vec(img)), 2);
  print("      generates E(Q_3)/E_2: ", g[1], " of ", g[2], if(g[1] == g[2], " yes", " NO"),
        "   image of alpha: ", #S, " elements   => dim ker alpha = ",
        if(#S == 1, 2, if(#S == 3, 1, "?")),
        if(#S == 1, "   => L_3 lies in one H_i: phi-stable",
           "   => stable iff the other kernel is non-zero (good ordinary lemma 6.4.1)")); }

main() = {
  print("=== 14a2 at p = 7, level 3 ===");
  print("y^2 = f(x) with f = x^3 - 11x^2 - 528x - 2240 IS 14a2 (conductor 14),");
  print("so no twist relates the surface model to E_0. Failing class: [1] at 7.");
  print("");
  symtable(7);
  print("   critical place, representatives of the class [1] of Q_7^x:");
  foreach([1, 2, 11, 15, 23], m, atp("14a2", [1,0,1,-36,-70], m, 7, 40, 40));
  print("   wild place v = 3, all four square classes of Q_3^x:");
  foreach([1, -1, 3, -3], m, at3("14a2", [1,0,1,-36,-70], m, 50, 40));
  print("");
  print("=== 19a1 at p = 19, level 3 ===");
  print("y^2 = f(x) with f = x^3 - 10x^2 - 4x - 6 has conductor 1216 = 2^6 * 19:");
  print("it is the twist of E_0 = 19a1 by m = 2. So E_d = E_0^(2d), and since 2");
  print("is a NON-residue mod 19, the surface's failing class [u] at 19 becomes");
  print("the class [1] for the parameter d' = 2d.");
  print("");
  symtable(19);
  print("   critical place, representatives of the class [1] of Q_19^x:");
  foreach([1, 5, 6, 7, 11], m, atp("19a1", [0,1,1,-9,-15], m, 19, 40, 40));
  print("   wild place v = 3, all four square classes of Q_3^x:");
  foreach([1, -1, 3, -3], m, at3("19a1", [0,1,1,-9,-15], m, 50, 40));
}
main();
print("");
print("### template3 finished");
quit;
