/* twoplace.gp --- can two places be live at once?
 *
 * Every theorem of chapter 7 arranges for beta_v to be trivial at all but ONE
 * place, so reciprocity pins that one down. If instead exactly TWO places p, q
 * are live, reciprocity gives beta_p + beta_q = 0 rather than beta_p = 0, and
 * the constraint is a CORRELATION between the two: the image R of E_d(Q) in
 * W_p + W_q is isotropic for gamma = beta_p + beta_q. If gamma is non-zero, R is
 * proper, so E_d(Q) is not dense in E_d(Q_p) x E_d(Q_q) -- while possibly being
 * dense in each factor. See chapter 9.
 *
 * This screens for surfaces where that happens, at level 2 with one rational
 * root. Both structural lemmas must hold, or the other places are not dead:
 *   - beta alternating at every place: the 2-torsion field must be Q(i), i.e.
 *     q(x) must be a SUM OF TWO SQUARES;
 *   - beta_q trivial at odd q | d (lemma 6.2.2): b must be a PERFECT SQUARE.
 * Writing q(x) = (x + al)^2 + mu^2 and b = al^2 + mu^2, the second says
 * al^2 + mu^2 = k^2: the family is indexed by PYTHAGOREAN TRIPLES.
 *
 * Then the coprimality argument confines the live places to 2 and the primes
 * dividing b = k^2, so the odd live places lie among the prime factors of the
 * HYPOTENUSE k. Two live odd places therefore need k with at least two distinct
 * prime factors -- and k, being a hypotenuse, is a product of primes = 1 mod 4,
 * so the smallest candidates are k = 65 and k = 85.
 *
 * Run:  gp -q -s 4000000000 < twoplace.gp
 */

read("kummer2.gp");
read("survey.gp");

unitpart(a, v) = truncate(a*v^(-valuation(a,v))) * v^valuation(a,v);
sqcls(z, v) = { my(k = valuation(z,v), u = z/v^k);
  if(v == 2, [k % 2, lift(Mod(truncate(u), 8))],
             [k % 2, if(issquare(Mod(truncate(u), v)), 1, -1)]); }
/* representatives of Q_v^x modulo squares. For v = 1 mod 4, -1 is a RESIDUE, so
   [1,-1,v,-v] covers only two of the four classes; use a primitive root. */
sqreps(v) = if(v == 2, [1,-1,2,-2,5,-5,10,-10], my(u = lift(znprimroot(v))); [1, u, v, u*v]);
inEn(P, v, n) = (P == [0]) || (valuation(P[1], v) <= -2*n);
/* the subgroup generated by the sampled points, inside E(Q_v)/E_n. The quotient
   has order Mval (n = 1) or 4*Mval (n = 3), so a G that grows past a few times
   that is a p-adic dedup failure, not a big group: bail out and report NO. */
genq(Em, v, n, pts) = {
  my(Ep = padiccurve(Em, v), G = List([[0]]), nw, grew = 1, T,
     cap = 8 * Mval(Em, v) * if(n == 1, 1, 4));
  for(k = 1, #pts, nw = 1;
    for(j = 1, #G, if(inEn(elladd(Ep, pts[k], ellneg(Ep, G[j])), v, n), nw = 0; break));
    if(nw, listput(G, pts[k])));
  while(grew, grew = 0;
    for(i = 1, #G, for(j = 1, #G, T = elladd(Ep, G[i], G[j]); nw = 1;
      for(k = 1, #G, if(inEn(elladd(Ep, T, ellneg(Ep, G[k])), v, n), nw = 0; break));
      if(nw, listput(G, T); grew = 1));
      if(#G > cap, return([0, -1]))));
  [#G, Mval(Em, v) * if(n == 1, 1, 4)]; }

/* beta_v non-trivial on E_d : y^2 = x(x^2+adx+bd^2), c(P) = x(P) modulo squares?
   The image has at most 4 elements (8 at v = 2), so reduce to one representative
   per class before pairing. Returns [live?, |image|, generated?] */
probe(a, b, d, v, prec, XMAX) = {
  my(E = ellinit([0,a*d,0,b*d^2,0]), Em, vE, pts, S = Set([[0,1]]), R = List([1]),
     g, n = if(v == 2, 3, 1), nz = 0);
  if(E == 0 || E.disc == 0, return([-1,0,0]));
  Em = ellminimalmodel(E, &vE);
  pts = ppointsE(E, v, prec, XMAX);
  if(#pts < 4, return([-1,0,0]));
  g = genq(Em, v, n, apply(P -> ellchangepoint(P, vE), pts));
  for(k = 1, #pts,
    if(valuation(pts[k][1], v) > prec - 10, next);
    my(c = sqcls(pts[k][1], v));
    if(!setsearch(S, c), S = setunion(S, [c]); listput(R, unitpart(pts[k][1], v))));
  for(k = 1, #R, for(l = 1, #R, if(hilbert(R[k], R[l], v) != 1, nz++)));
  [nz > 0, #S, g[1] == g[2]]; }

/* one member of the family: q(x) = (x+al)^2 + mu^2, b = k^2 = al^2 + mu^2 */
run(al, mu, k, prec, XMAX) = {
  my(a = 2*al, b = k^2, ps, lp = List());
  if(poldisc(x^3 + a*x^2 + b*x) == 0, return(0));
  ps = Set(concat([2], factor(2*b)[,1]~));       /* live places are among these */
  for(i = 1, #ps, my(v = ps[i], hit = List());
    foreach(sqreps(v), m, if(probe(a, b, m, v, prec, XMAX)[1] == 1, listput(hit, m)));
    if(#hit > 0, listput(lp, [v, Vec(hit)])));
  print("   (", al, ",", mu, ",", k, ")   f = x(x^2 + ", a, "x + ", b, ")   N = ",
        ellglobalred(ellminimalmodel(ellinit([0,a,0,b,0])))[1],
        "   k = ", factor(k)[,1]~, "   LIVE: ", Vec(lp),
        if(#lp == 1, "   one live place", if(#lp >= 2, "   *** TWO OR MORE ***", "   none")));
  #lp; }

/* the candidate in detail: every place, every class */
detail(a, b, vs, prec, XMAX) = {
  for(i = 1, #vs, my(v = vs[i]);
    foreach(sqreps(v), m,
      my(r = probe(a, b, m, v, prec, XMAX));
      print("      v = ", v, "   class of d = ", sqcls(m, v),
            "   generates: ", if(r[3], "yes", "NO"),
            "   |image of c| = ", r[2],
            if(r[1] == 1, "   LIVE", "   dead")))); }

main() = {
  print("=== the family where both structural lemmas hold ===");
  print("q(x) = (x+al)^2 + mu^2 with al^2 + mu^2 = k^2: sum of two squares (so");
  print("beta is alternating) and b = k^2 a perfect square (so 6.2.2 kills q | d).");
  print("The odd live places lie among the prime factors of the hypotenuse k.");
  print("");
  foreach([[0,1,1],[3,4,5],[4,3,5],[5,12,13],[12,5,13],[8,15,17],[15,8,17],
           [7,24,25],[24,7,25],[20,21,29],[21,20,29],[9,40,41],[12,35,37],
           [35,12,37],[28,45,53],[11,60,61],[16,63,65],[33,56,65],[56,33,65],
           [48,55,73],[13,84,85],[36,77,85],[39,80,89],[65,72,97]], w,
    run(w[1], w[2], w[3], 30, 25));
  print("");
  print("=== the candidate (33,56,65): f = x(x^2 + 66x + 4225), N = 7280 ===");
  print("Live at 5 and at 13, in the class [1] of each, and dead everywhere else.");
  print("");
  detail(66, 4225, [2, 5, 7, 13], 30, 25);
  print("");
  print("=== and (13,84,85): f = x(x^2 + 26x + 7225), N = 28560 ===");
  print("");
  detail(26, 7225, [2, 5, 7, 17], 30, 25);
}
main();
print("");
print("### twoplace finished");
quit;
