/* vell.gp --- beta at the wild place v = ell.
 *
 * beta_ell vanishes on W_ell as soon as dim W_ell <= 1 (beta is alternating).
 * When dim W_ell = 2 the question is whether L_ell = delta(W_ell) is stable
 * under phi, i.e. whether L = (L cap H_1) + (L cap H_2), where
 *      ker alpha_1 = psihat_2(B_2(Q_ell)) / ell E(Q_ell),
 *      ker alpha_2 = psihat_1(B_1(Q_ell)) / ell E(Q_ell)
 * are the two intersections pulled back to W_ell (Steps 1-5 of section 5.1.5).
 *
 * CAUTION. "Both non-zero" is SUFFICIENT for stability but not necessary, and an
 * earlier version of this script treated it as an equivalence. If one of the two
 * has dimension 2 -- i.e. L is contained in a single H_i -- then L is a direct
 * sum trivially and is stable, with the other intersection zero. So a run showing
 * one kernel zero and the other non-zero settles NOTHING until the dimension of
 * the non-zero one is known. The positive verdicts below (both non-zero, hence
 * both of dimension 1) are unaffected; the negative ones have been withdrawn.
 *
 * CLAIM. If E has good ORDINARY reduction at ell, and E[ell] = C_1 + C_2 with
 * C_1 = Z/ell generated by a Q_ell-rational point and C_2 = mu_ell, then both
 * are non-zero and beta_ell = 0. Reason: over Z_ell the closure of C_1 is the
 * constant (etale) group scheme Z/ell and that of C_2 is mu_ell (connected at
 * residue characteristic ell); ordinary means the connected-etale sequence of
 * E[ell] has both pieces of order ell, so C_1 splits it and
 * E[ell] = C_1 + C_2 as finite flat group schemes. The Kummer image at a place
 * of good reduction is the flat subgroup H^1_f, which is functorial, so it
 * splits along that decomposition -- and a split L_ell is phi-stable.
 *
 * This script checks the conclusion directly. Membership in ell E(Q_ell) is
 * decidable because ell E contains ell E_1 = E_2, so ell E is a union of
 * E_2-cosets and ell E / E_2 = ell (E(Q_ell)/E_2), a finite group.
 *
 * Run:  gp -q -s 4000000000 < vell.gp
 */

read("kummer2.gp");
read("survey.gp");

inEn(P, p, n)      = (P == [0]) || (valuation(P[1], p) <= -2*n);
sameE2(Ep, P, Q, p) = inEn(elladd(Ep, P, ellneg(Ep, Q)), p, 2);
m5(C)              = [C.a1, C.a2, C.a3, C.a4, C.a6];

/* representatives of E(Q_p)/E_2 and of ell E(Q_p)/E_2.  ell is passed
   separately from the place p even though this script only ever runs at
   p = ell: using the place as the exponent is an easy and silent mistake. */
grp(Em, p, ell, prec, XMAX) = {
  my(Ep = padiccurve(Em, p), pts = ppointsE(Em, p, prec, XMAX),
     G = List([[0]]), L = List([[0]]), nw);
  for(i = 1, #pts, nw = 1;
    for(j = 1, #G, if(sameE2(Ep, pts[i], G[j], p), nw = 0; break));
    if(nw, listput(G, pts[i])));
  for(i = 1, #G, my(R = ellmul(Ep, G[i], ell)); nw = 1;
    for(j = 1, #L, if(sameE2(Ep, R, L[j], p), nw = 0; break));
    if(nw, listput(L, R)));
  [Ep, #G, Vec(L)];
}
inLL(Ep, L, P, p) = { for(j = 1, #L, if(sameE2(Ep, P, L[j], p), return(1))); 0; }

/* is the point of Em with x = x0 rational over Q_p ? */
ratpt(C, x0, p, prec) = {
  my(D = (C.a1*x0 + C.a3)^2 + 4*(x0^3 + C.a2*x0^2 + C.a4*x0 + C.a6) + O(p^prec));
  if(D == 0, return(1)); issquare(D);
}
/* dim of E[p](Q_p), from the two kernel polynomials */
torsdim(Em, p, kers, prec) = {
  my(n = 0);
  for(i = 1, #kers,
    my(g = kers[i], rts);
    /* a linear kernel polynomial has an EXACT rational root; using the p-adic
       approximation instead makes the discriminant look like O(p^k) = 0 and
       the squareness test unreliable */
    rts = if(poldegree(g) == 1, [-polcoef(g,0)/polcoef(g,1)],
             polrootspadic(g, p, prec));
    for(k = 1, #rts, if(ratpt(Em, rts[k], p, prec), n++; break)));
  n;
}
dualof(B, Emin, ell, mp, otherker) = {
  my(fa, Edd, Eddm, v, rts, g = 1, ok = 1);
  rts = polrootsreal(otherker);
  if(#rts == poldegree(otherker),
    for(k = 1, #rts, my(r = bestappr(rts[k], 10^20));
      g *= (x - subst(mp[1], x, r)/subst(mp[3], x, r)^2));
    Edd = ellisogeny(B, g); Eddm = ellminimalmodel(ellinit(Edd[1]), &v);
    if(m5(Eddm) == m5(Emin), return([Edd, v])));
  fa = factor(elldivpol(B, ell));
  for(i = 1, #fa~, if(poldegree(fa[i,1]) != (ell-1)/2, next);
    Edd = ellisogeny(B, fa[i,1]); Eddm = ellminimalmodel(ellinit(Edd[1]), &v);
    if(m5(Eddm) == m5(Emin), return([Edd, v])));
  0;
}

run(name, ev, p, kers, prec, XMAX) = {
  my(E = ellinit(ev), Em, vE, gg, Ep, nG, L, lr, td, dW, both = 1, ap);
  Em = ellminimalmodel(E, &vE);
  lr = elllocalred(Em, p);
  td = torsdim(E, p, kers, prec);   /* kers are for the given model E, not Em */
  dW = 1 + td;
  ap = if(lr[2] == 1, ellap(Em, p), "-");
  gg = grp(Em, p, p, prec, XMAX);   /* here the place IS the level */ Ep = gg[1]; nG = gg[2]; L = gg[3];
  print(name, "   Kodaira ", lr[2], " (1 = good)  c = ", lr[4], "  a_", p, " = ", ap,
        "   dim E[", p, "](Q_", p, ") = ", td, "   dim W_", p, " = ", dW);
  if(dW <= 1,
    print("      dim W_", p, " <= 1, so beta_", p, " = 0 because beta is alternating.");
    print(""); return);
  for(i = 1, 2,
    my(Ei = ellisogeny(E, kers[i]), B, Bm, vB, du, pts, esc = 0, tot = 0, im);
    B = ellinit(Ei[1]); Bm = ellminimalmodel(B, &vB);
    du = dualof(B, Em, p, Ei[2], kers[3-i]);
    if(du == 0, print("      B_", i, ": no dual found"); both = 0; next);
    pts = ppointsE(Bm, p, prec, XMAX);
    for(k = 1, #pts,
      im = isogapply(du[1][2], ellchangepointinv(pts[k], vB));
      if(im == [0], next);
      im = ellchangepoint(im, du[2]); tot++;
      if(!inLL(Ep, L, im, p), esc++));
    if(esc == 0, both = 0);
    print("      ker(alpha_", 3-i, ") non-zero: ", esc > 0,
          "     (", esc, " of ", tot, " dual images escape ", p, "E)"));
  print("      => ", if(both,
    Str("both intersections non-zero, so each has dimension 1, so L_", p,
        " is phi-stable and beta_", p, " = 0"),
    Str("NOT CONCLUSIVE: one intersection came out zero, but stability also holds",
        " when the other has dimension 2 (L inside a single H_i), which this test",
        " does not measure")));
  print("");
}
disc(d) = if(d % 4 == 1, d, 4*d);

main() = {
  my(E14 = ellinit([5,0,7,0,0]), K14 = [x, 3*x+7], Ed, kd);
  print("=== 11a1 at v = ell = 5 ===");
  print("Every d in the class [1] at 11 with dim W_5 = 2 has d a square in Q_5,");
  print("hence 5 does not divide d, hence GOOD reduction at 5. One check suffices.");
  print("");
  run("11a1, d = 1  ", [0,-1,1,-10,-20], 5, [x^2-21*x+80, 5*x^2+5*x-29], 40, 40);

  print("=== 14a1 at v = ell = 3 ===");
  print("Here dim W_3 = 2 happens in two ways: d a square in Q_3 (good reduction");
  print("at 3), and 3 | d with -3d a square (ADDITIVE reduction). Only the first");
  print("is covered by the claim above.");
  print("");
  run("14a1, d = 1        ", [5,0,7,0,0], 3, K14, 40, 40);
  foreach([-3, 33, -15, 21], d,
    my(ev = elltwist(E14, disc(d)));
    Ed = ellinit(ev);
    kd = select(f -> poldegree(f) == 1, Vec(factor(elldivpol(Ed, 3))[,1]~));
    if(#kd != 2, print("14a1, d = ", d, ": found ", #kd, " linear kernel factors -- skipped"); next);
    run(Str("14a1, d = ", d, "  (3 | d)"), ev, 3, kd, 40, 40));
}
main();
print("### vell finished");
quit;
