/* ============================================================================
   additive.gp -- the additive places, survey document chapter 10.8.

   The gap left by Theorem 5 was the ADDITIVE candidates.  This script carries
   the three computations that close most of it.

   (1) THE SPLIT CLASS NEED NOT BE UNRAMIFIED.  Step 4 of the recipe said the
       live class is the unique UNRAMIFIED class making E_d split multiplicative.
       That is right when E is multiplicative at v, and wrong when E is additive
       POTENTIALLY MULTIPLICATIVE (type I_n*), where the split class is ramified.
       Such places are therefore not a gap at all: Theorem 5 covers them, via a
       twist with v | d.

   (2) LEMMA 7.  At an additive v NOT dividing ell, E_0(Q_v) is pro-v -- the
       formal group is pro-v and E_0/E_1 is the additive group of the residue
       field -- so E_0(Q_v)/ell = 0 and

              W_v = E_d(Q_v)/ell = Phi_v/ell,

       the component group mod ell.  Since c_v <= 4 for additive reduction:
         ell >= 5 : W_v = 0, so beta_v = 0;
         ell = 3  : dim W_v <= 1 (only c_v = 3, Phi = Z/3), so beta_v = 0 as
                    beta is alternating at odd ell;
         ell = 2  : dim W_v <= 2, with equality exactly for Phi = (Z/2)^2, i.e.
                    type I0* with c_v = 4.
       Verified below by comparing #E(Q_v)/ell with #Phi_v/ell.

   (3) THE REMAINING CASE, ell = 2 with I0* and c_v = 4.  There W_v = Phi is
       generated by the 2-torsion, so beta is a Hilbert symbol of ROOT
       DIFFERENCES and needs no point search:
              c_i(T_j) = e_j - e_i   (j != i),   c_i(T_i) = prod_{k!=i}(e_i-e_k).
       Checked below against a direct search.  These places ARE live.

   Note what (2) says about the wild place: at v = ell the formal group is
   pro-ell and contributes everything, which is why x^3-2 is live at v = 3 on a
   type II fibre with c_v = 1, where Phi/3 = 0.  The wild place is the only one
   where W_v sees the formal group at all.

   Functions: kodname, tw, ci, imgs, predict, direct, splitscan, lemma7, run.
   Output: results/survey-additive.txt
   ============================================================================ */

read("kummer2.gp"); read("survey.gp");

kodname(k) = if(k==1,"I0", if(k==2,"II", if(k==3,"III", if(k==4,"IV", if(k>4, concat(["I",k-4]), if(k==-1,"I0*", concat(["I",-k-4,"*"])))))));
tw(E,d) = ellminimalmodel(ellinit([-27*E.c4*d^2, -54*E.c6*d^3]));
uni(a,v) = truncate(a*v^(-valuation(a,v)))*v^valuation(a,v);
cl(z,v) = [valuation(z,v)%2, if(issquare(Mod(truncate(z/v^valuation(z,v)),v)),1,-1)];
crv(es) = ellinit([0, -(es[1]+es[2]+es[3]), 0, es[1]*es[2]+es[1]*es[3]+es[2]*es[3], -es[1]*es[2]*es[3]]);

/* (1) which square class makes E_d split multiplicative at v */
splitscan(nam, ec, v) = { my(E = ellminimalmodel(ellinit(ec)), r = elllocalred(E,v), reps, out = List());
  reps = [1, lift(znprimroot(v)), v, v*lift(znprimroot(v))];
  foreach(reps, m, my(F = tw(E,m), s = elllocalred(F,v));
    if(s[2] > 4 && ellap(F,v) == 1, listput(out, m)));
  print("   ", nam, "  v = ", v, "   E is ", kodname(r[2]), " with c_v = ", r[4],
        "   v(j) = ", valuation(E.j,v),
        "   split-multiplicative class: d = ", Vec(out),
        if(#out && out[1] % v == 0, "   <== RAMIFIED", "")); }

/* (2) W_v versus the component group, at an additive v not dividing ell.
   With full rational 2-torsion the joint map (c_1,c_2) is injective on W_v,
   so |W_v| is the size of its image.  Compare with |Phi_v / 2|. */
/* |Phi/2| = |Phi[2]|.  Phi is cyclic of order c_v EXCEPT for type I_n* with n
   EVEN (I0* included), where Phi = (Z/2)^2.  Kodaira code -1 is I0*, -4-n is I_n*. */
starn(k) = if(k == -1, 0, -k - 4);
phimod2(r) = if(r[2] < 0 && starn(r[2]) % 2 == 0 && r[4] == 4, 4, gcd(2, r[4]));
wsize(es, v) = { my(E = crv(es), pts, S = Set());
  pts = ppointsE(E, v, 30, 60);
  for(k = 1, #pts, my(x0 = pts[k][1], a = x0 - es[1], b = x0 - es[2]);
    if(a == 0 || b == 0, next);
    if(valuation(a,v) > 20 || valuation(b,v) > 20, next);
    S = setunion(S, [[cl(a,v), cl(b,v)]]));
  #S; }
lemma7(nam, es, v) = { my(E = ellminimalmodel(crv(es)), r = elllocalred(E,v), w, p2);
  w = wsize(es, v); p2 = phimod2(r);
  print("   ", nam, "   v = ", v, "   type ", kodname(r[2]), "   c_v = ", r[4],
        "   |Phi/2| = ", p2, "   measured |W_v| = ", w,
        if(w == p2, "   AGREE", "   *** DISAGREE ***")); }

/* (3) beta from root differences alone, versus a direct search */
ci(es, i, j) = if(i == j, prod(k = 1, 3, if(k == i, 1, es[i]-es[k])), es[j]-es[i]);
imgs(es, v, i) = { my(S = Set([[0,1]]), R = List([1]));
  for(j = 1, 3, my(c = ci(es,i,j)); if(!setsearch(S, cl(c,v)), S = setunion(S,[cl(c,v)]); listput(R, uni(c,v))));
  R; }
predict(es, v, ia, ib) = { my(RA = imgs(es,v,ia), RB = imgs(es,v,ib), nz = 0, tot = 0);
  for(i=1,#RA, for(j=1,#RB, tot++; if(hilbert(RA[i],RB[j],v)!=1, nz++)));
  print("      from root differences: |im c_", ia, "| = ", #RA, "  |im c_", ib, "| = ", #RB,
        "   non-trivial ", nz, "/", tot, if(nz, "   LIVE", "   trivial")); nz; }
direct(es, v, ia, ib) = { my(E = crv(es), pts, RA = List(), RB = List(), SA = Set(), SB = Set(), nz = 0, tot = 0);
  pts = ppointsE(E, v, 30, 60);
  for(k = 1, #pts, my(x0 = pts[k][1], ca, cb); ca = x0 - es[ia]; cb = x0 - es[ib];
    if(ca == 0 || cb == 0, next); if(valuation(ca,v) > 20 || valuation(cb,v) > 20, next);
    if(!setsearch(SA,cl(ca,v)), SA=setunion(SA,[cl(ca,v)]); listput(RA, uni(ca,v)));
    if(!setsearch(SB,cl(cb,v)), SB=setunion(SB,[cl(cb,v)]); listput(RB, uni(cb,v))));
  for(i=1,#RA, for(j=1,#RB, tot++; if(hilbert(RA[i],RB[j],v)!=1, nz++)));
  print("      direct point search:   |im c_", ia, "| = ", #SA, "  |im c_", ib, "| = ", #SB,
        "   non-trivial ", nz, "/", tot, if(nz, "   LIVE", "   trivial")); nz; }
run(es, v) = { my(E = ellminimalmodel(crv(es)), r = elllocalred(E,v), ok = 1);
  print("");
  print("   f = (x-", es[1], ")(x-", es[2], ")(x-", es[3], ")   v = ", v,
        "   type ", kodname(r[2]), "   c_v = ", r[4], "   v(j) = ", valuation(E.j,v));
  foreach([[1,3],[1,2],[2,3]], w,
    print("    phi = (c_", w[1], ", c_", w[2], "):");
    my(a = predict(es, v, w[1], w[2]), b = direct(es, v, w[1], w[2]));
    if((a > 0) != (b > 0), ok = 0; print("      *** DISAGREE ***")));
  if(ok, print("    -- root-difference prediction agrees with the search on every phi")); }

/* (4) census of component groups at additive places of the family */
census() = { my(n = 0, seen = List());
  for(e2 = 1, 20, for(e3 = -20, -1,
    my(E = ellminimalmodel(crv([0,e2,e3])));
    foreach(factor(2*E.disc)[,1]~, v,
      if(v == 2, next);
      my(r = elllocalred(E,v));
      if(r[2] > 4 || r[2] == 1, next);
      listput(seen, concat([kodname(r[2]), " c=", r[4]])))));
  seen = Set(Vec(seen));
  for(i = 1, #seen, print("      ", seen[i]));
  print("   every one has Phi = (Z/2)^2, i.e. dim W_v = 2 -- the cases with");
  print("   dim W_v = 1 (Phi = Z/2 or Z/4) do not arise with full 2-torsion here."); }

main() = {
  print("=== (1) the split-multiplicative class can be RAMIFIED ===");
  print("11a1 is split I5 at 11; its twist by 11 is I5*, and the class that");
  print("makes THAT split multiplicative is the ramified one.");
  splitscan("11a1",            [0,-1,1,-10,-20], 11);
  splitscan("11a1 twisted by 11", ellminimalmodel(tw(ellminimalmodel(ellinit([0,-1,1,-10,-20])), 11)), 11);
  print("");
  print("=== (2) Lemma 7: at additive v not dividing ell, W_v = Phi_v / ell ===");
  lemma7("x(x-5)(x+5)",   [0,5,-5],   5);
  lemma7("x(x-7)(x+7)",   [0,7,-7],   7);
  lemma7("x(x-3)(x+3)",   [0,3,-3],   3);
  lemma7("x(x-11)(x+11)", [0,11,-11], 11);
  lemma7("x(x-6)(x+3)",   [0,6,-3],   3);
  lemma7("x(x-9)(x+3)",   [0,9,-3],   3);
  lemma7("x(x-12)(x+15)", [0,12,-15], 3);
  print("   (the last three are I_n* with n even, hence Phi = (Z/2)^2, not Z/4)");
  print("");
  print("=== (3) additive places at ell = 2: I0* with c_v = 4 gives dim W_v = 2 ===");
  run([0, 5, -5], 5);
  run([0, 7, -7], 7);
  run([0, 3, -3], 3);
  run([0, 11, -11], 11);
  print("");
  print("=== (4) which component groups actually occur at additive places ===");
  print("in the full-2-torsion family f = x(x-e2)(x-e3), |e| <= 20:");
  census();
}
main();
print("");
print("### additive finished");
quit;
