\\ cert-extended.gp -- the extended density certificate for kummer-padic-density.typ.
\\ Run from this directory:
\\     gp -q -s 12000000000 cert-extended.gp < /dev/null > results/cert-extended.txt
\\ The run is a second and a half.  It was fifty until ordv stopped taking its
\\ multiples on the rational curve; see the note there.
\\
\\ For each prime p <= 200 and each square class of Q_p^*/(Q_p^*)^2, the witness
\\ twist d of the table in section 6.3 is extended with
\\   (1) the isomorphism type of E^d(Q_p), as Z_p x C_a x C_b ;
\\   (2) the generators of E^d(Q) actually used (redundant ones dropped) ;
\\   (3) their images in Z_p x C_a x C_b .
\\
\\ Conventions.  E_d : Y^2 = X^3 + d^2 X + d^3, the twist of E = 496a by d.
\\ For p >= 3 the formal group is E_1(Q_p) = Z_p with E_n <-> p^(n-1) Z_p, and
\\ M = #(E(Q_p)/E_1) = c_p * #Etilde^ns(F_p).  The torsion T = E(Q_p)_tors is
\\ torsion-free-complemented: E(Q_p) = Z_p x T.
\\   * good reduction with p not dividing M : T = E(F_p), read off by ellgroup,
\\     and the T-coordinate of a point is literally its reduction mod p.
\\   * additive reduction (the classes [p] and [up], where v_p(d) is odd) : the
\\     model has v_p(c_4) = 2, v_p(Delta) = 6, so the type is I_0^*, a_p = 0 and
\\     M = c_p * p.  The prime-to-p part of T is Phi(F_p), of order c_p; the
\\     p-part is trivial whenever a single point topologically generates, since
\\     Z_p x Z/p is not procyclic.  That is exactly what the index computation
\\     (M/m) p^(v-1) = 1 certifies, so the certificate determines the structure.
\\
\\ The Z_p-coordinate of a point is only defined up to a unit (the choice of a
\\ topological generator of Z_p), so what is recorded is its VALUATION: alpha is
\\ written u for a unit (valuation 0) and p^k u otherwise.  A point generates the
\\ Z_p factor iff its coordinate is a unit, iff the formal depth v_p(c(mP)) = 1.

cden(Q) = if (Q == [0], 0, sqrtint(denominator(Q[1])));
Ed(d)   = ellinit([d^2, d^3]);
Mval(E,p) =
{ my(a = ellap(E,p));
  if (Mod(E.disc,p) != 0, p + 1 - a, elllocalred(E,p)[4] * (p - a));
}
\\ order of Pbar in E(Q_p)/E_1, and the formal depth of that multiple.
\\ Two things keep this cheap, and the second was missing for a long time.
\\   * The order of Pbar in E(Q_p)/E_1 divides M, so only the DIVISORS of M
\\     need testing, and each is reached by one ellmul (double-and-add)
\\     rather than by M repeated additions.
\\   * The multiples are taken over Q_p and not over Q.  Multiplying by e
\\     multiplies the canonical height by e^2, so the numerator of x(e P)
\\     has about e^2 h(P) / log 10 decimal digits; this sweep pairs M up to
\\     596 with generators of height 20, and at p = 149, d = 13559 the exact
\\     x(M P) is 3 071 818 digits -- 21.8 seconds for ONE multiple, and it
\\     overflows an 8 Mbyte stack.  Modulo p^PRECX an ellmul costs the same
\\     whatever e and h(P) are: the same computation is 0.010 seconds.  The
\\     cost was paid on every divisor of M and not just the last, and ordv
\\     is called once per candidate generator by gensalone and again for
\\     printing, so it dominated the run.
\\ E_1 membership is then v_p(x) < 0 rather than p | cden, and the depth is
\\ -v_p(x)/2 rather than v_p(cden): for a point of E_1 the numerator of x is
\\ prime to p, so the two agree.  This is the idiom phiclass already uses --
\\ p-adic coordinates against the rational ellinit -- so no second curve is
\\ needed.  One thing does not survive the move: p-adically the point at
\\ infinity is not distinguishable from a very deep point of E_1, so the case
\\ e P = O, which the rational version excluded by hand with Q != [0], is
\\ excluded here from the order of P in E(Q) instead, computed once by
\\ ellorder (which returns 0 for a point of infinite order).  Every E^d(Q) on
\\ this sweep has trivial torsion, so the exclusion never fires; it is kept so
\\ that the function does not depend on the witness table for its correctness.
PRECX = 80;
ordv(E, P, p, M) =
{ my(n = ellorder(E, P), Pp = [P[1] + O(p^PRECX), P[2] + O(p^PRECX)]);
  foreach (divisors(M), e,
    if (n && e % n == 0, next);
    my(Q = ellmul(E, Pp, e), w);
    if (Q != [0] && (w = valuation(Q[1], p)) < 0,
      return([e, (-w)\2])));
  [0, 0];
}
\\ Subgroup of E(F_p) generated by the reductions of gens (good reduction).
\\ Done in the finite field: cheap.  Returns its order.
subgrp(E, gens, p) =
{ my(Ep = ellinit(E,p), S = Set([[0]]), frontier);
  foreach (gens, P,
    my(Q = [Mod(P[1],p), Mod(P[2],p)], T = Set([[0]]), R = [0]);
    for (k = 1, 4*p+20, R = elladd(Ep, R, Q); T = setunion(T, Set([R])); if (R == [0], break));
    my(U = List());
    foreach (Vec(S), a, foreach (Vec(T), b, listput(U, elladd(Ep, a, b))));
    S = Set(Vec(U)));
  #S;
}
\\ does this single point topologically generate E(Q_p)?  m = M and depth 1.
gensalone(E, P, p, M) =
{ my(r = ordv(E, P, p, M));
  r[1] == M && r[2] == 1;
}



\\ ---- the additive lines: T = Phi(F_p), and it need not be cyclic.
\\ For these d the reduction is additive, E_0/E_1 = G_a(F_p) of order p, and
\\ M = c_p * p, so |T| = c_p.  T is NOT automatically cyclic: for I_0^* with
\\ c_p = 4 the component group is (Z/2)^2, and only for I_1^* is it Z/4.  Which
\\ one it is can be decided without any Kodaira table: E_0(Q_p) is torsion-free
\\ for p > 2 (E_1 = Z_p is, and E_0/E_1 = Z/p is odd), so E[2](Q_p) injects into
\\ Phi -- hence T = (Z/2)^2 exactly when the cubic splits completely over Q_p.
prootsQp(E, p, prec) =
{ my(f = x^3 + E.a4*x + E.a6, fp = factorpadic(f, p, prec), L = List());
  for (j = 1, #fp~,
    if (poldegree(fp[j,1]) == 1,
      for (k = 1, fp[j,2],
        listput(L, -polcoeff(fp[j,1],0) / polcoeff(fp[j,1],1)))));
  \\ Canonical order: by the p-adic expansion read from the BOTTOM, i.e. by the
  \\ leading digit u = (r/p^v) mod p.  Sorting by lift(r) instead orders by the
  \\ HIGH-order digits and therefore depends on the working precision -- the same
  \\ kind of irreproducibility as a randomly chosen base.  Here the three roots
  \\ have valuation 1 with distinct leading digits (they are the roots of the
  \\ good-reduction cubic modulo p, which are distinct for I_0^*), so the leading
  \\ digit already separates them; the full lift is kept only as a tiebreak.
  my(V = Vec(L));
  vecsort(V, r -> [lift(r / p^valuation(r,p)) % p, lift(r)]);
}
\\ a short label for a root: these all have valuation 1, so u p with u mod p
rootlabel(r, p) =
{ my(v = valuation(r, p));
  if (v == 1, Str(lift(r / p) % p, "p"), Str(lift(r)));
}
singptp(E, p) =
{ my(a1 = E.a1, a2 = E.a2, a3 = E.a3, a4 = E.a4, a6 = E.a6);
  for (x = 0, p-1, for (y = 0, p-1,
    if (Mod(y^2 + a1*x*y + a3*y - x^3 - a2*x^2 - a4*x - a6, p) == 0 &&
        Mod(a1*y - 3*x^2 - 2*a2*x - a4, p) == 0 &&
        Mod(2*y + a1*x + a3, p) == 0, return([x,y]))));
  [];
}
\\ Is a p-ADIC point in E_0(Q_p)?  Negative valuation means it reduces to O,
\\ hence lies in E_1 and so in E_0; otherwise compare the reduction with the
\\ singular point.
inE0pad(Q, p, sp) =
{ if (Q == [0], return(1));
  if (valuation(Q[1], p) < 0, return(1));
  if (#sp == 0, return(1));
  !(valuation(Q[1] - sp[1], p) > 0 && valuation(Q[2] - sp[2], p) > 0);
}
\\ The class of P in Phi = (Z/2)^2, against the basis given by the first two
\\ 2-torsion points.  The 2-torsion is NOT rational -- its x-coordinates lie in
\\ Z_p and not in Z -- so this has to be done with p-adic arithmetic; treating
\\ the roots as exact rational points is what made an earlier version return no
\\ answer at all.
phiclass(E, P, p, rts, sp, prec) =
{ my(Pp = [P[1] + O(p^prec), P[2] + O(p^prec)]);
  if (inE0pad(Pp, p, sp), return([0,0]));
  my(idx = [[1,0],[0,1],[1,1]]);
  for (j = 1, 3,
    my(T2 = [rts[j], O(p^prec)]);
    if (inE0pad(ellsub(E, Pp, T2), p, sp), return(idx[j])));
  [-1,-1];
}

\\ A CANONICAL base for E(F_p), so that the class column is reproducible.
\\ ellgroup(E,p,1) returns a generator chosen AT RANDOM on each call -- five
\\ successive calls at p = 23 for d = 1 return (18,20), (9,7), (9,7), (1,7),
\\ (19,5) -- so a class computed against it is neither reproducible nor
\\ checkable by a reader, and two generators of the same twist dlogged against
\\ separate calls are not even mutually consistent.  Instead: order the affine
\\ points of E(F_p) lexicographically by (x,y) and take the FIRST point of
\\ maximal order; in the non-cyclic case take the first g_2 of order n_2 that is
\\ independent of g_1.  Deterministic, and statable in one line.
canonbase(E, p) =
{ my(Ep = ellinit(E, p), G = ellgroup(E, p), pts = List(), n1, n2, g1 = 0, g2 = 0);
  for (x = 0, p-1,
    my(r = x^3 + E.a4*x + E.a6);
    for (y = 0, p-1, if (Mod(y^2 - r, p) == 0, listput(pts, [Mod(x,p), Mod(y,p)]))));
  pts = Vec(pts);
  n1 = G[1];
  foreach (pts, P, if (g1 == 0 && ellorder(Ep, P) == n1, g1 = P));
  if (#G == 1, return([Ep, [g1], G]));
  n2 = G[2];
  foreach (pts, P,
    if (g2 == 0 && ellorder(Ep, P) == n2,
      \\ independent of g1 iff <g1,P> has order n1*n2
      my(ok = 1, k);
      for (k = 1, n2-1, if (ellmul(Ep, P, k) == [0], break);
        my(inside = 0, e);
        for (e = 0, n1-1, if (ellmul(Ep, g1, e) == ellmul(Ep, P, k), inside = 1; break));
        if (inside, ok = 0; break));
      if (ok, g2 = P)));
  [Ep, [g1, g2], G];
}

\\ discrete log of Pbar in E(F_p), against the CANONICAL base above
dlog(Ep, P, gens, cyc) =
{ my(g1 = gens[1], n1 = cyc[1]);
  if (P == [0], return(if (#cyc == 1, [0], [0,0])));
  if (#cyc == 1,
    for (e = 0, n1-1, if (ellmul(Ep,g1,e) == P, return([e]))); return([-1]));
  my(g2 = gens[2], n2 = cyc[2]);
  for (e = 0, n1-1, for (f = 0, n2-1,
    if (elladd(Ep, ellmul(Ep,g1,e), ellmul(Ep,g2,f)) == P, return([e,f]))));
  [-1,-1];
}

{
WIT = [
  [3,   [7, -1, 3, 6]],        [5,   [1, 3, 5, -35]],
  [7,   [1, -1, 7, -7]],       [11,  [3, 6, 11, -11]],
  [13,  [-1, 5, -13, 26]],     [17,  [-1, 7, 34, 51]],
  [19,  [1, -1, 95, -95]],     [23,  [1, -1, 46, 115]],
  [29,  [-1, 11, -29, 58]],    [31,  [1, -1, 31, -62]],
  [37,  [-11, 6, -37, 74]],    [41,  [-1, 3, 41, 123]],
  [43,  [1, -1, -86, 86]],     [47,  [-11, -149, 94, 705]],
  [53,  [11, 22, 53, 106]],    [59,  [1, 6, 295, -59]],
  [61,  [1, 7, -61, 122]],     [67,  [-221, 51, 2211, 134]],
  [71,  [1, -1, 71, -71]],     [73,  [3, -21, 146, -365]],
  [79,  [1, -1, 158, -158]],   [83,  [-22, -11, 83, 166]],
  [89,  [1, -7, 178, -267]],   [97,  [1, 7, 97, 485]],
  [101, [-1, 3, 101, -2626]],  [103, [1, -1, 103, 2266]],
  [107, [-7, -1, -1605, -107]],[109, [1, 6, 109, 654]],
  [113, [1, 3, 113, 339]],     [127, [-6, 3, 254, -127]],
  [131, [53, -11, 131, 8646]], [137, [7, 3, 274, -411]],
  [139, [51, 3, 139, -139]],   [149, [53, 94, -149, 13559]],
  [151, [1, -1, 755, 453]],    [157, [1, 5, 157, 2355]],
  [163, [1, -1, 978, 815]],    [167, [-13, -6, 334, -334]],
  [173, [51, 53, -173, 519]],  [179, [1, -19, 179, -537]],
  [181, [1, 7, -181, -1086]],  [191, [1, -1, 191, -191]],
  [193, [1, 5, -193, 965]],    [197, [-6, 3, 197, 394]],
  [199, [-6, 3, 199, -199]]
];
}
CLS = ["[1]", "[u]", "[p]", "[up]"];

entry(p, cls, d) =
{ my(E = Ed(d), M = Mval(E,p), good = (Mod(E.disc,p) != 0));
  my(g = ellrank(E), gens, used = List(), struct, T, Tstr);
  gens = concat(ellsaturation(E, g[4], 200), elltors(E)[3]);
  \\ one generator suffices iff its order in E(Q_p)/E_1 is M and its depth is 1
  for (i = 1, #gens,
    if (#used > 0, break);
    if (gensalone(E, gens[i], p, M), used = List([gens[i]])));
  if (#used == 0, used = List(gens));
  used = Vec(used);
  \\ structure of T
  if (good && M % p != 0,
    my(G = ellgroup(E,p));
    T = G,
    \\ else: additive class, or anomalous
    my(Mp = M / p^valuation(M,p), nr = #prootsQp(E, p, 60));
    T = if (Mp == 1, [],
          if (Mp == 4 && nr == 3, [2,2], [Mp])));
  Tstr = if (#T == 0, "Z_p",
          if (#T == 1, Str("Z_p x C", T[1]),
              Str("Z_p x C", T[1], " x C", T[2])));
  print("  p = ", p, "  class ", cls, "  d = ", d);
  print("      E_d : y^2 = x^3 + ", d^2, "x + ", d^3);
  print("      reduction at p : ",
        if (good, Str("good, a_p = ", ellap(E,p)),
            Str(elllocalred(E,p)[2], " (code), c_p = ", elllocalred(E,p)[4],
                ", a_p = ", ellap(E,p))),
        ",   M = ", M);
  print("      rank ", g[1], ", torsion ", elltors(E)[1],
        ",   E_d(Q_p) = ", Tstr);
  print("      generators used : ", used,
        if (#used < #gens, Str("   (of ", #gens, "; the rest are not needed)"), ""));
  \\ ONE canonical base for this (curve, prime), reused for every generator.
  \\ Good reduction: the lexicographic base in E_d(F_p).  Additive with
  \\ T = (Z/2)^2: the 2-torsion points, which map isomorphically onto Phi, taken
  \\ in the canonical order of prootsQp.  Additive with T cyclic: no base is
  \\ needed, since the order already determines the element (up to inversion
  \\ when |T| = 4).
  my(CB = if (good && M % p != 0, canonbase(E, p), 0));
  my(twotors = 0, sp = 0);
  if (#T == 2 && !good,
    my(rts = prootsQp(E, p, 60));
    twotors = rts; sp = singptp(E, p);
    print("      canonical base of T = Phi : the 2-torsion at x = ",
          [rootlabel(rts[1],p), rootlabel(rts[2],p)],
          "   (third root x = ", rootlabel(rts[3],p), ")"));
  if (type(CB) == "t_VEC",
    print("      canonical base of E_d(F_p) : ", CB[2]));
  foreach (used, P,
    my(r = ordv(E,P,p,M), coord);
    if (good && M % p != 0,
      my(Pp = if (Mod(cden(P),p) == 0, [0], [Mod(P[1],p), Mod(P[2],p)]));
      coord = dlog(CB[1], Pp, CB[2], CB[3]),
      if (type(twotors) == "t_VEC",
        coord = phiclass(E, P, p, twotors, sp, 40),
        coord = [r[1] / p^valuation(r[1], p)]));
    my(Tord = if (#T == 0, 1, if (#T == 1, T[1], T[1]*T[2])));
    print("        ", P, "  ->  ( ",
          if (r[2] == 1, "u", Str(p, "^", r[2]-1, " u")), " ; ",
          if (good && M % p != 0,
              Str("class ", coord),
              if (#T == 2, Str("class ", coord),
                  if (Tord == 1, "-",
                      Str("order ", coord[1], " in C", Tord,
                          if (coord[1] == Tord, " (a generator)", ""))))),
          " )",
          "     [ord in E/E_1 = ", r[1], ", formal depth ", r[2], "]"));
  print("");
}

print("=========================================================================");
print(" Extended density certificate for kummer-padic-density.typ, table 6.3");
print("=========================================================================");
print("");
print("E : v^2 = u^3 + u + 1 (496a, rank 1, trivial torsion).");
print("E_d : Y^2 = X^3 + d^2 X + d^3.   E_d(Q_p) = Z_p x T, T = E_d(Q_p)_tors.");
print("Z_p-coordinate recorded by valuation only (u = unit); a point generates");
print("the Z_p factor iff that coordinate is a unit, iff formal depth = 1.");
print("");

{
foreach (WIT, w,
  my(p = w[1], ds = w[2]);
  for (j = 1, 4, entry(p, CLS[j], ds[j])));
}
print("done.");
