# =====================================================================
# cert-extended.sage -- the extended density certificate of
# kummer-padic-density.typ section 3.4, rewritten in Sage.
#
# This is a port of cert-extended.gp.  The two are meant to be run
# against each other:
#
#     sage cert-extended.sage > results/cert-extended-sage.txt
#     diff results/cert-extended.txt results/cert-extended-sage.txt
#
# The output format is therefore PARI's, down to the "Mod(a, p)" spelling
# of a residue and the "[x, y]" spelling of a point, so that the diff is
# empty when the two agree and readable when they do not.  Nothing is
# printed here that the GP version does not print.
#
# WHAT IS ACTUALLY INDEPENDENT.  Sage sits on top of PARI, so a rewrite
# cannot be independent of it in the way that, say, a second descent
# would be.  What changes is which layer does the work:
#
#   ellrank + ellsaturation  ->  E.gens(algorithm='pari')
#   elltors                  ->  E.torsion_subgroup()
#   ellgroup                 ->  E.change_ring(GF(p)).abelian_group()
#   elllocalred              ->  E.kodaira_symbol(p), E.tamagawa_number(p)
#   factorpadic              ->  roots over Qp(p, prec)
#   ellsub with p-adic coords->  arithmetic on E over Qp(p, prec)
#
# and, more to the point, every convention that the GP file had to state
# by hand -- the canonical base, the ordering of the p-adic roots, the
# divisors-only search for the order in E/E_1 -- is restated here in a
# different language, so a transcription error in either version shows up
# as a diff rather than as agreement.
#
# WHAT THE DIFF SAYS (run of 2026-08-25: 7.2s here, 1.6s for the GP
# file, since ordv moved to Q_p).  All 180 blocks agree on
# every computed invariant: reduction type and code, c_p, a_p, M, rank,
# torsion, the isomorphism type of E^d(Q_p), the canonical base, and --
# as a multiset over the generators used -- the valuation of alpha, the
# order in E/E_1 and the formal depth.  The diff is not empty, and every
# line of it is the Mordell-Weil BASIS rather than a result:
#
#   * ORDER.  Sage sorts the points it returns and PARI does not, so on
#     the two-generator lines the pair is listed the other way round.
#   * SIGN.  Six images come back as -P where the GP file has P.  A class
#     is a discrete log, so it negates with the point; checked, and all
#     six satisfy class_gp + class_sage = 0 mod n_i in every coordinate.
#   * WHICH POINT.  One line, p = 17, [up], d = 51, exhibits a different
#     lone sufficient generator: [-714/25, 23409/125] here against
#     [-17, 289] there.  Both pass gensalone with (ord, depth) = (34, 1)
#     = (M, 1) -- checked in both directions -- and the certificate's
#     claim is that ONE generator suffices, not which one.  The two
#     appear together, and agree, on the p = 67 line where both are used.
#
# So the basis is a choice and the certificate does not depend on it,
# which is the same point the GP file makes about the canonical base and
# about the ordering of the p-adic roots, one level up.
#
# ---------------------------------------------------------------------
# For each prime p <= 200 and each square class of Q_p^*/(Q_p^*)^2, the
# witness twist d of the table in section 3.3 is extended with
#   (1) the isomorphism type of E^d(Q_p), as Z_p x C_a x C_b ;
#   (2) the generators of E^d(Q) actually used (redundant ones dropped) ;
#   (3) their images in Z_p x C_a x C_b .
#
# Conventions.  E_d : Y^2 = X^3 + d^2 X + d^3, the twist of E = 496a by d.
# For p >= 3 the formal group is E_1(Q_p) = Z_p with E_n <-> p^(n-1) Z_p,
# and M = #(E(Q_p)/E_1) = c_p * #Etilde^ns(F_p).  The torsion
# T = E(Q_p)_tors is torsion-free-complemented: E(Q_p) = Z_p x T.
#   * good reduction with p not dividing M : T = E(F_p), read off by the
#     abelian group of the reduction, and the T-coordinate of a point is
#     literally its reduction mod p.
#   * additive reduction (the classes [p] and [up], where v_p(d) is odd):
#     the model has v_p(c_4) = 2, v_p(Delta) = 6, so the type is I_0^*,
#     a_p = 0 and M = c_p * p.  The prime-to-p part of T is Phi(F_p), of
#     order c_p; the p-part is trivial whenever a single point
#     topologically generates, since Z_p x Z/p is not procyclic.  That is
#     exactly what the index computation (M/m) p^(v-1) = 1 certifies, so
#     the certificate determines the structure.  (The p-part is computed,
#     rather than asserted, by cert-ptors.gp.)
#
# The Z_p-coordinate of a point is only defined up to a unit (the choice
# of a topological generator of Z_p), so what is recorded is its
# VALUATION: alpha is written u for a unit (valuation 0) and p^k u
# otherwise.  A point generates the Z_p factor iff its coordinate is a
# unit, iff the formal depth v_p(c(mP)) = 1.
#
# The GP file also carries a routine `subgrp`, the order of the subgroup
# of E(F_p) generated by a set of reductions.  Nothing calls it; it is
# dead code there and is not carried over.
# =====================================================================

# ---------------------------------------------------------------------
# PARI-shaped printing.  Everything user-visible goes through these, so
# the diff against results/cert-extended.txt stays honest.
# ---------------------------------------------------------------------

def ptstr(P):
    """A rational point as PARI prints it: [x, y], or [0] at infinity."""
    if P.is_zero():
        return "[0]"
    return "[%s, %s]" % (P[0], P[1])

def ptliststr(L):
    return "[" + ", ".join(ptstr(P) for P in L) + "]"

def modstr(P, p):
    """A point of E(F_p) as PARI prints it: [Mod(x, p), Mod(y, p)]."""
    if P.is_zero():
        return "[0]"
    return "[Mod(%s, %s), Mod(%s, %s)]" % (ZZ(P[0]), p, ZZ(P[1]), p)

def modliststr(L, p):
    return "[" + ", ".join(modstr(P, p) for P in L) + "]"

def veci(v):
    """A vector of integers as PARI prints it: [a, b]."""
    return "[" + ", ".join(str(a) for a in v) + "]"

def vecs(v):
    """A vector of strings as PARI prints it: ["a", "b"]."""
    return "[" + ", ".join('"%s"' % a for a in v) + "]"


# ---------------------------------------------------------------------
# the curve, the size of E(Q_p)/E_1, and the formal depth
# ---------------------------------------------------------------------

def cden(P):
    """c, where P = (a/c^2, b/c^3).  0 at infinity."""
    if P.is_zero():
        return ZZ(0)
    return ZZ(P[0].denominator()).isqrt()

def Ed(d):
    return EllipticCurve(QQ, [d^2, d^3])

def Mval(E, p):
    a = E.ap(p)
    if E.discriminant() % p != 0:
        return ZZ(p + 1 - a)
    return ZZ(E.tamagawa_number(p) * (p - a))

PRECX = 80

_qpcurves = {}

def padiccurve(E, p, prec=PRECX):
    """E over Q_p, memoised on (a4, a6, p, prec).

    Every generator of a given block wants the same curve and building it
    is not free.  The GP file does not need this: there, p-adic
    coordinates can be handed straight to the rational ellinit, which is
    what phiclass does.  Sage wants the curve itself over Q_p.
    """
    key = (E.a4(), E.a6(), p, prec)
    EK = _qpcurves.get(key)
    if EK is None:
        K = Qp(p, prec)
        EK = EllipticCurve(K, [K(E.a4()), K(E.a6())])
        _qpcurves[key] = EK
    return EK

def ordv(E, P, p, M):
    """Order of Pbar in E(Q_p)/E_1, and the formal depth of that multiple.

    Two things keep this cheap.  The order of Pbar divides M, so only the
    DIVISORS of M need testing, each reached by one scalar multiplication
    (double-and-add) rather than by M repeated additions.  And the
    multiples are taken over Q_p and not over Q: multiplying by e
    multiplies the canonical height by e^2, so x(e P) has about
    e^2 h(P) / log 10 digits, which at p = 149, d = 13559 is 3 071 818 of
    them and 21.8 seconds for a single multiple.  Modulo p^PRECX the cost
    is flat in e and in h(P), and the same multiple takes 0.010s.  The
    price was paid on every divisor of M, and ordv is called once per
    candidate generator by gensalone and again for printing.

    E_1 membership is then v_p(x) < 0 rather than p | cden, and the depth
    is -v_p(x)/2 rather than v_p(cden): for a point of E_1 the numerator
    of x is prime to p, so the two agree.

    One thing does not survive the move: p-adically the point at infinity
    is not distinguishable from a very deep point of E_1, so the case
    e P = O -- which the rational version excluded with an explicit
    is_zero test -- is excluded here from the order of P in E(Q), taken
    once.  Every E^d(Q) on this sweep has trivial torsion so nothing is
    ever skipped, but the function should not depend on the witness table
    for its correctness.
    """
    EK = padiccurve(E, p)
    K = EK.base_ring()
    n = ZZ(P.order()) if P.has_finite_order() else ZZ(0)
    Pp = EK.point([K(P[0]), K(P[1]), K(1)], check=False)
    for e in divisors(M):
        if n and e % n == 0:
            continue
        Q = e * Pp
        if not Q.is_zero():
            w = Q[0].valuation()
            if w < 0:
                return (ZZ(e), ZZ(-w // 2))
    return (ZZ(0), ZZ(0))

def gensalone(E, P, p, M):
    """Does this single point topologically generate E(Q_p)?"""
    e, v = ordv(E, P, p, M)
    return e == M and v == 1


# ---------------------------------------------------------------------
# the additive lines: T = Phi(F_p), and it need not be cyclic
#
# For these d the reduction is additive, E_0/E_1 = G_a(F_p) of order p,
# and M = c_p * p, so |T| = c_p.  T is NOT automatically cyclic: for
# I_0^* with c_p = 4 the component group is (Z/2)^2, and only for I_1^*
# is it Z/4.  Which one it is can be decided without any Kodaira table:
# E_0(Q_p) is torsion-free for p > 2 (E_1 = Z_p is, and E_0/E_1 = Z/p is
# odd), so E[2](Q_p) injects into Phi -- hence T = (Z/2)^2 exactly when
# the cubic splits completely over Q_p.
# ---------------------------------------------------------------------

def prootsQp(E, p, prec):
    """Roots of x^3 + a4 x + a6 in Q_p, with multiplicity, canonically ordered.

    Canonical order: by the p-adic expansion read from the BOTTOM, i.e. by
    the leading digit u = (r/p^v) mod p.  Sorting by the integer lift
    instead orders by the HIGH-order digits and therefore depends on the
    working precision -- the same kind of irreproducibility as a randomly
    chosen base.  Here the three roots have valuation 1 with distinct
    leading digits (they are the roots of the good-reduction cubic modulo
    p, which are distinct for I_0^*), so the leading digit already
    separates them; the full lift is kept only as a tiebreak.
    """
    K = Qp(p, prec)
    R = PolynomialRing(K, 'X')
    X = R.gen()
    f = X^3 + K(E.a4()) * X + K(E.a6())
    L = []
    for (r, m) in f.roots():
        L += [r] * m
    def key(r):
        return (ZZ(r.unit_part()) % p, ZZ(r))
    return sorted(L, key=key)

def rootlabel(r, p):
    """A short label for a root: these all have valuation 1, so u p."""
    if r.valuation() == 1:
        return "%sp" % (ZZ(r / p) % p)
    return str(ZZ(r))

def singptp(E, p):
    """The singular point of the reduction mod p, or None.

    The GP version searches the whole of F_p x F_p.  It need not: p is odd
    throughout, so the partial in y, 2y + a1 x + a3 = 0, already determines
    y from x, and only the p values of x have to be tried.  The x are still
    taken in increasing order, so the point returned is the same one.
    """
    F = GF(p)
    a1, a2, a3, a4, a6 = [F(a) for a in E.a_invariants()]
    for x0 in range(p):
        X = F(x0)
        Y = -(a1*X + a3) / 2
        if (Y^2 + a1*X*Y + a3*Y - X^3 - a2*X^2 - a4*X - a6 == 0
                and a1*Y - 3*X^2 - 2*a2*X - a4 == 0):
            return (ZZ(x0), ZZ(Y))
    return None

def inE0pad(Q, sp):
    """Is a p-ADIC point in E_0(Q_p)?

    Negative valuation means it reduces to O, hence lies in E_1 and so in
    E_0; otherwise compare the reduction with the singular point.
    """
    if Q.is_zero():
        return True
    if Q[0].valuation() < 0:
        return True
    if sp is None:
        return True
    return not ((Q[0] - sp[0]).valuation() > 0 and (Q[1] - sp[1]).valuation() > 0)

def phiclass(E, P, p, rts, sp, prec):
    """The class of P in Phi = (Z/2)^2, against the first two 2-torsion points.

    The 2-torsion is NOT rational -- its x-coordinates lie in Z_p and not
    in Z -- so this has to be done with p-adic arithmetic; treating the
    roots as exact rational points is what made an earlier version of the
    GP file return no answer at all.
    """
    K = Qp(p, prec)
    EK = EllipticCurve(K, [K(E.a4()), K(E.a6())])
    Pp = EK.point([K(P[0]), K(P[1]), K(1)], check=False)
    if inE0pad(Pp, sp):
        return [0, 0]
    idx = [[1, 0], [0, 1], [1, 1]]
    for j in range(3):
        T2 = EK.point([K(ZZ(rts[j])), K(0), K(1)], check=False)
        if inE0pad(Pp - T2, sp):
            return idx[j]
    return [-1, -1]


# ---------------------------------------------------------------------
# A CANONICAL base for E(F_p), so that the class column is reproducible.
#
# A generator chosen by the library is chosen AT RANDOM on each call --
# five successive PARI calls at p = 23 for d = 1 return (18,20), (9,7),
# (9,7), (1,7), (19,5) -- so a class computed against it is neither
# reproducible nor checkable by a reader, and two generators of the same
# twist dlogged against separate calls are not even mutually consistent.
# Instead: order the affine points of E(F_p) lexicographically by (x,y)
# and take the FIRST point of maximal order; in the non-cyclic case take
# the first g_2 of order n_2 that is independent of g_1.  Deterministic,
# and statable in one line.
# ---------------------------------------------------------------------

def ellgroup(E, p):
    """The structure of E(F_p) in PARI's order: [n1] or [n1, n2] with n2 | n1.

    Sage lists the invariants the other way round (d1 | d2 | ...), so they
    are reversed here; the printed group is C_n1 x C_n2 as in the GP file.
    """
    inv = E.change_ring(GF(p)).abelian_group().invariants()
    return [ZZ(n) for n in reversed(inv)]

def canonbase(E, p):
    """(E(F_p), canonical generators, structure in PARI's order)."""
    Ep = E.change_ring(GF(p))
    G = ellgroup(E, p)
    F = GF(p)
    a4, a6 = F(E.a4()), F(E.a6())
    # The affine points, lexicographically by (x, y).  The GP version tries
    # every y for every x; here the two y over a given x are the square roots
    # of r, listed smaller lift first, which is the same order in p steps
    # instead of p^2.  At p = 199 that is the difference between a minute a
    # line and no time at all.
    pts = []
    for x0 in range(p):
        X = F(x0)
        r = X^3 + a4*X + a6
        if r == 0:
            pts.append(Ep.point([X, F(0), F(1)], check=False))
        elif r.is_square():
            y0 = ZZ(r.sqrt())
            for y in sorted([y0, p - y0]):
                pts.append(Ep.point([X, F(y), F(1)], check=False))
    n1 = G[0]
    g1 = None
    for P in pts:
        if g1 is None and P.order() == n1:
            g1 = P
    if len(G) == 1:
        return (Ep, [g1], G)
    n2 = G[1]
    # independent of g1 iff <g1> meets <g2> only in O
    span1 = set()
    Q = Ep(0)
    for e in range(n1):
        span1.add(Q)
        Q = Q + g1
    g2 = None
    for P in pts:
        if g2 is None and P.order() == n2:
            ok = True
            R = P
            for k in range(1, n2):
                if R.is_zero():
                    break
                if R in span1:
                    ok = False
                    break
                R = R + P
            if ok:
                g2 = P
    return (Ep, [g1, g2], G)

def dlog(Ep, P, gens, cyc):
    """Discrete log of Pbar in E(F_p), against the CANONICAL base above."""
    g1, n1 = gens[0], cyc[0]
    if P.is_zero():
        return [0] if len(cyc) == 1 else [0, 0]
    if len(cyc) == 1:
        for e in range(n1):
            if e * g1 == P:
                return [e]
        return [-1]
    g2, n2 = gens[1], cyc[1]
    for e in range(n1):
        eg = e * g1
        for f in range(n2):
            if eg + f * g2 == P:
                return [e, f]
    return [-1, -1]


# ---------------------------------------------------------------------
# the witness table of section 3.3
# ---------------------------------------------------------------------

WIT = [
  (3,   [7, -1, 3, 6]),        (5,   [1, 3, 5, -35]),
  (7,   [1, -1, 7, -7]),       (11,  [3, 6, 11, -11]),
  (13,  [-1, 5, -13, 26]),     (17,  [-1, 7, 34, 51]),
  (19,  [1, -1, 95, -95]),     (23,  [1, -1, 46, 115]),
  (29,  [-1, 11, -29, 58]),    (31,  [1, -1, 31, -62]),
  (37,  [-11, 6, -37, 74]),    (41,  [-1, 3, 41, 123]),
  (43,  [1, -1, -86, 86]),     (47,  [-11, -149, 94, 705]),
  (53,  [11, 22, 53, 106]),    (59,  [1, 6, 295, -59]),
  (61,  [1, 7, -61, 122]),     (67,  [-221, 51, 2211, 134]),
  (71,  [1, -1, 71, -71]),     (73,  [3, -21, 146, -365]),
  (79,  [1, -1, 158, -158]),   (83,  [-22, -11, 83, 166]),
  (89,  [1, -7, 178, -267]),   (97,  [1, 7, 97, 485]),
  (101, [-1, 3, 101, -2626]),  (103, [1, -1, 103, 2266]),
  (107, [-7, -1, -1605, -107]),(109, [1, 6, 109, 654]),
  (113, [1, 3, 113, 339]),     (127, [-6, 3, 254, -127]),
  (131, [53, -11, 131, 8646]), (137, [7, 3, 274, -411]),
  (139, [51, 3, 139, -139]),   (149, [53, 94, -149, 13559]),
  (151, [1, -1, 755, 453]),    (157, [1, 5, 157, 2355]),
  (163, [1, -1, 978, 815]),    (167, [-13, -6, 334, -334]),
  (173, [51, 53, -173, 519]),  (179, [1, -19, 179, -537]),
  (181, [1, 7, -181, -1086]),  (191, [1, -1, 191, -191]),
  (193, [1, 5, -193, 965]),    (197, [-6, 3, 197, 394]),
  (199, [-6, 3, 199, -199])
]

CLS = ["[1]", "[u]", "[p]", "[up]"]


def entry(p, cls, d):
    E = Ed(d)
    M = Mval(E, p)
    good = (E.discriminant() % p != 0)

    # E.gens(algorithm='pari') is ellrank followed by Sage's own saturation --
    # the same two steps as the GP file's ellrank + ellsaturation, and it raises
    # rather than guess if the rank is not determined.  Sage's DEFAULT algorithm
    # is mwrank, which is not a variant reading of the same computation but a
    # different and far slower one: over two minutes on d = 13559 against half a
    # second here, and no extra certainty, since the pari path returns only when
    # #gens meets the upper bound and so proves the rank outright.
    fgens = E.gens(algorithm='pari')
    gens = list(fgens) + [T.element() for T in E.torsion_subgroup().gens()]
    rank = E.rank()
    ntors = E.torsion_order()

    # one generator suffices iff its order in E(Q_p)/E_1 is M and its depth is 1
    used = []
    for P in gens:
        if used:
            break
        if gensalone(E, P, p, M):
            used = [P]
    if not used:
        used = list(gens)

    # structure of T
    if good and M % p != 0:
        T = ellgroup(E, p)
    else:
        # additive class, or anomalous
        Mp = M // p^(M.valuation(p))
        nr = len(prootsQp(E, p, 60))
        if Mp == 1:
            T = []
        elif Mp == 4 and nr == 3:
            T = [2, 2]
        else:
            T = [Mp]
    if len(T) == 0:
        Tstr = "Z_p"
    elif len(T) == 1:
        Tstr = "Z_p x C%s" % T[0]
    else:
        Tstr = "Z_p x C%s x C%s" % (T[0], T[1])

    print("  p = %s  class %s  d = %s" % (p, cls, d))
    print("      E_d : y^2 = x^3 + %sx + %s" % (d^2, d^3))
    if good:
        red = "good, a_p = %s" % E.ap(p)
    else:
        red = "%s (code), c_p = %s, a_p = %s" % (
            E.kodaira_symbol(p)._pari_code(), E.tamagawa_number(p), E.ap(p))
    print("      reduction at p : %s,   M = %s" % (red, M))
    print("      rank %s, torsion %s,   E_d(Q_p) = %s" % (rank, ntors, Tstr))
    print("      generators used : %s%s" % (
        ptliststr(used),
        "   (of %s; the rest are not needed)" % len(gens) if len(used) < len(gens) else ""))

    # ONE canonical base for this (curve, prime), reused for every generator.
    # Good reduction: the lexicographic base in E_d(F_p).  Additive with
    # T = (Z/2)^2: the 2-torsion points, which map isomorphically onto Phi,
    # taken in the canonical order of prootsQp.  Additive with T cyclic: no
    # base is needed, since the order already determines the element (up to
    # inversion when |T| = 4).
    CB = canonbase(E, p) if (good and M % p != 0) else None
    twotors, sp = None, None
    if len(T) == 2 and not good:
        rts = prootsQp(E, p, 60)
        twotors, sp = rts, singptp(E, p)
        print("      canonical base of T = Phi : the 2-torsion at x = %s"
              "   (third root x = %s)" % (
                  vecs([rootlabel(rts[0], p), rootlabel(rts[1], p)]),
                  rootlabel(rts[2], p)))
    if CB is not None:
        print("      canonical base of E_d(F_p) : %s" % modliststr(CB[1], p))

    for P in used:
        e, v = ordv(E, P, p, M)
        if good and M % p != 0:
            Ep = CB[0]
            Pp = Ep(0) if cden(P) % p == 0 else Ep.point(
                [GF(p)(P[0]), GF(p)(P[1]), GF(p)(1)], check=False)
            coord = dlog(Ep, Pp, CB[1], CB[2])
        elif twotors is not None:
            coord = phiclass(E, P, p, twotors, sp, 40)
        else:
            coord = [e // p^(e.valuation(p))]
        Tord = 1 if len(T) == 0 else (T[0] if len(T) == 1 else T[0] * T[1])
        alpha = "u" if v == 1 else "%s^%s u" % (p, v - 1)
        if (good and M % p != 0) or len(T) == 2:
            tpart = "class %s" % veci(coord)
        elif Tord == 1:
            tpart = "-"
        else:
            tpart = "order %s in C%s%s" % (
                coord[0], Tord, " (a generator)" if coord[0] == Tord else "")
        print("        %s  ->  ( %s ; %s )     [ord in E/E_1 = %s, formal depth %s]"
              % (ptstr(P), alpha, tpart, e, v))
    print("", flush=True)


print("=========================================================================")
print(" Extended density certificate for kummer-padic-density.typ, table 6.3")
print("=========================================================================")
print("")
print("E : v^2 = u^3 + u + 1 (496a, rank 1, trivial torsion).")
print("E_d : Y^2 = X^3 + d^2 X + d^3.   E_d(Q_p) = Z_p x T, T = E_d(Q_p)_tors.")
print("Z_p-coordinate recorded by valuation only (u = unit); a point generates")
print("the Z_p factor iff that coordinate is a unit, iff formal depth = 1.")
print("")

for (p, ds) in WIT:
    for j in range(4):
        entry(p, CLS[j], ds[j])

print("done.")
