\\ cert-lprimary.gp -- the l-primary rewrite of the single-place sweep of
\\ sections 3.3 and 3.4.  cert-extended.gp is left exactly as it was; this runs
\\ beside it and must reproduce its verdicts.  Run from this directory:
\\     gp -q -s 8000000000 cert-lprimary.gp < /dev/null > results/cert-lprimary.txt
\\
\\ WHY REWRITE A SWEEP THAT ALREADY WORKS.  Section 3.4 reports, per generator,
\\ the pair (m, v) -- the order of Pbar in E(Q_p)/E_1 and the formal depth of
\\ mP -- and forms the closure index (M/m) p^(v-1).  That single number mixes
\\ every prime together: an index of 6 does not say whether the obstruction is
\\ at 2, at 3, or one of each, and on the lines needing two generators there is
\\ no single m to report at all, so the index has to come from a lattice
\\ determinant.  The l-primary picture of section 2.3.4 takes the group apart
\\ instead.
\\
\\ THE POINT, AND IT IS SHARPER HERE THAN FOR THE LEDGER.  Write
\\     G = E^d(Q_p) = G_p (+) (+)_{l != p} G_l,   G_p = Z_p x T[p^oo],
\\     G_l = T[l^oo].
\\ A closed subgroup decomposes the same way, R = (+)_l R_l, so
\\     [G : R] = prod_l [G_l : R_l].
\\ For the LEDGER, coverage did NOT decompose into independent per-layer
\\ conditions: a pair must lie in ONE AND THE SAME entry, so the choice has to
\\ be constant across layers.  Density of a SINGLE reach has no such coupling:
\\     E^d(Q) is dense in E^d(Q_p)   <=>   R_l = G_l  for every l,
\\ genuinely independent conditions, one per layer.  That is why the single-place
\\ sweep is the right place to do the rewrite first.
\\
\\ THE TWO KINDS OF LAYER.
\\  * DIAGONAL, l = p.  cert-ptors.gp shows T[p^oo] = 0 on every line here, so
\\    G_p = Z_p and R_p = p^k Z_p: the layer index is p^k, ONE INTEGER, exact,
\\    with no truncation.  And k is not a search -- the depth formula of section
\\    3.4.2 gives depth(M P) = v_p(alpha) + 1 for every P, so
\\        k = min over generators of depth(M P_i), minus 1,
\\    valid at additive places too, where v_p(M) > 0 makes the (m, v) bookkeeping
\\    of section 3.4 fiddly.
\\  * OFF-DIAGONAL, l != p.  G_l = T[l^oo] is finite of order l^v_l(M), and
\\    since E_1 is pro-p it injects into the finite group G/E_1 of order M.  So
\\    the whole computation happens there: multiply each generator's image by
\\    M / l^v_l(M) to land in the l-part, close under addition, compare orders.
\\
\\ NO DISCRETE LOGARITHMS ANYWHERE, which is the incidental prize.  Sections 2.5
\\ and 3.4 both record the same trap -- ellgroup(E,p,1) returns a generator
\\ chosen at random on each call, so any class column computed against it is
\\ irreproducible, and two generators dlogged against separate calls are not even
\\ mutually consistent.  A layer index is an order, not a coordinate: it needs
\\ no base at all.  Cosets are compared by inE1 on the difference, so no coset
\\ table is built either (arenainit's is O(M^3) and hopeless at p = 199).

read("ledger.gp");
PRECL2 = 80;

Edmin(d) = { my(v, Em = ellminimalmodel(ellinit([d^2, d^3]), &v)); [Em, v]; }

\\ ---- diagonal layer l = p:  R_p = p^k Z_p, index p^k.
\\ depth(M P) = v_p(alpha) + 1, so k = min_i depth(M P_i) - 1.  Returns -1 for
\\ a generator that is locally torsion at p (alpha = 0, no finite granularity).
kdiag(Em, pts, p) =
{ my(M = Mval(Em, p), Ep = padiccurve(Em, p), best = -1);
  for (i = 1, #pts,
    my(P = [pts[i][1] + O(p^PRECL2), pts[i][2] + O(p^PRECL2)], R = ellmul(Ep, P, M));
    if (R == [0], next);
    if (valuation(R[1], p) >= 0, next);
    my(k = -valuation(R[1], p)/2 - 1);
    if (k > PRECL2 \ 4, next);        \\ M P is numerically O, so alpha = 0
    if (best < 0 || k < best, best = k));
  best;
}
\\ ---- off-diagonal layer l != p: the subgroup of G/E_1 generated by the
\\ l-parts of the images.  Equality of cosets is inE1 on the difference, so no
\\ list of coset representatives is needed.
sameclass(Ep, p, Q1, Q2) =
{ if (Q1 == [0] && Q2 == [0], return(1));
  inE1(if (Q1 == [0], Q2, if (Q2 == [0], Q1, ellsub(Ep, Q1, Q2))), p);
}
\\ Order of the subgroup of (G/E_1)_l generated by the l-parts of the images.
\\ Built incrementally, the standard way: for each new generator Q find the
\\ least j >= 1 with jQ already in the subgroup, then the subgroup grows by the
\\ factor j, its elements being r + iQ for r in it and 0 <= i < j.  (Closing
\\ naively by repeated pairwise addition needs as many passes as the order --
\\ a fixed guard of 40 silently under-counts a cyclic layer of order 139, which
\\ is exactly what p = 163 has.)
lsubgrp(Em, pts, p, l) =
{ my(M = Mval(Em, p), e = valuation(M, l), ord = l^e, c = M / ord,
     Ep = padiccurve(Em, p), reps = List([[0]]), Q, R, j, S, new);
  for (i = 1, #pts,
    Q = ellmul(Ep, [pts[i][1] + O(p^PRECL2), pts[i][2] + O(p^PRECL2)], c);
    if (inE1(Q, p), next);            \\ trivial in this layer
    \\ least j >= 1 with jQ in the subgroup built so far
    j = 0; R = [0];
    for (t = 1, ord,
      R = if (R == [0], Q, elladd(Ep, R, Q));
      my(hit = 0);
      for (s = 1, #reps, if (sameclass(Ep, p, R, reps[s]), hit = 1; break));
      if (hit, j = t; break));
    if (j == 0, j = ord);
    new = List(); S = [0];
    for (i2 = 1, j-1,
      S = if (S == [0], Q, elladd(Ep, S, Q));
      for (s = 1, #reps,
        listput(new, if (reps[s] == [0], S, elladd(Ep, reps[s], S)))));
    reps = List(concat(Vec(reps), Vec(new))));
  #reps;
}

\\ ---- the witness table of section 3.3, verbatim from cert-extended.gp
{
WIT = [
  [3,   [7, -1, 3, 6]],        [5,   [1, 3, 5, -35]],
  [7,   [1, -1, 7, -7]],       [11,  [3, 6, 11, -11]],
  [13,  [-1, 5, -13, 26]],     [17,  [-1, 7, 34, 51]],
  [19,  [1, -1, 95, -95]],     [23,  [1, -1, 46, 115]],
  [29,  [-1, 11, -29, 58]],    [31,  [1, -1, 31, -62]],
  [37,  [-11, 6, -37, 74]],    [41,  [-1, 3, 41, 123]],
  [43,  [1, -1, -86, 86]],     [47,  [-11, -149, 94, 705]],
  [53,  [11, 22, 53, 106]],    [59,  [1, 6, 295, -59]],
  [61,  [1, 7, -61, 122]],     [67,  [-221, 51, 2211, 134]],
  [71,  [1, -1, 71, -71]],     [73,  [3, -21, 146, -365]],
  [79,  [1, -1, 158, -158]],   [83,  [-22, -11, 83, 166]],
  [89,  [1, -7, 178, -267]],   [97,  [1, 7, 97, 485]],
  [101, [-1, 3, 101, -2626]],  [103, [1, -1, 103, 2266]],
  [107, [-7, -1, -1605, -107]],[109, [1, 6, 109, 654]],
  [113, [1, 3, 113, 339]],     [127, [-6, 3, 254, -127]],
  [131, [53, -11, 131, 8646]], [137, [7, 3, 274, -411]],
  [139, [51, 3, 139, -139]],   [149, [53, 94, -149, 13559]],
  [151, [1, -1, 755, 453]],    [157, [1, 5, 157, 2355]],
  [163, [1, -1, 978, 815]],    [167, [-13, -6, 334, -334]],
  [173, [51, 53, -173, 519]],  [179, [1, -19, 179, -537]],
  [181, [1, 7, -181, -1086]],  [191, [1, -1, 191, -191]],
  [193, [1, 5, -193, 965]],    [197, [-6, 3, 197, 394]],
  [199, [-6, 3, 199, -199]]
];
}
CLS = ["[1]", "[u]", "[p]", "[up]"];

\\ Minimal number of generators of the layer G_l, i.e. dim G_l/l.  This is the
\\ whole point of the decomposition: the rank dichotomy of section 2.3 is a
\\ statement about ONE layer, and the certificate can now name which prime it is.
\\ Good reduction: ellgroup's STRUCTURE is deterministic (it is only the
\\ generator returned by ellgroup(E,p,1) that is random), so it settles this.
\\ Additive: T is the prime-to-p part of Phi, of order c_p, and section 3.4
\\ establishes T = (Z/2)^2 exactly when the cubic splits completely over Q_p.
nroots(d, p) =
{ my(f = x^3 + d^2*x + d^3, fp = factorpadic(f, p, 40), n = 0);
  for (j = 1, #fp~, if (poldegree(fp[j,1]) == 1, n += fp[j,2]));
  n;
}
layerrank(E, d, p, l) =
{ if (Mod(E.disc, p) != 0 && Mval(ellminimalmodel(E), p) % p != 0,
    my(G = ellgroup(E, p), r = 0);
    for (i = 1, #G, if (G[i] % l == 0, r++));
    return(r));
  \\ additive (or anomalous, where the prime-to-p part is trivial anyway)
  my(cp = Mval(ellminimalmodel(E), p), w);
  cp = cp / p^valuation(cp, p);
  if (cp % l != 0, return(0));
  if (l == 2 && cp % 4 == 0 && nroots(d, p) == 3, 2, 1);
}

\\ One block per (p, class, d); inside it one line per layer, i.e. one line per
\\ (p, d, l).  Density at p is: every layer index is 1.
\\ Total index for a given set of points, layer by layer.  Used twice: once for
\\ the whole generating set, and once per single generator, since "how many
\\ generators are NEEDED" is not "how many the twist has" -- section 3.4 drops
\\ the redundant ones, and a rank-2 twist very often has a lone generator that
\\ already does the job.
totidx(E, Em, d, p, pts) =
{ my(M = Mval(Em, p), k = kdiag(Em, pts, p), t);
  if (k < 0, return(-1));
  t = p^k;
  foreach (factor(M)[,1]~, l,
    if (l == p, next);
    t *= l^valuation(M, l) / lsubgrp(Em, pts, p, l));
  t;
}

entry(p, cls, d) =
{ my(E = ellinit([d^2, d^3]), EE = Edmin(d), Em = EE[1], v = EE[2], M = Mval(Em, p));
  my(g = ellrank(E), gens, pts, tot = 1);
  NONCYC = 0;
  gens = concat(ellsaturation(E, g[4], 200), elltors(E)[3]);
  pts = apply(P -> ellchangepointinv(P, v), gens);
  print("  p = ", p, "  class ", cls, "  d = ", d, "   M = ", M,
        "   rank ", g[1], "   generators ", #pts);
  my(k = kdiag(Em, pts, p));
  if (k < 0,
    print("      l = ", p, "  (diagonal)  G_l = Z_", p,
          "        R_l = 0             index INFINITE   <<<< no granularity");
    tot = -1,
    print("      l = ", p, "  (diagonal)  G_l = Z_", p,
          "        R_l = ", p, "^", k, " Z_", p, "     index ", p^k,
          if (k == 0, "   FULL", "")));
  foreach (factor(M)[,1]~, l,
    if (l == p, next);
    my(e = valuation(M, l), ord = l^e, r = lsubgrp(Em, pts, p, l), idx = ord / r);
    my(rk = layerrank(E, d, p, l));
    print("      l = ", l, "              G_l order ", ord, " (rank ", rk, ")",
          "   R_l order ", r, "   index ", idx, if (idx == 1, "   FULL", ""),
          if (rk >= 2, "   <-- NON-CYCLIC LAYER: forces rank >= 2", ""));
    if (rk >= 2, NONCYC = 1);
    if (tot > 0, tot *= idx));
  if (tot > 0,
    print("      total index = product over layers = ", tot,
          if (tot == 1, "   DENSE", "   *** NOT DENSE ***")));
  \\ how many generators are NEEDED: one suffices iff some single one is dense
  my(need = #pts);
  for (i = 1, #pts, if (totidx(E, Em, d, p, [pts[i]]) == 1, need = 1; break));
  print("      generators needed : ", need,
        if (need > 1, "   (no single one is dense)", ""));
  [tot, NONCYC, need];
}

print("=========================================================================");
print(" l-primary certificate for the single-place sweep, sections 3.3 and 3.4");
print("=========================================================================");
print("");
print("E : v^2 = u^3 + u + 1 (496a).   E_d : Y^2 = X^3 + d^2 X + d^3, minimal");
print("model at p.   E^d(Q_p) = G_p (+) (+)_{l != p} G_l, with G_p = Z_p (the");
print("p-torsion vanishes on every line, cert-ptors.gp) and G_l = T[l^oo] of");
print("order l^v_l(M).   A closed subgroup decomposes the same way, so");
print("     [G : R] = prod_l [G_l : R_l],");
print("and density at p is R_l = G_l for EVERY layer -- independent conditions,");
print("one per layer.  (For the LEDGER of section 2.3 coverage does NOT split");
print("like this: a pair must lie in one and the same entry, so the choice is");
print("coupled across layers.  A single reach has no such coupling.)");
print("");
print("One line per (p, d, l).  No discrete logarithms anywhere: a layer index");
print("is an order, not a coordinate, so it needs no base -- which is also why");
print("the ellgroup randomness trap of sections 2.5 and 3.4 cannot arise here.");
print("");
{
my(nl = 0, nd = 0, bad = List(), rows = 0, nc = 0, ng2 = 0, nclist = List(), pcyc = List());
foreach (WIT, w,
  my(p = w[1], ds = w[2]);
  for (j = 1, 4,
    my(t = entry(p, CLS[j], ds[j]));
    nl++;
    rows += 1 + #select(l -> l != p, factor(Mval(Edmin(ds[j])[1], p))[,1]~);
    if (t[1] == 1, nd++, listput(bad, [p, CLS[j], ds[j], t[1]]));
    if (t[2], nc++; listput(nclist, [p, CLS[j], ds[j], t[3]]));
    if (t[3] > 1, ng2++; if (!t[2], listput(pcyc, [p, CLS[j], ds[j]])));
    print("")));
print("-------------------------------------------------------------------------");
print("  blocks (p, class, d)      : ", nl);
print("  layer lines (p, d, l)     : ", rows);
print("  total index 1             : ", nd);
print("  disagreements with 3.3    : ", nl - nd);
foreach (Vec(bad), b, print("    *** p = ", b[1], " ", b[2], " d = ", b[3], " index ", b[4]));
print("");
print("  lines NEEDING two generators  : ", ng2, "   (section 3.4 reports 22)");
print("  of which G is NOT procyclic   : ", nc, "   -- rank >= 2 genuinely FORCED");
print("  of which G IS procyclic       : ", ng2 - nc, "   -- an artefact of the BASIS");
print("");
print("  Those are different statements and the flat index cannot separate them.");
print("  A non-cyclic layer means no single point of E^d(Q_p) generates, so no");
print("  rank-1 twist could ever have worked.  A procyclic G with two generators");
print("  needed means only that neither point ellsaturation returned is dense --");
print("  some other point of the SAME group is.  Section 3.4 reported 22 in one");
print("  bucket and called them all non-procyclic; ", ng2 - nc, " of them is not.");
print("");
print("  lines where rank >= 2 is forced (non-cyclic layer, now NAMED):");
foreach (Vec(nclist), b,
  print("    p = ", b[1], "  ", b[2], "  d = ", b[3], "   generators needed ", b[4]));
print("");
print("  lines where G is procyclic but the basis is unlucky:");
foreach (Vec(pcyc), b, print("    p = ", b[1], "  ", b[2], "  d = ", b[3]));
print("-------------------------------------------------------------------------");
}
print("");
print("-------------------------------------------------------------------------");
print(" The one procyclic exception, worked out: p = 83, class [u], d = -11");
print("-------------------------------------------------------------------------");
{
my(p = 83, d = -11, E = ellinit([d^2,d^3]), EE = Edmin(d), Em = EE[1], v = EE[2]);
my(g = ellrank(E), gens = concat(ellsaturation(E, g[4], 200), elltors(E)[3]));
my(pts = apply(P -> ellchangepointinv(P, v), gens), found = 0);
print("  Etilde(F_83) = ", ellgroup(E,p), " -- CYCLIC, so E^d(Q_83) = Z_83 x C_78 is procyclic");
print("  layer ranks : ", [[l, layerrank(E,d,p,l)] | l <- factor(Mval(Em,p))[,1]~],
      "   (all 1: no layer forces two generators)");
print("  P_1 alone : total index ", totidx(E,Em,d,p,[pts[1]]), "    -- fails at the layer l = 3");
print("  P_2 alone : total index ", totidx(E,Em,d,p,[pts[2]]), "   -- fails at the layer l = 13");
print("  together  : total index ", totidx(E,Em,d,p,pts));
print("  They fail at DIFFERENT layers, which is exactly what the decomposition");
print("  shows and the flat index hides.  So a combination should fix it:");
for (a = -3, 3, for (b = -3, 3,
  if (a == 0 && b == 0 || found >= 4, next);
  my(Q = elladd(Em, ellmul(Em,pts[1],a), ellmul(Em,pts[2],b)));
  if (Q == [0], next);
  if (totidx(E,Em,d,p,[Q]) == 1, found++;
    print("    ", a, " P_1 + ", b, " P_2   is a SINGLE point of index 1"))));
print("  So one generator does suffice here; section 3.4's basis simply missed it.");
}
print("");
print("done.");
