\\ cert-lprimary.gp -- the l-primary certificate for the single-place sweep of
\\ sections 3.3 and 3.4.  cert-extended.gp is left exactly as it was; this runs
\\ beside it and must reproduce its verdicts.  Run from this directory:
\\     gp -q -s 8000000000 cert-lprimary.gp < /dev/null > results/cert-lprimary.txt
\\
\\ WHAT THE l-PRIMARY APPROACH IS, WHICH THE FIRST VERSION OF THIS FILE LEFT
\\ IMPLICIT.  G := E^d(Q_p) is profinite abelian and topologically finitely
\\ generated, so a CLOSED subgroup R equals G as soon as R.Phi(G) = G, where
\\ Phi(G) is the Frattini subgroup -- the intersection of the maximal open
\\ subgroups.  In the abelian case a maximal open subgroup has prime index, so
\\ Phi(G) is the closure of the subgroup generated by all l-th powers, and
\\        G / Phi(G)  =  prod_l  G/lG .
\\ Only finitely many factors are nonzero: G = Z_p x T, so G/lG = Z_p/l x T/lT,
\\ and l is invertible in Z_p unless l = p.  Hence the relevant l are p itself
\\ together with the primes dividing #T -- "the primes dividing the order of G"
\\ read as a supernatural number, p^oo times #T.  The factors have coprime
\\ orders, so surjecting onto the product is surjecting onto each factor.  Thus
\\
\\        E^d(Q) is dense in E^d(Q_p)
\\            <=>  E^d(Q) --> E^d(Q_p)/l  is onto for every such l,
\\
\\ and each l is checked separately.  That is the whole algorithm, and it is why
\\ the conditions are INDEPENDENT here.  (For the LEDGER of section 2.3 they are
\\ not: coverage asks that a pair lie in ONE AND THE SAME entry, so the choice
\\ is coupled across layers and the test becomes a mask intersection.  Density
\\ of a single reach has no such coupling.)
\\
\\ WHAT THE CERTIFICATE THEREFORE HAS TO SHOW.  Each G/lG is an F_l-vector space
\\ of dimension at most 2, so per triple (p, d, l) the checkable content is:
\\   (1) a BASIS of E^d(Q_p)/l, in a form suited to the reduction type;
\\   (2) the IMAGES in that basis of explicit generators of E^d(Q), listed once
\\       per pair (p, d) so that the l-lines can refer back to them;
\\   (3) the rank of the resulting matrix over F_l -- onto iff it is the
\\       dimension.
\\ The first version of this file reported only |R_l| against |G_l|, which is
\\ the same verdict with the reasoning deleted.
\\
\\ THE BASES, BY REDUCTION TYPE.
\\  * l = p.  T has no p-torsion (cert-ptors.gp), so T/pT = 0 and
\\    G/pG = Z_p/pZ_p is ONE-dimensional.  There is no canonical basis -- the
\\    identification with F_p is only defined up to F_p^*, since a topological
\\    generator of Z_p has to be chosen -- so the only invariant content of an
\\    image is whether it VANISHES.  It does not exactly when the Z_p-coordinate
\\    is a unit, i.e. when v_p(alpha) = 0, i.e. depth(M P) = 1.
\\  * l != p, good reduction.  T = Etilde(F_p), and with the canonical base
\\    (g_1, g_2) of section 3.4.1 (lexicographically first point of maximal
\\    order, then the first independent one of the right order),
\\    T = C_n1 (+) C_n2 gives T/lT with basis the images of those g_i with
\\    l | n_i.  Coordinates are discrete logarithms, so the base must be
\\    canonical or the column is meaningless -- ellgroup(E,p,1) returns a
\\    RANDOM generator on each call (sections 2.5, 3.4).  ellgroup's STRUCTURE
\\    is deterministic and is used freely.
\\  * l != p, additive reduction.  T is the prime-to-p part of Phi(F_p), of
\\    order c_p.  When Phi = (Z/2)^2 the basis is the 2-TORSION POINTS, which
\\    map isomorphically onto Phi; they are named by their x-coordinate, which
\\    has v_p = 1 and so is written u p (section 3.4.3).  When Phi is cyclic of
\\    order m, T/2T is one-dimensional and the image of P is its class in C_m
\\    reduced mod 2 -- nonzero exactly when that class has order m.

\\ WHERE THE TIME GOES.  Both valalpha and ordE1 want multiples of a
\\ RATIONAL point, and both used to take them on the rational curve, which
\\ is the obvious thing and the wrong one: e P has canonical height
\\ e^2 h(P), and this sweep pairs M up to 596 with generators of height 20,
\\ so x(e P) reaches millions of digits.  At p = 199 a single exact
\\ multiple is 1 197 893 digits and 5.4 seconds; ordE1 wanted one per
\\ divisor of M.  Both now work on padiccurve modulo p^PRECL2, where the
\\ cost of an ellmul is flat in e and in h(P).  The output is unchanged to
\\ the byte and the run went from 18.3 seconds to 1.7.

read("ledger.gp");
PRECL2 = 80;

cden(Q) = if (Q == [0], 0, sqrtint(denominator(Q[1])));
Ed(d)   = ellinit([d^2, d^3]);
\\ E_d is minimal at p on every line here: v_p(c_4) = v_p(48) + 2 v_p(d) <= 3 < 4.
MvalE(E, p) =
{ my(a = ellap(E,p));
  if (Mod(E.disc,p) != 0, p + 1 - a, elllocalred(E,p)[4] * (p - a));
}

\\ ---- verbatim from cert-extended.gp, so the two certificates use literally the
\\ same canonical base and the same p-adic component map.  Copied rather than
\\ read() in, because reading that file would re-run its whole 180-line sweep.
prootsQp(E, p, prec) =
{ my(f = x^3 + E.a4*x + E.a6, fp = factorpadic(f, p, prec), L = List());
  for (j = 1, #fp~,
    if (poldegree(fp[j,1]) == 1,
      for (k = 1, fp[j,2],
        listput(L, -polcoeff(fp[j,1],0) / polcoeff(fp[j,1],1)))));
  \\ Canonical order: by the p-adic expansion read from the BOTTOM, i.e. by the
  \\ leading digit u = (r/p^v) mod p.  Sorting by lift(r) instead orders by the
  \\ HIGH-order digits and therefore depends on the working precision -- the same
  \\ kind of irreproducibility as a randomly chosen base.  Here the three roots
  \\ have valuation 1 with distinct leading digits (they are the roots of the
  \\ good-reduction cubic modulo p, which are distinct for I_0^*), so the leading
  \\ digit already separates them; the full lift is kept only as a tiebreak.
  my(V = Vec(L));
  vecsort(V, r -> [lift(r / p^valuation(r,p)) % p, lift(r)]);
}
rootlabel(r, p) =
{ my(v = valuation(r, p));
  if (v == 1, Str(lift(r / p) % p, "p"), Str(lift(r)));
}
singptp(E, p) =
{ my(a1 = E.a1, a2 = E.a2, a3 = E.a3, a4 = E.a4, a6 = E.a6);
  for (x = 0, p-1, for (y = 0, p-1,
    if (Mod(y^2 + a1*x*y + a3*y - x^3 - a2*x^2 - a4*x - a6, p) == 0 &&
        Mod(a1*y - 3*x^2 - 2*a2*x - a4, p) == 0 &&
        Mod(2*y + a1*x + a3, p) == 0, return([x,y]))));
  [];
}
inE0pad(Q, p, sp) =
{ if (Q == [0], return(1));
  if (valuation(Q[1], p) < 0, return(1));
  if (#sp == 0, return(1));
  !(valuation(Q[1] - sp[1], p) > 0 && valuation(Q[2] - sp[2], p) > 0);
}
phiclass(E, P, p, rts, sp, prec) =
{ my(Pp = [P[1] + O(p^prec), P[2] + O(p^prec)]);
  if (inE0pad(Pp, p, sp), return([0,0]));
  my(idx = [[1,0],[0,1],[1,1]]);
  for (j = 1, 3,
    my(T2 = [rts[j], O(p^prec)]);
    if (inE0pad(ellsub(E, Pp, T2), p, sp), return(idx[j])));
  [-1,-1];
}
canonbase(E, p) =
{ my(Ep = ellinit(E, p), G = ellgroup(E, p), pts = List(), n1, n2, g1 = 0, g2 = 0);
  for (x = 0, p-1,
    my(r = x^3 + E.a4*x + E.a6);
    for (y = 0, p-1, if (Mod(y^2 - r, p) == 0, listput(pts, [Mod(x,p), Mod(y,p)]))));
  pts = Vec(pts);
  n1 = G[1];
  foreach (pts, P, if (g1 == 0 && ellorder(Ep, P) == n1, g1 = P));
  if (#G == 1, return([Ep, [g1], G]));
  n2 = G[2];
  foreach (pts, P,
    if (g2 == 0 && ellorder(Ep, P) == n2,
      \\ independent of g1 iff <g1,P> has order n1*n2
      my(ok = 1, k);
      for (k = 1, n2-1, if (ellmul(Ep, P, k) == [0], break);
        my(inside = 0, e);
        for (e = 0, n1-1, if (ellmul(Ep, g1, e) == ellmul(Ep, P, k), inside = 1; break));
        if (inside, ok = 0; break));
      if (ok, g2 = P)));
  [Ep, [g1, g2], G];
}
dlog(Ep, P, gens, cyc) =
{ my(g1 = gens[1], n1 = cyc[1]);
  if (P == [0], return(if (#cyc == 1, [0], [0,0])));
  if (#cyc == 1,
    for (e = 0, n1-1, if (ellmul(Ep,g1,e) == P, return([e]))); return([-1]));
  my(g2 = gens[2], n2 = cyc[2]);
  for (e = 0, n1-1, for (f = 0, n2-1,
    if (elladd(Ep, ellmul(Ep,g1,e), ellmul(Ep,g2,f)) == P, return([e,f]))));
  [-1,-1];
}

\\ PARI's Kodaira code as the usual symbol.  Calibrated against this table:
\\ 1 = I_0 (good, v_p(Delta) = 0); 4+n = I_n (multiplicative); -1 = I_0^*;
\\ -4-n = I_n^*; 2,3,4 = II,III,IV and -2,-3,-4 = II^*,III^*,IV^*.
kodsym(k) =
{ if (k == 1, return("I_0"));
  if (k == 2, return("II"));  if (k == 3, return("III")); if (k == 4, return("IV"));
  if (k > 4, return(Str("I_", k-4)));
  if (k == -1, return("I_0*"));
  if (k == -2, return("II*")); if (k == -3, return("III*")); if (k == -4, return("IV*"));
  Str("I_", -k-4, "*");
}

\\ ---- the diagonal layer l = p.  v_p(alpha_P), from depth(M P) = v_p(alpha)+1.
\\ Returns -1 when M P is numerically O, i.e. alpha = 0 (P locally torsion at p).
valalpha(E, P, p, M) =
{ my(Ep = padiccurve(E, p),
     Q = ellmul(Ep, [P[1] + O(p^PRECL2), P[2] + O(p^PRECL2)], M));
  if (Q == [0] || valuation(Q[1], p) >= 0, return(-1));
  my(k = -valuation(Q[1], p)/2 - 1);
  if (k > PRECL2 \ 4, -1, k);
}
\\ order of Pbar in E(Q_p)/E_1: the least divisor e of M with eP in E_1.
\\ Two things keep this cheap, and the second was missing until now.
\\   * Only the DIVISORS of M are tested, each reached by one ellmul rather
\\     than by e repeated additions.
\\   * The multiples are taken over Q_p and not over Q.  This is the same
\\     point valalpha makes just above: e P has canonical height e^2 h(P),
\\     so the exact x(e P) runs to millions of digits once e is of the size
\\     of M and the generator has any height, while modulo p^PRECL2 the
\\     cost of an ellmul is flat in e and in h(P).  The earlier version
\\     multiplied on the RATIONAL curve and paid that price on every
\\     divisor of M, not just the last one.
\\ E_1 membership is then v_p(x) < 0, which is the p-adic reading of the old
\\ test p | cden.  One thing does not survive the move: p-adically the point
\\ at infinity is not distinguishable from a very deep point of E_1, so the
\\ case e P = O, which the rational version excluded by hand with Q != [0],
\\ is excluded here from the order of P in E(Q) instead -- computed once, by
\\ ellorder, which returns 0 for a point of infinite order.  On this sweep
\\ every E^d(Q) has trivial torsion so the exclusion never fires, but the
\\ function should not depend on the witness table for its correctness.
ordE1(E, P, p, M) =
{ my(Ep = padiccurve(E, p), n = ellorder(E, P),
     Pp = [P[1] + O(p^PRECL2), P[2] + O(p^PRECL2)]);
  foreach (divisors(M), e,
    if (n && e % n == 0, next);
    my(Q = ellmul(Ep, Pp, e));
    if (Q != [0] && valuation(Q[1], p) < 0, return(e)));
  M;
}

\\ ---- rank over F_l of a matrix of images given as rows
rankFl(rows, l) =
{ if (#rows == 0, return(0));
  my(m = matrix(#rows, #rows[1]));
  for (i = 1, #rows, for (j = 1, #rows[1], m[i,j] = Mod(rows[i][j], l)));
  matrank(m);
}

\\ ---- one block per (p, class, d): the generators of E^d(Q) once, then one
\\ line per relevant l with basis, images and rank.
entry(p, cls, d) =
{ my(E = Ed(d), M = MvalE(E,p), good = (Mod(E.disc,p) != 0), g = ellrank(E));
  my(gens = concat(ellsaturation(E, g[4], 200), elltors(E)[3]));
  my(Tstruct, Tord, CB = 0, rts = 0, sp = 0, layers = List(), allonto = 1);
  \\ the torsion T and its structure
  if (good && M % p != 0,
    Tstruct = ellgroup(E, p); CB = canonbase(E, p),
    my(c = M / p^valuation(M, p));
    Tstruct = if (c == 1, [],
               if (c == 4 && #prootsQp(E, p, 40) == 3, [2,2], [c]));
    if (#Tstruct > 0, rts = prootsQp(E, p, 40); sp = singptp(E, p)));
  Tord = if (#Tstruct == 0, 1, if (#Tstruct == 1, Tstruct[1], Tstruct[1]*Tstruct[2]));
  print("  p = ", p, "  class ", cls, "  d = ", d,
        "    E_d : y^2 = x^3 + ", d^2, "x + ", d^3);
  my(lr = elllocalred(E,p));
  print("      reduction ", if (good, "good", if (ellap(E,p) == 0, "additive", "multiplicative")),
        ",  Kodaira ", kodsym(lr[2]), ",  c_p = ", lr[4], ",  a_p = ", ellap(E,p),
        ",  M = ", M, ",  T = ",
        if (#Tstruct == 0, "trivial",
          if (#Tstruct == 1, Str("C", Tstruct[1]), Str("C2 x C2"))),
        ",   E^d(Q_p) = Z_", p, if (Tord > 1, Str(" x T"), ""));
  print("      E^d(Q) : rank ", g[1], ", torsion ", elltors(E)[1], ";  generators");
  for (i = 1, #gens, print("        P_", i, " = ", gens[i]));
  \\ the relevant l: p, and the primes dividing #T
  listput(layers, p);
  if (Tord > 1, foreach (factor(Tord)[,1]~, l, if (l != p, listput(layers, l))));
  layers = Vec(layers);
  print("      relevant l (p, and the primes dividing #T) : ", layers);
  foreach (layers, l,
    my(dim, basis, rows = List(), onto);
    if (l == p,
      \\ G/pG = Z_p/p, one-dimensional, no canonical basis
      dim = 1; basis = "-- (dim 1; the identification with F_p is only up to F_p^*)";
      for (i = 1, #gens,
        my(w = valalpha(E, gens[i], p, M));
        listput(rows, [if (w == 0, 1, 0)]));
      rows = Vec(rows);
      print("      l = ", l, "  (= p)   dim E^d(Q_p)/", l, " = ", dim);
      print("            basis  : ", basis);
      for (i = 1, #gens,
        my(w = valalpha(E, gens[i], p, M));
        print("            P_", i, " |-> ", if (w == 0, "nonzero", "0"),
              "      (v_", p, "(alpha) = ", if (w < 0, "infinity", w), ")"))
    ,
      if (good && M % p != 0,
        \\ T = Etilde(F_p) = C_n1 (+) C_n2 against the canonical base
        my(Ep = CB[1], bg = CB[2], cyc = CB[3], idx = List());
        for (i = 1, #cyc, if (cyc[i] % l == 0, listput(idx, i)));
        idx = Vec(idx); dim = #idx;
        basis = Str("images of ", [bg[i] | i <- idx], " in Etilde(F_", p, ")");
        for (i = 1, #gens,
          my(P = gens[i],
             Pb = if (Mod(cden(P),p) == 0, [0], [Mod(P[1],p), Mod(P[2],p)]),
             c = dlog(Ep, Pb, bg, cyc));
          listput(rows, vector(dim, j, c[idx[j]] % l)));
        rows = Vec(rows)
      ,
        \\ additive: T = Phi(F_p)
        if (#Tstruct == 2,
          dim = 2;
          basis = Str("the 2-torsion at x = ", [rootlabel(rts[1],p), rootlabel(rts[2],p)]);
          for (i = 1, #gens, listput(rows, phiclass(E, gens[i], p, rts, sp, 40)));
          rows = Vec(rows)
        ,
          \\ T cyclic.  This covers BOTH additive with Phi cyclic AND
          \\ multiplicative -- the p = 31 lines, where 31 is the bad prime of E
          \\ itself.  An earlier version handled the non-good case as though T
          \\ were always Phi(F_p); that is true only for ADDITIVE reduction,
          \\ where E_0/E_1 = G_a is a p-group and contributes nothing to T.  At
          \\ multiplicative reduction E_0/E_1 is the non-split torus, cyclic of
          \\ order p - a_p prime to p, and IS the whole of T -- so the component
          \\ group is the wrong place to look and both p = 31 lines came back
          \\ NOT ONTO.  The order of Pbar in E/E_1 is the right invariant and
          \\ needs no case analysis: for cyclic T = C_m the image in T/lT is
          \\ nonzero exactly when v_l(order) is v_l(m), i.e. the class is prime
          \\ to l.
          dim = 1;
          basis = Str("a generator of the cyclic T = C", Tord);
          for (i = 1, #gens,
            my(o = ordE1(E, gens[i], p, M));
            o = o / p^valuation(o, p);
            listput(rows, [if (valuation(o, l) == valuation(Tord, l), 1, 0)]));
          rows = Vec(rows)));
      print("      l = ", l, "        dim E^d(Q_p)/", l, " = ", dim);
      print("            basis  : ", basis);
      for (i = 1, #gens, print("            P_", i, " |-> ", rows[i])));
    onto = (rankFl(rows, l) == dim);
    if (!onto, allonto = 0);
    print("            rank over F_", l, " = ", rankFl(rows, l), " of ", dim,
          "   ==> ", if (onto, "ONTO", "*** NOT ONTO ***")));
  print("      dense at p : ", if (allonto, "YES (onto for every l)", "*** NO ***"));
  [allonto, #gens, Tstruct, layers];
}

\\ ---- the witness table of section 3.3, verbatim from cert-extended.gp
{
WIT = [
  [3,   [7, -1, 3, 6]],        [5,   [1, 3, 5, -35]],
  [7,   [1, -1, 7, -7]],       [11,  [3, 6, 11, -11]],
  [13,  [-1, 5, -13, 26]],     [17,  [-1, 7, 34, 51]],
  [19,  [1, -1, 95, -95]],     [23,  [1, -1, 46, 115]],
  [29,  [-1, 11, -29, 58]],    [31,  [1, -1, 31, -62]],
  [37,  [-11, 6, -37, 74]],    [41,  [-1, 3, 41, 123]],
  [43,  [1, -1, -86, 86]],     [47,  [-11, -149, 94, 705]],
  [53,  [11, 22, 53, 106]],    [59,  [1, 6, 295, -59]],
  [61,  [1, 7, -61, 122]],     [67,  [-221, 51, 2211, 134]],
  [71,  [1, -1, 71, -71]],     [73,  [3, -21, 146, -365]],
  [79,  [1, -1, 158, -158]],   [83,  [-22, -11, 83, 166]],
  [89,  [1, -7, 178, -267]],   [97,  [1, 7, 97, 485]],
  [101, [-1, 3, 101, -2626]],  [103, [1, -1, 103, 2266]],
  [107, [-7, -1, -1605, -107]],[109, [1, 6, 109, 654]],
  [113, [1, 3, 113, 339]],     [127, [-6, 3, 254, -127]],
  [131, [53, -11, 131, 8646]], [137, [7, 3, 274, -411]],
  [139, [51, 3, 139, -139]],   [149, [53, 94, -149, 13559]],
  [151, [1, -1, 755, 453]],    [157, [1, 5, 157, 2355]],
  [163, [1, -1, 978, 815]],    [167, [-13, -6, 334, -334]],
  [173, [51, 53, -173, 519]],  [179, [1, -19, 179, -537]],
  [181, [1, 7, -181, -1086]],  [191, [1, -1, 191, -191]],
  [193, [1, 5, -193, 965]],    [197, [-6, 3, 197, 394]],
  [199, [-6, 3, 199, -199]]
];
}
CLS = ["[1]", "[u]", "[p]", "[up]"];

print("=========================================================================");
print(" l-primary certificate for the single-place sweep, sections 3.3 and 3.4");
print("=========================================================================");
print("");
print("E : v^2 = u^3 + u + 1 (496a).   E_d : Y^2 = X^3 + d^2 X + d^3.");
print("");
print("G := E^d(Q_p) is profinite abelian and topologically finitely generated,");
print("so a closed subgroup R equals G as soon as R.Phi(G) = G, and for abelian");
print("G,  G/Phi(G) = prod_l G/lG.  With G = Z_p x T only l = p and the primes");
print("dividing #T contribute, and those factors have coprime orders.  Hence");
print("");
print("   E^d(Q) dense in E^d(Q_p)  <=>  E^d(Q) --> E^d(Q_p)/l onto for each l,");
print("");
print("checked one l at a time.  Each E^d(Q_p)/l is an F_l-space of dimension");
print("<= 2, so a line is: a basis, the images of the generators of E^d(Q) in");
print("it, and the rank of that matrix.  Generators are listed ONCE per (p,d).");
print("");
{
my(nl = 0, nd = 0, bad = List(), rows = 0, need2 = 0, noncyc = 0, ncl = List(), pcl = List());
foreach (WIT, w,
  my(p = w[1], ds = w[2]);
  for (j = 1, 4,
    my(t = entry(p, CLS[j], ds[j]));
    nl++; rows += #t[4];
    if (t[1], nd++, listput(bad, [p, CLS[j], ds[j]]));
    print("")));
print("-------------------------------------------------------------------------");
print("  blocks (p, class, d)          : ", nl);
print("  layer lines (p, d, l)         : ", rows);
print("  dense at p (onto for every l) : ", nd);
print("  disagreements with section 3.3: ", nl - nd);
foreach (Vec(bad), b, print("    *** p = ", b[1], " ", b[2], " d = ", b[3]));
print("-------------------------------------------------------------------------");
}
print("");
print("done.");
