\\ cert-extended.gp -- the extended density certificate for kummer-padic-density.typ.
\\ Run from this directory:
\\     gp -q -s 12000000000 cert-extended.gp < /dev/null > results/cert-extended.txt
\\
\\ For each prime p <= 200 and each square class of Q_p^*/(Q_p^*)^2, the witness
\\ twist d of the table in section 6.3 is extended with
\\   (1) the isomorphism type of E^d(Q_p), as Z_p x C_a x C_b ;
\\   (2) the generators of E^d(Q) actually used (redundant ones dropped) ;
\\   (3) their images in Z_p x C_a x C_b .
\\
\\ Conventions.  E_d : Y^2 = X^3 + d^2 X + d^3, the twist of E = 496a by d.
\\ For p >= 3 the formal group is E_1(Q_p) = Z_p with E_n <-> p^(n-1) Z_p, and
\\ M = #(E(Q_p)/E_1) = c_p * #Etilde^ns(F_p).  The torsion T = E(Q_p)_tors is
\\ torsion-free-complemented: E(Q_p) = Z_p x T.
\\   * good reduction with p not dividing M : T = E(F_p), read off by ellgroup,
\\     and the T-coordinate of a point is literally its reduction mod p.
\\   * additive reduction (the classes [p] and [up], where v_p(d) is odd) : the
\\     model has v_p(c_4) = 2, v_p(Delta) = 6, so the type is I_0^*, a_p = 0 and
\\     M = c_p * p.  The prime-to-p part of T is Phi(F_p), of order c_p; the
\\     p-part is trivial whenever a single point topologically generates, since
\\     Z_p x Z/p is not procyclic.  That is exactly what the index computation
\\     (M/m) p^(v-1) = 1 certifies, so the certificate determines the structure.
\\
\\ The Z_p-coordinate of a point is only defined up to a unit (the choice of a
\\ topological generator of Z_p), so what is recorded is its VALUATION: alpha is
\\ written u for a unit (valuation 0) and p^k u otherwise.  A point generates the
\\ Z_p factor iff its coordinate is a unit, iff the formal depth v_p(c(mP)) = 1.

cden(Q) = if (Q == [0], 0, sqrtint(denominator(Q[1])));
Ed(d)   = ellinit([d^2, d^3]);
Mval(E,p) =
{ my(a = ellap(E,p));
  if (Mod(E.disc,p) != 0, p + 1 - a, elllocalred(E,p)[4] * (p - a));
}
\\ order of Pbar in E(Q_p)/E_1, and the formal depth of that multiple
\\ The order of Pbar in E(Q_p)/E_1 divides M, so only the divisors of M need
\\ testing -- and each is reached by ellmul (double-and-add) rather than by M
\\ repeated additions.  That is the difference between minutes and milliseconds
\\ once the generators have large height.
ordv(E, P, p, M) =
{ my(D = divisors(M));
  foreach (D, e,
    my(Q = ellmul(E, P, e));
    if (Q != [0] && Mod(cden(Q), p) == 0,
      return([e, valuation(cden(Q), p)])));
  [0, 0];
}
\\ Subgroup of E(F_p) generated by the reductions of gens (good reduction).
\\ Done in the finite field: cheap.  Returns its order.
subgrp(E, gens, p) =
{ my(Ep = ellinit(E,p), S = Set([[0]]), frontier);
  foreach (gens, P,
    my(Q = [Mod(P[1],p), Mod(P[2],p)], T = Set([[0]]), R = [0]);
    for (k = 1, 4*p+20, R = elladd(Ep, R, Q); T = setunion(T, Set([R])); if (R == [0], break));
    my(U = List());
    foreach (Vec(S), a, foreach (Vec(T), b, listput(U, elladd(Ep, a, b))));
    S = Set(Vec(U)));
  #S;
}
\\ does this single point topologically generate E(Q_p)?  m = M and depth 1.
gensalone(E, P, p, M) =
{ my(r = ordv(E, P, p, M));
  r[1] == M && r[2] == 1;
}

\\ discrete log of Pbar in E(F_p), against the generators returned by ellgroup
dlog(Ep, P, gens, cyc) =
{ my(g1 = gens[1], n1 = cyc[1]);
  if (#cyc == 1,
    for (e = 0, n1-1, if (ellmul(Ep,g1,e) == P, return([e]))); return([-1]));
  my(g2 = gens[2], n2 = cyc[2]);
  for (e = 0, n1-1, for (f = 0, n2-1,
    if (elladd(Ep, ellmul(Ep,g1,e), ellmul(Ep,g2,f)) == P, return([e,f]))));
  [-1,-1];
}

{
WIT = [
  [3,   [7, -1, 3, 6]],        [5,   [1, 3, 5, -35]],
  [7,   [1, -1, 7, -7]],       [11,  [3, 6, 11, -11]],
  [13,  [-1, 5, -13, 26]],     [17,  [-1, 7, 34, 51]],
  [19,  [1, -1, 95, -95]],     [23,  [1, -1, 46, 115]],
  [29,  [-1, 11, -29, 58]],    [31,  [1, -1, 31, -62]],
  [37,  [-11, 6, -37, 74]],    [41,  [-1, 3, 41, 123]],
  [43,  [1, -1, -86, 86]],     [47,  [-11, -149, 94, 705]],
  [53,  [11, 22, 53, 106]],    [59,  [1, 6, 295, -59]],
  [61,  [1, 7, -61, 122]],     [67,  [-221, 51, 2211, 134]],
  [71,  [1, -1, 71, -71]],     [73,  [3, -21, 146, -365]],
  [79,  [1, -1, 158, -158]],   [83,  [-22, -11, 83, 166]],
  [89,  [1, -7, 178, -267]],   [97,  [1, 7, 97, 485]],
  [101, [-1, 3, 101, -2626]],  [103, [1, -1, 103, 2266]],
  [107, [-7, -1, -1605, -107]],[109, [1, 6, 109, 654]],
  [113, [1, 3, 113, 339]],     [127, [-6, 3, 254, -127]],
  [131, [53, -11, 131, 8646]], [137, [7, 3, 274, -411]],
  [139, [51, 3, 139, -139]],   [149, [53, 94, -149, 13559]],
  [151, [1, -1, 755, 453]],    [157, [1, 5, 157, 2355]],
  [163, [1, -1, 978, 815]],    [167, [-13, -6, 334, -334]],
  [173, [51, 53, -173, 519]],  [179, [1, -19, 179, -537]],
  [181, [1, 7, -181, -1086]],  [191, [1, -1, 191, -191]],
  [193, [1, 5, -193, 965]],    [197, [-6, 3, 197, 394]],
  [199, [-6, 3, 199, -199]]
];
}
CLS = ["[1]", "[u]", "[p]", "[up]"];

entry(p, cls, d) =
{ my(E = Ed(d), M = Mval(E,p), good = (Mod(E.disc,p) != 0));
  my(g = ellrank(E), gens, used = List(), struct, T, Tstr);
  gens = concat(ellsaturation(E, g[4], 200), elltors(E)[3]);
  \\ one generator suffices iff its order in E(Q_p)/E_1 is M and its depth is 1
  for (i = 1, #gens,
    if (#used > 0, break);
    if (gensalone(E, gens[i], p, M), used = List([gens[i]])));
  if (#used == 0, used = List(gens));
  used = Vec(used);
  \\ structure of T
  if (good && M % p != 0,
    my(G = ellgroup(E,p));
    T = G,
    \\ else: additive class, or anomalous
    my(Mp = M / p^valuation(M,p));
    T = if (Mp == 1, [], [Mp]));
  Tstr = if (#T == 0, "Z_p",
          if (#T == 1, Str("Z_p x C", T[1]),
              Str("Z_p x C", T[1], " x C", T[2])));
  print("  p = ", p, "  class ", cls, "  d = ", d);
  print("      E_d : y^2 = x^3 + ", d^2, "x + ", d^3);
  print("      reduction at p : ",
        if (good, Str("good, a_p = ", ellap(E,p)),
            Str(elllocalred(E,p)[2], " (code), c_p = ", elllocalred(E,p)[4],
                ", a_p = ", ellap(E,p))),
        ",   M = ", M);
  print("      rank ", g[1], ", torsion ", elltors(E)[1],
        ",   E_d(Q_p) = ", Tstr);
  print("      generators used : ", used,
        if (#used < #gens, Str("   (of ", #gens, "; the rest are not needed)"), ""));
  foreach (used, P,
    my(r = ordv(E,P,p,M), coord);
    if (good && M % p != 0,
      my(Ep = ellinit(E,p), G = ellgroup(E,p,1));
      my(Pp = [Mod(P[1],p), Mod(P[2],p)]);
      coord = dlog(Ep, Pp, G[3], G[2]),
      coord = [r[1] / p^valuation(r[1], p)]);
    my(Tord = if (#T == 0, 1, if (#T == 1, T[1], T[1]*T[2])));
    print("        ", P, "  ->  ( ",
          if (r[2] == 1, "u", Str(p, "^", r[2]-1, " u")), " ; ",
          if (good && M % p != 0,
              Str("class ", coord),
              if (Tord == 1, "-",
                  Str("order ", coord[1], " in C", Tord,
                      if (coord[1] == Tord, " (a generator)", "")))),
          " )",
          "     [ord in E/E_1 = ", r[1], ", formal depth ", r[2], "]"));
  print("");
}

print("=========================================================================");
print(" Extended density certificate for kummer-padic-density.typ, table 6.3");
print("=========================================================================");
print("");
print("E : v^2 = u^3 + u + 1 (496a, rank 1, trivial torsion).");
print("E_d : Y^2 = X^3 + d^2 X + d^3.   E_d(Q_p) = Z_p x T, T = E_d(Q_p)_tors.");
print("Z_p-coordinate recorded by valuation only (u = unit); a point generates");
print("the Z_p factor iff that coordinate is a unit, iff formal depth = 1.");
print("");

{
foreach (WIT, w,
  my(p = w[1], ds = w[2]);
  for (j = 1, 4, entry(p, CLS[j], ds[j])));
}
print("done.");
