# =====================================================================
# circle-interior.sage -- fields of triangulated packings in a rectangle
# with circles that touch no side ("three rows and more").
#
#     cd kummer
#     sage circle-interior.sage [NMAX] > ../results/circle-interior.txt
#
# Patterns come from circle-graph-search.py (plantri): every triangulated
# pattern with n circles, kept if some circle touches no side of the
# rectangle and every circle touches at least four objects (so no circle
# is just inscribed in a gap).  For each one:
#
#   1. the packing is found by least squares from a Tutte embedding;
#   2. Newton's method refines it to DIGITS digits on the polynomial
#      system: unknowns x_i, y_i, r_i, W (height 1), one equation per
#      tangency, (x_i - x_j)^2 + (y_i - y_j)^2 = (r_i + r_j)^2 for two
#      circles, y_i + r_i = 1, y_i = r_i, x_i = r_i, x_i + r_i = W for the
#      four sides;
#   3. PARI's algdep (LLL) finds the minimal polynomial of a random
#      rational combination theta of the unknowns, and of W;
#   4. certificate: every unknown is written as a rational polynomial in
#      theta (lindep) and all equations are checked to vanish exactly in
#      the number field Q(theta).  Then [Q(theta) : Q] is the degree of the
#      field F generated by the radii, the centres and W.
#
# Reported: deg F, deg W, whether sqrt 2 lies in F, the field
# discriminant's primes, and for deg F <= 11 the Galois group (polgalois).
# =====================================================================
import sys, time, random, importlib.util
import numpy as np

spec = importlib.util.spec_from_file_location('cgs', 'circle-graph-search.py')
cgs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cgs)

NMAX = int(sys.argv[1]) if len(sys.argv) > 1 else 6
NMIN = int(sys.argv[2]) if len(sys.argv) > 2 else 1
DIGITS = 2500
random.seed(int(7))


def system(n, cc, walls):
    names = ['x%d' % i for i in range(n)] + ['y%d' % i for i in range(n)] + ['r%d' % i for i in range(n)] + ['W']
    R = PolynomialRing(QQ, names)
    g = R.gens()
    x, y, r, W = g[:n], g[n:2 * n], g[2 * n:3 * n], g[3 * n]
    eqs = [(x[p] - x[q])^2 + (y[p] - y[q])^2 - (r[p] + r[q])^2 for p, q in cc]
    for p, sd in walls:
        eqs.append({'top': y[p] + r[p] - 1, 'bottom': y[p] - r[p], 'left': x[p] - r[p], 'right': W - x[p] - r[p]}[sd])
    return R, eqs


def newton(R, eqs, z0, digits):
    F = RealField(int(digits * 3.33) + 20)
    J = jacobian(vector(eqs), R.gens())
    z = vector(F, [F(c) for c in z0])
    for _ in range(80):
        Fz = vector(F, [e(*z) for e in eqs])
        Jz = matrix(F, [[e(*z) for e in row] for row in J.rows()])
        d = Jz.solve_right(-Fz)
        z += d
        if max(abs(c) for c in d) < F(10)^(-digits):
            break
    return z


def minpoly(val, digits):
    pv = pari(val)
    for dmax in (8, 16, 32, 64):
        p = pari.algdep(pv, dmax)
        best = min(p.factor()[0], key=lambda q: abs(q(pv)) if q.poldegree() > 0 else 1e99)
        h = max(abs(c) for c in best.Vec())
        if abs(best(pv)) < pari(10)^(-0.9 * digits) and (best.poldegree() + 1) * float(log(RR(h) + 1, 10)) < digits / 4:
            return QQ['T'](str(best).replace('x', 'T'))
    return None


def certify(eqs, zz, theta, D):
    """Write every unknown as a rational polynomial in theta (lindep at the
    precision of zz) and check all equations exactly in Q(theta)."""
    digits = int(zz[0].parent().prec() / 3.33) - 10
    m = minpoly(theta, digits)
    if m is None or m.degree() != D:
        return None
    Kf = NumberField(m.monic(), 'th')
    th = Kf.gen()
    exact = []
    for val in zz:
        rel = pari.lindep([pari(val)] + [pari(theta)^j for j in range(D)])
        rel = [QQ(c) for c in rel]
        if rel[0] == 0:
            return None
        exact.append(-sum(c * th^j for j, c in enumerate(rel[1:])) / rel[0])
    if all(e(*exact) == 0 for e in eqs):
        return Kf, exact
    return None


def analyse(n, cc, walls, z):
    R, eqs = system(n, cc, walls)
    zz = newton(R, eqs, list(z), DIGITS)
    zz2 = newton(R, eqs, list(zz), 2 * DIGITS)
    coeffs = [random.randint(int(-9), int(9)) for _ in range(3 * n + 1)]
    theta = sum(c * v for c, v in zip(coeffs, zz))
    theta2 = sum(c * v for c, v in zip(coeffs, zz2))
    mT = minpoly(theta, DIGITS)
    mW = minpoly(zz[3 * n], DIGITS)
    if mT is None or mW is None:
        return None
    assert abs(mT(theta2)) < RealField(int(2 * DIGITS * 3.33))(10)^(-int(1.8 * DIGITS))
    D = mT.degree()
    # certificate, with retries: more digits, and W itself as the generator
    # when it has the full degree
    attempt = None
    how = None
    for digits in (DIGITS, 3 * DIGITS, 6 * DIGITS):
        zk = zz if digits == DIGITS else newton(R, eqs, list(zz), digits)
        choices = [('random combination', sum(c * v for c, v in zip(coeffs, zk)))]
        if mW.degree() == D:
            choices.append(('W', zk[3 * n]))
        for name, th_val in choices:
            attempt = certify(eqs, zk, th_val, D)
            if attempt is not None:
                how = '%s, %d digits' % (name, digits)
                break
        if attempt is not None:
            break
    ok = attempt is not None
    Kf = attempt[0] if ok else NumberField(mT.monic(), 'th')
    gal = '?'
    if D <= 11:
        try:
            gal = str(pari(mT.monic().change_variable_name('x')).polgalois()[3])
        except Exception:
            pass
    disc_primes = list(Kf.discriminant().prime_factors()) if D <= 16 else 'not computed'
    return {'degF': D, 'degW': mW.degree(), 'certified': ok, 'how': how, 'sqrt2': Kf(2).is_square(),
            'galois': gal, 'disc_primes': disc_primes, 'W': float(zz[3 * n])}



def sqrt2_cluster(n, cc, walls):
    """Is there a corner cluster: circles P (top) and Q (bottom) touching the
    same side wall and each other, and a third circle R touching P, Q and
    the top or bottom line?  (In the two-row case this forces sqrt 2 in F.)"""
    E = set(cc)
    touch = {}
    for p, sd in walls:
        touch.setdefault(p, set()).add(sd)
    adj = lambda p, q: (min(p, q), max(p, q)) in E
    for side in ('left', 'right'):
        on = [p for p in range(n) if side in touch.get(p, ())]
        for P in on:
            for Q in on:
                if 'top' in touch[P] and 'bottom' in touch[Q] and P != Q and adj(P, Q):
                    for R in range(n):
                        if R not in (P, Q) and adj(R, P) and adj(R, Q) and touch.get(R, set()) & {'top', 'bottom'}:
                            return True
    return False



def sqrt2_triangle(n, cc, walls):
    """Is there a face P, Q, R with P on the top line, Q on the bottom line,
    P, Q, R pairwise tangent and R on the top or bottom line?  (This is the
    step of the two-row recursion that produces sqrt 2.)"""
    E = set(cc)
    touch = {}
    for p, sd in walls:
        touch.setdefault(p, set()).add(sd)
    adj = lambda p, q: (min(p, q), max(p, q)) in E
    for P in range(n):
        for Q in range(n):
            if P != Q and 'top' in touch.get(P, ()) and 'bottom' in touch.get(Q, ()) and adj(P, Q):
                for R in range(n):
                    if R not in (P, Q) and adj(R, P) and adj(R, Q) and touch.get(R, set()) & {'top', 'bottom'}:
                        return True
    return False


def spanning_ends(n, cc, walls):
    """Is each side wall touched by exactly one circle, a circle of radius
    1/2 touching both the top and the bottom?"""
    touch = {}
    for p, sd in walls:
        touch.setdefault(p, set()).add(sd)
    for side in ('left', 'right'):
        on = [p for p in range(n) if side in touch.get(p, ())]
        if len(on) != 1 or not {'top', 'bottom'} <= touch[on[0]]:
            return False
    return True

STATS = {}
STATS2 = {}
STATS3 = {}
EXCEPT = []
NOSQRT2 = []
print('Triangulated packings with circles touching no side: fields')
print('(every circle touches >= 4 objects; height 1)')
print()
for n in range(NMIN, NMAX + 1):
    t0 = time.time()
    rows = []
    for cc, walls, key in cgs.patterns(n):
        deg = [0] * n
        for p, q in cc:
            deg[p] += 1; deg[q] += 1
        touched = set(p for p, sd in walls)
        for p, sd in walls:
            deg[p] += 1
        interior = [i for i in range(n) if i not in touched]
        if not interior or min(deg) < 4:
            continue
        z = cgs.solve(n, cc, walls)
        if z is None:
            rows.append((cc, walls, interior, None))
            continue
        res = analyse(n, cc, walls, z)
        if res is not None:
            res['cluster'] = sqrt2_cluster(n, cc, walls)
            STATS[(res['cluster'], res['sqrt2'])] = STATS.get((res['cluster'], res['sqrt2']), 0) + 1
            res['triangle'] = sqrt2_triangle(n, cc, walls)
            res['spanning'] = spanning_ends(n, cc, walls)
            STATS3[(res['spanning'], res['sqrt2'])] = STATS3.get((res['spanning'], res['sqrt2']), 0) + 1
            STATS2[(res['triangle'], res['sqrt2'])] = STATS2.get((res['triangle'], res['sqrt2']), 0) + 1
            if res['triangle'] != res['sqrt2']:
                EXCEPT.append((n, cc, walls, res))
            if not res['sqrt2']:
                NOSQRT2.append((n, cc, walls, res))
        rows.append((cc, walls, interior, res))
    print('n = %d: %d patterns with an interior circle  (%.0fs)' % (n, len(rows), time.time() - t0))
    for cc, walls, interior, res in rows:
        if res is None:
            print('   [not solved or degree > 64]  %d interior' % len(interior))
            continue
        print('   %d interior   deg F %3d  deg W %3d  certified %-5s  sqrt2 in F %-5s  corner cluster %-5s  W = %.6f  disc primes %s  Galois %s'
              % (len(interior), res['degF'], res['degW'], res['certified'], res['sqrt2'], res['cluster'], res['W'], res['disc_primes'], res['galois']))
        if res['certified'] and res['how'] != 'random combination, %d digits' % DIGITS:
            print('        (certified with %s)' % res['how'])
        if not res['certified']:
            print('        tangencies %s' % cc)
            print('        sides      %s' % walls)
    sys.stdout.flush()

print()
print('(corner cluster, sqrt 2 in F) -> number of patterns:', STATS)
print('(top-bottom triangle with a third circle on a line, sqrt 2 in F) -> number of patterns:', STATS2)
print('(each side wall touched by one circle of radius 1/2 only, sqrt 2 in F) -> number of patterns:', STATS3)

print('patterns whose field does not contain sqrt 2:')
for n_, cc_, walls_, res_ in NOSQRT2:
    print('   n = %d  deg F %d  W = %.6f  disc primes %s  Galois %s' % (n_, res_['degF'], res_['W'], res_['disc_primes'], res_['galois']))
    print('      tangencies %s' % cc_)
    print('      sides      %s' % walls_)


def brick(k):
    """Top row A_1..A_k, middle row M_1..M_{k-1} touching no side,
    bottom row B_1..B_k; M_i touches A_i, A_{i+1}, B_i, B_{i+1}."""
    A = lambda i: i - 1
    B = lambda j: k + j - 1
    M = lambda i: 2 * k + i - 1
    n = 3 * k - 1
    cc = [(A(i), A(i + 1)) for i in range(1, k)] + [(B(j), B(j + 1)) for j in range(1, k)]
    cc += [(A(1), B(1)), (A(k), B(k))]
    for i in range(1, k):
        cc += [(A(i), M(i)), (A(i + 1), M(i)), (B(i), M(i)), (B(i + 1), M(i))]
    cc += [(M(i), M(i + 1)) for i in range(1, k - 1)]
    cc = sorted(tuple(sorted(e)) for e in cc)
    walls = sorted([(A(i), 'top') for i in range(1, k + 1)] + [(B(j), 'bottom') for j in range(1, k + 1)]
                   + [(A(1), 'left'), (B(1), 'left'), (A(k), 'right'), (B(k), 'right')])
    assert len(cc) + len(walls) == 3 * n + 1
    return n, cc, walls


print()
print('The brick family: rows of k, k-1, k circles')
for k in range(2, 6):
    t0 = time.time()
    n, cc, walls = brick(k)
    z = cgs.solve(n, cc, walls, attempts=200)
    if z is None:
        print('   k = %d: not solved' % k); continue
    res = analyse(n, cc, walls, z)
    if res is None:
        print('   k = %d (%d circles): degree > 64' % (k, n)); continue
    radii = sorted(set(round(float(r), 9) for r in z[2 * n:3 * n]))
    print('   k = %d (%d circles): deg F %3d  deg W %3d  certified %-5s  sqrt2 in F %-5s  W = %.6f  disc primes %s  Galois %s  (%.0fs)'
          % (k, n, res['degF'], res['degW'], res['certified'], res['sqrt2'], res['W'], res['disc_primes'], res['galois'], time.time() - t0))
    print('        distinct radii: %s' % radii)
    sys.stdout.flush()
