#import "@preview/cetz:0.4.2"

#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show link: set text(fill: blue.darken(20%))
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#let data = json("circle-porism.json")
#let red = rgb("#c0392b")
#let fills = (top: rgb("#d6e4f0"), bottom: rgb("#f6dcc8"), mid: rgb("#d5ecd4"))
#let names = (TL: $T_L$, TR: $T_R$, BR: $B_R$, BL: $B_L$, Bm: $B_M$, In: $I$)
#let fmt(x, d: 4) = str(calc.round(x, digits: d))

// a configuration: rectangle [0, W] x [0, 1], circles, and the two equal
// segments from the centre of TL to the contact points of TR (top) and BL
// (bottom), in red
#let picture(W, circles, unit: 2.6cm, graph: none, labels: true) = cetz.canvas(length: unit, {
  import cetz.draw: *
  rect((0, 0), (W, 1), stroke: 0.9pt)
  for c in circles {
    circle((c.x, c.y), radius: c.r, fill: fills.at(c.row), stroke: 0.55pt)
  }
  if graph != none {
    for e in graph.cc {
      let a = circles.at(e.at(0))
      let b = circles.at(e.at(1))
      line((a.x, a.y), (b.x, b.y), stroke: 0.4pt + luma(140))
    }
  }
  let tl = circles.find(c => c.label == "TL")
  let tr = circles.find(c => c.label == "TR")
  let bl = circles.find(c => c.label == "BL")
  let P = (tr.x, 1)
  let Q = (bl.x, 0)
  line((tl.x, tl.y), P, stroke: 1.1pt + red)
  line((tl.x, tl.y), Q, stroke: 1.1pt + red)
  circle((tl.x, tl.y), radius: 0.018, fill: red, stroke: none)
  circle(P, radius: 0.018, fill: red, stroke: none)
  circle(Q, radius: 0.018, fill: red, stroke: none)
  if labels {
    for c in circles {
      content((c.x + if c.label == "TL" { 0.09 } else { 0 }, c.y + if c.label == "TL" { 0.06 } else { 0 }),
        text(8pt, names.at(c.label)))
    }
    content((P.at(0), 1.06), text(8pt, fill: red)[$P$])
    content((Q.at(0), -0.07), text(8pt, fill: red)[$Q$])
  }
})

#align(center)[
  #text(size: 16pt, weight: "bold")[A porism with five circles]
  #v(2mm)
  #text(size: 10pt)[A length coincidence in a rigid packing of six circles, the reason it is not
  like the MathOverflow coincidence $A A' = H$, and an elementary proof]
  #v(1mm)
  #text(size: 9pt, style: "italic")[computations in `circle-porism.sage`, output in
  `results/circle-porism.txt`, figure data in `circle-porism.json`; found by
  `circle-coincidences.sage`]
]

#v(4mm)

#block(fill: luma(240), inset: 8pt, radius: 3pt, width: 100%)[
  *Summary.* In the rigid packing of @fig-packing, the centre of the top-left circle is equally
  far from the point $P$ where the top-right circle touches the top and the point $Q$ where
  the bottom-left circle touches the bottom. The coincidence does not use the interior circle
  $I$. Without $I$ the five remaining circles can move in a one-parameter family, and the
  coincidence holds along the whole family. With height $1$, it is equivalent to
  $ 2 thin r(T_L) thin r(T_R) = r(B_L), $
  and this identity is proved in @sec-proof. A statement that holds for a whole family as
  soon as the configuration closes up is a *porism*. The MathOverflow coincidence $A A' = H$
  is different: it fails as soon as any single tangency is dropped.
]

= The packing <sec-packing>

The diagram is the triangulated pattern `ITvhHdEUW` of `circle-graph-search.py`: six circles in
a rectangle of height $1$ and width $W = #fmt(data.W, d: 6)$. Four circles sit in the corners:
$T_L$, $T_R$, $B_R$, $B_L$. A fifth, $B_M$, touches the bottom between $B_L$ and $B_R$. The
sixth, $I$, touches no side. The tangencies are
- $T_L$ with the top, the left side, $B_L$, $T_R$, $B_M$ and $I$;
- $T_R$ with the top, the right side, $T_L$, $B_R$ and $I$;
- $B_R$ with the bottom, the right side, $T_R$, $B_M$ and $I$;
- $B_L$ with the bottom, the left side, $T_L$ and $B_M$;
- $B_M$ with the bottom, $B_L$, $T_L$, $B_R$ and $I$;
- $I$ with $T_L$, $T_R$, $B_R$ and $B_M$.

These are $19 = 3 dot 6 + 1$ tangencies, every gap is a curvilinear triangle, and so the
packing is rigid (`circle-packings.typ`, §1). Its field, generated by the radii, the centres
and $W$, has degree #data.degF, with Galois group $S_3 wreath C_2$, the generic group for
degree $6$. All coordinates were certified exactly in that field.

#figure(
  grid(
    columns: 2, column-gutter: 8mm, align: center + horizon,
    picture(data.W, data.circles, unit: 3.6cm),
    picture(data.W, data.circles, unit: 3.6cm, graph: data, labels: true),
  ),
  caption: [The packing (left), and with its circle–circle contacts as grey segments
  (right). Red: the two equal segments from the centre of $T_L$ to $P$, where $T_R$ touches
  the top, and to $Q$, where $B_L$ touches the bottom. Both have length
  $#fmt(data.length, d: 9)$.],
) <fig-packing>

= The coincidence <sec-coincidence>

Let $c$ be the centre of $T_L$, $P$ the point where $T_R$ touches the top, and $Q$ the point
where $B_L$ touches the bottom. Then
$ |c P| = |c Q| = #fmt(data.length, d: 12) dots $
exactly: the two squared lengths are equal in the number field of the packing. The common
squared length has degree $6$, with minimal polynomial
#align(center, text(9pt)[#raw(data.minpoly_len2)])

`circle-coincidences.sage` found this coincidence by comparing all segments between special
points of the diagram: corners, centres and points of tangency. It discards equalities that
hold for local or symmetric reasons, and this one survived. The search then asked which
tangencies the coincidence needs. It drops each of the $19$ contacts in turn, moves along the
resulting one-parameter family, and tests the coincidence there. It survives dropping any of
the four contacts of $I$, and fails when any other contact is dropped. So it does not
involve $I$ at all.

= The family of five circles <sec-family>

Remove $I$. The five remaining circles have $15$ contacts and $16$ unknowns (a centre and a
radius each, and $W$), so they move in a one-parameter family. The gap where $I$ was is now
a quadrilateral, bounded by $T_L$, $T_R$, $B_R$ and $B_M$. Take $r(T_L)$ as the parameter.
For $r(T_L)$ between $0.253$ and $0.413$, `circle-porism.sage` solves for the other circles
and compares $|c P|$ with $|c Q|$. They agree to the last digit, $10^(-16)$, at every member.
For $0.313 <= r(T_L) <= 0.353$ the configurations are honest packings; outside that range
the circles overlap, but the equality persists.

#let pick = data.family.filter(m => m.honest)
#let show-members = (pick.at(0), data.family.find(m => calc.abs(m.r - data.r0) < 1e-9), pick.at(pick.len() - 1))
#figure(
  grid(
    columns: 3, column-gutter: 5mm, align: center + bottom,
    ..show-members.map(m => stack(dir: ttb, spacing: 1.5mm,
      picture(m.W, m.circles, unit: 2.3cm, labels: false),
      text(8pt)[$r(T_L) = #fmt(m.r, d: 3)$ \ $|c P| = #fmt(m.a, d: 6)$ \ $|c Q| = #fmt(m.b, d: 6)$])),
  ),
  caption: [Three members of the family of five circles without $I$. The middle one is the
  packing of @fig-packing with $I$ removed. In each, the two red segments have equal
  length.],
) <fig-family>

= The proof <sec-proof>

Work with height $1$, and write $a = sqrt(r(T_L))$, $b = sqrt(r(T_R))$ and
$d = sqrt(r(B_L))$.

*Step 1: the coincidence as a statement about radii.* $T_L$ and $B_L$ touch each other and
the left side, so their points of contact with the left side are $2 a d$ apart. Since
$1 - r(T_L) - r(B_L) = 2 a d$, we get $(a + d)^2 = 1$, so $a + d = 1$. Now
$c = (a^2, 1 - a^2)$ and $Q = (d^2, 0)$, so
$ |c Q|^2 = (a^2 - d^2)^2 + (1 - a^2)^2 = (2a - 1)^2 + (1 - a^2)^2, $
using $a^2 - d^2 = (a - d)(a + d) = 2a - 1$. Also $T_L$ and $T_R$ touch each other and the
top, so $P = (a^2 + 2 a b, 1)$ and
$ |c P|^2 = (2 a b)^2 + a^4 . $
Subtracting, $|c P|^2 - |c Q|^2 = 4 a^2 b^2 - 2 (1 - a)^2$. So
$ |c P| = |c Q| quad <==> quad 2 a^2 b^2 = d^2 quad <==> quad 2 thin r(T_L) thin r(T_R) = r(B_L). $

*Step 2: the five circles force this relation.* Follow the bottom row from the left, as in
`circle-packings.typ` (§5). $B_M$ touches the bottom, $B_L$ and $T_L$, so by the recursion
of that section
$ sqrt(r(B_M)) = (1 - a) / (2a - 1 + sqrt(2) thin a), quad
  x(B_M) = (1 - a)^2 + 2 (1 - a) sqrt(r(B_M)). $
On the right, $T_R$ and $B_R$ touch each other and the right side, so as in step 1,
$sqrt(r(B_R)) = 1 - b$. The top row ends at $x(T_R) + r(T_R) = a^2 + 2 a b + b^2$, and the
bottom row at $x(B_R) + r(B_R) = x(B_M) + 2 sqrt(r(B_M)) (1 - b) + (1 - b)^2$. Both equal $W$:
$ (a + b)^2 = x(B_M) + 2 sqrt(r(B_M)) (1 - b) + (1 - b)^2 . $
The squares of $b$ cancel, so this equation is *linear* in $b$, with a unique solution for
each $a$. Substituting $b = (1 - a) \/ (sqrt(2) thin a)$ makes the two sides identically
equal as rational functions of $a$ (checked symbolically in `circle-porism.sage`). Hence
$ b = (1 - a) / (sqrt(2) thin a), quad "that is" quad 2 a^2 b^2 = (1 - a)^2 = d^2 , $
along the whole family. With step 1, this proves $|c P| = |c Q|$ for every configuration of
the five circles. $square$

The proof uses only the tangencies among $T_L, T_R, B_R, B_L, B_M$ and the sides, never $I$.
That is what the support computation of @sec-coincidence showed.

= Porisms and rigid coincidences <sec-porism>

Classically, a *porism* is a statement that if a configuration closes up once, it closes up
for a whole continuous family. Steiner's porism on chains of circles between two circles and
Poncelet's porism on polygons between two conics are the classical examples. Here the word is
used for a *length coincidence that is an identity on a flexible sub-configuration*: remove
some circles or tangencies so that what remains can move, and the coincidence still holds at
every member of that family. Such a coincidence does not use the rigidity of the packing; it
is a theorem about a smaller, flexible configuration, which the packing merely contains.

The coincidence of this note is a porism in that sense. The MathOverflow coincidence
$A A' = H$ of the six circles is not: dropping any one of its $19$ contacts, the sides
included, destroys it. It holds only at the isolated rigid configuration. Call that a
*rigid coincidence*.

`circle-coincidences.sage` sorts all the coincidences it finds into these two kinds, by
dropping each contact in turn and testing the coincidence on the resulting family
(`results/circle-coincidences.txt`). Over all diagrams searched (two-row zigzags up to
$k = 5$, packings with interior circles and at most six circles, and the brick family),
the result is:

#align(center, table(
  columns: 3, stroke: none, inset: (x: 8pt, y: 3pt), align: (center, center, center),
  table.hline(),
  [degree of the field], [rigid], [porisms],
  table.hline(stroke: 0.5pt),
  [$2$], [16], [207],
  [$3$], [1], [21],
  [$4$], [0], [28],
  [$6$], [1], [91],
  [$8$], [0], [1],
  table.hline(),
))

So $348$ of the $366$ coincidences are porisms. Of the $18$ rigid ones, $17$ lie in fields of
degree $2$ or $3$, where lengths are numbers such as $3\/2$, $sqrt(5)\/2$ or $sqrt(2)\/2$;
they look like arithmetic accidents rather than geometry. *The only rigid coincidence in a
field of larger degree is the MathOverflow one, $A A' = H$.*
