\\ local-kummer-p2.gp --- computations for local-kummer-p2.typ
\\
\\   E : y^2 = x^3 + 1   (j = 0, curve 36a1),  the place p = 2.
\\
\\ E[2] is generated by the roots of x^3 + 1 = (x+1)(x^2-x+1).  Over Q_2 the
\\ quadratic factor is irreducible and cuts out the UNRAMIFIED quadratic
\\ extension Q_4 = Q_2(zeta_3) = Q_2(sqrt(-3)).  So E[2] = Ind_{Q_4}^{Q_2} mu_2
\\ and Shapiro gives  H^1(Q_2, E[2]) = Q_4^* / (Q_4^*)^2,  the Kummer map being
\\
\\        delta : E(Q_2)/2E(Q_2) --> Q_4^*/(Q_4^*)^2,   P |-> x(P) - zeta_6,
\\
\\ where zeta_6 = -omega^2 = 1 + omega is the root of x^2-x+1 in Q_4.
\\
\\ Local arithmetic of Q_4 is done inside the NUMBER field K = Q(omega) at its
\\ (inert) prime above 2: K_pr = Q_4 on the nose, and nfhilbert(K,a,b,pr) is the
\\ Hilbert symbol of Q_4.  Since that symbol is nondegenerate on Q_4^*/(Q_4^*)^2,
\\ "is a square in Q_4" is decided by pairing against a basis -- no p-adic
\\ square-root extraction in a ramified tower is needed anywhere.
\\
\\ Run from this directory:   gp -q local-kummer-p2.gp > results/local-kummer-p2.txt

K  = nfinit(w^2 + w + 1);            \\ Q(omega),  omega = zeta_3
pr = idealprimedec(K, 2)[1];         \\ 2 is inert: e = 1, f = 2
W  = Mod(w, w^2 + w + 1);            \\ omega
hs(a,b) = nfhilbert(K, a, b, pr);    \\ Hilbert symbol of Q_4

\\ conjugation (Frobenius) and norm on K = Q(omega)
cf(z)  = my(l = lift(z)); [polcoef(l,0), polcoef(l,1)];
sig(z) = my(c = cf(z)); c[1] + c[2]*(-1 - W);
Nm(z)  = my(c = cf(z)); c[1]^2 - c[1]*c[2] + c[2]^2;

\\ basis of Q_4^*/(Q_4^*)^2 established in section 2
B = [2, -1, -2-W, -3-W];
issq(z) = my(ok = 1); for(i = 1, 4, if(hs(z, B[i]) == -1, ok = 0)); ok;
sgn4(z) = vector(4, i, if(hs(z, B[i]) == -1, 1, 0));

{ TAB = List();
  for(m = 0, 15,
    my(z = 1); for(i = 1, 4, if(bittest(m, i-1), z = z*B[i]));
    listput(TAB, [sgn4(z), vector(4, i, bittest(m, i-1))])); }
coord(z) = my(s = sgn4(z), r = -1); for(i = 1, 16, if(TAB[i][1] == s, r = TAB[i][2])); r;

bar() = print("=========================================================================");

bar();
print(" The local Kummer image of  y^2 = x^3 + 1  at  p = 2");
bar();
print("");

\\ ---------------------------------------------------------------- (1) the curve
E = ellinit([0,0,0,0,1]);
lr = elllocalred(E, 2);
print("(1) THE CURVE AND THE SIZE OF  E(Q_2)/2E(Q_2).");
print("");
print("    disc = ", E.disc, " = -2^4*3^3,   c4 = ", E.c4, ",   j = ", E.j);
print("    minimal at 2 : ", ellminimalmodel(E).disc == E.disc);
print("    conductor    : ", ellglobalred(E)[1]);
{ print("    at p = 2 : f = ", lr[1], ",  Kodaira type IV (code ", lr[2],
      "),  Tamagawa c_2 = ", lr[4]); }
print("    E(Q)_tors = Z/", elltors(E)[1], " generated by ", elltors(E)[3][1]);
print("");
{ print("    x^3 + 1 factors over Q as ", factor(x^3+1),
      "  and x^2-x+1 stays irreducible over Q_2 because -3 = ",
      lift(Mod(-3,8)), " mod 8 is not a square there."); }
print("    Hence  E(Q_2)[2] = {O, (-1,0)},  r_2 = 1, and");
print("      #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2*2 = 4 = 2^(r_2+1).");
print("    Structurally: E_1 = Z_2 (torsion free, since the only 2-torsion point");
print("    (-1,0) reduces to the nonsingular (1,0)), E_0/E_1 = Z/2 (additive");
print("    reduction), E/E_0 = Z/3 (c_2 = 3), so  E(Q_2) = Z_2 + Z/6.");
print("");

\\ ------------------------------------------------- (2) the group Q_4^*/(Q_4^*)^2
print("(2) THE TARGET  Q_4^*/(Q_4^*)^2  AND A BASIS.");
print("");
{ print("    2 is inert in K = Q(omega): e = ", pr[3], ", f = ", pr[4],
      ", so K_pr = Q_4."); }
print("    #Q_4^*/(Q_4^*)^2 = 2^([Q_4:Q_2]+2) = 2^4 = 16.   Reasons, in order of");
print("    increasing concreteness:");
print("      (i)   K^* = pi^Z x mu_(q-1) x U^(1) with U^(1) = mu_(2^oo)(K) x Z_2^d,");
print("            d = [K:Q_2].  Mod squares: Z/2 from the valuation, nothing from the");
print("            odd group mu_(q-1), 2^d from Z_2^d, and 2 from mu_(2^oo) (which is");
print("            {+-1} here: Q_2(i) is ramified, so i is not in Q_4).  2*1*4*2 = 16.");
print("      (ii)  Euler characteristic: #H^1(K,mu_2) = #H^0 * #H^2 * |2|_K^(-1)");
print("            = 2 * 2 * 2^d, the same 2^(d+2).");
print("      (iii) A FINITE count, below: 1+8O consists of squares, so O^*/(O^*)^2 is");
print("            computable inside the 64-element ring O/8O.");
print("");

\\ (iii) O^*/(O^*)^2 = (O/8O)^*/squares, since 1 + 8O lies inside (O^*)^2
Rm = 8;
mul8(u,v) = [(u[1]*v[1] - u[2]*v[2]) % Rm, (u[1]*v[2] + u[2]*v[1] - u[2]*v[2]) % Rm];
{ units8 = List();
  for(a = 0, Rm-1, for(b = 0, Rm-1,
    if((a^2 - a*b + b^2) % 2 == 1, listput(units8, [a,b]))));
  sq8 = List();
  for(i = 1, #units8,
    my(t = mul8(units8[i], units8[i]));
    if(!setsearch(Set(Vec(sq8)), t), listput(sq8, t)));
  print("    (O/8O)^* has ", #units8, " elements; exactly ", #sq8, " of them are squares:");
  print("      ", Vec(sq8), "  (written as [a,b] for a+b*w)  =  mu_3 * {1, 5},");
  print("    so #O^*/(O^*)^2 = ", #units8/#sq8, ",  and with the Z/2 from the valuation");
  print("    #Q_4^*/(Q_4^*)^2 = 2 * ", #units8/#sq8, " = ", 2*#units8/#sq8, ".");
  print(""); }
print("    the 16 classes, in coordinates (2, -1, -2-w, -3-w):");
print("      coords          representative      norm to Q_2   square?");
{ for(m = 0, 15,
    my(z = 1); for(i = 1, 4, if(bittest(m, i-1), z = z*B[i]));
    printf("      %s   %14s  %8s          %s\n", vector(4, i, bittest(m, i-1)),
           lift(z), Nm(z), if(issq(z), "yes", "no"))); }
print("    (only the trivial coordinate vector is a square: B is independent)");
print("");

\\ ------------------------------------------------------------ (3) the set V
print("(3) THE SET  V  OF COSET REPRESENTATIVES.");
print("");
y = sqrt(-7 + O(2^40));                     \\ sqrt(-7) in Z_2^*, the root = 3 mod 8
Y = lift(y + O(2^21));
T = [-1, 0];  P = [-2, y];  S = elladd(E, P, T);
print("    y := sqrt(-7) in Z_2^*  (-7 = 1 mod 8).  Hensel: y is pinned down by");
{ print("    y = ", lift(Mod(Y,8)), " mod 8; to 20 binary digits  y = ", lift(Mod(Y, 2^20)),
      "  mod 2^20,"); }
print("    i.e. y = ", y + O(2^20));
print("    -3y = ", lift(Mod(-3*Y, 2^20)), " mod 2^20.");
print("");
print("      V = { O,  (-1, 0),  (-2, y),  (-4, -3y) }");
print("");
{ print("    on the curve:  (-2,y) : ", ellisoncurve(E, P),
      "     (-4,-3y) : ", ellisoncurve(E, [-4, -3*y])); }
{ print("    (-2,y) + (-1,0) = (-4,-3y) :  x-error = ", S[1] + 4,
      ",  y-error = ", S[2] + 3*y); }
print("    x-coordinates are RATIONAL, so the Kummer classes below are exact;");
print("    the 2-adic precision only ever enters through y, and not at all in delta.");
print("");

\\ ------------------------------------------------------- (4) the Kummer image
print("(4) THE KUMMER IMAGE  delta(V) = image of E(Q_2) in Q_4^*/(Q_4^*)^2.");
print("");
print("      point        x        delta = x - zeta_6 = (x-1) - omega     N     N mod 8   coords");
{ VV = [["O", 0], ["(-1,0)", -1], ["(-2,y)", -2], ["(-4,-3y)", -4]];
  for(i = 1, 4,
    my(nm = VV[i][1], x = VV[i][2], z = if(i == 1, 1, x - 1 - W));
    printf("     %9s %5s   %22s  %6s   %3s     %s\n", nm, if(i==1,"-",x), lift(z),
           Nm(z), lift(Mod(Nm(z), 8)), coord(z))); }
print("");
print("    The four norms 1, 3, 7, 21 are 1, 3, 7, 5 mod 8: PAIRWISE DISTINCT in");
print("    Q_2^*/(Q_2^*)^2.  A square in Q_4 has square norm, so already the norm");
print("    separates the four classes.  delta is injective on E(Q_2)/2E(Q_2),");
print("    which has order 4 by (1), so V is exactly a set of coset representatives");
print("    and the four classes above are the FULL local image at 2:");
print("");
print("      Im(delta) = { 1, -2-w, -3-w, -5-w } = <[-2-w], [-3-w]>  =  (Z/2)^2.");
print("");
{ print("    homomorphism check  (-2-w)(-3-w) = ", lift((-2-W)*(-3-W)),
      "  vs  -5-w : quotient class = ", coord((-2-W)*(-3-W)*(-5-W))); }
print("    torsion checks (must be trivial: (0,1) = 2*(0,-1) lies in 2E(Q_2)) :");
print("      delta(0,1)  = ", lift(0-1-W), "  class ", coord(-1-W));
{ print("      delta(2,3)  = ", lift(2-1-W), "  class ", coord(1-W),
      "  (= class of (-1,0), as (2,3) = (-1,0) + 3-torsion)"); }
print("");

\\ -------------------------------------------------------- (5) brute force scan
print("(5) INDEPENDENT BRUTE-FORCE SCAN.");
print("");
print("    Sample x in Q (dense in Q_2) with x^3+1 a square in Q_2 -- each such x");
print("    gives a genuine point of E(Q_2) -- and record the class of x - zeta_6.");
{ found = List(); cnt = 0;
  for(k = 0, 6,
    for(a = -400, 400,
      if(k > 0 && a%2 == 0, next);
      my(x = a/4^k, v);
      v = x^3 + 1; if(v == 0, next);
      if(!issquare(v + O(2^60)), next);
      cnt++;
      my(c = coord(x - 1 - W));
      if(!setsearch(Set(Vec(found)), c), listput(found, c))));
  print("      points sampled          : ", cnt);
  print("      distinct classes reached: ", #found, "   ", Vec(found));
  print("      all inside <[-2-w],[-3-w]> : ",
        #select(c -> c[1] == 0 && c[2] == 0, Vec(found)) == #found); }
print("");

\\ ------------------------------------------------------------- (6) duality
print("(6) LOCAL DUALITY: THE IMAGE IS MAXIMAL ISOTROPIC.");
print("");
im = [1, -2-W, -3-W, -5-W];
print("    The Weil pairing on E[2] = Ind mu_2 is NOT the standard pairing on the");
print("    induced module: it composes it with the swap.  So under Shapiro the");
print("    Tate pairing on H^1(Q_2,E[2]) is  (a,b) |-> (a, sigma(b))_{Q_4},");
print("    sigma = Frobenius of Q_4/Q_2.  Both versions, on the image:");
print("");
print("      plain   ( u_i , u_j )        = ", matrix(4,4,i,j, hs(im[i], im[j])));
print("      twisted ( u_i , sigma(u_j) ) = ", matrix(4,4,i,j, hs(im[i], sig(im[j]))));
print("");
print("    The plain symbol is NOT trivial on the image; the twisted one is.");
{ L = List();
  for(m = 0, 15, my(z = 1); for(i = 1, 4, if(bittest(m, i-1), z = z*B[i]));
     if(hs(z, sig(-2-W)) == 1 && hs(z, sig(-3-W)) == 1, listput(L, lift(z))));
  print("    annihilator of the image under the twisted pairing: ", #L, " classes, ",
        Vec(L));
  print("    -- equal to the image itself, i.e. Im(delta) = Im(delta)^perp: maximal");
  print("       isotropic of order 4 in a group of order 16, as local duality demands."); }
print("");
print("    Position relative to the unramified classes H_ur = <-1, -2-w, -3-w>");
print("    (order 8; all four Kummer classes are UNIT classes, even though E has");
print("    additive reduction at 2):");
{ print("      (-1, sigma(-2-w)) = ", hs(-1, sig(-2-W)),
      "   so [-1] is not in the image, and"); }
print("      Im(delta) = { z in H_ur : (z, sigma(-2-w)) = 1 }, index 2 in H_ur.");
print("");

\\ ---------------------------------------------------- (7) etale algebra check
print("(7) CROSS-CHECK AGAINST THE FULL ETALE ALGEBRA  L = Q_2 x Q_4.");
print("");
print("    The classical descent map sends P to (x+1, x-zeta_6) in L^*/(L^*)^2");
print("    (for P = (-1,0) the first entry is replaced by (e1-e2)(e1-e3) = 3).");
print("    Its image is the norm-1 subgroup, of order 16 -- and the Q_2-entry is");
print("    determined by the Q_4-entry, since (x+1)*N(x-zeta_6) = y^2 is a square.");
print("    So nothing is lost by recording only the Q_4-entry:");
print("");
print("      x        Q_2-entry   mod 8      N(x - zeta_6)   mod 8");
{ for(i = 1, 3, my(x = [-1,-2,-4][i], c1, z);
    c1 = if(x == -1, 3, x+1); z = x - 1 - W;
    printf("     %3s   %9s   %5s   %13s   %5s\n", x, c1, lift(Mod(c1,8)),
           Nm(z), lift(Mod(Nm(z), 8)))); }
print("");
print("    Columns 3 and 5 agree in every row, as they must.");
print("");
bar();
print(" done.");
bar();
