read("kummer2.gp");

/* =====================================================================
   S-adic density   (document, section 2.2)

   X(Q_S) = prod_{p in S} X(Q_p) with the product topology.

   For one twist E_d, density of E_d(Q) in the PRODUCT prod_p E_d(Q_p) is
   what makes X(Q) dense in the corresponding component of X(Q_S).  Density
   in each factor SEPARATELY is strictly weaker: a closed subgroup can
   surject onto every factor without being the whole product.

   The two agree when the factors have pairwise coprime supernatural order.
   Since E_d(Q_p) = Z_p x T_p has order p^infinity * |T_p| and T_p embeds in
   E_d(Q_p)/E_1, that is implied by

       (*)  the integers p * M_p(d), p in S, are pairwise coprime.

   Counterexample when (*) fails: f = x^3+x+1, d = 1, S = {5,7}.  There
   M_5 = 9 and M_7 = 5, so E(Q_5)/5 x E(Q_7)/5 = F_5 x F_5, onto which the
   cyclic group E(Q) cannot surject -- yet E(Q) is dense in each factor.
   ===================================================================== */

/* the integers p*M_p(d) governing coprimality */
Mstar(Em, S) = vector(#S, i, S[i]*Mval(Em, S[i]));

coprimeS(Em, S) = {
  my(v = Mstar(Em, S), i, j);
  for(i = 1, #v, for(j = i+1, #v, if(gcd(v[i], v[j]) > 1, return(0))));
  1;
}

/* dense in every factor separately */
densefactorwise(Em, pts, S) = {
  my(i);
  for(i = 1, #S, if(!densegroup(Em, pts, S[i]), return(0)));
  1;
}

/* 1  = provably dense in the product (factorwise + coprime)
   0  = provably not (fails in some factor)
  -1  = factorwise dense but (*) fails, so undecided by this test          */
denseS(Em, pts, S) = {
  if(!densefactorwise(Em, pts, S), return(0));
  if(coprimeS(Em, S), return(1));
  -1;
}

/* S-adic square class of d: the tuple of local classes, packed as an index */
sqclassS(d, S) = {
  my(k = 0, i);
  for(i = 1, #S, k = 4*k + sqclass(d, S[i]));
  k;
}

/* For each tuple of square classes, look for a twist witnessing density.
   Sufficiency only needs ONE good d per tuple, so (*) is tested per d.    */
reportS(A, B, S, DMAX) = {
  my(nt = 4^#S, w = vector(nt, i, 0), u = vector(nt, i, 0), d, n, sg, td, k, r, nf, i);
  for(n = 1, DMAX,
    if(!issquarefree(n), next);
    for(sg = 0, 1,
      d = if(sg == 0, n, -n);
      k = sqclassS(d, S) + 1;
      if(w[k] != 0, next);
      td = twistdata(A, B, d);
      if(#td[2] == 0, next);
      r = denseS(td[1], td[2], S);
      if(r == 1, w[k] = d);
      if(r == -1 && u[k] == 0, u[k] = d)
    ));
  nf = 0;
  for(i = 1, nt, if(w[i] != 0, nf++));
  print("  f = x^3+(", A, ")x+(", B, ")   S = ", S);
  print("    tuples of square classes: ", nt, "   witnessed: ", nf);
  for(i = 1, nt,
    if(w[i] != 0,
       print("      tuple ", i-1, " : d = ", w[i])
     , print("      tuple ", i-1, " : none",
             if(u[i] != 0, Str("  (d=", u[i], " is factorwise dense but (*) fails)"), ""))));
  nf == nt;
}

/* ---------------------------------------------------------------------
   Level-2 test in the PRODUCT.   (document, section 2.2)

   E_2(Q_p) is contained in the Frattini subgroup of E_d(Q_p) for odd p
   (E_2 = p E_1 subset p G_p), and Frattini subgroups multiply over finite
   products.  So a subgroup of G_S = prod_p E_d(Q_p) surjecting onto the
   FINITE group  B = prod_p E_d(Q_p)/E_2(Q_p)  of order prod_p p*M_p is
   already dense in G_S.  At p = 2 one must use E_3 instead.

   This decides density in the product outright -- no coprimality needed.  */

inE2p(Q, p) = (Q == [0]) || (valuation(Q[1], p) <= -4);

/* order of B = prod_p G_p / E_2 */
Border(Em, S) = { my(t = 1, i); for(i = 1, #S, t *= S[i]*Mval(Em, S[i])); t; }

/* Is the subgroup generated by pts dense in prod_{p in S} Em(Q_p)?
   Triangular reduction against the product filtration, exactly as
   densegroup but with the membership test taken at every place at once. */
denseprod(Em, pts, S) = {
  my(N, r, Ep, P, cf, idx, rem, dv, mi, bvec, k, i, j, t, s, cc, S2, C2, ok, q);
  N = Border(Em, S); r = #pts;
  if(N == 0 || r == 0, return(0));
  Ep = vector(#S, i, padiccurve(Em, S[i]));
  P  = vector(#S, i, vector(r, j,
         [pts[j][1] + O(S[i]^PREC), pts[j][2] + O(S[i]^PREC)]));
  /* an element is a coefficient vector; realise it at place i on demand */
  cf = [vector(r, j, 0)];
  idx = 1;
  for(i = 1, r,
    rem = N \ idx;
    dv = divisors(rem); mi = 0; bvec = 0;
    for(t = 1, #dv,
      k = dv[t];
      for(s = 1, #cf,
        cc = cf[s]; cc[i] += k;
        ok = 1;
        for(q = 1, #S,
          my(A = [0], j2);
          for(j2 = 1, r, if(cc[j2] != 0,
            A = if(A == [0], ellmul(Ep[q], P[q][j2], cc[j2]),
                             elladd(Ep[q], A, ellmul(Ep[q], P[q][j2], cc[j2])))));
          if(!inE2p(A, S[q]), ok = 0; break()));
        if(ok, mi = k; bvec = cc; break(2))));
    if(mi == 0, next);
    S2 = List();
    for(j = 0, mi-1, for(s = 1, #cf, cc = cf[s]; cc[i] += j; listput(S2, cc)));
    cf = Vec(S2); idx *= mi
  );
  idx == N;
}

/* Search by tuple of square classes, deciding each twist with denseprod.
   Finding one witness per tuple proves density in X(Q_S) outright.        */
reportSprod(A, B, S, DMAX) = {
  my(nt = 4^#S, w = vector(nt, i, 0), d, n, sg, td, k, nf, i);
  for(n = 1, DMAX,
    if(!issquarefree(n), next);
    for(sg = 0, 1,
      d = if(sg == 0, n, -n);
      k = sqclassS(d, S) + 1;
      if(w[k] != 0, next);
      td = twistdata(A, B, d);
      if(#td[2] == 0, next);
      if(denseprod(td[1], td[2], S), w[k] = d)
    ));
  nf = 0; for(i = 1, nt, if(w[i] != 0, nf++));
  print("  f = x^3+(", A, ")x+(", B, ")   S = ", S,
        "   tuples witnessed: ", nf, " / ", nt);
  for(i = 1, nt, if(w[i] == 0, print("      tuple ", i-1, " : none found")));
  nf == nt;
}
