#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#align(center)[
  #text(size: 16pt, weight: "bold")[Ш of $y^2 = x^3 + p x$ at the Fermat primes]
  #v(2mm)
  #text(size: 10pt)[Why the shape $(ZZ slash 2^(k-1))^2$ is forced, and what the
  pattern really asks]
  #v(1mm)
  #text(size: 9pt, style: "italic")[on a question of Rene Pannekoek]
]

#v(4mm)

= The observation <sec-obs>

For $E_d : y^2 = x^3 + d x$ and $p = 2^(2^k) + 1$ a Fermat prime, computation suggests
$ Ш(E_p) tilde.equiv (ZZ slash 2^(k-1) ZZ)^2 , $
that is $Ш = 0, (ZZ slash 2)^2, (ZZ slash 4)^2, (ZZ slash 8)^2$ for $p = 5, 17, 257, 65537$.

The pattern splits cleanly into two questions of very different character, and this is the main
point of what follows:

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *(a) Why is $Ш$ of the form $(ZZ slash 2^e)^2$?* --- because it cannot be anything else. This is
  forced, needs no BSD, and is proved in @sec-shape.

  #v(1.5mm)
  *(b) Why is $e = k - 1$?* --- this is the whole content, and it is equivalent to a single
  statement about an $L$-value, @sec-size. We do not explain it.
]

= The shape is forced <sec-shape>

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Theorem 1.* Let $p equiv 1$ $(mod 8)$ be a prime with $L(E_p, 1) != 0$. Then
  $ Ш(E_p)[2^infinity] tilde.equiv (ZZ slash 2^e ZZ)^2 quad "for some" e >= 1 . $
  No conjecture is used.

  #v(2mm)
  _Proof._ Four inputs.

  #v(1.5mm)
  *(i)* $E_p$ has complex multiplication by $ZZ[i]$, so by Coates--Wiles $L(E_p,1) != 0$ forces
  $"rank" E_p (QQ) = 0$, and by Rubin $Ш(E_p)$ is finite.

  #v(1.5mm)
  *(ii)* $E_p (QQ)_"tors" = ZZ slash 2$, generated by $(0,0)$: the curve $y^2 = x^3 + d x$ has full
  2-torsion only when $-d$ is a square, and $ZZ slash 4$ only for $d = 4$.

  #v(1.5mm)
  *(iii)* $"Sel"^((2))(E_p) tilde.equiv (ZZ slash 2)^3$ for $p equiv 1$ $(mod 8)$ --- this is the
  computation in Silverman X.6.

  #v(1.5mm)
  *(iv)* The descent sequence
  $ 0 -> E_p (QQ) slash 2 E_p (QQ) -> "Sel"^((2))(E_p) -> Ш(E_p)[2] -> 0 $
  now reads $0 -> ZZ slash 2 -> (ZZ slash 2)^3 -> Ш[2] -> 0$, since rank 0 and torsion
  $ZZ slash 2$ give $dim E_p (QQ) slash 2 = 1$. Hence
  $ dim_(bb(F)_2) Ш(E_p)[2] = 2 . $
  A finite abelian 2-group with $dim A[2] = 2$ is a product of *exactly two* cyclic groups,
  $ZZ slash 2^(e_1) times ZZ slash 2^(e_2)$; and the Cassels--Tate pairing on $Ш$ is
  alternating and non-degenerate, which forces the 2-primary part to be of the form $A times A$,
  so $e_1 = e_2$. $qed$
]

So *nothing* about the Fermat primes is needed for the shape: every $p equiv 1$ $(mod 8)$ with
$L(E_p,1) != 0$ has $Ш[2^infinity] = (ZZ slash 2^e)^2$. Two independent confirmations from the
computation:

- for $p = 17, 257, 65537$, `ellrank` returns the interval $0 .. 2$ rather than a rank --- and
  PARI's documentation says the 2-descent "never" determines the rank when Ш has 4-torsion. It is
  telling us, without being asked, that $Ш$ has 4-torsion for $p = 257$ and $65537$ and not for
  $p = 17$;
- $dim "Sel"^((2))$ comes out 3 for $p = 17, 257, 65537$ and 2 for $p = 5$, matching (iii).

= The size is one $L$-value <sec-size>

Now bring in BSD. For every one of the 64 primes $p equiv 1$ $(mod 8)$ below 3000 with
$L(E_p,1) != 0$ we computed
$ #[the Tamagawa product] c = 2, quad #[the torsion] |T| = 2 , $
so the BSD formula collapses to
$ \# Ш(E_p) = L(E_p,1) / Omega dot (|T|^2) / c = 2 dot L(E_p,1) / Omega . $
And in all 64 cases the $L$-value has the *Waldspurger square shape*
$ L(E_p,1) / Omega = 2 m^2, quad m in ZZ_(>0) , $
so that $\# Ш = (2 m)^2$ --- consistent with Theorem 1, and with the odd part of $Ш$ being
$(ZZ slash m_"odd")^2$. Writing $e = 1 + v_2 (m)$ we get $Ш[2^infinity] = (ZZ slash 2^e)^2$.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *So the question is exactly:* why is $m(p) = 2^(k-2)$, equivalently
  $ L(E_p, 1) / Omega = 2^(2k-3) , $
  for $p = 2^(2^k) + 1$?
]

The three computable cases, the last of which we computed here rather than taking on trust:

#align(center, table(
  columns: 6, align: (center, center, center, center, center, center),
  stroke: 0.4pt + luma(170), inset: (x: 7pt, y: 3.5pt),
  table.header([$k$], [$p$], [$L(1) slash Omega$], [$m$], [$\# Ш$], [$Ш$]),
  [1], [5], [--- (rank 1)], [---], [1], [0],
  [2], [17], [2], [1], [4], [$(ZZ slash 2)^2$],
  [3], [257], [8], [2], [16], [$(ZZ slash 4)^2$],
  [4], [65537], [*32*], [4], [*64*], [$(ZZ slash 8)^2$],
))

#v(2mm)

= What is special about a Fermat prime here <sec-fermat>

Two things, and it is not clear which is doing the work.

*The Gaussian factorisation is as degenerate as possible.* Writing $p = a^2 + b^2$ with $a$ odd,
$ p = 2^(2^k) + 1 = 1^2 + (2^(2^(k-1)))^2 quad ==> quad a = 1, quad b = 2^(2^(k-1)) . $
So $a$ is as small as it can be and $b$ is a pure power of 2 --- the splitting $p = pi overline(pi)$
in $ZZ[i]$ has $pi = 1 + 2^(2^(k-1)) i$.

*The unit group is a 2-group.* $\#bb(F)_p^times = p - 1 = 2^(2^k)$, so every quartic, octic and
higher residue symbol modulo $p$ takes values in 2-power roots of unity, and $2$ has order exactly
$2^(k+1)$ modulo $p$, since $2^(2^k) equiv -1$.

Either could plausibly force the 2-adic valuation of the $L$-value. But the data warn against the
easy guess that $v_2 (b)$ alone decides $m$:

#align(center, table(
  columns: 4, align: (center, center, center, center),
  stroke: 0.4pt + luma(170), inset: (x: 7pt, y: 3.5pt),
  table.header([$p$], [$a$], [$b$], [$m$]),
  [4177], [9],  [64], [2],
  [4217], [11], [64], [2],
  [4721], [25], [64], [2],
  [4937], [29], [64], [*4*],
))

#v(2mm)

Same $b$, same $v_2 (b) = 6$, and $m$ jumps. Whatever governs $m$ sees more than the 2-adic size of
$b$. (Nor is $m$ always a power of 2: $p = 857$ gives $m = 3$ and $\# Ш = 36$, and $p = 2017, 2617$
also give $m = 3$.)

= Two remarks on the question as posed <sec-remarks>

*The weaker question is not weaker.* Since Theorem 1 gives $Ш[2^infinity] = (ZZ slash 2^e)^2$, the
*exponent* of $Ш[2^infinity]$ is exactly $2^e$. So "is the exponent divisible by $2^(k-1)$" and "is
$Ш tilde.equiv (ZZ slash 2^(k-1))^2$" are the same statement, once the shape is known. There is no
intermediate target to aim at.

*Why $d = 2^(32) + 1$ hangs.* That $d$ is composite, so Silverman X.6 does not apply and even the
Selmer rank is not given by the same recipe. Worse, the conductor is $2^6 d^2 approx 1.2 dot
10^(21)$, so an $L$-value computation needs on the order of $sqrt(N) approx 3.4 dot 10^(10)$ terms.
That is why Sage and Magma do not return: it is not a subtlety, just the size.

= Status <sec-status>

*Proved, unconditionally:* Theorem 1. For every prime $p equiv 1$ $(mod 8)$ with $L(E_p,1) != 0$,
$Ш(E_p)[2^infinity] tilde.equiv (ZZ slash 2^e)^2$. This answers the shape half of the question and
removes the mystery from it --- the pattern's most striking feature, that Ш is a *square* of a
cyclic group, is a theorem about any such $p$, not a property of Fermat primes.

*Computed:* $c = |T| = 2$ and $L(1) slash Omega = 2 m^2$ for all 64 rank-0 primes $p equiv 1$
$(mod 8)$ below 3000; and $L(E_(65537), 1) slash Omega = 32$, giving $\# Ш = 64$ --- the $k = 4$
case, verified here independently.

*Not explained:* why $m = 2^(k-2)$ at the Fermat primes. Everything reduces to that one statement,
and it is a statement about the 2-adic valuation of a Waldspurger coefficient in the quadratic twist
family $y^2 = x^3 + d x$. The natural place to look is a Tunnell-style formula for that family, with
the Fermat condition entering through $a = 1$, $b = 2^(2^(k-1))$.
