#set page(paper: "a4", margin: (x: 2.0cm, y: 2.2cm), numbering: "1")
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")
#show link: set text(fill: blue.darken(20%))
#show raw.where(block: true): it => block(
  fill: luma(247), inset: 8pt, radius: 3pt, width: 100%, breakable: true,
  text(size: 8pt, it),
)

#align(center)[
  #text(size: 16pt, weight: "bold")[Splitting completely is a property of the closure]
  #v(2mm)
  #text(size: 10pt)[One direction is multiplicativity of $e$ and $f$ and needs no hypothesis at
  all; the converse is where "Galois closure" earns its name, and the density $1 slash [L : QQ]$
  is what it costs]
  #v(1mm)
  #text(size: 9pt, style: "italic")[a question of René Pannekoek's; checks in
  `splitting-galois-closure.gp`]
]

#v(4mm)

#block(fill: luma(240), inset: 9pt, radius: 3pt, width: 100%)[
  *The one-line answer.* Yes, and the Galois hypothesis is not used: $K subset.eq L$ is enough
  (@sec-easy). What is worth extracting is that the *converse* also holds, so that
  $ p " splits completely in " K quad <==> quad p " splits completely in " L , $
  and that the converse is exactly where $L$ has to be the *closure* and not merely some larger
  field (@sec-converse, and the control in @sec-control). Two corollaries follow, both of which
  catch people out: the density of the completely split primes of $K$ is $1 slash [L : QQ]$ and not
  $1 slash [K : QQ]$ (@sec-density), and $"Spl"(K)$ cannot distinguish two non-isomorphic fields
  with the same closure --- $QQ[x] slash (x^4 - 2)$ and $QQ[x] slash (x^4 + 2)$ are a small example
  (@sec-corollary).
]

= The easy direction <sec-easy>

Write $"Spl"(F)$ for the set of rational primes that split completely in a number field $F$, i.e.
those $p$ with $e(frak(q) slash p) = f(frak(q) slash p) = 1$ for every prime $frak(q)$ of $F$ above
$p$.

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Proposition.* Let $K subset.eq L$ be number fields. If $p$ splits completely in $L$ then $p$
  splits completely in $K$. In particular $"Spl"(L) subset.eq "Spl"(K)$.

  #v(2mm)
  _Proof._ Let $frak(p)$ be a prime of $K$ above $p$. Since $L slash K$ is an extension of number
  fields there is a prime $frak(P)$ of $L$ above $frak(p)$. Ramification indices and residue
  degrees are multiplicative in towers:
  $ e(frak(P) slash p) = e(frak(P) slash frak(p)) dot e(frak(p) slash p) , wide
    f(frak(P) slash p) = f(frak(P) slash frak(p)) dot f(frak(p) slash p) . $
  By hypothesis both left-hand sides are $1$, so $e(frak(p) slash p) = f(frak(p) slash p) = 1$.
  This holds for every prime $frak(p)$ of $K$ above $p$. $qed$
]

#v(2mm)
Nothing here uses that $L$ is Galois, or that it is the closure of $K$; the same argument gives the
statement for *every* intermediate field of $L slash QQ$ at once, which is what check 2 verifies on
all ten subfields of a degree-$8$ closure.

= The same thing in the group <sec-group>

Suppose now $L slash QQ$ is Galois with group $G$, and $K = L^H$ for $H = "Gal"(L slash K)$. Fix
$p$ unramified in $L$, a prime $frak(P)$ of $L$ above it, and let $D = D_frak(P) subset.eq G$ be the
decomposition group --- cyclic, generated by $"Frob"_p$. Then

#block(inset: (left: 12pt, y: 2pt), stroke: (left: 2pt + luma(190)))[
  - $p$ splits completely in $L$ #h(4mm) $<==>$ #h(4mm) $D = 1$;
  - $p$ splits completely in $K$ #h(4mm) $<==>$ #h(4mm) $D subset.eq sigma H sigma^(-1)$ for every
    $sigma in G$.
]

#v(2mm)
The second is the orbit count: the primes of $K$ above $p$ correspond to the double cosets
$H backslash G slash D$, and all of them have residue degree $1$ exactly when $D$ is swallowed by
every conjugate of $H$. From this the proposition of @sec-easy is immediate --- if $D = 1$ the
second condition is vacuous --- but the reformulation is worth having because it makes the converse
visible.

= The converse, and where the closure is used <sec-converse>

#block(stroke: 0.6pt + black, inset: 9pt, radius: 3pt, width: 100%)[
  *Proposition.* Let $L$ be the *Galois closure* of $K$ over $QQ$. If $p$ splits completely in $K$
  then $p$ splits completely in $L$. Hence $"Spl"(K) = "Spl"(L)$.

  #v(2mm)
  _Proof._ First, $p$ is unramified in $L$: it is unramified in $K$, hence in every conjugate of
  $K$, and $L$ is the compositum of those conjugates. Now by @sec-group,
  $ D subset.eq inter.big_(sigma in G) sigma H sigma^(-1) = "core"_G (H) , $
  and $"core"_G (H)$ --- the largest normal subgroup of $G$ contained in $H$ --- is *trivial*,
  precisely because $L$ is the Galois closure: $L^("core"_G (H))$ is the smallest Galois extension
  of $QQ$ containing $K$, so it is $L$ itself, so the core is $1$. Therefore $D = 1$. $qed$
]

#v(2mm)
That is the whole role of the word *closure* in the statement. Take $L$ any larger field and the
core argument has nothing to say; take $L$ Galois but strictly bigger than the closure and the core
of $H$ is a nontrivial normal subgroup, which is exactly the room in which a prime can split
completely in $K$ and fail to do so in $L$.

= What fails without it <sec-control>

The control is worth doing rather than merely asserting. Take $K = QQ(2^(1 slash 3))$ and
$M = K(sqrt(7))$: both of degree $6$ over $QQ$, but $M$ is neither Galois nor the closure of $K$.
Below $10^5$ (check 3):

#align(center, table(
  columns: 4, align: (left, center, right, right),
  stroke: 0.4pt + luma(170), inset: (x: 10pt, y: 3.5pt),
  table.header([field], [degree], [$abs("Spl")$ below $10^5$], [in $"Spl"(K)$ but not here]),
  [$K = QQ(2^(1 slash 3))$], [$3$], [$1559$], [---],
  [$L$, the closure of $K$], [$6$], [$1559$], [$0$],
  [$M = K(sqrt(7))$], [$6$], [$766$], [$793$],
))

#v(2mm)
$L$ and $M$ have the same degree over $QQ$ and both contain $K$. One of them satisfies the converse
exactly; the other misses about half the primes. Degree is not what matters.

= The density <sec-density>

Chebotarev is a statement about a Galois extension, so it applies to $L$ and not to $K$: the primes
with $"Frob"_p = 1$ in $"Gal"(L slash QQ)$ have density $1 slash [L : QQ]$. By @sec-converse those
are exactly the primes of $"Spl"(K)$, so

$ lim_(X --> infinity) (abs({p in "Spl"(K) : p <= X})) / (pi(X)) = 1 / [L : QQ] , $

with $[L : QQ]$ and *not* $[K : QQ]$ in the denominator. The two agree only when $K$ is already
Galois. Check 4, over the $9592$ primes below $10^5$:

#align(center, table(
  columns: 5, align: (left, center, right, right, right),
  stroke: 0.4pt + luma(170), inset: (x: 9pt, y: 3.5pt),
  table.header([$K$], [$[L : QQ]$], [observed], [$1 slash [L:QQ]$], [$1 slash [K:QQ]$]),
  [$x^3 - 2$], [$6$], [$0.16253$], [$0.16667$], [$0.33333$],
  [$x^4 - 2$], [$8$], [$0.12323$], [$0.12500$], [$0.25000$],
  [$x^4 - x - 1$], [$24$], [$0.03910$], [$0.04167$], [$0.25000$],
))

#v(2mm)
The last row is the one to keep in mind: a quartic field whose Galois group is $S_4$ has completely
split primes of density $1 slash 24$, six times sparser than the naive guess. It is also why
$"Spl"$ is a slow invariant to compute with --- for a generic quintic the density is $1 slash 120$.

= Two fields, one splitting set <sec-corollary>

Since $"Spl"(K) = "Spl"(L)$ and $L$ depends only on $K$ up to isomorphism, $"Spl"$ is an invariant
of the closure alone. So it cannot distinguish two fields that share one. The smallest example is
already inside @sec-density: the Galois closure of $QQ(2^(1 slash 4))$ is
$L = QQ(2^(1 slash 4), i)$ of degree $8$, and its quartic subfields are (check 5)

#align(center, table(
  columns: 4, align: (left, center, right, left),
  stroke: 0.4pt + luma(170), inset: (x: 10pt, y: 3.5pt),
  table.header([subfield], [closure degree], [$abs("Spl")$ below $10^5$], [comment]),
  [$QQ[x] slash (x^4 + 1)$], [$4$], [$2384$], [$= QQ(zeta_8)$, already Galois],
  [$QQ[x] slash (x^4 - 2)$], [$8$], [$1182$], [disc $-2048$],
  [$QQ[x] slash (x^4 + 2)$], [$8$], [$1182$], [disc $+2048$],
))

#v(2mm)
The last two are *not isomorphic* --- their field discriminants have opposite sign, and `nfisisom`
confirms it --- yet their sets of completely split primes below $10^5$ are equal element by
element, because both have $L$ as Galois closure. The cyclotomic one, being Galois already, has
$"Spl"$ of density $1 slash 4$ and roughly twice as many primes.

#block(fill: rgb("#fff4e6"), inset: 8pt, radius: 3pt, width: 100%)[
  *What this does and does not say.* Equality of $"Spl"$ is strictly weaker than arithmetic
  equivalence. $QQ[x] slash (x^4 plus.minus 2)$ have the *same* completely split primes but
  *different* discriminants, hence different Dedekind zeta functions: the splitting behaviour they
  share is only at the completely split primes, and the other Frobenius classes tell them apart.
  Arithmetically equivalent fields --- same zeta function, non-isomorphic --- need a Gassmann
  triple and first occur in degree $7$.
]

= What the companion script checks <sec-gp>

`splitting-galois-closure.gp`, results in `results/splitting-galois-closure.txt`. All primes below
$10^5$; splitting is decided by `idealprimedec` in the ring of integers on both sides, never by
factoring the defining polynomial, so the equivalence is not assumed anywhere.

#v(1mm)
- *(1)* $"Spl"(K) = "Spl"(L)$ element by element for $x^3 - 2$, $x^4 - 2$, $x^4 - x - 1$, with
  closures of degree $6, 8, 24$. Neither set difference is ever nonempty.
- *(2)* The easy direction of @sec-easy on *all ten* subfields of the degree-$8$ closure of
  $x^4 - 2$: none of the $1182$ completely split primes fails to split in any of them.
- *(3)* The control of @sec-control: $M = K(sqrt(7))$ misses $793$ of the $1559$ primes of
  $"Spl"(K)$, while the closure misses none.
- *(4)* The densities of @sec-density against $1 slash [L : QQ]$ and $1 slash [K : QQ]$.
- *(5)* The quartic subfields of @sec-corollary, their closure degrees, their splitting sets
  compared as sets, and `nfisisom` on $x^4 - 2$ against $x^4 + 2$.

= References <sec-refs>

#block(inset: (left: 4pt))[
#set enum(numbering: "[1]")
+ J. Neukirch, *Algebraic Number Theory*, Springer 1999. I §8--§9 for the decomposition group and
  the double-coset description of the primes above $p$ used in @sec-group.
+ J. S. Milne, *Algebraic Number Theory*, course notes, #link("https://www.jmilne.org/math/")[jmilne.org].
  Splitting in towers, the Frobenius, and Chebotarev in the form used in @sec-density.
+ R. Perlis, *On the equation $zeta_K (s) = zeta_(K') (s)$*, J. Number Theory *9* (1977), 342--360.
  Arithmetic equivalence, and why it is strictly stronger than the agreement of $"Spl"$ noted in
  @sec-corollary; the degree-$7$ minimum lives here.
+ #link("https://kconrad.math.uconn.edu/blurbs/")[K. Conrad, expository notes on Chebotarev and on
  splitting of primes]. The cleanest short treatment of the equivalence of @sec-converse.
]
