#!/usr/bin/env python3
"""Turn the CM-batch runs into survey-tables-cm.typ.

Reads   results/survey-cm.txt          (43 surfaces, all p <= 200)
        results/surfaces-cm.txt        (the curve list, from cm-surfaces.sage)
        results/survey-cm-sextic.txt   (x^3+B at p = 3, B <= 100 cubefree)
        results/survey-cm-quartic.txt  (x^3+Ax at p = 2, |A| <= 60 squarefree)
The handful of numbers from the audit / deep-hunt / pairing runs are
transcribed into the tables below; those runs are in results/survey-cm-*.txt.

Run from this directory:  python3 survey-tables-cm.py
"""
import re, json

# ---- parse the CM main run --------------------------------------------
def parse(path):
    S, cur = [], None
    for ln in open(path).read().splitlines():
        if ln.startswith("=== "):
            lbl = ln[4:].split("  f =")[0].strip()
            a, b, c = re.findall(r"\((-?\d+)\)", ln)[:3]
            cur = dict(label=lbl, f=(int(a), int(b), int(c)), primes=[])
            S.append(cur)
        elif ln.startswith("INFO "):
            cur["rootsQ2"] = int(re.search(r"rootsQ2=(\d+)", ln).group(1))
            cur["discf"] = int(re.search(r"discf=(-?\d+)", ln).group(1))
        elif ln.startswith("SWEEP "):
            cur["tsweep"] = int(re.search(r"time=(\d+)", ln).group(1))
        elif ln.startswith("P "):
            t = ln.split()
            cur["primes"].append(dict(p=int(t[1]), w=[int(x) for x in t[2:6]],
                                      path=t[6], nf=int(t[7])))
        elif ln.startswith("ODD "):
            cur["full"] = int(re.search(r"full=(\d+)/", ln).group(1))
            cur["cheap"] = int(re.search(r"cheap=(\d+)", ln).group(1))
            cur["desc"] = int(re.search(r"desc=(\d+)", ln).group(1))
            cur["todd"] = int(re.search(r"time=(\d+)", ln).group(1))
        elif ln.startswith("TWO "):
            cur["w2"] = [int(x) for x in re.search(r"\[([^\]]*)\]", ln).group(1).split(",")]
            cur["cover2"] = int(re.search(r"cover=(\d+)/", ln).group(1))
            cur["tp2"] = int(re.search(r"time=(\d+)", ln).group(1))
        elif ln.startswith("TOTAL "):
            cur["ttot"] = int(re.search(r"time=(\d+)", ln).group(1))
    return S

S = parse("results/survey-cm.txt")
by = {s["label"]: s for s in S}

ident = {}
for ln in open("results/surfaces-cm.txt"):
    t = ln.split()
    if ln.startswith("#") or len(t) < 9: continue
    lbl = {"rigid": "rigid:%s", "j0": "j0:%s", "j1728": "j1728:%s"}[t[0]] % t[1]
    ident[lbl] = dict(fam=t[0], par=int(t[1]), Nmin=int(t[5]), N=int(t[6]),
                      rank=int(t[7]), nfac=int(t[8]))

# ---- deeper passes ----------------------------------------------------
resolved_odd = {("rigid:-163", 199, 2): 1949802}
p2final = {k: list(by[k]["w2"]) for k in by}
p2final["rigid:-7"] = [201, 11, 53, 319, 66, 134, 10, 1518]
p2final["j1728:7"] = [129, 3, -3, -129, -670, 22, -22, 670]
p2final["j1728:1"] = [-15, 3, -3, 15, 0, -10, 10, 0]

CMNAME = {-3: "-3", -4: "-4"}

def poly(a, b, c):
    def term(co, v):
        if co == 0: return ""
        return " %s %s%s" % ("+" if co > 0 else "-",
                             abs(co) if (abs(co) != 1 or v == "") else "", v)
    return "x^3" + term(a, "x^2") + term(b, "x") + term(c, "")

out = []; W = out.append
W("// GENERATED by survey-tables.py -- CM batch.  Do not edit by hand.\n")

ORD = [s["label"] for s in S]

# ============ CM identification + summary ==============================
W("#let cmtable = table(")
W("  columns: 9, align: (left, center, left, right, right, right, right, center, center),")
W("  stroke: 0.4pt + luma(170), inset: (x: 4pt, y: 2.5pt),")
W("  table.header([*surface*], [$D$], [$f$], [$N_min$], [$r$], [$n_(QQ_2)$],")
W("               [cheap], [odd $p$], [$p = 2$]),")
for lbl in ORD:
    i = ident[lbl]; s = by[lbl]
    D = {"rigid": str(i["par"]), "j0": "-3", "j1728": "-4"}[i["fam"]]
    nm = {"rigid": "$D = %d$" % i["par"],
          "j0": "$B = %d$" % i["par"],
          "j1728": "$A = %d$" % i["par"]}[i["fam"]]
    nodd = s["full"] + sum(1 for (l, p, k) in resolved_odd if l == lbl)
    deep_odd = any(l == lbl for (l, p, k) in resolved_odd)
    n2 = sum(1 for x in p2final[lbl] if x != 0)
    base2 = s["cover2"]
    mo = "#super[\\*]" if nodd < 45 else ("#super[+]" if deep_odd else "")
    m2 = "#super[\\*]" if n2 < 8 else ("#super[+]" if base2 < 8 else "")
    W("  [%s], [%s], [$%s$], [%d], [%d], [%d], [%d], [%d/45%s], [%d/8%s]," %
      (nm, D, poly(*s["f"]), i["Nmin"], i["rank"], s["rootsQ2"],
       s["cheap"], nodd, mo, n2, m2))
W(")\n")

# ============ the two CM defects =======================================
W("#let cmfailtable = table(")
W("  columns: 8, align: (left, right, center, center, right, center, right, right),")
W("  stroke: 0.4pt + luma(170), inset: (x: 5pt, y: 3pt),")
W("  table.header([*surface*], [$p$], [class], [$g$], [$M_p$], [Kodaira], [$c_p$],")
W("               [rank $>= 2$ twists tried]),")
W('  [$x^3 + 2$  ($B = 2$)], [3], [$[3]$], [2], [9], [$"IV"^*$], [3], [97],')
W('  [$x^3 + x$  ($A = 1$)], [2], [$[2]$], [2], [4], [$"II"$], [1], [79],')
W('  [$x^3 + x$  ($A = 1$)], [2], [$[14]$], [2], [4], [$"II"$], [1], [79],')
W(")\n")

# ============ the family scans =========================================
sx = []
for ln in open("results/survey-cm-sextic.txt"):
    m = re.match(r"\s+B=(\d+)\s+\[([^\]]*)\]\s+\[([^\]]*)\]\s+(\d)/4", ln)
    if m:
        sx.append((int(m.group(1)), [int(x) for x in m.group(2).split(",")], int(m.group(4))))
qt = []
for ln in open("results/survey-cm-quartic.txt"):
    m = re.match(r"\s+A=(-?\d+)\s+\[([^\]]*)\]\s+(\d)/8", ln)
    if m:
        qt.append((int(m.group(1)), [int(x) for x in m.group(2).split(",")], int(m.group(3))))

def cell(d):
    return "[%d]" % d if d != 0 else '[#text(fill: rgb("#b00"))[---]]'

W("#let sextictable = {")
W("  let rows = (")
for (B, w, nf) in sx:
    W("    ([%d], %s)," % (B, ", ".join(cell(d) for d in w)))
W("  )")
W("  let t(sel) = table(columns: 5, align: right, stroke: 0.4pt + luma(170),")
W("    inset: (x: 3pt, y: 1.6pt),")
W("    table.header([$B$], [$[1]$], [$[u]$], [$[3]$], [$[u dot 3]$]),")
W("    ..sel.flatten())")
W("  let n = rows.len()")
W("  let k = calc.ceil(n / 3)")
W("  grid(columns: (auto, auto, auto), column-gutter: 0.7cm, align: top,")
W("    t(rows.slice(0, k)), t(rows.slice(k, 2*k)), t(rows.slice(2*k, n)))")
W("}\n")

W("#let quartictable = table(")
W("  columns: 9, align: right, stroke: 0.4pt + luma(170), inset: (x: 3pt, y: 1.6pt),")
W("  table.header([$A$], [$[1]$], [$[3]$], [$[5]$], [$[7]$], [$[2]$], [$[6]$],")
W("               [$[10]$], [$[14]$]),")
for (A, w, n) in qt:
    W("  [%d], %s," % (A, ", ".join(cell(d) for d in w)))
W(")\n")

# ============ per-surface witness tables ===============================
def ptab(rows):
    o = ["table(", "  columns: 5, align: right, stroke: 0.4pt + luma(170),",
         "  inset: (x: 4pt, y: 2pt),",
         "  table.header([$p$], [$[1]$], [$[u]$], [$[p]$], [$[u p]$]),"]
    o += ["  " + r for r in rows]; o.append(")")
    return "\n".join(o)

W("#let cmprimetables = [")
for lbl in ORD:
    s = by[lbl]; i = ident[lbl]
    nm = {"rigid": "CM discriminant $D = %d$" % i["par"],
          "j0": "$j = 0$, $B = %d$" % i["par"],
          "j1728": "$j = 1728$, $A = %d$" % i["par"]}[i["fam"]]
    W("  === %s#h(1fr)#text(size: 9pt)[$f = %s$, $N_min = %d$]"
      % (nm, poly(*s["f"]), i["Nmin"]))
    rows = []
    for q in s["primes"]:
        cs = []
        for kk in range(4):
            d = q["w"][kk]
            key = (lbl, q["p"], kk)
            if d == 0 and key in resolved_odd:
                cs.append("[%d#super[+]]" % resolved_odd[key])
            else:
                cs.append(cell(d))
        rows.append("[%d], %s," % (q["p"], ", ".join(cs)))
    half = (len(rows) + 1) // 2
    W("  #set text(size: 8pt)")
    W("  #grid(columns: (auto, auto), column-gutter: 0.9cm, align: top,")
    W("    " + ptab(rows[:half]).replace("\n", "\n    ") + ",")
    W("    " + ptab(rows[half:]).replace("\n", "\n    ") + ",")
    W("  )")
    W("  #set text(size: 10.5pt)")
    W("  #v(2mm)")
W("]\n")

open("survey-tables-cm.typ", "w").write("\n".join(out) + "\n")
print("wrote survey-tables-cm.typ")
print("surfaces:", len(S), " sextic scanned:", len(sx), " quartic scanned:", len(qt))
print("CM total wall time: %.1f s" % (sum(s["ttot"] for s in S)/1000))
