

# This file was *autogenerated* from the file verify-dual.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1115 = Integer(1115); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_60 = Integer(60); _sage_const_6 = Integer(6); _sage_const_21 = Integer(21); _sage_const_87 = Integer(87); _sage_const_300 = Integer(300)# =====================================================================
# Independent check, in Sage, of the one computational input to the
# theorem of section 5.2.4:  both dual-isogeny images lie in E_1.
#
# The PARI version (control.gp, dualinE1) builds the duals by hand --
# locating the kernel by trial and matching the codomain up to a sixth
# power -- and evaluates them with its own substitution code.  Here we
# use Sage's EllipticCurveIsogeny.dual() and rational_maps() instead, so
# the dual construction and the evaluation are both independent.
#
# Run (image is amd64, so it emulates on Apple silicon):
#   docker run --rm --platform linux/amd64 -v "$PWD":/work -w /work \
#          sagemath/sagemath:latest sage verify-dual.sage
# =====================================================================

R = QQ['x']; (x,) = R._first_ngens(1)

print("=== Kodaira type at 3, four classes (f = x^3 - 2) ===")
for (cls, d) in [("[1]", -_sage_const_1115 ), ("[u]", -_sage_const_1 ), ("[3]", _sage_const_3 ), ("[u*3]", -_sage_const_3 )]:
    E = EllipticCurve(QQ, [_sage_const_0 , -_sage_const_2 *d**_sage_const_3 ])
    ld = E.local_data(_sage_const_3 )
    print("   class %-6s d=%-6s  Kodaira %-5s  c_3 = %s"
          % (cls, d, ld.kodaira_symbol(), ld.tamagawa_number()))

print()
print("=== dual images: does any Q_3-point of the codomain leave E_1 ? ===")
K = Qp(_sage_const_3 , _sage_const_60 )

def qp_points(C, XMAX):
    """Q_3-points of C with integral x-coordinate."""
    a4, a6 = C.a4(), C.a6()
    pts = []
    for x0 in range(-XMAX, XMAX + _sage_const_1 ):
        s = x0**_sage_const_3  + a4*x0 + a6
        if s == _sage_const_0 :
            continue
        v = s.valuation(_sage_const_3 )
        if v % _sage_const_2 :
            continue
        if kronecker((s / _sage_const_3 **v) % _sage_const_3 , _sage_const_3 ) != _sage_const_1 :
            continue
        y = K(s).sqrt()
        pts += [(K(x0), y), (K(x0), -y)]
    return pts

total, bad = _sage_const_0 , _sage_const_0 
for d in [-_sage_const_3 , _sage_const_6 , -_sage_const_21 , _sage_const_87 ]:
    E = EllipticCurve(QQ, [_sage_const_0 , -_sage_const_2 *d**_sage_const_3 ])
    for nm, ker in [("phi_1", x), ("phi_2", x - _sage_const_2 *d)]:
        ph = E.isogeny(ker)
        C, du = ph.codomain(), ph.dual()
        assert du.domain() == C and du.degree() == _sage_const_3 
        if E.rank() > _sage_const_0 :                       # dual o phi = [3]
            P = E.gens()[_sage_const_0 ]
            assert du(ph(P)) == _sage_const_3 *P
        fx, fy = du.rational_maps()
        tested = outside = _sage_const_0 
        for (X, Y) in qp_points(C, _sage_const_300 ):
            try:
                xx = fx(X, Y)
            except ZeroDivisionError:
                continue                       # image is O, which lies in E_1
            tested += _sage_const_1 
            if xx.valuation() >= _sage_const_0 :            # integral x  =>  NOT in E_1
                outside += _sage_const_1 
        total += tested; bad += outside
        print("   d=%-4s %s : %4d points tested, %d outside E_1"
              % (d, nm, tested, outside))

print()
print("total %d points tested, %d outside E_1" % (total, bad))
print("=> W_3 is NOT phi-stable, i.e. beta_3 is not identically zero"
      if bad == _sage_const_0  else "=> UNEXPECTED: containment fails")

