/* ============================================================================
   wild-tamagawa.gp -- testing, and REFUTING, the Tamagawa conjecture of
   chapter 11 (survey document 11.5).

   Chapter 11 reduces a live wild place at odd ell to two conditions: (i)
   dim W_ell = 2, i.e. a Q_ell-rational ell-torsion point, and (ii) the
   C_0-descent map alpha not identically zero.  On the single surface available,
   x^3 - 2, the two were tracked by ell | c_ell, which suggested that (ii) is
   governed by the Tamagawa number.  It is not.

   TWO MEASUREMENT TRAPS had to be cleared first.

   (1) The image of alpha is a subgroup of Q_3^x/(Q_3^x)^3, but the set of VALUES
       over a SAMPLE of points is not: the sample is not closed under addition.
       That is why alpha3.gp reports image sizes like 2 and 5 and flags them as
       "not a subgroup order" -- the flag is correct and the reading of #S as a
       dimension is what is wrong.  Here the SPAN of the sampled values is taken
       instead, inside (Z/3)^2 with coordinates (v_3 mod 3, unit class mod 9).
       Calibration: x^3-2 gives dim 0 at d = 1 and dim 2 at d = 6, as 5.1.5 and
       10.5.1 require.

   (2) Before trusting that, the tangent evaluation L(P) = y - y0 - m(x - x0)
       was checked to be multiplicative modulo cubes: 400 of 400 pairs on each
       of three curves.  So the map is a genuine homomorphism and (1) is the
       whole explanation.

   RESULT.  Over curves with additive potentially good reduction at 3 and
   dim W_3 = 2: the conjecture fails, 8 of 14.  And it fails structurally, not
   marginally: type II with c_3 = 1 occurs BOTH with dim im alpha = 0 and with
   dim im alpha = 1.  Reduction type and Tamagawa number together therefore do
   NOT determine whether alpha vanishes, so no recipe in the style of 10.6 can
   reach the wild place.  What does survive, as an observation, is the one
   direction 3 | c_3 ==> alpha =/= 0 (4 of 4 here).

   Output: results/survey-wild-tamagawa.txt
   ============================================================================ */

/* alpha3.gp --- the image of the level-3 descent map at v = ell = 3.
 *
 * WHY. beta_3 vanishes iff L_3 = delta(W_3) is phi-stable, iff
 *      L_3 = (L_3 cap H_1) + (L_3 cap H_2),
 * and dim(L_3 cap H_1) = dim ker alpha_2, dim(L_3 cap H_2) = dim ker alpha_1.
 * Since ker alpha_1 cap ker alpha_2 = ker delta = 0, the two dimensions sum to
 * at most dim W_3 = 2, with equality exactly when L_3 is phi-stable. So:
 *
 *      dim ker alpha_1 = 2                      => stable  (L_3 lies in H_2)
 *      dim ker alpha_1 = 1 and ker alpha_2 != 0 => stable  (both are 1)
 *      dim ker alpha_1 = 0                      => stable iff alpha_2 = 0
 *
 * vell.gp tests only whether ker alpha_i is non-zero, which cannot separate the
 * first line from the third. This script measures the DIMENSION, and does it
 * without any p-adic point arithmetic on isogeny images.
 *
 * HOW. If C is a Galois-stable line generated by a Q_3-rational point S, then
 * the C-quotient component of the Kummer map is evaluation of the function with
 * divisor 3(S) - 3(O) -- for a curve y^2 = g(x) and S of order 3 that is the
 * tangent at S, since the tangent meets E only there:
 *      alpha(P) = y(P) - y0 - m (x(P) - x0)   mod cubes,   m = g'(x0)/(2 y0).
 * Its values lie in Q_3^x mod cubes, of order 9, and a class there is pinned
 * down by (v_3 mod 3, unit part mod 9 up to sign): U^(2) = 1 + 9 Z_3 lies in the
 * cubes because 2 > 3e/(p-1) = 3/2, and -1 is a cube. That needs only x mod 9,
 * so no precision is lost.
 *
 * The script also checks that the sampled points GENERATE E(Q_3)/E_2. Since
 * alpha is a homomorphism and 3E contains E_2, generating that quotient means
 * the computed image is the whole image -- without which "image = 0" would be
 * an artefact of a bad sample.
 *
 * Run:  gp -q -s 4000000000 < alpha3.gp
 */

read("kummer2.gp");
read("survey.gp");

cub3(x)   = { my(v = valuation(x, 3), u = x/3^v, t);
              t = truncate(u) % 9; if(t > 4, t = 9 - t); [v % 3, t]; }
inE2(P)   = (P == [0]) || (valuation(P[1], 3) <= -4);
sameE2(Ep, P, Q) = inE2(elladd(Ep, P, ellneg(Ep, Q)));

/* do the sampled points generate E(Q_3)/E_2 ? */
generates(Em, pts) = {
  my(Ep = padiccurve(Em, 3), G = List([[0]]), nw, grew = 1, T, M);
  for(i = 1, #pts, nw = 1;
    for(j = 1, #G, if(sameE2(Ep, pts[i], G[j]), nw = 0; break));
    if(nw, listput(G, pts[i])));
  while(grew, grew = 0;
    for(i = 1, #G, for(j = 1, #G, T = elladd(Ep, G[i], G[j]); nw = 1;
      for(k = 1, #G, if(sameE2(Ep, T, G[k]), nw = 0; break));
      if(nw, listput(G, T); grew = 1))));
  M = Mval(Em, 3) * 3;                    /* #E(Q_3)/E_2 = M * #E_1/E_2 */
  [#G, M];
}

/* E : y^2 = g(x) for ev = [0, A, 0, B, C].  These are top-level functions on
   purpose: an arrow closure assigned inside a braced function body binds
   greedily and swallows the rest of the body. */
gval(ev, X)  = X^3 + ev[2]*X^2 + ev[4]*X + ev[5];
dgval(ev, X) = 3*X^2 + 2*ev[2]*X + ev[4];

/* E : y^2 = g(x) given by [0, A, 0, B, C] */
run(name, ev, prec, XMAX) = {
  my(E = ellinit(ev), Em, vE, K, xs, x0 = 0, y0, m, pts, S = Set(),
     used = 0, gen, dimim, found = 0);
  Em = ellminimalmodel(E, &vE);
  K  = select(f -> poldegree(f) == 1, Vec(factor(elldivpol(E, 3))[,1]~));
  xs = vector(#K, i, -polcoef(K[i], 0)/polcoef(K[i], 1));
  for(i = 1, #xs, if(issquare(gval(ev, xs[i]) + O(3^prec)), x0 = xs[i]; found = 1; break));
  if(!found,
     print(name, "   no Q_3-rational 3-torsion, so dim W_3 = 1 and beta_3 = 0");
     print(""); return);
  y0 = sqrt(gval(ev, x0) + O(3^prec));
  m  = dgval(ev, x0)/(2*y0);
  pts = ppointsE(E, 3, prec, XMAX);
  gen = generates(Em, apply(P -> ellchangepoint(P, vE), pts));
  for(k = 1, #pts,
    my(L = pts[k][2] - y0 - m*(pts[k][1] - x0));
    if(valuation(L, 3) > prec - 10, next);
    used++;
    S = setunion(S, [cub3(L)]));
  dimim = if(#S == 1, 0, if(#S == 3, 1, if(#S == 9, 2, -1)));
  print(name, "   3-torsion at x = ", x0, "   sample generates E(Q_3)/E_2: ",
        gen[1], " of ", gen[2], if(gen[1] == gen[2], "  yes", "  NO"));
  print("      image of alpha has ", #S, " classes",
        if(dimim < 0, "   *** not a subgroup order ***",
           Str("  =>  dim im = ", dimim, ",  dim ker = ", 2 - dimim)),
        "   (", used, " points)");
  print("      verdict: ", if(dimim == 0, "L_3 lies in one H_i, so PHI-STABLE and beta_3 = 0",
                        if(dimim == 1, "dim ker alpha = 1; stable iff the other kernel is non-zero (vell.gp)",
                           "ker alpha = 0; stable only if the other alpha vanishes")));
  print("");
}
Ed(d) = [0, 10*d, 0, 105*d^2, -116*d^3];

/* E_d over Q_3 depends on d only through its class in Q_3^x modulo squares, so
   FOUR representatives settle every squarefree d at once. For squarefree d the
   four classes are: 3 does not divide d with d = 1 or 2 mod 3, and 3 | d with
   d/3 = 1 or 2 mod 3. */
kodname(k) = if(k==1,"I0", if(k==2,"II", if(k==3,"III", if(k==4,"IV", if(k>4, concat(["I",k-4]), if(k==-1,"I0*", if(k==-2,"II*", if(k==-3,"III*", if(k==-4,"IV*", concat(["I",-k-4,"*"]))))))))));
/* cub3 gives [v mod 3, t] with t in {1,2,4}; the unit group is cyclic of order 3
   generated by 4 mod 9, with 1 -> 0, 4 -> 1, 7 = -2 -> 2 (cub3 folds 7 to 2). */
uidx(t) = if(t == 1, 0, if(t == 4, 1, if(t == 2, 2, -1)));
Lval(P, x0, y0, m) = P[2] - y0 - m*(P[1] - x0);
/* dim of the SUBGROUP GENERATED by the sampled values, inside (Z/3)^2 */
adim(ev, prec, XMAX, CUT) = { my(E = ellinit(ev), Em, vE, K, xs, x0 = 0, y0, m, pts,
    V = List(), found = 0, gen);
  Em = ellminimalmodel(E, &vE);
  K  = select(f -> poldegree(f) == 1, Vec(factor(elldivpol(E, 3))[,1]~));
  xs = vector(#K, i, -polcoef(K[i], 0)/polcoef(K[i], 1));
  for(i = 1, #xs, if(issquare(gval(ev, xs[i]) + O(3^prec)), x0 = xs[i]; found = 1; break));
  if(!found, return([-1,0]));
  y0 = sqrt(gval(ev, x0) + O(3^prec));
  m  = dgval(ev, x0)/(2*y0);
  pts = ppointsE(E, 3, prec, XMAX);
  gen = generates(Em, apply(P -> ellchangepoint(P, vE), pts));
  for(k = 1, #pts, my(L = Lval(pts[k], x0, y0, m), c);
    if(L == 0 || valuation(L,3) > CUT, next);
    c = cub3(L);
    if(uidx(c[2]) < 0, next);
    listput(V, [c[1], uidx(c[2])]));
  [if(#V == 0, 0, matrank(Mod(Mat(Vec(V)~), 3))), gen[1] == gen[2]]; }
scan(M, prec, XMAX) = { my(seen = List(), n = 0, agree = 0, dis = 0);
  print("=== v = ell = 3, additive and potentially good, dim W_3 = 2 ===");
  print("=== does alpha vanish exactly when 3 does not divide c_3 ? ===");
  for(A = -M, M, for(B = -M, M, for(C = -M, M,
    my(ev = [0,A,0,B,C], E, Em, r, key, d);
    if(n > 60, next);
    if(poldisc(x^3+A*x^2+B*x+C) == 0, next);
    E = ellinit(ev); if(E == 0, next);
    Em = ellminimalmodel(E); r = elllocalred(Em, 3);
    if(r[2] == 1 || r[2] > 4, next);
    if(valuation(Em.j, 3) < 0, next);
    key = [Em.a1,Em.a2,Em.a3,Em.a4,Em.a6];
    if(setsearch(Set(Vec(seen)), key), next);
    listput(seen, key);
    d = adim(ev, prec, XMAX, 25);
    if(d[1] < 0, next);
    n++;
    my(alive = (d[1] > 0), pred = (r[4] % 3 == 0));
    if(alive == pred, agree++, dis++);
    print("   x^3+", A, "x^2+", B, "x+", C, "  ", kodname(r[2]), " c_3=", r[4],
          "  3|c_3: ", if(pred, "yes", "no "), "   dim im alpha = ", d[1],
          "   ", if(alive == pred, "agree", "*** DISAGREE ***"),
          if(d[2], "", "  [no gen]")))));
  print("");
  print("   === ", agree, " agree, ", dis, " disagree, out of ", n, " ==="); }
print("calibration first:");
print("   x^3-2 d=1: dim im alpha = ", adim([0,0,0,0,-2], 60, 30, 25)[1], "  (expect 0)");
print("   x^3-2 d=6: dim im alpha = ", adim([0,0,0,0,-432], 60, 30, 25)[1], "  (expect > 0)");
print("");
scan(9, 60, 30);
quit;
